# $FreeBSD: src/usr.sbin/wlconfig/Makefile,v 1.3.2.1 2001/04/25 12:11:12 ru Exp $
# $DragonFly: src/usr.sbin/wlconfig/Makefile,v 1.3 2008/10/29 18:18:05 swildner Exp $
PROG=	wlconfig
MAN=	wlconfig.8
WARNS?=	2

.include <bsd.prog.mk>
