# $DragonFly: src/secure/usr.bin/ssh/Makefile.etc,v 1.2 2008/04/08 12:12:53 swildner Exp $
#

FILES=		ssh_config
FILESDIR=	/etc/ssh
FILESOWN=	${BINOWN}
FILESGRP=	${BINGRP}
FILESMODE=	644

.include "../../Makefile.ssh.common"
.include <bsd.prog.mk>
