.\" Copyright (c) 2004,2005 The DragonFly Project.  All rights reserved.
.\" 
.\" This code is derived from software contributed to The DragonFly Project
.\" by Matthew Dillon <dillon@backplane.com>
.\" 
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $DragonFly: src/sbin/jscan/jscan.8,v 1.3 2005/07/06 06:06:44 dillon Exp $
.\"
.Dd March 6, 2005
.Dt JSCAN 8
.Os
.Sh NAME
.Nm jscan
.Nd journal file processing program
.Sh SYNOPSIS
.Nm
.Fl 2rd
.Op Ar journal_files
.Pp
.Sh DESCRIPTION
The
.Nm
utility scans journal files for the purposes of debugging dumps, restoration,
undo, mirroring, and other journaling features.
.Bl -tag -width indent
.It Fl 2
Implement the full-duplex acknowledgement protocol on the input descriptor.
Note that shell pipes are full-duplex and can be used with this option.
.It Fl d
dumps the contents of the journaling file in a human readable format.
.It Fl r
will cause the journal be scanned backwards.  Transactions will be dumped in
reverse order.  However, note that due to parallelism the order will not be
the exact reverse of a forward scan, since large transactions are not dumped
until all stream segments have been collected for them.
.El
.Pp
.Sh FILES
.Sh SEE ALSO
.Xr mountctl 8
.Sh BUGS
.Sh CAVEATS
This utility is currently under construction and not all features have been
implemented yet.  In fact, most have not.
.Sh HISTORY
The
.Nm
utility first appeared in DragonFly .
