#
# $DragonFly: src/sbin/jscan/Makefile,v 1.2 2005/07/05 00:26:03 dillon Exp $

PROG=	jscan
SRCS=	jscan.c jfile.c jstream.c subs.c dump_debug.c dump_mirror.c
MAN=	jscan.8
WARNS?= 6

.include <bsd.prog.mk>
