#
# $DragonFly: src/sbin/jscan/Makefile,v 1.5 2006/10/17 00:55:41 pavalos Exp $

PROG=	jscan
SRCS=	jscan.c jfile.c jstream.c jsession.c subs.c \
	dump_debug.c dump_mirror.c dump_record.c dump_output.c
MAN=	jscan.8
NO_STRICT_ALIASING=

.include <bsd.prog.mk>
