#	from: @(#)Makefile	5.8 (Berkeley) 7/28/90
# $FreeBSD: src/usr.sbin/rarpd/Makefile,v 1.7.2.1 2001/04/25 12:10:41 ru Exp $
# $DragonFly: src/usr.sbin/rarpd/Makefile,v 1.2 2003/06/17 04:30:02 dillon Exp $

PROG=	rarpd
MAN=	rarpd.8

CFLAGS+= -DTFTP_DIR=\"/tftpboot\"

.include <bsd.prog.mk>
