.\" Copyright (c) 2005 The DragonFly Project.  All rights reserved.
.\"
.\" This code is derived from software contributed to The DragonFly Project
.\" by Maxime Labelle.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd April 6, 2009
.Dt BATTD 8
.Os
.Sh NAME
.Nm battd
.Nd Battery status monitoring daemon
.Sh SYNOPSIS
.Nm
.Op Fl dEhT
.Op Fl c Ar seconds
.Op Fl e Ar command
.Op Fl f Ar device
.Op Fl p Ar percent
.Op Fl s Ar status
.Op Fl t Ar minutes
.Sh DESCRIPTION
The
.Nm
daemon monitors the status of the battery or batteries present in the system.
The daemon will alert all users on the system and may execute a supplied
command once a particular criterion has been met.
The criteria are based
on the percentage remaining, the time remaining and the status of the battery.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl c Ar seconds
Interval in seconds for checking the battery status.
Default is
.Ar 30
seconds.
.It Fl d
Start in debug mode (works when
.Nm
is compiled with
.Fl DDEBUG ) .
.It Fl e Ar command
Execute
.Ar command
once condition has been met.
.It Fl E
Execute command only once after a condition has been met.
.It Fl f Ar device
Specifies a different device path to be used.
Default is
.Pa /dev/apm .
.It Fl h
Print
.Nm
command line usage and exit.
.It Fl p Ar percent
Alert users when the remaining battery life has reached approximately
.Ar percent .
Default is
.Ar 10 .
A value of
.Ar 0
turns this alert off.
.It Fl s Ar status
Alert users when the remaining battery has reached a given status.
The status specified can either be
.Ar high ,
.Ar low
or
.Ar critical .
.It Fl t Ar minutes
Alert users when the remaining battery time has reached approximately
.Ar minutes .
.It Fl T
Alert users when the system has approximately 10 minutes remaining battery time,
but don't execute command
.Pq Fl e
on this alert.
.El
.Sh EXAMPLES
.Dl "battd -p 50 -s low"
Alert users when the battery percentage has reached 50% and
once again when the status reaches
.Ar low .
.Pp
.Dl "battd -t 15 -c 10"
Alert users when the battery has 15 minutes worth of power remaining
and once again when battery percentage has reached 10%.
Decrease the interval between checking the battery to 10 seconds.
.Pp
.Dl "battd -Tt4 -p0 -Ee \*q/sbin/shutdown -p +2 Battery_Low\*q"
Alert users when the battery has 10 minutes worth power remaining and
alert again when 4 minutes is remaining and then execute the given
.Xr shutdown 8
command once.
(User will have to
.Xr kill 1
the
.Xr shutdown 8
process, if AC power is connected to system and shutdown isn't wanted.)
.Sh SEE ALSO
.Xr viapm 4 ,
.Xr apm 8 ,
.Xr apmd 8 ,
.Xr syslogd 8 ,
.Xr zzz 8
.Sh HISTORY
The
.Nm
command first appeared in
.Dx 1.1 .
.Sh AUTHORS
.An Liam J. Foy Aq Mt liamfoy@dragonflybsd.org
.Pp
Man page contributions by:
.An Maxime Labelle Aq Mt mlabelle@vt220.com
.An Sarunas Vancevicius Aq Mt svan@redbrick.dcu.ie
