#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $DragonFly: src/usr.sbin/battd/Makefile,v 1.3 2005/08/28 20:15:38 liamfoy Exp $

PROG=	battd	
MAN=	battd.8

LDADD+=	-lutil
DPADD+=	${LIBUTIL}

.include <bsd.prog.mk>
