# $FreeBSD: src/sys/modules/netgraph/ppp/Makefile,v 1.1.4.3 2001/12/21 09:00:49 ru Exp $
# $DragonFly: src/sys/netgraph/ppp/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $
# $Whistle: Makefile,v 1.1 1999/01/24 02:52:12 archie Exp $

KMOD=		ng_ppp
SRCS= 		ng_ppp.c

.include <bsd.kmod.mk>
