# $FreeBSD: src/usr.sbin/chkgrp/Makefile,v 1.2.2.2 2001/04/25 12:09:22 ru Exp $
# $DragonFly: src/usr.sbin/chkgrp/Makefile,v 1.2 2003/06/17 04:29:52 dillon Exp $

PROG=	chkgrp
MAN=	chkgrp.8

.include <bsd.prog.mk>
