# $FreeBSD: src/usr.sbin/quot/Makefile,v 1.5.2.2 2002/03/15 18:12:41 mikeh Exp $
# $DragonFly: src/usr.sbin/quot/Makefile,v 1.3 2005/01/17 01:49:24 cpressey Exp $

PROG=	quot
MAN=	quot.8
NO_STRICT_ALIASING=

.include <bsd.prog.mk>
