# $FreeBSD: src/gnu/usr.bin/binutils/libopcodes/Makefile.alpha,v 1.3.2.2 2002/09/01 23:39:17 obrien Exp $
# $DragonFly: src/gnu/usr.bin/binutils/libopcodes/Attic/Makefile.alpha,v 1.2 2003/06/17 04:25:45 dillon Exp $

SRCS+=	alpha-dis.c alpha-opc.c
CFLAGS+= -DARCH_alpha
