#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $DragonFly: src/usr.sbin/installer/Makefile,v 1.1 2008/03/12 01:34:49 dave Exp $

SUBDIR= libaura libdfui libinstaller dfuife_curses dfuibe_installer

.include <bsd.subdir.mk>
