# $FreeBSD: src/usr.bin/chat/Makefile,v 1.7.2.1 2001/04/25 11:29:17 ru Exp $
# $DragonFly: src/usr.bin/chat/Makefile,v 1.3 2004/01/31 06:56:43 dillon Exp $

PROG=	chat
CFLAGS+=-Wall
MAN=	chat.8

.include <bsd.prog.mk>
