# $FreeBSD: src/usr.bin/chat/Makefile,v 1.7.2.1 2001/04/25 11:29:17 ru Exp $
# $DragonFly: src/usr.bin/chat/Makefile,v 1.5 2007/08/27 16:50:52 pavalos Exp $

PROG=	chat
MAN=	chat.8

.include <bsd.prog.mk>
