# $FreeBSD: src/sys/boot/ia64/Makefile,v 1.2 2001/09/12 08:34:26 dfr Exp $
# $DragonFly: src/sys/boot/ia64/Makefile,v 1.1 2003/11/10 06:08:37 dillon Exp $

SUBDIR=		libski skiload

.include <bsd.subdir.mk>
