# $DragonFly: src/sys/dev/usbmisc/uslcom/Makefile,v 1.2 2007/09/29 21:13:09 swildner Exp $

.PATH: ${.CURDIR}/../ucom

KMOD=	uslcom
SRCS=	uslcom.c opt_usb.h device_if.h bus_if.h

.include <bsd.kmod.mk>
