# $FreeBSD: src/sys/modules/syscons/warp/Makefile,v 1.3 1999/08/28 00:47:56 peter Exp $
# $DragonFly: src/sys/dev/misc/syscons/warp/Makefile,v 1.3 2008/02/04 22:22:06 swildner Exp $

KMOD=	warp_saver
SRCS= 	warp_saver.c

KCFLAGS+= -I${.CURDIR}/..

.include <bsd.kmod.mk>
