# $DragonFly: doc/en/Makefile,v 1.1.1.1 2004/04/02 09:35:45 hmp Exp $

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = en

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
