# $FreeBSD: src/gnu/usr.bin/binutils/as/Makefile.inc,v 1.3.2.2 2002/09/01 23:39:13 obrien Exp $
# $DragonFly: src/gnu/usr.bin/binutils214/as/Attic/Makefile.inc,v 1.1 2004/02/01 08:53:03 dillon Exp $

# BINDIR
.include "${.CURDIR}/../../Makefile.inc"
