# $FreeBSD: src/sys/modules/ntfs/Makefile,v 1.5 1999/12/12 20:34:07 peter Exp $
# $DragonFly: src/sys/vfs/ntfs/Makefile,v 1.4 2004/08/13 17:51:12 dillon Exp $

KMOD=	ntfs
SRCS=	ntfs_vfsops.c ntfs_vnops.c ntfs_subr.c ntfs_ihash.c \
	ntfs_compr.c
NOMAN=

.include <bsd.kmod.mk>
