# $FreeBSD: src/gnu/usr.bin/man/catman/Makefile,v 1.11.2.2 2001/04/25 14:04:13 ru Exp $
# $DragonFly: src/gnu/usr.bin/man/catman/Attic/Makefile,v 1.2 2003/06/17 04:25:46 dillon Exp $

MAINTAINER=	wosch

SCRIPTS=	catman.perl
MAN=		catman.1

.include <bsd.prog.mk>
