# $FreeBSD: src/kerberosIV/usr.bin/Makefile,v 1.2 1999/08/28 01:31:26 peter Exp $
# $DragonFly: src/kerberosIV/usr.bin/Attic/Makefile,v 1.2 2003/06/17 04:26:25 dillon Exp $

SUBDIR=	kadmin kauth kdestroy kinit klist ksrvtgt telnet

.include <bsd.subdir.mk>
