.\"
.\" Copyright (c) 2014 The DragonFly Project.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd November 8, 2014
.Dt IASL 8
.Os
.Sh NAME
.Nm iasl
.Nd ACPI Source Language compiler, ACPI table compiler, and AML disassembler
.Sh SYNOPSIS
.Nm
.Op Ar option ...
.Op Ar file ...
.Sh DESCRIPTION
The following options are supported:
.Bl -tag -width indent
.It Fl @ Ar file
Specify command file.
.It Fl bf
Create debug file (full tree only) (*.txt).
.It Fl bp Ar depth
Prune ASL parse tree.
.It Fl bs
Create debug file (parse tree only) (*.txt).
.It Fl bt Ar type
Object type to be pruned from the parse tree.
.It Fl cr
Disable Resource Descriptor error checking.
.It Fl d Ar file1 Op Ar file2
Disassemble or decode binary ACPI tables to file (*.dsl).
The
.Ar file2
is optional, file type is automatically detected.
.It Fl D Ar symbol
Define symbol for preprocessor use.
.It Fl da Ar file ...
Disassemble multiple tables from single namespace.
.It Fl db
Do not translate Buffers to Resource Templates.
.It Fl dc Ar file ...
Disassemble AML and immediately compile it.
Obtain the DSDT from the current system if no input file has it.
.It Fl dl
Emit legacy ASL code only (no C-style operators).
.It Fl e Ar file ...
Include ACPI table(s) for external symbol resolution.
.It Fl f
Ignore errors, force creation of AML output file(s).
.It Fl fe Ar file
Specify external symbol declaration file.
.It Fl G
Compile custom table that contains generic operators.
.It Fl h
Display the help message.
.It Fl hc
Display operators allowed in constant expressions.
.It Fl hf
Display help for output filename generation.
.It Fl hr
Display ACPI reserved method names.
.It Fl ht
Display currently supported ACPI table names.
.It Fl I Ar directory
Specify additional include directory.
.It Fl ia
Create include file in assembler (*.inc).
.It Fl ic
Create include file in C (*.h).
.It Fl in
Ignore NoOp opcodes.
.It Fl in
Ignore NoOp operators.
.It Fl l
Create mixed listing file (ASL source and AML) (*.lst).
.It Fl li
Create preprocessed output file (*.i).
.It Fl lm
Create hardware summary map file (*.map).
.It Fl ln
Create namespace file (*.nsp).
.It Fl ls
Create combined source file (expanded includes) (*.src).
.It Fl m Ar size
Set internal line buffer size (in Kbytes).
.It Fl n
Parse only, no output generation.
.It Fl oa
Disable all optimizations (compatibility mode).
.It Fl of
Disable constant folding.
.It Fl oi
Disable integer optimization to Zero/One/Ones.
.It Fl on
Disable named reference string optimization.
.It Fl ot
Display compile times and statistics.
.It Fl P
Preprocess only and create preprocessor output file (*.i).
.It Fl p Ar prefix
Specify path/filename prefix for all output files.
.It Fl Pn
Disable preprocessor.
.It Fl r Ar revision
Override table header Revision (1-255).
.It Fl sa
Create source file in assembler (*.asm).
.It Fl sc
Create source file in C (*.c).
.It Fl so
Create offset table in C (*.offset.h).
.It Fl T Ar sig | ALL | *
Create table template file for ACPI
.Ar sig .
.It Fl ta
Create hex AML table in assembler (*.hex).
.It Fl tc
Create hex AML table in C (*.hex).
.It Fl ts
Create hex AML table in ASL (*.hex).
.It Fl v
Display compiler version.
.It Fl va
Disable all errors/warnings/remarks.
.It Fl ve
Report only errors (ignore warnings and remarks).
.It Fl vi
Less verbose errors and warnings for use with IDEs.
.It Fl vo
Enable optimization comments.
.It Fl vr
Disable remarks.
.It Fl vs
Disable signon.
.It Fl vt
Create verbose template files (full disassembly).
.It Fl vt
Dump binary table data in hex format within output file.
.It Fl vw Ar message_id
Disable specific warning or remark.
.It Fl w1 | Fl w2 | Fl w3
Set warning reporting level.
.It Fl we
Report warnings as errors.
.It Fl x Ar level
Set debug level for trace output.
.It Fl z
Do not insert new compiler ID for DataTables.
.El
.Sh SEE ALSO
.Xr acpi 4 ,
.Xr acpibin 8 ,
.Xr acpiconf 8 ,
.Xr acpidump 8 ,
.Xr acpiexec 8 ,
.Xr acpihelp 8 ,
.Xr acpinames 8 ,
.Xr acpixtract 8
.Pp
.Lk https://acpica.org/documentation/
.Pp
.Lk https://acpica.org/sites/acpica/files/aslcompiler_5.pdf
.Sh AUTHORS
The
.Nm
utility is provided by
.Tn Intel
as part of their
.Sy ACPICA
distribution.
.Pp
This manual page was written by
.An Sascha Wildner .
