# $FreeBSD: src/usr.sbin/dpt/dpt_ctls/Makefile,v 1.4.2.2 2001/07/21 01:31:40 obrien Exp $
# $DragonFly: src/usr.sbin/dpt/dpt_ctls/Makefile,v 1.2 2003/06/17 04:29:53 dillon Exp $

PROG=	dpt_ctls
MAN=	dpt_ctls.8

CFLAGS+=-Wall -I${.CURDIR}/../../../sys

.include <bsd.prog.mk>
