SUBDIR= 	cc_prep
SUBDIR+=	libiberty
SUBDIR+=	libdecnumber
SUBDIR+=	cc_tools
SUBDIR+=	liblto_plugin
SUBDIR+=	libbackend
SUBDIR+=	libcommon
SUBDIR+=	libcommon-target
SUBDIR+=	libcpp
SUBDIR+=	cc1
SUBDIR+=	cc
SUBDIR+=	cpp
SUBDIR+=	gcov
SUBDIR+=	cc1plus
SUBDIR+=	c++
SUBDIR+=	cc1obj

.ORDER: ${SUBDIR}

.include <bsd.subdir.mk>
