# $FreeBSD: src/secure/usr.bin/sftp/Makefile,v 1.1.2.3 2002/07/03 22:20:30 des Exp $
# $DragonFly: src/secure/usr.bin/sftp/Makefile,v 1.3 2004/07/31 19:03:01 geekgod Exp $

PROG=	sftp
SRCS=   sftp.c sftp-client.c sftp-common.c sftp-glob.c

.include "../../Makefile.ssh.common"
.include <bsd.prog.mk>
