# $FreeBSD: src/usr.sbin/mptable/Makefile,v 1.2.2.1 2001/04/25 12:10:08 ru Exp $
# $DragonFly: src/usr.sbin/mptable/Makefile,v 1.2 2003/06/17 04:29:57 dillon Exp $

PROG = mptable

BINMODE = 550

.include <bsd.prog.mk>
