# $FreeBSD: src/kerberosIV/lib/Makefile.inc,v 1.2 1999/08/28 01:31:15 peter Exp $
# $DragonFly: src/kerberosIV/lib/Attic/Makefile.inc,v 1.2 2003/06/17 04:26:25 dillon Exp $

SHLIB_MAJOR?=	3
SHLIB_MINOR?=	0

.include "../Makefile.inc"
