# $FreeBSD: src/kerberosIV/lib/Makefile,v 1.2 1999/08/28 01:31:14 peter Exp $
# $DragonFly: src/kerberosIV/lib/Attic/Makefile,v 1.2 2003/06/17 04:26:25 dillon Exp $

SUBDIR=	libroken libsl libacl libkadm libkafs libkdb libkrb libtelnet

.include <bsd.subdir.mk>
