#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/share/man/man7/Makefile,v 1.10.2.7 2002/12/28 19:09:50 dillon Exp $
# $DragonFly: src/share/man/man7/Makefile,v 1.7 2006/12/03 21:04:22 swildner Exp $

#MISSING: eqnchar.7 ms.7 term.7
MAN=	ascii.7 build.7 clocks.7 development.7 environ.7 firewall.7 hier.7 \
	hostname.7 intro.7 mailaddr.7 nls.7 operator.7 release.7 \
	security.7 tuning.7 committer.7
MLINKS=	intro.7 miscellaneous.7

.include <bsd.prog.mk>
