#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/share/man/man7/Makefile,v 1.10.2.7 2002/12/28 19:09:50 dillon Exp $

#MISSING: eqnchar.7 ms.7 term.7
MAN=	ascii.7 \
	build.7 \
	clocks.7 \
	committer.7 \
	development.7 \
	environ.7 \
	firewall.7 \
	hier.7 \
	hostname.7 \
	intro.7 \
	mailaddr.7 \
	nls.7 \
	operator.7 \
	pkgsrc.7 \
	release.7 \
	script.7 \
	security.7 \
	standards.7 \
	stdint.7 \
	tuning.7 \
	vkernel.7

MLINKS=	intro.7 miscellaneous.7
MLINKS+=release.7 nrelease.7
MLINKS+=vkernel.7 vcd.4 \
	vkernel.7 vkd.4 \
	vkernel.7 vke.4

.include <bsd.prog.mk>
