#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/strings/Makefile,v 1.3.6.1 2001/04/25 11:29:40 ru Exp $
# $DragonFly: src/usr.bin/strings/Attic/Makefile,v 1.5 2004/12/31 03:53:25 dillon Exp $

PROG=	strings
MAN=	strings.1aout
BINDIR= /usr/libexec/binutils212/aout

WARNS?= 6
.include <bsd.prog.mk>
