# $FreeBSD: src/gnu/usr.bin/groff/src/utils/Makefile,v 1.1.2.1 2001/04/26 17:08:37 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/utils/Makefile,v 1.2 2003/06/17 04:25:46 dillon Exp $

SUBDIR=		addftinfo afmtodit hpftodit indxbib lkbib lookbib pfbtops tfmtodit

.include <bsd.subdir.mk>
