# $FreeBSD: src/gnu/usr.bin/groff/src/utils/Makefile.inc,v 1.1.2.1 2001/04/26 17:08:37 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/utils/Makefile.inc,v 1.2 2003/06/17 04:25:46 dillon Exp $

TOPREL=		../../..
DIST_SUBDIR=	src/utils/${.CURDIR:T}

.include "../../Makefile.inc"
