# $FreeBSD: src/release/picobsd/tinyware/help/Makefile,v 1.2 1999/08/28 01:33:53 peter Exp $
# $DragonFly: src/release/picobsd/tinyware/help/Attic/Makefile,v 1.2 2003/06/17 04:27:20 dillon Exp $
#
PROG=help
SRCS+=help.c
NOMAN=yes

.include <bsd.prog.mk>


