#	$NetBSD: Makefile,v 1.30 2008/02/24 02:43:18 dholland Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

PROG=	monop
SRCS=	monop.c cards.c execute.c getinp.c houses.c jail.c misc.c \
	morg.c print.c prop.c rent.c roll.c spec.c trade.c
MAN=	monop.6

.include <bsd.prog.mk>
