# $DragonFly: src/gnu/usr.bin/cc34/cc_tools/genconditions/Makefile,v 1.1 2004/06/14 22:27:54 joerg Exp $

.include "../Makefile.inc"

PROG=	genconditions
SRCS=	genconditions.c insn-modes.h genrtl.h min-insn-modes.c gtype-desc.h
SRCS+=	bitmap.c errors.c gensupport.c ggc-none.c dummy-conditions.c rtl.c
SRCS+=	read-rtl.c
SRCS+=	concat.c hashtab.c obstack.c safe-ctype.c xexit.c xmalloc.c xstrdup.c

.include <bsd.hostprog.mk>
