# $FreeBSD: src/share/doc/psd/13.rcs/Makefile,v 1.2 1999/08/28 00:18:21 peter Exp $
# $DragonFly: src/share/doc/psd/13.rcs/Makefile,v 1.2 2003/06/17 04:36:56 dillon Exp $

SUBDIR=	rcs rcs_func

.include <bsd.subdir.mk>

