# $DragonFly: src/gnu/usr.bin/cc34/cc_tools/Makefile,v 1.1 2004/06/14 22:27:54 joerg Exp $

SUBDIR=	 gengenrtl genmodes gengtype genpreds gencheck genconstants
SUBDIR+= genconditions genflags gencodes genattr genattrtab genemit
SUBDIR+= genconfig genextract genopinit genoutput genpeep genrecog
SUBDIR+= gcov-iov

SUBDIR+= fini

.include <bsd.subdir.mk>
