# $DragonFly: src/lib/pam_module/pam_opieaccess/Makefile,v 1.2 2005/07/28 19:25:41 joerg Exp $

LIB=	pam_opieaccess
SRCS=	pam_opieaccess.c
MAN=	pam_opieaccess.8

DPADD=	${LIBOPIE}
LDADD=	-lopie

.include <bsd.lib.mk>
