# $DragonFly: src/lib/pam_module/pam_opieaccess/Makefile,v 1.1 2005/07/12 23:08:53 joerg Exp $

LIB=	pam_opieaccess
SRCS=	pam_opieaccess.c
WARNS?=	6
MAN=	pam_opieaccess.8

LDADD=	-lopie

.include <bsd.lib.mk>
