# $FreeBSD: src/sys/modules/vn/Makefile,v 1.5.2.1 2001/07/24 09:49:43 dd Exp $ 
# $DragonFly: src/sys/dev/disk/vn/Makefile,v 1.3 2004/08/13 17:51:05 dillon Exp $ 

.PATH:  ${.CURDIR}/../../dev/vn
KMOD=   vn
SRCS=   vn.c
NOMAN=

.include <bsd.kmod.mk>
