# 
# $DragonFly: doc/en/articles/Makefile.inc,v 1.1.1.1 2004/04/02 09:35:45 hmp Exp $
# $DragonFly: doc/en/articles/Makefile.inc,v 1.1.1.1 2004/04/02 09:35:45 hmp Exp $
#

DESTDIR?=	${DOCDIR}/en/articles/${.CURDIR:T}
