# $DragonFly: doc/en/articles/Makefile,v 1.1.1.1 2004/04/02 09:35:45 hmp Exp $
# $DragonFly: doc/en/articles/Makefile,v 1.1.1.1 2004/04/02 09:35:45 hmp Exp $

SUBDIR+= contributors

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
