# $FreeBSD: src/usr.sbin/pcvt/vttest/Makefile,v 1.6 1999/10/03 10:35:03 marcel Exp $
# $DragonFly: src/usr.sbin/pcvt/vttest/Attic/Makefile,v 1.3 2003/08/11 03:59:25 rob Exp $

PROG=		vttest
CFLAGS+=	-DUSEMYSTTY
SRCS=		main.c esc.c

.include <bsd.prog.mk>
