.\" $DragonFly: src/usr.sbin/resident/resident.8,v 1.1 2004/01/20 18:46:22 dillon Exp $
.\"
.Dd May 21, 2003
.Dt RESIDENT 1
.Os
.Sh NAME
.Nm resident
.Nd Make a dynamic binary resident.
.Sh SYNOPSIS
.Nm
.Ar program ...
.Sh DESCRIPTION
.Sh SEE ALSO
.Xr ld 1 ,
.Xr ldd 1 ,
.Xr nm 1 ,
.Xr rtld 1
.Sh HISTORY
