# $FreeBSD: src/sys/modules/nullfs/Makefile,v 1.10 1999/12/12 16:47:29 peter Exp $
# $DragonFly: src/sys/vfs/nullfs/Makefile,v 1.4 2004/08/13 17:51:12 dillon Exp $

KMOD=	null
SRCS=	null_subr.c null_vfsops.c null_vnops.c
NOMAN=

.include <bsd.kmod.mk>
