# $FreeBSD: src/usr.bin/minigzip/Makefile,v 1.3 1999/08/28 01:04:00 peter Exp $
# $DragonFly: src/usr.bin/minigzip/Attic/Makefile,v 1.2 2003/06/17 04:29:29 dillon Exp $

PROG=	minigzip
LDADD+=	-lz
DPADD+=	${LIBZ}
.PATH:	${.CURDIR}/../../lib/libz

.include <bsd.prog.mk>
