# $FreeBSD: src/sys/modules/bpf/deflate/Makefile,v 1.2.4.3 2001/12/21 09:00:47 ru Exp $
# $DragonFly: src/sys/netgraph/deflate/Makefile,v 1.3 2003/08/14 23:26:36 dillon Exp $
# $Whistle: Makefile,v 1.1 1999/12/03 01:44:28 archie Exp $

KMOD=		ng_deflate
SRCS= 		ng_deflate.c
KMODDEPS=	netgraph

.include <bsd.kmod.mk>
