.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)larn.6	5.5 (Berkeley) 12/30/93
.\" $FreeBSD: src/games/larn/larn.6,v 1.6.2.3 2001/07/22 11:01:22 dd Exp $
.\"
.Dd December 30, 1993
.Dt LARN 6
.Os
.Sh NAME
.Nm larn
.Nd exploring the caverns of Larn
.Sh SYNOPSIS
.Nm
.Op Fl H Ar number
.Op Fl hnr
.Op Fl o Ar optsfile
.Sh DESCRIPTION
.Nm Larn
is a fantasy game in which your child has contracted
a strange disease, and none of your home remedies
seem to have any effect.  You set out to find a remedy in a limited
amount of time, and to collect gold along the way of course!
.Pp
The options are:
.Bl -tag -width "-o optsfile"
.It Fl H Ar number
Set the hardness of the game.
.It Fl h
Print the command line options.
.It Fl n
Suppress the welcome message at start up, putting you directly
into the game.
.It Fl o Ar optsfile
Specify a different options file than
.Pa ~/.larnopts .
.It Fl r
Restore a checkpointed game after it has died.
.El
.Sh COMMANDS
These are the keyboard commands:
.Bl -column "v" "print program version" "g" "give present pack weight"
.It Sy h Ta "move to the left" Ta Sy H Ta "run left"
.It Sy j Ta "move down" Ta Sy J Ta "run down"
.It Sy k Ta "move up" Ta Sy K Ta "run up"
.It Sy l Ta "move to the right" Ta Sy L Ta "run right"
.It Sy y Ta "move northwest" Ta Sy Y Ta "run northwest"
.It Sy u Ta "move northeast" Ta Sy U Ta "run northeast"
.It Sy b Ta "move southwest" Ta Sy B Ta "run southwest"
.It Sy n Ta "move southeast" Ta Sy N Ta "run southeast"
.It Sy \&. Ta "stay here" Ta Sy Z Ta "teleport yourself"
.It Sy c Ta "cast a spell" Ta Sy w Ta "wield a weapon"
.It Sy q Ta "quaff a potion" Ta Sy r Ta "read a scroll"
.It Sy W Ta "wear armor" Ta Sy T Ta "take off armor"
.It Sy D Ta "list all items found" Ta Sy e Ta "eat something"
.It Sy ^ Ta "identify a trap" Ta Sy g Ta "give present pack weight"
.It Sy d Ta "drop an item" Ta Sy i Ta "inventory your pockets"
.It Sy P Ta "give tax status" Ta Sy Q Ta "quit the game"
.It Sy v Ta "print program version" Ta Sy S Ta "save the game"
.It Sy \&? Ta "this help screen" Ta Sy A Ta "create diagnostic file"
.El
.Sh OPTIONS FILE
The file
.Pa ~/.larnopts
may be used to set a few options for
.Nm Larn .
A sequence of words terminated by whitespace is used to specify options.
.Bl -column "enable-checkpointing" "Define what the savegame filename will be."
.It Sy Word Ta Sy Meaning
.It bold-objects Ta "Select bold display of objects."
.It inverse-objects Ta "Select inverse video display of objects."
.It no-introduction Ta "Do not display intro message."
.It enable-checkpointing Ta "Turn on periodic checkpointing."
.It no-beep Ta "Disable beeping of the terminal."
.It male Ta "Choose your sex to be a man."
.It female Ta "Choose your sex to be a woman."
.It "name: \*qname\*q" Ta "Choose your playing name."
.It "monster: \*qname\*q" Ta "Choose a name for a monster."
.It "savefile: \*qfile\*q" Ta "Define what the savegame filename will be."
.El
.Pp
Your name and monster names must be enclosed in double quotation marks and may
be up to 34 characters long.  Longer names are truncated.
Anything enclosed in quotation marks is considered one word, and must be
separated from other words by whitespace.
.Sh SPECIAL NOTES
When
.Sy dropping gold ,
if you type '*' as your amount, all your gold gets dropped.
In general, typing in '*' means all of what you are interested in.
This is true when visiting the bank, or when contributing at altars.
.Pp
You can get out of the store, trading post, school, or home by hitting
.Sy <esc> .
.Pp
When casting a spell, if you need a list of spells you can cast, type \fBD\fP
as the first letter of your spell.  The available list of spells will be shown,
after which you may enter the spell code.  This only works on the 1st letter
of the spell you are casting.
.Sh FILES
.Bl -tag -width "/var/games/larn/lscore12.0" -compact
.It Pa /var/games/larn/lscore12.0
Score file.
.It Pa /var/games/larn/llog12.0
Log file.
.It Pa ~/.larnopts
Options file.
.El
.Sh AUTHORS
.An Noah Morgan
