# $FreeBSD: src/usr.bin/less/Makefile.common,v 1.3.2.1 2000/06/30 01:03:15 ps Exp $
# $DragonFly: src/usr.bin/less/Makefile.common,v 1.6 2007/06/03 04:23:45 pavalos Exp $

LSDIR=	${.CURDIR}/../../contrib/less-403
.PATH:	${LSDIR}

CFLAGS+=-I${.CURDIR}/../less -I${LSDIR}

.SUFFIXES: .nro .1

.nro.1:
	${LN} -s ${.IMPSRC} ${.TARGET}
