# $FreeBSD: src/usr.bin/less/Makefile.common,v 1.3.2.1 2000/06/30 01:03:15 ps Exp $
# $DragonFly: src/usr.bin/less/Makefile.common,v 1.2 2003/06/17 04:29:27 dillon Exp $

LSDIR=	${.CURDIR}/../../contrib/less
.PATH:	${LSDIR}

CFLAGS+=-I${.CURDIR}/../less -I${LSDIR}

.SUFFIXES: .nro .1

.nro.1:
	ln -s ${.IMPSRC} ${.TARGET}
