# $DragonFly: src/sbin/rconfig/Makefile,v 1.1 2004/06/18 02:46:46 dillon Exp $

PROG		= rconfig
SRCS		= rconfig.c subs.c server.c client.c
CFLAGS	       += -Wall -Wstrict-prototypes
MAN		= rconfig.8

.include <bsd.prog.mk>
