# $FreeBSD: src/release/picobsd/tinyware/simple_httpd/Makefile,v 1.6 1999/08/28 01:33:59 peter Exp $
# $DragonFly: src/release/picobsd/tinyware/simple_httpd/Attic/Makefile,v 1.2 2003/06/17 04:27:20 dillon Exp $
#
PROG=simple_httpd
SRCS= 	simple_httpd.c
NOMAN=yes

.include <bsd.prog.mk>
