# $FreeBSD: src/sys/modules/splash/Makefile.inc,v 1.2 1999/08/28 00:47:37 peter Exp $
# $DragonFly: src/sys/dev/video/fb/Makefile.inc,v 1.2 2003/06/17 04:28:46 dillon Exp $

.include "../Makefile.inc"
