# $FreeBSD: src/sys/modules/splash/Makefile,v 1.3 1999/08/28 00:47:37 peter Exp $
# $DragonFly: src/sys/dev/video/fb/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $

SUBDIR=	bmp pcx

.include <bsd.subdir.mk>
