# $FreeBSD: src/usr.bin/truncate/Makefile,v 1.1.2.1 2000/08/04 08:05:52 sheldonh Exp $
# $DragonFly: src/usr.bin/truncate/Makefile,v 1.4 2007/08/27 16:51:00 pavalos Exp $

PROG=		truncate

.include <bsd.prog.mk>
