# This installs standard mailer.conf samples based on sendmail, postfix
# and OpenSMTPD from ports.  They are overwritten during each installworld

FILESDIR=	/etc/mail/
FILESMODE=	644

FILES+=		README \
		mailer.conf.dma \
		mailer.conf.opensmtpd \
		mailer.conf.postfix \
		mailer.conf.sendmail

.include <bsd.prog.mk>
