# $FreeBSD: src/gnu/usr.bin/groff/src/libs/libbib/Makefile,v 1.4 2004/10/24 15:32:28 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/libs/libbib/Makefile,v 1.3 2005/09/01 20:47:13 asmodai Exp $

LIB=		bib
INTERNALLIB=
SRCS=		common.cpp index.cpp linear.cpp search.cpp map.c

.include <bsd.lib.mk>
