# $FreeBSD: src/usr.bin/units/Makefile,v 1.5.2.1 2002/02/18 16:16:57 ru Exp $
# $DragonFly: src/usr.bin/units/Makefile,v 1.2 2003/06/17 04:29:33 dillon Exp $

PROG=	units
FILES=	units.lib
FILESDIR=	${SHAREDIR}/misc

.include <bsd.prog.mk>
