# $FreeBSD: src/usr.bin/units/Makefile,v 1.5.2.1 2002/02/18 16:16:57 ru Exp $
# $DragonFly: src/usr.bin/units/Makefile,v 1.3 2005/02/02 06:22:30 cpressey Exp $

PROG=	units
WARNS?=	6
FILES=	units.lib
FILESDIR=	${SHAREDIR}/misc

.include <bsd.prog.mk>
