# $FreeBSD: src/kerberos5/usr.bin/Makefile,v 1.3.2.3 2002/04/30 14:57:43 nectar Exp $
# $DragonFly: src/kerberos5/usr.bin/Makefile,v 1.2 2003/06/17 04:26:18 dillon Exp $

SUBDIR=	k5admin k5destroy k5init k5list k5passwd k5su krb5-config telnet

.include <bsd.subdir.mk>
