# $FreeBSD: src/kerberos5/usr.bin/Makefile.inc,v 1.1.1.1 2000/01/15 21:38:04 markm Exp $
# $DragonFly: src/kerberos5/usr.bin/Makefile.inc,v 1.2 2003/06/17 04:26:18 dillon Exp $

BINDIR=	/usr/bin

.include "../Makefile.inc"
