# $FreeBSD: src/usr.bin/brandelf/Makefile,v 1.3.6.3 2001/08/02 01:07:27 obrien Exp $
# $DragonFly: src/usr.bin/brandelf/Makefile,v 1.2 2003/06/17 04:29:25 dillon Exp $

MAINTAINER=	obrien

PROG=	brandelf
WARNS?=	2

.include <bsd.prog.mk>
