# $FreeBSD: src/usr.bin/brandelf/Makefile,v 1.3.6.3 2001/08/02 01:07:27 obrien Exp $
# $DragonFly: src/usr.bin/brandelf/Makefile,v 1.4 2005/01/16 04:28:00 cpressey Exp $

PROG=	brandelf
WARNS?=	6

.include <bsd.prog.mk>
