# $FreeBSD: src/usr.bin/brandelf/Makefile,v 1.3.6.3 2001/08/02 01:07:27 obrien Exp $
# $DragonFly: src/usr.bin/brandelf/Makefile,v 1.3 2004/01/31 06:56:43 dillon Exp $

PROG=	brandelf
WARNS?=	2

.include <bsd.prog.mk>
