#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/du/Makefile,v 1.4.2.1 2000/07/02 10:45:29 ps Exp $
# $DragonFly: src/usr.bin/du/Makefile,v 1.5 2008/08/04 19:22:44 swildner Exp $

PROG=	du
DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
