# $FreeBSD: src/usr.sbin/dpt/dpt_ctlinfo/Makefile,v 1.5.2.2 2001/07/21 01:31:39 obrien Exp $
# $DragonFly: src/usr.sbin/dpt/dpt_ctlinfo/Makefile,v 1.2 2003/06/17 04:29:53 dillon Exp $

PROG=	dpt_ctlinfo
MAN=	dpt_ctlinfo.8

CFLAGS+=-Wall -I${.CURDIR}/../../../sys

.include <bsd.prog.mk>
