# $FreeBSD: src/usr.bin/rusers/Makefile,v 1.4.2.1 2001/04/25 11:29:37 ru Exp $
# $DragonFly: src/usr.bin/rusers/Makefile,v 1.2 2003/06/17 04:29:31 dillon Exp $

PROG = rusers

DPADD=	${LIBRPCSVC}
LDADD=	-lrpcsvc

.include <bsd.prog.mk>
