.\" $DragonFly: src/usr.sbin/prebind/Attic/prebind.8,v 1.1 2003/09/18 21:23:06 dillon Exp $
.\"
.Dd May 21, 2003
.Dt PREBIND 1
.Os
.Sh NAME
.Nm prebind
.Nd create Relocation Cache prebinding file.
.Sh SYNOPSIS
.Nm
.Ar program ...
.Sh DESCRIPTION
.Sh SEE ALSO
.Xr ld 1 ,
.Xr ldd 1 ,
.Xr nm 1 ,
.Xr rtld 1
.Sh HISTORY
