#
# $FreeBSD: src/gnu/usr.bin/binutils/Makefile.inc,v 1.4.2.2 2002/09/01 23:39:12 obrien Exp $
# $DragonFly: src/gnu/usr.bin/binutils/Attic/Makefile.inc,v 1.4 2004/01/28 16:41:17 joerg Exp $
#

BINDIR?=	/usr/libexec/binutils212/elf
