# $FreeBSD: src/usr.bin/lesskey/Makefile,v 1.2.2.2 2001/04/25 11:29:26 ru Exp $
# $DragonFly: src/usr.bin/lesskey/Makefile,v 1.2 2003/06/17 04:29:27 dillon Exp $

PROG=	lesskey
SRCS=	lesskey.c version.c
CLEANFILES= lesskey.1
WARNS?=	2

.include "${.CURDIR}/../less/Makefile.common"
.include <bsd.prog.mk>
