#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.sbin/chown/Makefile,v 1.5.2.1 2001/04/25 12:09:22 ru Exp $
# $DragonFly: src/usr.sbin/chown/Makefile,v 1.2 2003/06/17 04:29:52 dillon Exp $

PROG=	chown
CFLAGS+=-DSUPPORT_DOT
MAN=	chgrp.1 chown.8
LINKS=	${BINDIR}/chown /usr/bin/chgrp

.include <bsd.prog.mk>
