# $FreeBSD: src/sys/modules/isp/Makefile,v 1.4 2008/05/04 14:59:24 marius Exp $

KMOD=	isp
SRCS=	bus_if.h device_if.h pci_if.h \
	opt_cam.h opt_isp.h \
	isp.c isp_library.c isp_target.c isp_freebsd.c isp_pci.c

.include <bsd.kmod.mk>
