# $FreeBSD: src/share/doc/legal/intel_iwi/Makefile,v 1.2 2007/03/02 18:10:55 flz Exp $

NOOBJ=
FILES=		${.CURDIR}/../../../../sys/contrib/dev/iwi/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal/intel_iwi

.include <bsd.prog.mk>
