#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/sbin/mknod/Makefile,v 1.2.14.1 2001/04/25 10:58:32 ru Exp $
# $DragonFly: src/sbin/mknod/Makefile,v 1.3 2005/01/01 23:09:57 cpressey Exp $

PROG=	mknod
MAN=	mknod.8
WARNS?=	6

.include <bsd.prog.mk>
