#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: head/share/doc/smm/03.fsck/Makefile 216178 2010-12-04 10:11:20Z uqs $

VOLUME=	smm/03.fsck
SRCS=	0.t 1.t 2.t 3.t 4.t
MACROS=	-ms

.include <bsd.doc.mk>
