# $FreeBSD: src/usr.sbin/stallion/Makefile,v 1.4.2.1 2001/08/30 12:29:57 murray Exp $
# $DragonFly: src/usr.sbin/stallion/Makefile,v 1.2 2003/06/17 04:30:03 dillon Exp $

SUBDIR=	bootcode stlload stlstats stlstty

.include <bsd.subdir.mk>
