# $FreeBSD: src/gnu/usr.bin/binutils/libopcodes/Makefile.i386,v 1.2.2.2 2002/09/01 23:39:17 obrien Exp $
# $DragonFly: src/gnu/usr.bin/binutils214/libopcodes/Attic/Makefile.amd64,v 1.1 2004/02/02 05:43:11 dillon Exp $

SRCS+=	i386-dis.c
CFLAGS+= -DARCH_i386
