# Makefile.modules - build the modules (executed from the modules: target
# in Makefile).
#
# $DragonFly: src/sys/Makefile.modules,v 1.1 2003/08/16 22:00:16 dillon Exp $
SUBDIR=bus crypto emulation dev kern net netgraph netproto vfs

.include <bsd.subdir.mk>

