# Makefile.modules - build the modules (executed from the modules: target
# in Makefile).
#
# $DragonFly: src/sys/Makefile.modules,v 1.2 2003/10/20 04:47:30 dillon Exp $
SUBDIR=bus checkpt crypto emulation dev kern net netgraph netproto vfs

.include <bsd.subdir.mk>

