# $FreeBSD: src/usr.sbin/lpr/filters.ru/Makefile,v 1.5.2.2 2002/04/28 23:17:09 gad Exp $
# $DragonFly: src/usr.sbin/lpr/filters.ru/Makefile,v 1.2 2003/06/17 04:29:56 dillon Exp $

SUBDIR=	koi2alt koi2855

FILES=	bjc-240.sh.sample

.include "Makefile.inc"
.include <bsd.prog.mk>
