# $FreeBSD: src/usr.sbin/lpr/filters.ru/Makefile.inc,v 1.1.2.1 2002/02/01 01:03:40 gad Exp $
# $DragonFly: src/usr.sbin/lpr/filters.ru/Makefile.inc,v 1.2 2003/06/17 04:29:56 dillon Exp $

BINDIR=	/usr/libexec/lpr/ru
