.\" (c) Copyright 2010 by Matthew Dillon and Dima Ruban.  Permission to
.\"    use and distribute based on the DragonFly copyright.
.\"
.Dd June 28, 2010
.Dt POWERD 8
.Os
.Sh NAME
.Nm powerd
.Nd simple acpi-based cpu/power control
.Sh SYNOPSIS
.Nm
.Op Fl d
.Sh DESCRIPTION
The
.Nm
daemon monitors the cpu load and automatically adjusts the cpu
frequency up or down.
.Pp
All cpus will be set to their maximum frequency when the 1-second
machine load exceeds 25% of one cpu.  All cpus will be set to their
minimum frequency when the 10-second machine load drops below 12% of
one cpu.
.Sh DIAGNOSTICS
The
.Nm
utility will exit with a non-zero code if the required sysctls are not
present.
.Sh SEE ALSO
.Xr acpi 4
.Sh HISTORY
The
.Nm
command first appeared in
.Dx 2.8
.Sh BUGS
I'm shocked I tell you, shocked that there might be bugs in this program!
