.\" (c) Copyright 2010 by Matthew Dillon and Dima Ruban.  Permission to
.\"    use and distribute based on the DragonFly copyright.
.\"
.Dd October 28, 2014
.Dt POWERD 8
.Os
.Sh NAME
.Nm powerd
.Nd simple ACPI based CPU/power control
.Sh SYNOPSIS
.Nm
.Op Fl dt
.Op Fl p Ar hysteresis
.Op Fl u Ar trigger_up
.Op Fl r Ar poll_time
.Op Fl T Ar sample_time
.Sh DESCRIPTION
The
.Nm
daemon monitors the CPU load and automatically adjusts the CPU
frequency up or down.
.Pp
All CPUs will be set to their maximum frequency when the 1 second
machine load exceeds 25% of one CPU.
All CPUs will be set to their
minimum frequency when the 10 second machine load drops below 12% of
one CPU.
.Pp
The options are as follows:
.Bl -tag -width ".Fl p Ar hysteresis"
.It Fl d
Debug option.
Causes
.Nm
to not go to the background and prints some debug output to
.Va stdout .
.It Fl p Ar hysteresis
Percent of the upper limit to subtract as an hysteresis value to scale
down to the min frequency.
The default is 10 (meaning 10%).
.It Fl t
Turbo mode.
Disables switching to turbo mode as maximum frequency completely.
Switching to turbo mode as maximum frequency is enabled by default,
if the CPU supports it.
.It Fl u Ar trigger_up
Per CPU load limit in percent to force maximum frequency.
The default is 25 (meaning an instantanious load of 0.25 on a
single cpu).  The load is calculated over 3 polls.
It is suggested that this value not be made lower than
around 7.
.It Fl r Ar poll_time
Polling time in seconds.  Default is 1.0.
Setting this value lower will poll for load changes faster.
For example, a workstation might want to use 0.2 or 0.4.
.Nm can become unstable if you make this value too small.
.It Fl T Ar sample_time
Total sample interval in seconds.  Default is 8.0.
This effects how quickly powerd ratchets down the frequency
and cpus on an idle machine.  Longer times will ratchet down
more slowly.
For example, a workstation might want to use a value of 30.0.
.El
.Sh DIAGNOSTICS
The
.Nm
utility will exit with a non-zero code if the required sysctls are not
present.
.Sh SEE ALSO
.Xr acpi 4 ,
.Xr est 4 ,
.Xr powernow 4
.Sh HISTORY
The
.Nm
command first appeared in
.Dx 2.7 .
.Sh BUGS
I'm shocked I tell you, shocked that there might be bugs in this program!
