# $FreeBSD: src/usr.sbin/i4b/Makefile,v 1.4.2.2 2002/04/24 18:50:03 joerg Exp $
# $DragonFly: src/usr.sbin/i4b/Makefile,v 1.2 2003/06/17 04:29:53 dillon Exp $

SUBDIR=	dtmfdecode g711conv isdnd isdndebug isdndecode isdnmonitor isdnphone \
	isdntel isdntelctl isdntest isdntrace man

.include <bsd.subdir.mk>

