SUBDIR=	pam_chroot \
	pam_deny \
	pam_echo \
	pam_exec \
	pam_ftpusers \
	pam_group \
	pam_guest \
	pam_lastlog \
	pam_login_access \
	pam_nologin \
	pam_passwdqc \
	pam_permit \
	pam_rhosts \
	pam_rootok \
	pam_securetty \
	pam_self \
	pam_unix

# maximum parallelism
#
SUBDIR_ORDERED=

.include <bsd.subdir.mk>
