# $FreeBSD: src/secure/usr.bin/ssh-keyscan/Makefile,v 1.1.2.3 2002/07/03 22:20:32 des Exp $
# $DragonFly: src/secure/usr.bin/ssh-vulnkey/Makefile,v 1.1 2008/05/16 11:44:56 corecode Exp $

PROG=	ssh-vulnkey
SRCS=	ssh-vulnkey.c roaming_dummy.c
WARNS?=	2

.include "../../Makefile.ssh.common"
.include <bsd.prog.mk>
