# $FreeBSD: src/sys/modules/syscons/daemon/Makefile,v 1.6.2.2 2002/12/01 09:01:09 nyan Exp $
# $DragonFly: src/sys/dev/misc/syscons/daemon/Attic/Makefile,v 1.2 2003/06/17 04:28:47 dillon Exp $

KMOD=	daemon_saver
SRCS= 	daemon_saver.c

NOMAN=
CFLAGS+= -I${.CURDIR}/..

.include <bsd.kmod.mk>
