# $FreeBSD: src/sbin/dumpon/Makefile,v 1.4.2.1 2001/04/25 10:58:16 ru Exp $
# $DragonFly: src/sbin/dumpon/Makefile,v 1.4 2006/10/17 00:55:40 pavalos Exp $

PROG=	dumpon
MAN=	dumpon.8

.include <bsd.prog.mk>
