# $FreeBSD: src/sbin/dumpon/Makefile,v 1.4.2.1 2001/04/25 10:58:16 ru Exp $
# $DragonFly: src/sbin/dumpon/Makefile,v 1.2 2003/06/17 04:27:32 dillon Exp $

PROG=	dumpon
MAN=	dumpon.8

.include <bsd.prog.mk>
