# $FreeBSD: src/sbin/dumpon/Makefile,v 1.4.2.1 2001/04/25 10:58:16 ru Exp $
# $DragonFly: src/sbin/dumpon/Makefile,v 1.3 2005/01/14 06:02:45 cpressey Exp $

PROG=	dumpon
WARNS?=	6
MAN=	dumpon.8

.include <bsd.prog.mk>
