.PATH: ${.CURDIR}/../../../../../../usr.sbin/installer/libaura/

PROG=dict2
SRCS=dict2.c mem.c dict.c

CLEANFILES+=	*.core

CFLAGS+= -I${.CURDIR}/../../../../../../usr.sbin/installer/libaura
NOMAN=

.include <bsd.prog.mk>
