.PATH: ${.CURDIR}/../../../crypto/libressl/apps/openssl

NOOBJ=	noobj
FILES=	cert.pem openssl.cnf
FILESDIR=	/usr/share/examples/etc/ssl
FILESOWN=	${BINOWN}
FILESGRP=	${BINGRP}
FILESMODE=	644

.include <bsd.prog.mk>
