.\"
.\" Copyright (c) 2014 The DragonFly Project.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd April 10, 2014
.Dt ACPIBIN 8
.Os
.Sh NAME
.Nm acpibin
.Nd miscellaneous manipulation of binary ACPI tables
.Sh SYNOPSIS
.Nm
.Op Ar option ...
.Sh DESCRIPTION
The following options are supported:
.Bl -tag -width indent
.It Fl c Ar file1 Ar file2
Compare two binary AML files.
.It Fl d Ar in Ar out
Dump AML binary to text file.
.It Fl e Ar sig Ar in Ar out
Extract binary AML table from AcpiDump file.
.It Fl h Ar file
Display table header for binary AML file.
.It Fl s Ar file
Update checksum for binary AML file.
.It Fl t
Terse mode.
.It Fl v
Display version information.
.El
.Sh SEE ALSO
.Xr acpi 4 ,
.Xr acpiconf 8 ,
.Xr acpidump 8 ,
.Xr acpiexec 8 ,
.Xr acpihelp 8 ,
.Xr acpinames 8 ,
.Xr acpixtract 8 ,
.Xr iasl 8
.Pp
.Lk https://acpica.org/documentation/
.Sh AUTHORS
The
.Nm
utility is provided by
.Tn Intel
as part of their
.Sy ACPICA
distribution.
.Pp
This manual page was written by
.An Sascha Wildner .
