# $FreeBSD: src/lib/libc/alpha/stdlib/Makefile.inc,v 1.3 1999/08/27 23:58:09 peter Exp $
# $DragonFly: src/lib/libcr/alpha/stdlib/Attic/Makefile.inc,v 1.2 2003/06/17 04:26:41 dillon Exp $

MDSRCS+=	abs.c div.c labs.c ldiv.c
