#ifndef _ECC_E5_REG_H_
#define _ECC_E5_REG_H_

#ifndef _SYS_BITOPS_H_
#include <sys/bitops.h>
#endif

#define PCI_E5_VID_ID				0x8086
#define PCI_E5_IMC_DIMM_MAX			3
#define PCI_E5_IMC_ERROR_RANK_MAX		8

#define PCISLOT_E5_UBOX0			11
#define PCIFUNC_E5_UBOX0			0
#define PCI_E5_UBOX0_DID_ID			0x0e1e
#define PCI_E5_UBOX0_CPUNODEID			0x40
#define PCI_E5_UBOX0_CPUNODEID_LCLNODEID	__BITS(0, 2) /* local socket */

#define PCISLOT_E5_IMC_CPGC			15
#define PCIFUNC_E5_IMC_CPGC			0
#define PCI_E5_IMC_CPGC_DID_ID			0x0ea8
#define PCI_E5_IMC_CPGC_MCMTR			0x7c
#define PCI_E5_IMC_CPGC_MCMTR_CHN_DISABLE(c)	__BIT(16 + (c))
#define PCI_E5_IMC_CPGC_MCMTR_IMC_MODE		__BITS(12, 13)
#define PCI_E5_IMC_CPGC_MCMTR_IMC_MODE_DDR3	0
#define PCI_E5_IMC_CPGC_MCMTR_ECC_EN		__BIT(2)

/* Channel Target Address Decoder, per-channel */
#define PCISLOT_E5_IMC_CTAD			15
#define PCIFUNC_E5_IMC_CTAD(c)			(2 + (c))
#define PCI_E5_IMC_CTAD_DID_ID(c)		(0x0eaa + (c))
#define PCI_E5_IMC_CTAD_DIMMMTR(dimm)		(0x80 + ((dimm) * 4))
#define PCI_E5_IMC_CTAD_DIMMMTR_RANK_DISABLE(r)	__BIT(16 + (r))
#define PCI_E5_IMC_CTAD_DIMMMTR_RANK_DISABLE_ALL __BITS(16, 19)
#define PCI_E5_IMC_CTAD_DIMMMTR_DIMM_POP	__BIT(14)
#define PCI_E5_IMC_CTAD_DIMMMTR_RANK_CNT	__BITS(12, 13)
#define PCI_E5_IMC_CTAD_DIMMMTR_RANK_CNT_SR	0
#define PCI_E5_IMC_CTAD_DIMMMTR_RANK_CNT_DR	1
#define PCI_E5_IMC_CTAD_DIMMMTR_RANK_CNT_QR	2
#define PCI_E5_IMC_CTAD_DIMMMTR_RANK_CNT_RSVD	3
#define PCI_E5_IMC_CTAD_DIMMMTR_DDR3_WIDTH	__BITS(7, 8)
#define PCI_E5_IMC_CTAD_DIMMMTR_DDR3_WIDTH_4	0
#define PCI_E5_IMC_CTAD_DIMMMTR_DDR3_WIDTH_8	1
#define PCI_E5_IMC_CTAD_DIMMMTR_DDR3_WIDTH_16	2
#define PCI_E5_IMC_CTAD_DIMMMTR_DDR3_WIDTH_RSVD	3
#define PCI_E5_IMC_CTAD_DIMMMTR_DDR3_DNSTY	__BITS(5, 6)
#define PCI_E5_IMC_CTAD_DIMMMTR_DDR3_DNSTY_1G	0
#define PCI_E5_IMC_CTAD_DIMMMTR_DDR3_DNSTY_2G	1
#define PCI_E5_IMC_CTAD_DIMMMTR_DDR3_DNSTY_4G	2
#define PCI_E5_IMC_CTAD_DIMMMTR_DDR3_DNSTY_8G	3

/* ERROR, per-channel */
#define PCISLOT_E5_IMC_ERROR			16
#define PCIFUNC_E5_IMC_ERROR_CHN0		2
#define PCIFUNC_E5_IMC_ERROR_CHN1		3
#define PCIFUNC_E5_IMC_ERROR_CHN2		6
#define PCIFUNC_E5_IMC_ERROR_CHN3		7
#define PCI_E5_IMC_ERROR_CHN0_DID_ID		0x0eb2
#define PCI_E5_IMC_ERROR_CHN1_DID_ID		0x0eb3
#define PCI_E5_IMC_ERROR_CHN2_DID_ID		0x0eb6
#define PCI_E5_IMC_ERROR_CHN3_DID_ID		0x0eb7
#define PCI_E5_IMC_ERROR_COR_ERR_CNT(i)		(0x104 + ((i) * 4))
#define PCI_E5_IMC_ERROR_COR_ERR_CNT_HI_OVFL	__BIT(31)
#define PCI_E5_IMC_ERROR_COR_ERR_CNT_HI		__BITS(16, 30)
#define PCI_E5_IMC_ERROR_COR_ERR_CNT_LO_OVFL	__BIT(15)
#define PCI_E5_IMC_ERROR_COR_ERR_CNT_LO		__BITS(0, 14)
#define PCI_E5_IMC_ERROR_COR_ERR_TH(i)		(0x11c + ((i) * 4))
#define PCI_E5_IMC_ERROR_COR_ERR_TH_HI		__BITS(16, 30)
#define PCI_E5_IMC_ERROR_COR_ERR_TH_LO		__BITS(0, 14)
#define PCI_E5_IMC_ERROR_COR_ERR_STAT		0x134
#define PCI_E5_IMC_ERROR_COR_ERR_STAT_RANKS	__BITS(0, 7)

#endif	/* !_ECC_E5_REG_H_ */
