#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/en_US.ISO8859-1/books/handbook/x11/Makefile,v 1.1 2001/06/30 14:55:40 nik Exp $
# $DragonFly: doc/en/books/handbook/x11/Makefile,v 1.1 2004/06/25 15:24:35 justin Exp $
#

CHAPTERS= 	x11/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
