# $NetBSD: Makefile,v 1.1 2001/08/17 21:42:10 thorpej Exp $
# $DragonFly: src/sbin/brconfig/Attic/Makefile,v 1.1 2005/12/21 16:33:20 corecode Exp $

PROG=	brconfig
MAN=	brconfig.8

.include <bsd.prog.mk>
