# $FreeBSD: src/lib/csu/amd64/Makefile,v 1.18 2003/06/30 12:53:39 ru Exp $
# $DragonFly: src/lib/csu/amd64/Makefile.csu,v 1.2 2007/07/11 21:12:50 corecode Exp $

CSUDIR?=	${.CURDIR}

SRCS+=		crt1.c crti.S crtn.S
OBJS+=		gcrt1.o
INSTALLOBJS+=	crt1.o crti.o crtn.o gcrt1.o

CFLAGS+=	-I${CSUDIR}/../common \
		-I${CSUDIR}/../../libc/include

.PATH:		${CSUDIR} ${CSUDIR}/../common

gcrt1.o: crt1.c
	${CC} ${CFLAGS} -DGCRT -c -o gcrt1.o ${CSUDIR}/crt1.c
