# $DragonFly: src/gnu/usr.bin/cc40/cc_tools/genconditions/Attic/Makefile,v 1.1 2005/06/05 22:43:20 corecode Exp $

.include "../Makefile.inc"

PROG=	genconditions
SRCS=	genconditions.c insn-modes.h gtype-desc.h
SRCS+=	${EARLY_SRCS} ${RTL_SRCS} ${ERRORS_SRCS}

.include <bsd.hostprog.mk>
