# $FreeBSD: src/libexec/mknetid/Makefile,v 1.4.2.2 2001/08/21 16:45:16 ru Exp $
# $DragonFly: src/libexec/mknetid/Makefile,v 1.2 2003/06/17 04:27:07 dillon Exp $

PROG=	mknetid
SRCS=	mknetid.c hash.c parse_group.c

MAN=	netid.5 mknetid.8

.include <bsd.prog.mk>
