# $FreeBSD: src/sys/modules/sbsh/Makefile,v 1.1.2.1 2003/04/15 18:15:08 fjoe Exp $
# $DragonFly: src/sys/dev/netif/sbsh/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $

.PATH: ${.CURDIR}/../../dev/sbsh

KMOD=	if_sbsh
SRCS=	if_sbsh.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
