#
# $FreeBSD: src/sbin/mount_ntfs/Makefile,v 1.2.2.2 2001/10/12 22:08:43 semenu Exp $
#

PROG=	mount_ntfs
MAN=	mount_ntfs.8
DPADD=	${LIBUTIL} ${LIBKICONV}
LDADD=	-lutil -lkiconv

.include <bsd.prog.mk>
