# $FreeBSD: src/kerberosIV/usr.sbin/Makefile.inc,v 1.2 1999/08/28 01:31:33 peter Exp $
# $DragonFly: src/kerberosIV/usr.sbin/Attic/Makefile.inc,v 1.2 2003/06/17 04:26:25 dillon Exp $

BINDIR=	/usr/sbin

.include "../Makefile.inc"
