# $FreeBSD: src/sys/modules/canbus/Makefile,v 1.1.2.1 2003/02/10 13:11:51 nyan Exp $
# $DragonFly: src/sys/bus/canbus/Attic/Makefile,v 1.3 2003/08/15 01:19:47 dillon Exp $

KMOD	= canbus
SRCS	= canbus.c
SRCS	+= device_if.h bus_if.h canbus_if.h canbus_if.c

.include <bsd.kmod.mk>
