# Makefile.inc
# $FreeBSD: src/libexec/bootpd/tools/Makefile.inc,v 1.4.2.1 2001/04/25 10:40:49 ru Exp $
# $DragonFly: src/libexec/bootpd/tools/Makefile.inc,v 1.2 2003/06/17 04:27:07 dillon Exp $

BINDIR=		/usr/sbin
