# ASF - Add Symbol Files, a helper utility for debugging kernel modules
# $FreeBSD$
# $DragonFly: src/usr.sbin/asf/Makefile,v 1.1 2004/06/18 21:20:55 hmp Exp $

PROG=	asf
MAN=	asf.8

.include <bsd.prog.mk>
