# $FreeBSD: src/sbin/pc98/fdisk/Makefile,v 1.1.2.2 2001/04/25 10:58:45 ru Exp $
# $DragonFly: src/sbin/pc98/fdisk/Attic/Makefile,v 1.2 2003/06/17 04:27:34 dillon Exp $

PROG=	fdisk
MAN=	fdisk.8

CFLAGS	+= -DPC98

.include <bsd.prog.mk>
