# $FreeBSD: src/usr.sbin/ctm/Makefile.inc,v 1.4 1999/08/28 01:15:58 peter Exp $
# $DragonFly: src/usr.sbin/ctm/Attic/Makefile.inc,v 1.2 2003/06/17 04:29:53 dillon Exp $

.if exists(${.CURDIR}/../../Makefile.inc)
.include "${.CURDIR}/../../Makefile.inc"
.endif
