#!/bin/sh

FSTYPE=$2
MOUNTFROM="/dev/${3#/dev/}"
VOLUME=$4
OPTIONS=$5

cryptsetup isLuks $MOUNTFROM || {
	echo "ERROR: not a LUKS device: $MOUNTFROM"
	return 1
}
cryptsetup $OPTIONS luksOpen $MOUNTFROM $VOLUME || {
	echo "ERROR: failed to open LUKS device: $MOUNTFROM"
	return 2
}
mount -o ro -t $FSTYPE /dev/mapper/$VOLUME $NEW_ROOT || {
	echo "ERROR: failed to mount $FSTYPE from /dev/mapper/$VOLUME"
	return 3
}
