#!/bin/sh

FSTYPE=$2
DEVICE="/dev/${3#/dev/}"
VOLUME=$4
OPTIONS=$5

# Handle the PFS label of a HAMMER/HAMMER2 filesystem.
LABEL=
case $DEVICE in
*@*)
	LABEL="@${DEVICE#*@}"
	DEVICE=${DEVICE%@*}
	;;
esac
MOUNTFROM="/dev/mapper/${VOLUME}${LABEL}"

tcplay -m $VOLUME -d $DEVICE $OPTIONS || {
	echo "ERROR: failed to open tcplay device: $DEVICE"
	return 2
}
mount -o ro -t $FSTYPE $MOUNTFROM $NEW_ROOT || {
	echo "ERROR: failed to mount $FSTYPE from $MOUNTFROM"
	return 3
}
