#	@(#)Makefile	8.6 (Berkeley) 5/8/95
# $FreeBSD: src/sbin/mount/Makefile,v 1.9.2.1 2001/04/25 10:58:33 ru Exp $

PROG=	mount
SRCS=	mount.c vfslist.c
MAN=	mount.8

LDADD=	-lutil
DPADD=	${LIBUTIL}

DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
