#	@(#)Makefile	8.6 (Berkeley) 5/8/95
# $FreeBSD: src/sbin/mount/Makefile,v 1.9.2.1 2001/04/25 10:58:33 ru Exp $
# $DragonFly: src/sbin/mount/Makefile,v 1.2 2003/06/17 04:27:33 dillon Exp $

PROG=	mount
SRCS=	mount.c mount_ufs.c getmntopts.c vfslist.c
MAN=	mount.8
# We do NOT install the getmntopts.3 man page.

.include <bsd.prog.mk>
