# $FreeBSD: head/sys/modules/sound/driver/t4dwave/Makefile 110498 2003-02-07 13:56:33Z nyan $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_t4dwave
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	t4dwave.c

.include <bsd.kmod.mk>
