# $FreeBSD: src/sys/modules/netgraph/echo/Makefile,v 1.1.4.3 2001/12/21 09:00:48 ru Exp $
# $DragonFly: src/sys/netgraph/echo/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:20 archie Exp $

KMOD=		ng_echo
SRCS= 		ng_echo.c

.include <bsd.kmod.mk>
