# $FreeBSD: src/tools/tools/ifinfo/Makefile,v 1.4 1999/08/28 00:54:28 peter Exp $
# $DragonFly: src/tools/tools/ifinfo/Makefile,v 1.2 2003/06/17 04:29:11 dillon Exp $

PROG=	ifinfo
SRCS=	ifinfo.c rfc1650.c
NOMAN=

.include <bsd.prog.mk>
