#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/printf/Makefile,v 1.1.1.1.14.1 2002/04/29 16:45:16 jmallett Exp $
# $DragonFly: src/usr.bin/printf/Makefile,v 1.3 2004/12/31 20:32:59 cpressey Exp $

PROG=	printf
WARNS?=	7

.include <bsd.prog.mk>
