#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/abi,v 1.2 2003/05/05 15:38:41 mtm Exp $
# $DragonFly: src/etc/rc.d/abi,v 1.6 2008/01/09 18:51:08 josepht Exp $
#

# PROVIDE: abi
# REQUIRE: LOGIN
# BEFORE:  securelevel

. /etc/rc.subr

echo -n 'Additional ABI support:'

name="sysvipc"
rcvar=`set_rcvar`
start_cmd="sysv_start"
stop_cmd=":"

sysv_start()
{
	echo -n ' sysvipc'
	kldload sysvmsg >/dev/null 2>&1
	kldload sysvsem >/dev/null 2>&1
	kldload sysvshm >/dev/null 2>&1
}
load_rc_config $name
run_rc_command "$1"

name="linux"
rcvar=`set_rcvar`
start_cmd="linux_start"

linux_start()
{
	echo -n ' linux'
	if ! kldstat -q -m "linuxaout" || ! kldstat -q -m "linuxelf"; then
		kldload linux > /dev/null 2>&1
	fi
	if [ -x /compat/linux/sbin/ldconfig ]; then
		/compat/linux/sbin/ldconfig
	fi
}
load_rc_config $name
run_rc_command "$1"

echo '.'
