#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/abi,v 1.2 2003/05/05 15:38:41 mtm Exp $
#

# PROVIDE: abi
# REQUIRE: LOGIN
# BEFORE:  securelevel

. /etc/rc.subr

echo -n 'Additional ABI support:'

name="linux"
rcvar=`set_rcvar`
start_cmd="linux_start"

linux_start()
{
	echo -n ' linux'
	kldload -n linux
	if [ -x /compat/linux/sbin/ldconfig ]; then
		/compat/linux/sbin/ldconfig
	fi
}
load_rc_config $name
run_rc_command "$1"

echo '.'
