#!/bin/sh
#
# $NetBSD: accounting,v 1.7 2002/03/22 04:33:57 thorpej Exp $
# $FreeBSD: src/etc/rc.d/accounting,v 1.4 2002/10/12 10:31:31 schweikh Exp $
# $DragonFly: src/etc/rc.d/accounting,v 1.3 2004/01/26 17:21:15 rob Exp $
#

# PROVIDE: accounting
# REQUIRE: mountall
# BEFORE: DAEMON
# KEYWORD: DragonFly 

. /etc/rc.subr

name="accounting"
rcvar=`set_rcvar`
accounting_command="/usr/sbin/accton"
accounting_file="/var/account/acct"
start_cmd="accounting_start"
stop_cmd="accounting_stop"

accounting_start()
{
	_dir=`dirname "$accounting_file"`
	if [ ! -d `dirname "$_dir"` ]; then
		if ! mkdir -p "$_dir"; then
			warn "Could not create $_dir."
			return 1
		fi
	fi
	if [ ! -e "$accounting_file" ]; then
		touch "$accounting_file"
	fi
	echo "Turning on accounting."
	${accounting_command} ${accounting_file}
}

accounting_stop()
{
	echo "Turning off accounting."
	${accounting_command}
}

load_rc_config $name
run_rc_command "$1"
