#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/adjkerntz,v 1.2 2003/04/18 17:55:05 mtm Exp $
# $DragonFly: src/etc/rc.d/adjkerntz,v 1.3 2005/11/19 21:47:32 swildner Exp $
#

# PROVIDE: adjkerntz
# REQUIRE: diskless mountcritlocal random
# BEFORE: netif

. /etc/rc.subr

name="adjkerntz"
start_cmd="adjkerntz -i"
stop_cmd=":"

load_rc_config $name
run_rc_command "$1"
