#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/adjkerntz,v 1.2 2003/04/18 17:55:05 mtm Exp $
# $DragonFly: src/etc/rc.d/adjkerntz,v 1.1 2003/07/24 06:35:37 dillon Exp $
#

# PROVIDE: adjkerntz
# REQUIRE: diskless mountcritlocal random
# BEFORE: netif
# KEYWORD: DragonFly FreeBSD 

. /etc/rc.subr

name="adjkerntz"
start_cmd="adjkerntz -i"
stop_cmd=":"

load_rc_config $name
run_rc_command "$1"
