#!/bin/sh
#
# $NetBSD: amd,v 1.10 2002/04/29 12:08:17 lukem Exp $
# $FreeBSD: src/etc/rc.d/amd,v 1.9 2002/10/12 10:31:31 schweikh Exp $
# $DragonFly: src/etc/rc.d/amd,v 1.5 2005/11/19 21:47:32 swildner Exp $
#

# PROVIDE: amd
# REQUIRE: rpcbind mountcritremote ypbind nfsclient
# BEFORE: DAEMON

. /etc/rc.subr

name="amd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

	start_precmd="amd_precmd"
	command_args="&"

amd_precmd()
{
		if ! checkyesno nfs_client_enable; then
			force_depend nfsclient || return 1
		fi

		if ! checkyesno rpcbind_enable  && \
			! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
			then
				force_depend rpcbind || return 1
		fi

		case ${amd_map_program} in
			[Nn][Oo] | '')
			;;
		*)
			rc_flags="${rc_flags} `eval ${amd_map_program}`"
			;;
		esac

		case "${amd_flags}" in
			'')
			if [ ! -r /etc/amd.conf ]; then
				warn 'amd will not load without arguments'
				return 1
			fi
			;;
		esac
}

load_rc_config $name
run_rc_command "$1"
