#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/archdep,v 1.5 2003/05/06 00:09:51 obrien Exp $
# $DragonFly: src/etc/rc.d/Attic/archdep,v 1.6 2006/08/25 22:37:08 swildner Exp $
#

# PROVIDE: archdep
# REQUIRE: LOGIN
# BEFORE: abi

. /etc/rc.subr

name=archdep
load_rc_config $name

# should we print out unaligned access warnings?
#
unaligned_warnings()
{
	if ! checkyesno unaligned_print; then
		sysctl machdep.unaligned_print=0
	fi
}

_arch=`${SYSCTL_N} hw.machine`
echo -n "Initial $_arch initialization:"
case $_arch in
i386)
	;;
ia64)
	unaligned_warnings
	;;
esac

dummy_rc_command "$1"

echo '.'
