#!/bin/sh
#
# $DragonFly: src/etc/rc.d/battd,v 1.2 2005/11/19 21:47:32 swildner Exp $
#

# PROVIDE: battd
# REQUIRE: DAEMON apm
# BEFORE:  LOGIN

. /etc/rc.subr

name="battd"
rcvar=`set_rcvar`
start_precmd="battd_precmd"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

battd_precmd()
{
	case `${SYSCTL_N} hw.machine_arch` in
	i386)
		# Enable apm if it is not already enabled
		if ! checkyesno apm_enable  && \
		    ! /etc/rc.d/apm forcestatus 1>/dev/null 2>&1
		then
			force_depend apm || return 1
		fi
		;;
	*)
		return 1
		;;
	esac
	return 0
}

load_rc_config $name
run_rc_command "$1"
