#!/bin/sh
#
# $NetBSD: bthcid,v 1.1 2006/06/19 15:44:36 gdamore Exp $
# $DragonFly: src/etc/rc.d/bthcid,v 1.1 2008/01/30 14:10:19 hasso Exp $

# PROVIDE: bthcid
# REQUIRE: bluetooth
# BEFORE: LOGIN

$rc_subr_loaded . /etc/rc.subr

name="bthcid"
rcvar=$name

command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
