#!/bin/sh
#
# $NetBSD: ccd,v 1.3 2000/05/13 08:45:06 lukem Exp $
# $FreeBSD: src/etc/rc.d/ccd,v 1.2 2002/06/13 22:14:36 gordon Exp $
# $DragonFly: src/etc/rc.d/ccd,v 1.1 2003/07/24 06:35:37 dillon Exp $
#

# PROVIDE: disks
# KEYWORD: DragonFly FreeBSD NetBSD

. /etc/rc.subr

name="ccd"
start_cmd="ccd_start"
stop_cmd=":"

ccd_start()
{
	if [ -f /etc/ccd.conf ]; then
		echo "Configuring CCD devices."
		ccdconfig -C
	fi
}

load_rc_config $name
run_rc_command "$1"
