#!/bin/sh
#
# Load default devfs(5) rules.
#

# PROVIDE: devfs
# REQUIRE: rcconf
# BEFORE:  disks

. /etc/rc.subr

name="devfs"

load_rc_config $name
dummy_rc_command "$1"

load_rules()
{
	echo -n "Loading devfs rules:"
	set -- $devfs_config_files
	for file; do
		if [ -r $file ]; then
			echo -n " $file"
			/sbin/devfsctl -a -f $file
		fi
	done
	echo '.'
}

case "$1" in
*start)
	load_rules
	;;
esac
