#!/bin/sh
#
# $NetBSD: dhcpd,v 1.5 2002/03/22 04:33:58 thorpej Exp $
# $FreeBSD: src/etc/rc.d/dhcpd,v 1.2 2002/06/13 22:14:36 gordon Exp $
# $DragonFly: src/etc/rc.d/Attic/dhcpd,v 1.2 2005/01/12 02:32:15 joerg Exp $
#

# PROVIDE: dhcpd
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: DragonFly

. /etc/rc.subr

name="dhcpd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf /var/db/${name}.leases"

load_rc_config $name
run_rc_command "$1"
