#!/bin/sh
#
#$DragonFly: src/etc/rc.d/dntpd,v 1.2 2005/11/19 21:47:32 swildner Exp $

# PROVIDE: dntpd
# REQUIRE: NETWORKING
# BEFORE:  LOGIN

. /etc/rc.subr

name=dntpd
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
required_files=""
load_rc_config $name
run_rc_command "$1"
