#!/bin/sh

# PROVIDE: ftpd
# REQUIRE: DAEMON
# BEFORE:  LOGIN

. /etc/rc.subr

name="ftpd"
rcvar=`set_rcvar`
pidfile="/var/run/${name}.pid"
command="/usr/libexec/${name}"
command_args="-D -p $pidfile"

load_rc_config $name
run_rc_command "$1"
