#!/bin/sh
#
# $NetBSD: gated,v 1.3 2000/05/13 08:45:06 lukem Exp $
# $DragonFly: src/etc/rc.d/Attic/gated,v 1.1 2003/07/24 06:35:37 dillon Exp $
#

# PROVIDE: gated
# REQUIRE: DAEMON

. /etc/rc.subr

name="gated"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"

load_rc_config $name
run_rc_command "$1"
