#!/bin/sh
#
# $DragonFly: src/etc/rc.d/Attic/ifwatchd,v 1.1 2003/07/24 06:35:37 dillon Exp $
#

# PROVIDE: ifwatchd
# REQUIRE: mountcritremote network

. /etc/rc.subr

name="ifwatchd"
rcvar=$name
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"

