#!/bin/sh
#
# $NetBSD: inetd,v 1.6 2000/09/19 13:04:38 lukem Exp $
# $FreeBSD: src/etc/rc.d/inetd,v 1.2 2002/06/13 22:14:36 gordon Exp $
# $DragonFly: src/etc/rc.d/inetd,v 1.2 2004/01/26 17:21:15 rob Exp $
#

# PROVIDE: inetd
# REQUIRE: DAEMON LOGIN
# KEYWORD: DragonFly shutdown

. /etc/rc.subr

name="inetd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
