#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/kerberos,v 1.3 2003/03/08 09:50:10 markm Exp $
# $DragonFly: src/etc/rc.d/kerberos,v 1.2 2004/01/26 17:21:15 rob Exp $
#

# PROVIDE: kerberos
# REQUIRE: NETWORKING
# KEYWORD: DragonFly

. /etc/rc.subr

name="kerberos5"
load_rc_config $name
rcvar="kerberos5_server_enable"
command="${kerberos5_server}"
command_args="&"

run_rc_command "$1"
