#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/kpasswdd,v 1.2 2003/05/06 02:28:03 mtm Exp $
# $DragonFly: src/etc/rc.d/kpasswdd,v 1.4 2006/10/24 09:24:15 victor Exp $
#

# PROVIDE: kpasswdd
# REQUIRE: kadmin
# BEFORE: DAEMON

. /etc/rc.subr

name="kpasswdd"
load_rc_config $name
rcvar="kpasswdd_server_enable"
unset start_cmd
command="${kpasswdd_server_program}"
command_args="&"
required_vars="kadmind5_server_enable"

run_rc_command "$1"
