#!/bin/sh
#
# $NetBSD: lpd,v 1.5 2002/03/22 04:33:59 thorpej Exp $
# $FreeBSD: src/etc/rc.d/lpd,v 1.3 2002/09/06 16:18:05 gordon Exp $
# $DragonFly: src/etc/rc.d/lpd,v 1.2 2004/01/27 00:42:45 rob Exp $
#

# PROVIDE: lpd
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: DragonFly

. /etc/rc.subr

name="lpd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
required_files="/etc/printcap"

load_rc_config $name
run_rc_command "$1"
