#!/bin/sh
#
# $DragonFly: src/etc/rc.d/mixer,v 1.3 2004/04/15 12:59:29 joerg Exp $
#

# PROVIDE: mixer
# REQUIRE: lkm

. /etc/rc.subr

name="mixer"
rcvar="mixer"
start_cmd="mixer_start"
stop_cmd="mixer_stop"
mixer_conf=/etc/mixer.conf

mixer_start()
{
	if [ -r $mixer_conf ]; then
		echo "Loading mixer settings"
		cat $mixer_conf| xargs mixer 
	fi
}

mixer_stop()
{
	[ -z "$mixer_conf" ] && return
	if [ -w $mixer_conf -o \( ! -e $mixer_conf -a -w `dirname $mixer_conf` \) ]; then
		echo "Storing mixer settings"
		mixer -s > $mixer_conf
	fi
}

load_rc_config $name
run_rc_command "$1"
