#!/bin/sh
#
# $NetBSD: mountall,v 1.3 2000/05/13 08:45:07 lukem Exp $
# $FreeBSD: src/etc/rc.d/mountall,v 1.2 2002/06/13 22:14:36 gordon Exp $
# $DragonFly: src/etc/rc.d/Attic/mountall,v 1.1 2003/07/24 06:35:37 dillon Exp $
#

# PROVIDE: mountall
# REQUIRE: beforemountlkm

. /etc/rc.subr

name="mountall"
start_cmd="echo 'Mounting all filesystems...'; mount -a"
stop_cmd="echo 'Unmounting all filesystems...'; umount -a"

load_rc_config $name
run_rc_command "$1"
