#!/bin/sh
#
# $NetBSD: moused,v 1.1 2001/10/29 23:25:01 augustss Exp $
# $FreeBSD: src/etc/rc.d/moused,v 1.3 2002/09/27 16:54:21 gordon Exp $
# $DragonFly: src/etc/rc.d/moused,v 1.3 2004/05/12 01:48:40 cpressey Exp $
#

# PROVIDE: moused
# REQUIRE: DAEMON
# KEYWORD: DragonFly

. /etc/rc.subr

name=moused
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
start_cmd="moused_start"
stop_cmd="moused_stop"
sig_stop="-INT"

# stdin must be redirected because it might be for a serial console
#
viddev=/dev/ttyv0

moused_start()
{
	echo -n 'Starting moused:'
	/usr/sbin/moused ${moused_flags} -p ${moused_port} -t ${moused_type}

	_mousechar_arg=
	case ${mousechar_start} in
	[Nn][Oo] | '')
		;;
	*)
		echo -n ' mousechar_start'
		_mousechar_arg="-M ${mousechar_start}"
		;;
	esac

	vidcontrol < ${viddev} ${_mousechar_arg} -m on

	echo '.'
}

moused_stop()
{
	pids="`check_process $command`"
	if [ -n "$pids" ]; then
		for pid in $pids; do
			kill $sig_stop $pid
		done
	fi

	vidcontrol < ${viddev} -m off
}

load_rc_config $name
run_rc_command "$1"
