#!/bin/sh
#
# $NetBSD: mrouted,v 1.6 2002/03/22 04:33:59 thorpej Exp $
# $FreeBSD: src/etc/rc.d/mrouted,v 1.5 2003/06/29 05:15:57 mtm Exp $
# $DragonFly: src/etc/rc.d/mrouted,v 1.1 2003/07/24 06:35:37 dillon Exp $
#

# PROVIDE: mrouted
# REQUIRE: netif routing
# KEYWORD: DragonFly FreeBSD NetBSD

. /etc/rc.subr

name="mrouted"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
