#!/bin/sh
#
# $NetBSD: mrouted,v 1.6 2002/03/22 04:33:59 thorpej Exp $
# $FreeBSD: src/etc/rc.d/mrouted,v 1.5 2003/06/29 05:15:57 mtm Exp $
# $DragonFly: src/etc/rc.d/mrouted,v 1.2 2004/01/27 00:42:45 rob Exp $
#

# PROVIDE: mrouted
# REQUIRE: netif routing
# KEYWORD: DragonFly

. /etc/rc.subr

name="mrouted"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
