#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/mroute6d,v 1.2 2003/01/25 23:14:08 mtm Exp $
# $DragonFly: src/etc/rc.d/mroute6d,v 1.1 2003/07/24 06:35:37 dillon Exp $
#

# PROVIDE: mroute6d
# REQUIRE: network_ipv6
# KEYWORD: DragonFly FreeBSD

. /etc/rc.subr

name="mroute6d"
rcvar=`set_rcvar`
command="/usr/local/sbin/pim6dd"

load_rc_config $name
run_rc_command "$1"
