#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/msgs,v 1.1 2002/06/13 22:14:36 gordon Exp $
# $DragonFly: src/etc/rc.d/msgs,v 1.3 2004/01/27 00:42:45 rob Exp $
#

# PROVIDE: msgs
# REQUIRE: LOGIN
# KEYWORD: DragonFly

. /etc/rc.subr
dummy_rc_command "$1"

# Make a bounds file for msgs(1) if there isn't one already
#
if [ -d /var/msgs -a ! -f /var/msgs/bounds -a ! -L /var/msgs/bounds ]; then
	echo 0 > /var/msgs/bounds
fi
