#!/bin/sh
#
# $NetBSD: nfsd,v 1.4 2001/06/16 06:13:10 lukem Exp $
# $FreeBSD: src/etc/rc.d/nfsd,v 1.9 2003/01/24 00:37:52 mtm Exp $
#

# PROVIDE: nfsd
# REQUIRE: nfsserver rpcbind mountd
# KEYWORD: shutdown

. /etc/rc.subr

name="nfsd"
rcvar=`set_rcvar nfs_server`
command="/sbin/${name}"
start_precmd="nfsd_precmd"
sig_stop="USR1"

nfsd_precmd()
{
	if ! ${SYSCTL} -q vfs.nfs >/dev/null; then
		force_depend nfsserver || return 1
	fi

	if ! checkyesno rpcbind_enable  && \
	   ! /etc/rc.d/rpcbind forcestatus >/dev/null 2>&1
	then
		force_depend rpcbind || return 1
	fi

	if ! checkyesno mountd_enable  && \
	   ! /etc/rc.d/mountd forcestatus >/dev/null 2>&1
	then
		force_depend mountd || return 1
	fi

	if checkyesno nfs_reserved_port_only; then
		echo 'NFS on reserved port only=YES'
		${SYSCTL_W} vfs.nfs.nfs_privport=1 >/dev/null
	fi

	return 0
}

load_rc_config $name
command_args="${nfs_server_flags}"

run_rc_command "$1"
