#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/othermta,v 1.2 2002/08/09 17:45:04 gordon Exp $
# $DragonFly: src/etc/rc.d/othermta,v 1.4 2005/11/19 21:47:32 swildner Exp $
#

# PROVIDE: mail
# REQUIRE: LOGIN

# XXX - TEMPORARY SCRIPT UNTIL YOU WRITE YOUR OWN REPLACEMENT.
#
. /etc/rc.subr
load_rc_config 'XXX'
dummy_rc_command "$1"

if [ -n "${mta_start_script}" ]; then
	[ "${mta_start_script}" != "/etc/rc.sendmail" ] && \
	    sh ${mta_start_script} "$1"
fi
