#!/bin/sh

# $DragonFly: src/etc/rc.d/resident,v 1.2 2004/02/06 08:49:55 rob Exp $
#

# PROVIDE: resident
# REQUIRE: mountcritremote
# KEYWORD: DragonFly

. /etc/rc.subr

name=resident
rcvar='resident_enable'
required_files="/etc/resident.conf"
start_cmd="resident_start"
stop_cmd=":"

resident_start()
{
if [ -f /etc/resident.conf ]; then
        while read path 
        do
                case ${path} in
                \#*|"")
                        ;;
                *)
			if [ -f ${path} ]; then
				resident ${path}
			else
                        file ${path} | grep shared | cut -f1 -d ':' -s | xargs resident
			fi
                esac
        done < /etc/resident.conf
fi

}

load_rc_config $name
run_rc_command "$1"
