#!/bin/sh
#
# $NetBSD: route6d,v 1.5 2002/03/22 04:34:00 thorpej Exp $
# $FreeBSD: src/etc/rc.d/route6d,v 1.5 2003/01/25 23:14:08 mtm Exp $
#

# PROVIDE: route6d
# REQUIRE: network_ipv6
# BEFORE:  NETWORKING

. /etc/rc.subr

name="route6d"
rcvar="ipv6_router_enable"

load_rc_config $name

command="${ipv6_router_program:-/usr/sbin/${name}}"
command_args=${ipv6_router_flags}

run_rc_command "$1"
