#!/bin/sh
#
# $NetBSD: routed,v 1.7 2002/03/22 04:34:00 thorpej Exp $
# $FreeBSD: src/etc/rc.d/routed,v 1.6 2003/06/29 05:15:57 mtm Exp $
#

# PROVIDE: routed
# REQUIRE: netif routing
# BEFORE:  NETWORKING

. /etc/rc.subr

name="routed"
rcvar="router_enable"

load_rc_config $name

command="${router_program:-/sbin/${name}}"
command_args=${router_flags}

run_rc_command "$1"
