#!/bin/sh
#
# $NetBSD: securelevel,v 1.4 2002/03/22 04:34:00 thorpej Exp $
# $FreeBSD: src/etc/rc.d/securelevel,v 1.6 2003/05/05 15:38:41 mtm Exp $
# $DragonFly: src/etc/rc.d/securelevel,v 1.3 2004/01/27 00:42:46 rob Exp $
#

# PROVIDE: securelevel
# KEYWORD: DragonFly 

. /etc/rc.subr

name="securelevel"
start_cmd="securelevel_start"
stop_cmd=":"

securelevel_start()
{
	# Last chance to set sysctl variables that failed the first time.
	#
	/etc/rc.d/sysctl lastload

	case ${kern_securelevel_enable} in
	[Yy][Ee][Ss])
		if [ ${kern_securelevel} -ge 0 ]; then
			echo 'Raising kernel security level: '
			${SYSCTL_W} kern.securelevel=${kern_securelevel}
		fi
		;;
	esac
}

load_rc_config $name
run_rc_command "$1"
