#!/bin/sh
#
# $NetBSD: SERVERS,v 1.9 2002/03/22 04:33:57 thorpej Exp $
# $FreeBSD: src/etc/rc.d/SERVERS,v 1.3 2002/10/12 13:49:21 schweikh Exp $
# $DragonFly: src/etc/rc.d/SERVERS,v 1.3 2004/01/26 17:21:15 rob Exp $
#

# PROVIDE: SERVERS
# REQUIRE: mountcritremote
# KEYWORD: DragonFly 

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
. /etc/rc.subr
dummy_rc_command "$1"

