#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/usbd,v 1.1 2002/06/13 22:14:36 gordon Exp $
# $DragonFly: src/etc/rc.d/usbd,v 1.1 2003/07/24 06:35:37 dillon Exp $
#

# PROVIDE: usbd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: DragonFly FreeBSD

. /etc/rc.subr

name="usbd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
