#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/usbd,v 1.1 2002/06/13 22:14:36 gordon Exp $
#

# PROVIDE: usbd
# REQUIRE: DAEMON
# BEFORE: LOGIN

. /etc/rc.subr

name="usbd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
if [ -c /dev/usb ]; then
	run_rc_command "$1"
else
	dummy_rc_command "$1"
fi
