#!/bin/sh
#
# $NetBSD: ypbind,v 1.5 2002/03/22 04:34:01 thorpej Exp $
# $FreeBSD: src/etc/rc.d/ypbind,v 1.6 2003/07/09 03:21:03 mtm Exp $
# $DragonFly: src/etc/rc.d/ypbind,v 1.3 2004/01/27 00:55:43 rob Exp $
#

# PROVIDE: ypbind
# REQUIRE: ypserv
# BEFORE:  DAEMON
# KEYWORD: DragonFly

. /etc/rc.subr

name="ypbind"
command="/usr/sbin/${name}"
start_precmd="ypbind_precmd"

load_rc_config $name
rcvar="nis_client_enable"
command_args="${nis_client_flags}"
ypbind_precmd()
{
	if ! checkyesno rpcbind_enable  && \
	! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
	then
		force_depend rpcbind || return 1
	fi
	_domain=`domainname`
	if [ -z "$_domain" ]; then
		warn "NIS domainname(1) is not set."
		return 1
	fi
}

run_rc_command "$1"
