#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/ypupdated,v 1.4 2003/07/09 03:21:03 mtm Exp $
# $DragonFly: src/etc/rc.d/ypupdated,v 1.1 2003/07/24 06:35:37 dillon Exp $
#

# PROVIDE: ypupdated
# REQUIRE: rpcbind ypserv
# KEYWORD: DragonFly FreeBSD

. /etc/rc.subr

name="ypupdated"
rcvar="rpc_ypupdated_enable"
command="/usr/sbin/rpc.${name}"
start_precmd="rpc_ypupdated_precmd"

rpc_ypupdated_precmd()
{
	if ! checkyesno rpcbind_enable  && \
	    ! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
	then
		force_depend rpcbind || return 1
	fi
	if ! checkyesno nis_server_enable && \
	    ! /etc/rc.d/ypserv forcestatus 1>/dev/null 2>&1
	then
		force_depend ypserv || return 1
	fi

	_domain=`domainname`
	if [ -z "$_domain" ]; then
		warn "NIS domainname(1) is not set."
		return 1
	fi
}

load_rc_config $name
run_rc_command "$1"
