#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/ypxfrd,v 1.5 2003/07/09 03:21:03 mtm Exp $
# $DragonFly: src/etc/rc.d/ypxfrd,v 1.3 2005/11/19 21:47:32 swildner Exp $
#

# PROVIDE: ypxfrd
# REQUIRE: rpcbind

. /etc/rc.subr

name="ypxfrd"
rcvar="nis_ypxfrd_enable"
command="/usr/sbin/rpc.${name}"
start_precmd="ypxfrd_precmd"
load_rc_config $name
command_args="${nis_ypxfrd_flags}"

ypxfrd_precmd()
{
	if ! checkyesno rpcbind_enable  && \
	    ! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
	then
		force_depend rpcbind || return 1
	fi
	if ! checkyesno nis_server_enable && \
	    ! /etc/rc.d/ypserv forcestatus 1>/dev/null 2>&1
	then
		force_depend ypserv || return 1
	fi

	_domain=`domainname`
	if [ -z "$_domain" ]; then
		warn "NIS domainname(1) is not set."
		return 1
	fi
}

run_rc_command "$1"
