# $FreeBSD: src/sys/modules/ste/Makefile,v 1.7 2000/01/28 11:26:37 bde Exp $
# $DragonFly: src/sys/dev/netif/ste/Makefile,v 1.4 2006/06/25 11:02:39 corecode Exp $

KMOD	= if_ste
SRCS	= if_ste.c device_if.h bus_if.h pci_if.h
SRCS	+= miibus_if.h

.include <bsd.kmod.mk>
