# $DragonFly: src/sys/dev/Makefile,v 1.7 2006/10/10 18:31:01 dillon Exp $
#

SUBDIR=acpica5 agp bridge crypto disk drm est misc netif pccard powermng raid \
	serial sound usbmisc video

.include <bsd.subdir.mk>
