# Note that this files is under a "BSD" copyright (c) by David O'Brien 1997, 
# even though it may live in src/gnu/...

# $FreeBSD: src/gnu/usr.bin/cpio/doc/Makefile,v 1.3 1999/08/27 23:35:24 peter Exp $
# $DragonFly: src/gnu/usr.bin/cpio/doc/Makefile,v 1.2 2003/06/17 04:25:45 dillon Exp $

.PATH:	${.CURDIR}/../../../../contrib/cpio

INFO = cpio

INFOSECTION= "Cpio Documentation"
INFOENTRY_cpio="* CPIO: (cpio).                 Making tape (or disk) archives."

SRCDIR= ${.CURDIR}/../../../../contrib/cpio

.include <bsd.info.mk>
