# Makefile - module build for nata modules
#
# $DragonFly: src/sys/dev/disk/nata/Makefile,v 1.1 2006/12/04 14:40:37 tgen Exp $

#SUBDIR=	nata natacard natadisk nataisa natapci natapicam natapicd natapifd \
#	natapist nataraid natausb
# XXX TGEN These are ready for more heavy testing, the others are still largely untested.
SUBDIR=		nata natadisk natapci natapicd

.include <bsd.subdir.mk>
