# Makefile - module build for nata modules
#
# $DragonFly: src/sys/dev/disk/nata/Makefile,v 1.4 2006/12/06 20:20:51 tgen Exp $

#SUBDIR=	nata natacard natadisk nataisa natapci natapicam natapicd natapifd \
#	natapist nataraid natausb
# XXX TGEN These are ready for more heavy testing, the others are still largely untested.
SUBDIR=		nata natacard natadisk nataisa natapci natapicd natapifd \
		natapist natapicam natausb

.include <bsd.subdir.mk>
