# Makefile - module build for nata modules
#
# $DragonFly: src/sys/dev/disk/nata/Makefile,v 1.2 2006/12/05 19:30:14 tgen Exp $

#SUBDIR=	nata natacard natadisk nataisa natapci natapicam natapicd natapifd \
#	natapist nataraid natausb
# XXX TGEN These are ready for more heavy testing, the others are still largely untested.
SUBDIR=		nata natacard natadisk nataisa natapci natapicd natapifd \
		natapist

.include <bsd.subdir.mk>
