#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $Id: Makefile,v 1.2 2001/10/02 06:03:21 jdw Exp $
# $DragonFly: src/usr.sbin/clog/Makefile,v 1.1 2004/10/30 20:26:46 dillon Exp $

PROG=	clog
SRCS=	clog.c 
MAN8=	clog.8
COPTS+=	-Wall

.include <bsd.prog.mk>
