.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Chris Torek and the American National Standards Committee X3,
.\" on Information Processing Systems.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)printf.3	8.1 (Berkeley) 6/4/93
.\" $FreeBSD: head/lib/libc/stdio/wprintf.3 208027 2010-05-13 12:07:55Z uqs $
.\"
.Dd November 17, 2013
.Dt WPRINTF_L 3
.Os
.Sh NAME
.Nm wprintf_l ,
.Nm fwprintf_l ,
.Nm swprintf_l ,
.Nm vfwprintf_l ,
.Nm vswprintf_l ,
.Nm vwprintf_l
.Nd formatted wide character output conversion
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In stdio.h
.In wchar.h
.In xlocale.h
.Ft int
.Fn fwprintf_l "FILE * restrict stream" "locale_t loc" "const wchar_t * restrict format" ...
.Ft int
.Fn swprintf_l "wchar_t * restrict ws" "size_t n" "locale_t loc" "const wchar_t * restrict format" ...
.Ft int
.Fn wprintf_l "locale_t loc" "const wchar_t * restrict format" ...
.In stdarg.h
.Ft int
.Fn vfwprintf_l "FILE * restrict stream" "locale_t loc" "const wchar_t * restrict format" "va_list ap"
.Ft int
.Fn vswprintf_l "wchar_t * restrict ws" "size_t n" "locale_t loc" "const wchar_t *restrict format" "va_list ap"
.Ft int
.Fn vwprintf_l "locale_t loc" "const wchar_t * restrict format" "va_list ap"
.Sh DESCRIPTION
The above functions are used to convert formatted output in the locale
.Fa loc .
They behave in the same way as the versions without the _l suffix, but use
the specified locale rather than the global or per-thread locale.
See the specific manual pages for more information.
.Sh SEE ALSO
.Xr wprintf 3 ,
.Xr xlocale 3
.Sh STANDARDS
These functions do not conform to any specific standard so they should be
considered as non-portable local extensions.
