# $FreeBSD: src/sys/modules/firewire/fwe/Makefile,v 1.2.2.2 2003/04/28 03:29:19 simokawa Exp $
# $DragonFly: src/sys/dev/netif/fwe/Makefile,v 1.4 2005/07/28 00:06:09 joerg Exp $

# Makefile for the fwe(4) module (Ethernet over IEEE1394)

KMOD=	if_fwe
SRCS=	if_fwe.c
SRCS+=	bus_if.h device_if.h opt_inet.h

.include <bsd.kmod.mk>
