#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/showmount/Makefile,v 1.3.14.1 2001/04/25 11:29:39 ru Exp $
# $DragonFly: src/usr.bin/showmount/Makefile,v 1.4 2007/08/27 16:50:58 pavalos Exp $

PROG=	showmount
MAN=	showmount.8

.include <bsd.prog.mk>
