#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/showmount/Makefile,v 1.3.14.1 2001/04/25 11:29:39 ru Exp $
# $DragonFly: src/usr.bin/showmount/Makefile,v 1.3 2005/09/05 04:22:07 swildner Exp $

PROG=	showmount
MAN=	showmount.8
WARNS?=	6

.include <bsd.prog.mk>
