# $FreeBSD: src/sys/modules/kue/Makefile,v 1.2 2000/01/28 11:26:30 bde Exp $
# $DragonFly: src/sys/dev/netif/kue/Makefile,v 1.3 2005/07/28 00:06:09 joerg Exp $

S	= ${.CURDIR}/../..
KMOD	= if_kue
SRCS	= if_kue.c opt_bdg.h opt_usb.h device_if.h bus_if.h
SRCS	+= miibus_if.h

.include <bsd.kmod.mk>
