#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $DragonFly: src/games/snake/snscore/Makefile,v 1.3 2006/10/08 16:22:36 pavalos Exp $

PROG=	snscore
CFLAGS+= -I${.CURDIR}/../snake
NOMAN=

.include "../../Makefile.inc"
.include <bsd.prog.mk>
