#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $DragonFly: src/games/snake/snscore/Makefile,v 1.2 2006/09/03 23:47:56 pavalos Exp $

PROG=	snscore
CFLAGS+=-I${.CURDIR}/../snake
NOMAN=	noman
WARNS?=	6

.include "../../Makefile.inc"
.include <bsd.prog.mk>
