# $FreeBSD: src/etc/periodic/monthly/Makefile,v 1.2.2.1 2002/07/18 12:36:07 ru Exp $
# $DragonFly: src/etc/periodic/monthly/Makefile,v 1.2 2003/06/17 04:24:48 dillon Exp $

FILES=	200.accounting \
	999.local

.include <bsd.prog.mk>
