# $FreeBSD: src/etc/periodic/monthly/Makefile,v 1.2.2.1 2002/07/18 12:36:07 ru Exp $
# $DragonFly: src/etc/periodic/monthly/Makefile,v 1.3 2006/10/04 21:39:23 dillon Exp $

FILES=	200.accounting \
	300.statistics \
	999.local

.include <bsd.prog.mk>
