# $FreeBSD: src/sys/modules/netgraph/tty/Makefile,v 1.1.4.3 2001/12/21 09:00:50 ru Exp $
# $DragonFly: src/sys/netgraph/tty/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:22 archie Exp $

KMOD=		ng_tty
SRCS= 		ng_tty.c
KMODDEPS=	netgraph

.include <bsd.kmod.mk>
