#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/dirname/Makefile,v 1.2.6.1 2001/08/02 01:49:44 obrien Exp $
# $DragonFly: src/usr.bin/dirname/Makefile,v 1.3 2004/12/30 17:49:39 liamfoy Exp $

PROG=	dirname
WARNS?= 6	
NOMAN=	noman

.include <bsd.prog.mk>
