#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/colcrt/Makefile,v 1.2.6.1 2001/08/02 01:29:07 obrien Exp $
# $DragonFly: src/usr.bin/colcrt/Makefile,v 1.4 2007/08/27 16:50:52 pavalos Exp $

PROG=	colcrt

.include <bsd.prog.mk>
