#	@(#)Makefile	1.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/ktrace/Makefile,v 1.6 1999/08/28 01:02:32 peter Exp $
# $DragonFly: src/usr.bin/ktrace/Makefile,v 1.2 2003/06/17 04:29:27 dillon Exp $

PROG=	ktrace
SRCS=	ktrace.c subr.c
MLINKS= ktrace.1 trace.1 

.include <bsd.prog.mk>
