# $FreeBSD: src/usr.sbin/wicontrol/Makefile,v 1.3.2.1 2001/04/25 12:11:11 ru Exp $
# $DragonFly: src/usr.sbin/wicontrol/Attic/Makefile,v 1.3 2004/07/28 08:38:33 joerg Exp $

PROG=	wicontrol
MAN=	wicontrol.8

WARNS?=	6

.include <bsd.prog.mk>
