/*
 * THIS FILE AUTOMATICALLY GENERATED.  DO NOT EDIT.
 */
/* $NetBSD: pcidevs,v 1.606 2004/01/06 19:44:17 matt Exp $ */

/*
 * Copyright (c) 1995, 1996 Christopher G. Demetriou
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *      This product includes software developed by Christopher G. Demetriou
 *	for the NetBSD Project.
 * 4. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

const struct pci_knowndev pci_knowndevs[] = {
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C996,
	    0,
	    "3Com",
	    "3c996 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C940,
	    0,
	    "3Com",
	    "3c940 Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C590,
	    0,
	    "3Com",
	    "3c590 Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C595TX,
	    0,
	    "3Com",
	    "3c595-TX 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C595T4,
	    0,
	    "3Com",
	    "3c595-T4 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C595MII,
	    0,
	    "3Com",
	    "3c595-MII 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C940B,
	    0,
	    "3Com",
	    "3c940B Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C900TPO,
	    0,
	    "3Com",
	    "3c900-TPO Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C900COMBO,
	    0,
	    "3Com",
	    "3c900-COMBO Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C905TX,
	    0,
	    "3Com",
	    "3c905-TX 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C905T4,
	    0,
	    "3Com",
	    "3c905-T4 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C910SOHOB,
	    0,
	    "3Com",
	    "3c910 OfficeConnect 10/100B Ethernet",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3CR990TX95,
	    0,
	    "3Com",
	    "3CR990-TX-95 10/100 Ethernet with 3XP",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3CR990TX97,
	    0,
	    "3Com",
	    "3CR990-TX-97 10/100 Ethernet with 3XP",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C990B,
	    0,
	    "3Com",
	    "3c990B 10/100 Ethernet with 3XP",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3CR990SVR95,
	    0,
	    "3Com",
	    "3CR990-SVR-95 10/100 Ethernet with 3XP",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3CR990SVR97,
	    0,
	    "3Com",
	    "3CR990-SVR-97 10/100 Ethernet with 3XP",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C990BSVR,
	    0,
	    "3Com",
	    "3c990BSVR 10/100 Ethernet with 3XP",
	},
	{
	    PCI_VENDOR_ACCTON, PCI_PRODUCT_ACCTON_MPX5030,
	    0,
	    "Accton Technology",
	    "MPX 5030/5038 Ethernet",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC5900,
	    0,
	    "Adaptec",
	    "AIC-5900 ATM",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC5905,
	    0,
	    "Adaptec",
	    "AIC-5905 ATM",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC6915,
	    0,
	    "Adaptec",
	    "AIC-6915 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_ADDTRON, PCI_PRODUCT_ADDTRON_RHINEII,
	    0,
	    "Addtron Technology",
	    "Rhine II 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_ADDTRON, PCI_PRODUCT_ADDTRON_8139,
	    0,
	    "Addtron Technology",
	    "8139 Ethernet",
	},
	{
	    PCI_VENDOR_ADMTEK, PCI_PRODUCT_ADMTEK_ADM8211,
	    0,
	    "",
	    "ADMtek ADM8211 11Mbps 802.11b WLAN",
	},
	{
	    PCI_VENDOR_AIRONET, PCI_PRODUCT_AIRONET_PC4xxx,
	    0,
	    "Aironet Wireless Communications",
	    "Aironet PC4500/PC4800 Wireless LAN Adapter",
	},
	{
	    PCI_VENDOR_AIRONET, PCI_PRODUCT_AIRONET_350,
	    0,
	    "Aironet Wireless Communications",
	    "Aironet 350 Wireless LAN Adapter",
	},
	{
	    PCI_VENDOR_AIRONET, PCI_PRODUCT_AIRONET_MPI350,
	    0,
	    "Aironet Wireless Communications",
	    "Aironet 350 miniPCI Wireless LAN Adapter",
	},
	{
	    PCI_VENDOR_AIRONET, PCI_PRODUCT_AIRONET_PC4500,
	    0,
	    "Aironet Wireless Communications",
	    "Aironet PC4500 Wireless LAN Adapter",
	},
	{
	    PCI_VENDOR_AIRONET, PCI_PRODUCT_AIRONET_PC4800,
	    0,
	    "Aironet Wireless Communications",
	    "Aironet PC4800 Wireless LAN Adapter",
	},
	{
	    PCI_VENDOR_ALTEON, PCI_PRODUCT_ALTEON_BCM5700,
	    0,
	    "Alteon",
	    "ACEnic BCM5700 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_ALTEON, PCI_PRODUCT_ALTEON_BCM5701,
	    0,
	    "Alteon",
	    "ACEnic BCM5701 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_ALTIMA, PCI_PRODUCT_ALTIMA_AC1000,
	    0,
	    "Altima",
	    "AC1000 Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_ALTIMA, PCI_PRODUCT_ALTIMA_AC1001,
	    0,
	    "Altima",
	    "AC1001 Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_ALTIMA, PCI_PRODUCT_ALTIMA_AC9100,
	    0,
	    "Altima",
	    "AC9100 Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_AMD64_MISC,
	    0,
	    "Advanced Micro Devices",
	    "AMD64 Miscellaneous configuration",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_AMD64_F10_MISC,
	    0,
	    "Advanced Micro Devices",
	    "Family 10h Miscellaneous",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_AMD64_F11_MISC,
	    0,
	    "Advanced Micro Devices",
	    "Family 11h Miscellaneous",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_PCNET_PCI,
	    0,
	    "Advanced Micro Devices",
	    "PCnet-PCI Ethernet",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_PCNET_HOME,
	    0,
	    "Advanced Micro Devices",
	    "PCnet-Home HomePNA Ethernet",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_GEODE_LX_PCHB,
	    0,
	    "Advanced Micro Devices",
	    "Geode LX",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_CS5536_PCIB,
	    0,
	    "Advanced Micro Devices",
	    "CS5536 ISA",
	},
	{
	    PCI_VENDOR_APPLE, PCI_PRODUCT_APPLE_BCM5701,
	    0,
	    "Apple Computer",
	    "BCM5701",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_SB600_SATA,
	    0,
	    "ATI Technologies",
	    "SB600 SATA",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_SB700_AHCI,
	    0,
	    "ATI Technologies",
	    "SB700 AHCI",
	},
	{
	    PCI_VENDOR_ATHEROS, PCI_PRODUCT_ATHEROS_AR5210,
	    0,
	    "Atheros Communications, Inc.",
	    "AR5210",
	},
	{
	    PCI_VENDOR_BELKIN, PCI_PRODUCT_BELKIN_F5D6001,
	    0,
	    "Belkin",
	    "F5D6001 802.11b",
	},
	{
	    PCI_VENDOR_BLUESTEEL, PCI_PRODUCT_BLUESTEEL_5501,
	    0,
	    "Bluesteel Networks",
	    "5501",
	},
	{
	    PCI_VENDOR_BLUESTEEL, PCI_PRODUCT_BLUESTEEL_5601,
	    0,
	    "Bluesteel Networks",
	    "5601",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5752,
	    0,
	    "Broadcom Corporation",
	    "BCM5752 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5752M,
	    0,
	    "Broadcom Corporation",
	    "BCM5752M",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5700,
	    0,
	    "Broadcom Corporation",
	    "BCM5700 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5701,
	    0,
	    "Broadcom Corporation",
	    "BCM5701 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5702,
	    0,
	    "Broadcom Corporation",
	    "BCM5702 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5703,
	    0,
	    "Broadcom Corporation",
	    "BCM5703 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5704C,
	    0,
	    "Broadcom Corporation",
	    "BCM5704C Gigabit Ethernet (1000BASE-T)",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5704S_ALT,
	    0,
	    "Broadcom Corporation",
	    "BCM5704S Alt",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5705,
	    0,
	    "Broadcom Corporation",
	    "BCM5705 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5705K,
	    0,
	    "Broadcom Corporation",
	    "BCM5705K 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5717,
	    0,
	    "Broadcom Corporation",
	    "BCM5717 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5718,
	    0,
	    "Broadcom Corporation",
	    "BCM5718 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5719,
	    0,
	    "Broadcom Corporation",
	    "BCM5719 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5720,
	    0,
	    "Broadcom Corporation",
	    "BCM5720",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5721,
	    0,
	    "Broadcom Corporation",
	    "BCM5721 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5722,
	    0,
	    "Broadcom Corporation",
	    "BCM5722",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5723,
	    0,
	    "Broadcom Corporation",
	    "BCM5723",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5705M,
	    0,
	    "Broadcom Corporation",
	    "BCM5705M 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5705M_ALT,
	    0,
	    "Broadcom Corporation",
	    "BCM5705M 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5720_ALT,
	    0,
	    "Broadcom Corporation",
	    "BCM5720 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5714,
	    0,
	    "Broadcom Corporation",
	    "BCM5714 1000baseT Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5714S,
	    0,
	    "Broadcom Corporation",
	    "BCM5714S",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5780,
	    0,
	    "Broadcom Corporation",
	    "BCM5780",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5780S,
	    0,
	    "Broadcom Corporation",
	    "BCM5780S",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5705F,
	    0,
	    "Broadcom Corporation",
	    "BCM5705F",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5754M,
	    0,
	    "Broadcom Corporation",
	    "BCM5754M",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5755M,
	    0,
	    "Broadcom Corporation",
	    "BCM5755M",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5756,
	    0,
	    "Broadcom Corporation",
	    "BCM5756",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5750,
	    0,
	    "Broadcom Corporation",
	    "BCM5750 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5751,
	    0,
	    "Broadcom Corporation",
	    "BCM5751 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5715,
	    0,
	    "Broadcom Corporation",
	    "BCM5715",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5715S,
	    0,
	    "Broadcom Corporation",
	    "BCM5715S",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5754,
	    0,
	    "Broadcom Corporation",
	    "BCM5754",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5755,
	    0,
	    "Broadcom Corporation",
	    "BCM5755",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5750M,
	    0,
	    "Broadcom Corporation",
	    "BCM5750M 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5751M,
	    0,
	    "Broadcom Corporation",
	    "BCM5751M 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5751F,
	    0,
	    "Broadcom Corporation",
	    "BCM5751F",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5761E,
	    0,
	    "Broadcom Corporation",
	    "BCM5761E",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5761,
	    0,
	    "Broadcom Corporation",
	    "BCM5761",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57762,
	    0,
	    "Broadcom Corporation",
	    "BCM57762",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57766,
	    0,
	    "Broadcom Corporation",
	    "BCM57766",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5761S,
	    0,
	    "Broadcom Corporation",
	    "BCM5761S",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5761SE,
	    0,
	    "Broadcom Corporation",
	    "BCM5761SE",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5764,
	    0,
	    "Broadcom Corporation",
	    "BCM5764",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5787F,
	    0,
	    "Broadcom Corporation",
	    "BCM5787F",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5787M,
	    0,
	    "Broadcom Corporation",
	    "BCM5787M",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5782,
	    0,
	    "Broadcom Corporation",
	    "BCM5782 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5784,
	    0,
	    "Broadcom Corporation",
	    "BCM5784",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5785F,
	    0,
	    "Broadcom Corporation",
	    "BCM5785F",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5785G,
	    0,
	    "Broadcom Corporation",
	    "BCM5785G",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5786,
	    0,
	    "Broadcom Corporation",
	    "BCM5786",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5787,
	    0,
	    "Broadcom Corporation",
	    "BCM5787",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5787F,
	    0,
	    "Broadcom Corporation",
	    "BCM5787F",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5788,
	    0,
	    "Broadcom Corporation",
	    "BCM5788 10/100/1000 Enternet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5789,
	    0,
	    "Broadcom Corporation",
	    "BCM5789 10/100/1000 Enternet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5702X,
	    0,
	    "Broadcom Corporation",
	    "BCM5702X 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5703X,
	    0,
	    "Broadcom Corporation",
	    "BCM5703X 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5704S,
	    0,
	    "Broadcom Corporation",
	    "BCM5704S Gigabit Ethernet (1000BASE-X)",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57761,
	    0,
	    "Broadcom Corporation",
	    "BCM57761 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57781,
	    0,
	    "Broadcom Corporation",
	    "BCM57781 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57791,
	    0,
	    "Broadcom Corporation",
	    "BCM57791 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57786,
	    0,
	    "Broadcom Corporation",
	    "BCM57786",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57765,
	    0,
	    "Broadcom Corporation",
	    "BCM57765 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57785,
	    0,
	    "Broadcom Corporation",
	    "BCM57785 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57795,
	    0,
	    "Broadcom Corporation",
	    "BCM57795 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57782,
	    0,
	    "Broadcom Corporation",
	    "BCM57782",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5702_ALT,
	    0,
	    "Broadcom Corporation",
	    "BCM5702 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5703A3,
	    0,
	    "Broadcom Corporation",
	    "BCM5703 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5781,
	    0,
	    "Broadcom Corporation",
	    "BCM5781",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5753,
	    0,
	    "Broadcom Corporation",
	    "BCM5753",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5753M,
	    0,
	    "Broadcom Corporation",
	    "BCM5753M",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5753F,
	    0,
	    "Broadcom Corporation",
	    "BCM5753F",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5903M,
	    0,
	    "Broadcom Corporation",
	    "BCM5903M",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4401B0,
	    0,
	    "Broadcom Corporation",
	    "BCM4401-B0 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5901,
	    0,
	    "Broadcom Corporation",
	    "BCM5901 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5901A2,
	    0,
	    "Broadcom Corporation",
	    "BCM5901A 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5906,
	    0,
	    "Broadcom Corporation",
	    "BCM5906",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM5906M,
	    0,
	    "Broadcom Corporation",
	    "BCM5906M",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57760,
	    0,
	    "Broadcom Corporation",
	    "BCM57760",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57780,
	    0,
	    "Broadcom Corporation",
	    "BCM57780",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57788,
	    0,
	    "Broadcom Corporation",
	    "BCM57788",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM57790,
	    0,
	    "Broadcom Corporation",
	    "BCM57790",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4301,
	    0,
	    "Broadcom Corporation",
	    "BCM4301 802.11b Wireless Lan",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4307,
	    0,
	    "Broadcom Corporation",
	    "BCM4307 802.11b Wireless Lan",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4311,
	    0,
	    "Broadcom Corporation",
	    "BCM4311 802.11a/b/g Wireless Lan",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4312,
	    0,
	    "Broadcom Corporation",
	    "BCM4312 802.11a/b/g Wireless Lan",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4318,
	    0,
	    "Broadcom Corporation",
	    "BCM4318 802.11b/g Wireless Lan",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4319,
	    0,
	    "Broadcom Corporation",
	    "BCM4319 802.11a/b/g Wireless Lan",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4306_1,
	    0,
	    "Broadcom Corporation",
	    "BCM4306 802.11b/g Wireless Lan",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4306_2,
	    0,
	    "Broadcom Corporation",
	    "BCM4306 802.11a Wireless Lan",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4309,
	    0,
	    "Broadcom Corporation",
	    "BCM4309 802.11a/b/g Wireless Lan",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4306_3,
	    0,
	    "Broadcom Corporation",
	    "BCM4306 802.11b/g Wireless Lan",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4401,
	    0,
	    "Broadcom Corporation",
	    "BCM4401 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_BCM4402,
	    0,
	    "Broadcom Corporation",
	    "BCM4402 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_5801,
	    0,
	    "Broadcom Corporation",
	    "5801 Security processor",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_5802,
	    0,
	    "Broadcom Corporation",
	    "5802 Security processor",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_5805,
	    0,
	    "Broadcom Corporation",
	    "5805 Security processor",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_5820,
	    0,
	    "Broadcom Corporation",
	    "5820 Security processor",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_5821,
	    0,
	    "Broadcom Corporation",
	    "5821 Security processor",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_5822,
	    0,
	    "Broadcom Corporation",
	    "5822 Security processor",
	},
	{
	    PCI_VENDOR_BROADCOM, PCI_PRODUCT_BROADCOM_5823,
	    0,
	    "Broadcom Corporation",
	    "5823 Security processor",
	},
	{
	    PCI_VENDOR_BROOKTREE, PCI_PRODUCT_BROOKTREE_BT848,
	    0,
	    "Brooktree",
	    "Bt848 Video Capture",
	},
	{
	    PCI_VENDOR_BROOKTREE, PCI_PRODUCT_BROOKTREE_BT849,
	    0,
	    "Brooktree",
	    "Bt849 Video Capture",
	},
	{
	    PCI_VENDOR_BROOKTREE, PCI_PRODUCT_BROOKTREE_BT878,
	    0,
	    "Brooktree",
	    "Bt878 Video Capture",
	},
	{
	    PCI_VENDOR_BROOKTREE, PCI_PRODUCT_BROOKTREE_BT879,
	    0,
	    "Brooktree",
	    "Bt879 Video Capture",
	},
	{
	    PCI_VENDOR_CNET, PCI_PRODUCT_CNET_GIGACARD,
	    0,
	    "CNet",
	    "GigaCard",
	},
	{
	    PCI_VENDOR_COMPEX, PCI_PRODUCT_COMPEX_NE2KETHER,
	    0,
	    "Compex",
	    "Ethernet",
	},
	{
	    PCI_VENDOR_COMPEX, PCI_PRODUCT_COMPEX_RL100ATX,
	    0,
	    "Compex",
	    "RL100-ATX 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_COMTROL, PCI_PRODUCT_COMTROL_ROCKETPORT32EXT,
	    0,
	    "Comtrol",
	    "RocketPort 32 port external",
	},
	{
	    PCI_VENDOR_COMTROL, PCI_PRODUCT_COMTROL_ROCKETPORT8EXT,
	    0,
	    "Comtrol",
	    "RocketPort 8 port external",
	},
	{
	    PCI_VENDOR_COMTROL, PCI_PRODUCT_COMTROL_ROCKETPORT16EXT,
	    0,
	    "Comtrol",
	    "RocketPort 16 port external",
	},
	{
	    PCI_VENDOR_COMTROL, PCI_PRODUCT_COMTROL_ROCKETPORT4QUAD,
	    0,
	    "Comtrol",
	    "RocketPort 4 port w/ quad cable",
	},
	{
	    PCI_VENDOR_COMTROL, PCI_PRODUCT_COMTROL_ROCKETPORT8OCTA,
	    0,
	    "Comtrol",
	    "RocketPort 8 port w/ octa cable",
	},
	{
	    PCI_VENDOR_COMTROL, PCI_PRODUCT_COMTROL_ROCKETPORT8RJ,
	    0,
	    "Comtrol",
	    "RocketPort 8 port w/ RJ11s",
	},
	{
	    PCI_VENDOR_COMTROL, PCI_PRODUCT_COMTROL_ROCKETPORT4RJ,
	    0,
	    "Comtrol",
	    "RocketPort 4 port w/ RJ11s",
	},
	{
	    PCI_VENDOR_COMTROL, PCI_PRODUCT_COMTROL_ROCKETMODEM6,
	    0,
	    "Comtrol",
	    "RocketModem 6 port",
	},
	{
	    PCI_VENDOR_COMTROL, PCI_PRODUCT_COMTROL_ROCKETMODEM4,
	    0,
	    "Comtrol",
	    "RocketModem 4 port",
	},
	{
	    PCI_VENDOR_COREGA, PCI_PRODUCT_COREGA_CB_TXD,
	    0,
	    "Corega",
	    "FEther CB-TXD 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_COREGA, PCI_PRODUCT_COREGA_2CB_TXD,
	    0,
	    "Corega",
	    "FEther II CB-TXD 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_COREGA, PCI_PRODUCT_COREGA_CG_LAPCIGT,
	    0,
	    "Corega",
	    "CG-LAPCIGT 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_DELTA, PCI_PRODUCT_DELTA_RHINEII,
	    0,
	    "Delta Electronics",
	    "Rhine II 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_DELTA, PCI_PRODUCT_DELTA_8139,
	    0,
	    "Delta Electronics",
	    "8139 Ethernet",
	},
	{
	    PCI_VENDOR_DIGI, PCI_PRODUCT_DIGI_SYNC570I_2PB1,
	    0,
	    "Digi International",
	    "SYNC/570i-PCI 2 port (mapped below 1M)",
	},
	{
	    PCI_VENDOR_DIGI, PCI_PRODUCT_DIGI_SYNC570I_4PB1,
	    0,
	    "Digi International",
	    "SYNC/570i-PCI 4 port (mapped below 1M)",
	},
	{
	    PCI_VENDOR_DIGI, PCI_PRODUCT_DIGI_SYNC570I_2P,
	    0,
	    "Digi International",
	    "SYNC/570i-PCI 2 port",
	},
	{
	    PCI_VENDOR_DIGI, PCI_PRODUCT_DIGI_SYNC570I_4P,
	    0,
	    "Digi International",
	    "SYNC/570i-PCI 4 port",
	},
	{
	    PCI_VENDOR_DLINK, PCI_PRODUCT_DLINK_DL1002,
	    0,
	    "D-Link Systems",
	    "DL-1002 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_DLINK, PCI_PRODUCT_DLINK_DFE530TXPLUS,
	    0,
	    "D-Link Systems",
	    "DFE-530TXPLUS 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_DLINK, PCI_PRODUCT_DLINK_DFE690TXD,
	    0,
	    "D-Link Systems",
	    "DFE-690TXD 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_DLINK, PCI_PRODUCT_DLINK_DGE528T,
	    0,
	    "D-Link Systems",
	    "DGE-528T Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_DLINK, PCI_PRODUCT_DLINK_DGE530T_B1,
	    0,
	    "D-Link Systems",
	    "DGE-530T B1",
	},
	{
	    PCI_VENDOR_DLINK, PCI_PRODUCT_DLINK_DGE530T_A1,
	    0,
	    "D-Link Systems",
	    "DGE-530T A1",
	},
	{
	    PCI_VENDOR_EFFICIENTNETS, PCI_PRODUCT_EFFICIENTNETS_ENI155PF,
	    0,
	    "Efficent Networks",
	    "155P-MF1 ATM (FPGA)",
	},
	{
	    PCI_VENDOR_EFFICIENTNETS, PCI_PRODUCT_EFFICIENTNETS_ENI155PA,
	    0,
	    "Efficent Networks",
	    "155P-MF1 ATM (ASIC)",
	},
	{
	    PCI_VENDOR_MARVELL, PCI_PRODUCT_MARVELL_YUKON,
	    0,
	    "Marvell (was Galileo Technology)",
	    "Yukon 88E8001/8003/8010",
	},
	{
	    PCI_VENDOR_MARVELL, PCI_PRODUCT_MARVELL_YUKON_BELKIN,
	    0,
	    "Marvell (was Galileo Technology)",
	    "Yukon (Belkin F5D5005)",
	},
	{
	    PCI_VENDOR_MARVELL, PCI_PRODUCT_MARVELL_88SE6121,
	    0,
	    "Marvell (was Galileo Technology)",
	    "88SE6121 SATA/ATA controller",
	},
	{
	    PCI_VENDOR_MARVELL, PCI_PRODUCT_MARVELL_88SE6145,
	    0,
	    "Marvell (was Galileo Technology)",
	    "88SE6145 SATA/ATA controller",
	},
	{
	    PCI_VENDOR_HIFN, PCI_PRODUCT_HIFN_7751,
	    0,
	    "Hifn",
	    "7751",
	},
	{
	    PCI_VENDOR_HIFN, PCI_PRODUCT_HIFN_6500,
	    0,
	    "Hifn",
	    "6500",
	},
	{
	    PCI_VENDOR_HIFN, PCI_PRODUCT_HIFN_7811,
	    0,
	    "Hifn",
	    "7811",
	},
	{
	    PCI_VENDOR_HIFN, PCI_PRODUCT_HIFN_7951,
	    0,
	    "Hifn",
	    "7951",
	},
	{
	    PCI_VENDOR_HIFN, PCI_PRODUCT_HIFN_7955,
	    0,
	    "Hifn",
	    "7954/7955",
	},
	{
	    PCI_VENDOR_HIFN, PCI_PRODUCT_HIFN_7956,
	    0,
	    "Hifn",
	    "7956",
	},
	{
	    PCI_VENDOR_ICOMPRESSION, PCI_PRODUCT_ICOMPRESSION_ITVC16,
	    0,
	    "Conexant (iCompression)",
	    "iTVC16 MPEG2 codec",
	},
	{
	    PCI_VENDOR_ICOMPRESSION, PCI_PRODUCT_ICOMPRESSION_ITVC15,
	    0,
	    "Conexant (iCompression)",
	    "iTVC15 MPEG2 codec",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_PRO_WL_2100,
	    0,
	    "Intel",
	    "PRO/Wireless LAN 2100 3B Mini PCI Adapter",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82597EX,
	    0,
	    "Intel",
	    "PRO/10GbE LR Server Adapter",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_PRO_100_VE_5,
	    0,
	    "Intel",
	    "PRO/100 VE (LOM) Ethernet Controller with 82562ET/EZ/GT/GZ",
	},
	{
	    PCI_VENDOR_INVERTEX, PCI_PRODUCT_INVERTEX_AEON,
	    0,
	    "Invertex",
	    "AEON",
	},
	{
	    PCI_VENDOR_JMICRON, PCI_PRODUCT_JMICRON_JMC250,
	    0,
	    "JMicron Technology Corporation",
	    "JMC250 PCI Express Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_JMICRON, PCI_PRODUCT_JMICRON_JMC260,
	    0,
	    "JMicron Technology Corporation",
	    "JMC260 PCI Express Fast Ethernet",
	},
	{
	    PCI_VENDOR_KTI, PCI_PRODUCT_KTI_NE2KETHER,
	    0,
	    "KTI",
	    "Ethernet",
	},
	{
	    PCI_VENDOR_LEVELONE, PCI_PRODUCT_LEVELONE_LXT1001,
	    0,
	    "Level One",
	    "LXT-1001 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_LINKSYS, PCI_PRODUCT_LINKSYS_EG1032,
	    0,
	    "Linksys",
	    "EG1032 v2 Instant Gigabit Network Adapter",
	},
	{
	    PCI_VENDOR_LINKSYS, PCI_PRODUCT_LINKSYS_EG1064,
	    0,
	    "Linksys",
	    "EG1064 v2 Instant Gigabit Network Adapter",
	},
	{
	    PCI_VENDOR_LUCENT, PCI_PRODUCT_LUCENT_ET1310,
	    0,
	    "Lucent Technologies",
	    "ET1310 10/100/1000M Ethernet",
	},
	{
	    PCI_VENDOR_LUCENT, PCI_PRODUCT_LUCENT_ET1310_FAST,
	    0,
	    "Lucent Technologies",
	    "ET1310 10/100M Ethernet",
	},
	{
	    PCI_VENDOR_NETVIN, PCI_PRODUCT_NETVIN_5000,
	    0,
	    "NetVin",
	    "5000 Ethernet",
	},
	{
	    PCI_VENDOR_NS, PCI_PRODUCT_NS_DP83815,
	    0,
	    "National Semiconductor",
	    "DP83815 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_NS, PCI_PRODUCT_NS_DP83820,
	    0,
	    "National Semiconductor",
	    "DP83820 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_NS, PCI_PRODUCT_NS_SCx200_XBUS,
	    0,
	    "National Semiconductor",
	    "SCx200 X-BUS",
	},
	{
	    PCI_VENDOR_NS, PCI_PRODUCT_NS_SC1100_XBUS,
	    0,
	    "National Semiconductor",
	    "SC1100 X-Bus",
	},
	{
	    PCI_VENDOR_NETSEC, PCI_PRODUCT_NETSEC_7751,
	    0,
	    "NetSec",
	    "7751",
	},
	{
	    PCI_VENDOR_NORTEL, PCI_PRODUCT_NORTEL_BAYSTACK_21,
	    0,
	    "Nortel Networks (Northern Telecom)",
	    "Baystack 21 (Accton MPX EN5038)",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP04_LAN1,
	    0,
	    "Nvidia Corporation",
	    "MCP04 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP04_LAN2,
	    0,
	    "Nvidia Corporation",
	    "MCP04 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_CK804_LAN1,
	    0,
	    "Nvidia Corporation",
	    "CK804 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_CK804_LAN2,
	    0,
	    "Nvidia Corporation",
	    "CK804 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_NFORCE2_LAN,
	    0,
	    "Nvidia Corporation",
	    "nForce2 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_NFORCE3_LAN2,
	    0,
	    "Nvidia Corporation",
	    "nForce3 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_NFORCE3_LAN3,
	    0,
	    "Nvidia Corporation",
	    "nForce3 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_NFORCE3_LAN1,
	    0,
	    "Nvidia Corporation",
	    "nForce3 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_NFORCE3_LAN4,
	    0,
	    "Nvidia Corporation",
	    "nForce3 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_NFORCE3_LAN5,
	    0,
	    "Nvidia Corporation",
	    "nForce3 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_NFORCE_LAN,
	    0,
	    "Nvidia Corporation",
	    "nForce Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP51_LAN1,
	    0,
	    "Nvidia Corporation",
	    "MCP51 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP51_LAN2,
	    0,
	    "Nvidia Corporation",
	    "MCP51 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP55_LAN1,
	    0,
	    "Nvidia Corporation",
	    "MCP55 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP55_LAN2,
	    0,
	    "Nvidia Corporation",
	    "MCP55 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP61_LAN1,
	    0,
	    "Nvidia Corporation",
	    "MCP61 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP61_LAN2,
	    0,
	    "Nvidia Corporation",
	    "MCP61 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP61_LAN3,
	    0,
	    "Nvidia Corporation",
	    "MCP61 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP61_LAN4,
	    0,
	    "Nvidia Corporation",
	    "MCP61 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_AHCI_1,
	    0,
	    "Nvidia Corporation",
	    "MCP65 AHCI",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_AHCI_2,
	    0,
	    "Nvidia Corporation",
	    "MCP65 AHCI",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_AHCI_3,
	    0,
	    "Nvidia Corporation",
	    "MCP65 AHCI",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_AHCI_4,
	    0,
	    "Nvidia Corporation",
	    "MCP65 AHCI",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_LAN1,
	    0,
	    "Nvidia Corporation",
	    "MCP65 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_LAN2,
	    0,
	    "Nvidia Corporation",
	    "MCP65 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_LAN3,
	    0,
	    "Nvidia Corporation",
	    "MCP65 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_LAN4,
	    0,
	    "Nvidia Corporation",
	    "MCP65 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_AHCI_5,
	    0,
	    "Nvidia Corporation",
	    "MCP65 AHCI",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_AHCI_6,
	    0,
	    "Nvidia Corporation",
	    "MCP65 AHCI",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_AHCI_7,
	    0,
	    "Nvidia Corporation",
	    "MCP65 AHCI",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP65_AHCI_8,
	    0,
	    "Nvidia Corporation",
	    "MCP65 AHCI",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP67_LAN1,
	    0,
	    "Nvidia Corporation",
	    "MCP67 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP67_LAN2,
	    0,
	    "Nvidia Corporation",
	    "MCP67 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP67_LAN3,
	    0,
	    "Nvidia Corporation",
	    "MCP67 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP67_LAN4,
	    0,
	    "Nvidia Corporation",
	    "MCP67 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP67_AHCI_1,
	    0,
	    "Nvidia Corporation",
	    "MCP67 AHCI",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP77_LAN1,
	    0,
	    "Nvidia Corporation",
	    "MCP77 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP77_LAN2,
	    0,
	    "Nvidia Corporation",
	    "MCP77 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP77_LAN3,
	    0,
	    "Nvidia Corporation",
	    "MCP77 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP77_LAN4,
	    0,
	    "Nvidia Corporation",
	    "MCP77 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP73_LAN1,
	    0,
	    "Nvidia Corporation",
	    "MCP73 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP73_LAN2,
	    0,
	    "Nvidia Corporation",
	    "MCP73 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP73_LAN3,
	    0,
	    "Nvidia Corporation",
	    "MCP73 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP73_LAN4,
	    0,
	    "Nvidia Corporation",
	    "MCP73 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP79_LAN1,
	    0,
	    "Nvidia Corporation",
	    "MCP79 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP79_LAN2,
	    0,
	    "Nvidia Corporation",
	    "MCP79 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP79_LAN3,
	    0,
	    "Nvidia Corporation",
	    "MCP79 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP79_LAN4,
	    0,
	    "Nvidia Corporation",
	    "MCP79 Lan",
	},
	{
	    PCI_VENDOR_NVIDIA, PCI_PRODUCT_NVIDIA_MCP77_AHCI_5,
	    0,
	    "Nvidia Corporation",
	    "MCP77 AHCI",
	},
	{
	    PCI_VENDOR_PEPPERCON, PCI_PRODUCT_PEPPERCON_ROLF,
	    0,
	    "Peppercon AG",
	    "ROL/F-100 Fast Ethernet Adapter with ROL",
	},
	{
	    PCI_VENDOR_PLANEX, PCI_PRODUCT_PLANEX_FNW_3800_TX,
	    0,
	    "Planex Communications",
	    "FNW-3800-TX 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_PROLAN, PCI_PRODUCT_PROLAN_NE2KETHER,
	    0,
	    "ProLAN",
	    "Ethernet",
	},
	{
	    PCI_VENDOR_QLOGIC, PCI_PRODUCT_QLOGIC_ISP1020,
	    0,
	    "Q Logic",
	    "ISP1020",
	},
	{
	    PCI_VENDOR_QLOGIC, PCI_PRODUCT_QLOGIC_ISP1080,
	    0,
	    "Q Logic",
	    "ISP1080",
	},
	{
	    PCI_VENDOR_QLOGIC, PCI_PRODUCT_QLOGIC_ISP1240,
	    0,
	    "Q Logic",
	    "ISP1240",
	},
	{
	    PCI_VENDOR_QLOGIC, PCI_PRODUCT_QLOGIC_ISP2100,
	    0,
	    "Q Logic",
	    "ISP2100",
	},
	{
	    PCI_VENDOR_RALINK, PCI_PRODUCT_RALINK_RT2560,
	    0,
	    "",
	    "RT2560 802.11b/g",
	},
	{
	    PCI_VENDOR_RALINK, PCI_PRODUCT_RALINK_RT2561S,
	    0,
	    "",
	    "RT2561S 802.11b/g",
	},
	{
	    PCI_VENDOR_RALINK, PCI_PRODUCT_RALINK_RT2561,
	    0,
	    "",
	    "RT2561 802.11b/g",
	},
	{
	    PCI_VENDOR_RALINK, PCI_PRODUCT_RALINK_RT2661,
	    0,
	    "",
	    "RT2661 802.11b/g/n",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8029,
	    0,
	    "Realtek Semiconductor",
	    "8029 Ethernet",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8129,
	    0,
	    "Realtek Semiconductor",
	    "8129 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8101E,
	    0,
	    "Realtek Semiconductor",
	    "8101E PCIe 10/10 Ethernet",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8139B,
	    0,
	    "Realtek Semiconductor",
	    "8139B 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8139,
	    0,
	    "Realtek Semiconductor",
	    "8139 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8169SC,
	    0,
	    "Realtek Semiconductor",
	    "8169SC/8110SC Single-chip Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8168,
	    0,
	    "Realtek Semiconductor",
	    "8168/8111B PCIe Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8169,
	    0,
	    "Realtek Semiconductor",
	    "8169 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8180,
	    0,
	    "Realtek Semiconductor",
	    "8180 802.11b",
	},
	{
	    PCI_VENDOR_SILAN, PCI_PRODUCT_SILAN_SC92031,
	    0,
	    "Hangzhou Silan Microelectronics",
	    "SC92031 based fast ethernet adapter",
	},
	{
	    PCI_VENDOR_SILAN, PCI_PRODUCT_SILAN_8139D,
	    0,
	    "Hangzhou Silan Microelectronics",
	    "8139D fast ethernet adapter",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_900,
	    0,
	    "Silicon Integrated System",
	    "SiS 900 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_7016,
	    0,
	    "Silicon Integrated System",
	    "SiS 7016 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_SMC, PCI_PRODUCT_SMC_83C170,
	    0,
	    "Standard Microsystems",
	    "83C170 (\"EPIC/100\") Fast Ethernet",
	},
	{
	    PCI_VENDOR_SUN, PCI_PRODUCT_SUN_5821,
	    0,
	    "Sun Microsystems, Inc.",
	    "Sun bcm5821",
	},
	{
	    PCI_VENDOR_SUN, PCI_PRODUCT_SUN_SCA1K,
	    0,
	    "Sun Microsystems, Inc.",
	    "Crypto Accelerator 1000",
	},
	{
	    PCI_VENDOR_SUNDANCETI, PCI_PRODUCT_SUNDANCETI_ST201,
	    0,
	    "Sundance Technology",
	    "ST201 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_SURECOM, PCI_PRODUCT_SURECOM_NE34,
	    0,
	    "Surecom Technology",
	    "NE-34 Ethernet",
	},
	{
	    PCI_VENDOR_SCHNEIDERKOCH, PCI_PRODUCT_SCHNEIDERKOCH_SKNET_GE,
	    0,
	    "Schneider & Koch",
	    "SK-NET GE",
	},
	{
	    PCI_VENDOR_SCHNEIDERKOCH, PCI_PRODUCT_SCHNEIDERKOCH_SK9821v2,
	    0,
	    "Schneider & Koch",
	    "SK-9821 v2.0",
	},
	{
	    PCI_VENDOR_SCHNEIDERKOCH, PCI_PRODUCT_SCHNEIDERKOCH_SK_9DX1,
	    0,
	    "Schneider & Koch",
	    "SK-NET SK-9DX1 Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_SCHNEIDERKOCH, PCI_PRODUCT_SCHNEIDERKOCH_SK_9D41,
	    0,
	    "Schneider & Koch",
	    "SK-9D41 1000BASE-X",
	},
	{
	    PCI_VENDOR_SII, PCI_PRODUCT_SII_3132,
	    0,
	    "Silicon Image",
	    "Sii3132",
	},
	{
	    PCI_VENDOR_TTTECH, PCI_PRODUCT_TTTECH_MC322,
	    0,
	    "TTTech",
	    "MC322",
	},
	{
	    PCI_VENDOR_TI, PCI_PRODUCT_TI_ACX100A,
	    0,
	    "Texas Instruments",
	    "ACX100A 802.11b",
	},
	{
	    PCI_VENDOR_TI, PCI_PRODUCT_TI_ACX100B,
	    0,
	    "Texas Instruments",
	    "ACX100B 802.11b",
	},
	{
	    PCI_VENDOR_TI, PCI_PRODUCT_TI_ACX111,
	    0,
	    "Texas Instruments",
	    "ACX111 802.11b/g",
	},
	{
	    PCI_VENDOR_USR2, PCI_PRODUCT_USR2_997902,
	    0,
	    "US Robotics",
	    "Robotics 997902 Gigabit Ethernet",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT86C926,
	    0,
	    "VIA Technologies",
	    "VT86C926 Amazon PCI-Ethernet Controller",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT3043,
	    0,
	    "VIA Technologies",
	    "VT3043 (Rhine) 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT6105M,
	    0,
	    "VIA Technologies",
	    "VT6105M (Rhine III) 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT6102,
	    0,
	    "VIA Technologies",
	    "VT6102 (Rhine II) 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT6105,
	    0,
	    "VIA Technologies",
	    "VT6105 (Rhine III) 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT612X,
	    0,
	    "VIA Technologies",
	    "VT612X 10/100/1000 Ethernet",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT8623_VGA,
	    0,
	    "VIA Technologies",
	    "VT8623 (Apollo CLE266) VGA Controller",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT8623,
	    0,
	    "VIA Technologies",
	    "VT8623 (Apollo CLE266) CPU-PCI Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT8251_SATA,
	    0,
	    "VIA Technologies",
	    "VT8251 SATA",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT86C100A,
	    0,
	    "VIA Technologies",
	    "VT86C100A (Rhine-II) 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_WINBOND, PCI_PRODUCT_WINBOND_W89C840F,
	    0,
	    "Winbond Electronics",
	    "W89C840F 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_WINBOND, PCI_PRODUCT_WINBOND_W89C940F,
	    0,
	    "Winbond Electronics",
	    "W89C940F Ethernet",
	},
	{
	    PCI_VENDOR_HAUPPAUGE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hauppauge Computer Works",
	    NULL,
	},
	{
	    PCI_VENDOR_TTTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "TTTech",
	    NULL,
	},
	{
	    PCI_VENDOR_ATI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ATI Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_NS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "National Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_NCR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "AT&T Global Information Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_AMD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Micro Devices",
	    NULL,
	},
	{
	    PCI_VENDOR_DELL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dell Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_SIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Silicon Integrated System",
	    NULL,
	},
	{
	    PCI_VENDOR_TI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Texas Instruments",
	    NULL,
	},
	{
	    PCI_VENDOR_WINBOND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Winbond Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_APPLE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Apple Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_QLOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Q Logic",
	    NULL,
	},
	{
	    PCI_VENDOR_SUN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sun Microsystems, Inc.",
	    NULL,
	},
	{
	    PCI_VENDOR_SII, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Silicon Image",
	    NULL,
	},
	{
	    PCI_VENDOR_BROOKTREE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Brooktree",
	    NULL,
	},
	{
	    PCI_VENDOR_STB, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "STB Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_3COM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "3Com",
	    NULL,
	},
	{
	    PCI_VENDOR_SMC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Standard Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_SURECOM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Surecom Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_NVIDIA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Nvidia Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_REALTEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Realtek Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_IODATA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "I-O Data Device",
	    NULL,
	},
	{
	    PCI_VENDOR_VIATECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "VIA Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_ACCTON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Accton Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_EFFICIENTNETS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Efficent Networks",
	    NULL,
	},
	{
	    PCI_VENDOR_SCHNEIDERKOCH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Schneider & Koch",
	    NULL,
	},
	{
	    PCI_VENDOR_DIGI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Digi International",
	    NULL,
	},
	{
	    PCI_VENDOR_DLINK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "D-Link Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_MARVELL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Marvell (was Galileo Technology)",
	    NULL,
	},
	{
	    PCI_VENDOR_LUCENT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Lucent Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Compex",
	    NULL,
	},
	{
	    PCI_VENDOR_COMTROL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Comtrol",
	    NULL,
	},
	{
	    PCI_VENDOR_COREGA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Corega",
	    NULL,
	},
	{
	    PCI_VENDOR_NORTEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Nortel Networks (Northern Telecom)",
	    NULL,
	},
	{
	    PCI_VENDOR_ALTEON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alteon",
	    NULL,
	},
	{
	    PCI_VENDOR_USR2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "US Robotics",
	    NULL,
	},
	{
	    PCI_VENDOR_FORTEMEDIA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Forte Media",
	    NULL,
	},
	{
	    PCI_VENDOR_CNET, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "CNet",
	    NULL,
	},
	{
	    PCI_VENDOR_LEVELONE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Level One",
	    NULL,
	},
	{
	    PCI_VENDOR_HIFN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hifn",
	    NULL,
	},
	{
	    PCI_VENDOR_SUNDANCETI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sundance Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ASKEY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Askey Computer Corp.",
	    NULL,
	},
	{
	    PCI_VENDOR_AVERMEDIA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Avermedia Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_AIRONET, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Aironet Wireless Communications",
	    NULL,
	},
	{
	    PCI_VENDOR_INVERTEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Invertex",
	    NULL,
	},
	{
	    PCI_VENDOR_BROADCOM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Broadcom Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_PLANEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Planex Communications",
	    NULL,
	},
	{
	    PCI_VENDOR_DELTA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Delta Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_TERRATEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "TerraTec Electronic",
	    NULL,
	},
	{
	    PCI_VENDOR_BLUESTEEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Bluesteel Networks",
	    NULL,
	},
	{
	    PCI_VENDOR_NETSEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetSec",
	    NULL,
	},
	{
	    PCI_VENDOR_ATHEROS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Atheros Communications, Inc.",
	    NULL,
	},
	{
	    PCI_VENDOR_LINKSYS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Linksys",
	    NULL,
	},
	{
	    PCI_VENDOR_ALTIMA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Altima",
	    NULL,
	},
	{
	    PCI_VENDOR_PEPPERCON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Peppercon AG",
	    NULL,
	},
	{
	    PCI_VENDOR_BELKIN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Belkin",
	    NULL,
	},
	{
	    PCI_VENDOR_SILAN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hangzhou Silan Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_JMICRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "JMicron Technology Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_ADDTRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Addtron Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ICOMPRESSION, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Conexant (iCompression)",
	    NULL,
	},
	{
	    PCI_VENDOR_NETVIN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetVin",
	    NULL,
	},
	{
	    PCI_VENDOR_INTEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Intel",
	    NULL,
	},
	{
	    PCI_VENDOR_PROLAN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ProLAN",
	    NULL,
	},
	{
	    PCI_VENDOR_KTI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "KTI",
	    NULL,
	},
	{
	    PCI_VENDOR_ADP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Adaptec",
	    NULL,
	},
	{
	    PCI_VENDOR_INVALID, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "INVALID VENDOR ID",
	    NULL,
	},
	{ 0, 0, 0, NULL, NULL, }
};
