--- pyproject.toml.orig	2023-02-25 10:36:04 UTC
+++ pyproject.toml
@@ -4,7 +4,7 @@ requires = ["setuptools >= 61"]
 build-backend = "setuptools.build_meta"
 
 [project]
-name = "Pygments"
+name = "pygments"
 dynamic = ["version"]
 requires-python = ">=3.7"
 license = {text = "BSD-2-Clause"}
