# $FreeBSD: src/gnu/usr.bin/cc/Makefile.fe,v 1.2 2002/05/10 08:54:43 obrien Exp $
# $DragonFly: src/gnu/usr.bin/cc3/Attic/Makefile.fe,v 1.1 2004/01/17 22:40:14 drhodus Exp $

#	Front-end-only bits

version!=	sed -n /version_string/p ${GCCDIR}/version.c | sed -e 's/.*\"\([^ \"]*\)[ \"].*/\1/'
