#	@(#)Makefile	8.1 (Berkeley) 6/5/93
#	$Id: Makefile,v 1.1.1.1 1999/08/08 23:31:13 itojun Exp $
# $FreeBSD: src/usr.sbin/prefix/Makefile,v 1.1.2.4 2002/08/08 09:47:50 ru Exp $
# $DragonFly: src/usr.sbin/prefix/Makefile,v 1.2 2003/06/17 04:30:01 dillon Exp $

SCRIPTS=prefix.sh
MAN=	prefix.8

.include <bsd.prog.mk>
