# $FreeBSD: src/sys/boot/powerpc/Makefile,v 1.1 2000/10/16 10:46:10 obrien Exp $
# $DragonFly: src/sys/boot/powerpc/Makefile,v 1.1 2003/11/10 06:08:40 dillon Exp $

SUBDIR=		loader

.include <bsd.subdir.mk>
