# $DragonFly: src/lib/libm/Makefile,v 1.5 2005/07/26 21:15:19 joerg Exp $

LIB=		m
SHLIB_MAJOR=	3
WARNS?=		6

# Don't MD fragment must be included before MI fragment.
.include "arch/${MACHINE_ARCH}/Makefile.inc"
.include "man/Makefile.inc"
.include "src/Makefile.inc"

.include <bsd.lib.mk>
