# $FreeBSD: src/kerberosIV/include/Makefile,v 1.3 1999/09/19 22:00:51 markm Exp $
# $DragonFly: src/kerberosIV/include/Attic/Makefile,v 1.2 2003/06/17 04:26:25 dillon Exp $

.if exists(${.OBJDIR}/../../include)
INCLUDEOBJDIR=	${.OBJDIR}/../include
.else
INCLUDEOBJDIR=	${.CURDIR}/../include
.endif

depend lint tags:

.include <bsd.prog.mk>
