# $FreeBSD: src/secure/usr.bin/ssh-add/Makefile,v 1.2.2.3 2002/07/03 22:20:31 des Exp $
# $DragonFly: src/secure/usr.bin/ssh-add/Makefile,v 1.3 2004/07/31 19:03:01 geekgod Exp $

PROG=	ssh-add
WARNS?=	3

.include "../../Makefile.ssh.common"
.include <bsd.prog.mk>
