# $FreeBSD: src/share/doc/psd/28.cvs/Makefile,v 1.2 1999/08/28 00:18:32 peter Exp $
# $DragonFly: src/share/doc/psd/28.cvs/Makefile,v 1.3 2004/06/26 17:44:23 dillon Exp $

# XXX removed from build, this file no longer exists in 1.12.8. 
# XXX fixme, do something with the .texi files.
#
VOLUME= psd/28.cvs
MACROS= -ms
SRCDIR= ${.CURDIR}/../../../../contrib/cvs-1.12.8/doc
SRCS=	cvs-paper.ms
USE_PIC=	yes
USE_TBL=	yes

.include <bsd.doc.mk>
