# $FreeBSD: src/lib/libsbuf/Makefile,v 1.3.2.1 2002/10/10 19:24:35 kbyanc Exp $
# $DragonFly: src/lib/libsbuf/Makefile,v 1.2 2003/06/17 04:26:51 dillon Exp $

LIB=	sbuf
SRCS=	subr_sbuf.c 
WARNS?= 2

.PATH:	${.CURDIR}/../../sys/kern

.include <bsd.lib.mk>
