# $DragonFly: src/lib/pam_module/pam_permit/Makefile,v 1.1 2005/07/08 15:42:01 joerg Exp $

LIB=	pam_permit
SRCS=	pam_permit.c
WARNS?=	2
WARNS_NO_UNUSED_PARAMETERS=

.include <bsd.lib.mk>

.PATH: ${OPENPAM_DIR}/modules/pam_permit
