#	Makefile for xten (Stark) 10/30/93
# $FreeBSD: src/usr.sbin/xten/Makefile,v 1.8 1999/08/28 01:21:01 peter Exp $
# $DragonFly: src/usr.sbin/xten/Makefile,v 1.2 2003/06/17 04:30:04 dillon Exp $

PROG=	xten
CFLAGS+= -I${.CURDIR}/../../libexec/xtend

.include <bsd.prog.mk>
