# $FreeBSD: src/usr.bin/lessecho/Makefile,v 1.2.2.1 2000/06/30 01:03:15 ps Exp $

PROG=	lessecho
SRCS=	lessecho.c version.c
CLEANFILES= lessecho.1
WARNS?=	2

.include "${.CURDIR}/../less/Makefile.common"
.include <bsd.prog.mk>
