.\" Copyright (c) 2007 The DragonFly Project.  All rights reserved.
.\" 
.\" This code is derived from software contributed to The DragonFly Project
.\" by Matthew Dillon <dillon@backplane.com>
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\" 
.\" $DragonFly: src/sbin/mount_hammer/mount_hammer.8,v 1.9 2008/07/03 06:36:27 dillon Exp $
.Dd June 24, 2008
.Dt MOUNT_HAMMER 8
.Os
.Sh NAME
.Nm mount_hammer
.Nd mount a HAMMER file system
.Sh SYNOPSIS
.Nm
.Op Fl o Ar mount-options
.Op Fl T Ar transactionid
.Ar special ...
.Ar mount-point
.Nm
.Op Fl u
.Op Fl o Ar mount-options
.Ar mount-point
.Sh DESCRIPTION
The
.Nm
utility mounts a HAMMER filesystem backed by one or more block devices.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl o Ar mount-options
Specify mount options, which are a comma delimited set of options (see
.Xr mount 8 ) .
Supported mount options are:
.Bl -tag -width indent
.It Ar ro
Issue a read-only mount.
.It Ar nohistory
Put the entire filesystem in no-history mode.  Change history is not
retained.
Use of this option may increase the overhead of doing mirroring.
This option is generally only used in an emergency.
.El
.It Fl T Ar transactionid
Mount the filesystem as-of a particular
transaction id.
The mount will automatically be made read-only.
The
.Ar transactionid
must be specified as a 64 bit hex value prefixed with "0x".
.It Fl u
Update the mount point.  This is typically used to upgrade a mount to
read-write or downgrade it to read-only.
.El
.Sh NOTES
Note that issuing a read-only mount which requires UNDOs to be run will
still run the UNDOs, but will not flush the buffer cache buffers until/if
the mount is updated to read-write.
.Sh EXAMPLES
.Bd -literal -offset indent
mount_hammer -o ro,noatime /dev/ad0s1d /dev/ad1s1d /mnt
.Ed
.Pp
Mount a hammer filesystem made up of two volumes onto
.Pa /mnt .
.Sh DIAGNOSTICS
Exit status is 0 on success and 1 on error.
.Sh SEE ALSO
.Xr disklabel 8 ,
.Xr fdisk 8 ,
.Xr hammer 8 ,
.Xr newfs_hammer 8
.Sh HISTORY
The
.Nm
utility first appeared in
.Dx 1.11 .
.Sh AUTHORS
.An Matthew Dillon Aq dillon@backplane.com
