.\" Copyright (c) 2007 The DragonFly Project.  All rights reserved.
.\" 
.\" This code is derived from software contributed to The DragonFly Project
.\" by Matthew Dillon <dillon@backplane.com>
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\" 
.Dd September 27, 2009
.Dt MOUNT_HAMMER 8
.Os
.Sh NAME
.Nm mount_hammer
.Nd mount a HAMMER file system
.Sh SYNOPSIS
.Nm
.Op Fl o Ar options
.Op Fl T Ar transaction-id
.Ar special ...
.Ar node
.Nm
.Op Fl o Ar options
.Op Fl T Ar transaction-id
.Ar special Ns Oo Cm \&: Ns Ar special Oc Ns *
.Ar node
.Nm
.Fl u
.Op Fl o Ar options
.Ar node
.Sh DESCRIPTION
The
.Nm
utility mounts a
.Nm HAMMER
file system backed by
.Ar special
file(s) at mount point
.Ar node .
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl o Ar options
Options are specified with a
.Fl o
flag followed by a comma separated string of options.
See the
.Xr mount 8
man page for possible options and their meanings.
The following
.Nm HAMMER
specific options are also available:
.Bl -tag -width indent
.It Cm nohistory
Put the entire file system in no-history mode.
Change history is not retained.
Use of this option may increase the overhead of doing mirroring.
This option is generally only used in an emergency.
.It Cm master= Ns Ar id
Assign a master id for the entire mount which applies to all PFSs under
the mount.
This is intended to help support multi-master and fail-over operation.
Multi-master operation is not yet supported.
If you intend
to upgrade slaves to masters and downgrade masters to slaves as part of
a fail-over setup, it's a good idea to assign a different master id
to the
.Nm HAMMER
mounts making up the fail-over group.
.It Cm nomirror
By default a
.Nm HAMMER
mount assigns a master id of 0.
You can force no-mirror operation by specifying this option.
This option disables
mirror transaction id propagation in the B-Tree and will improve write
performance somewhat but also prevents incremental mirroring from working
at all, and is not recommended.
.El
.It Fl T Ar transaction-id
Mount the file system as-of a particular
transaction id.
The mount will automatically be made read-only.
The
.Ar transaction-id
must be specified as a 64 bit hex value prefixed with "0x".
.It Fl u
Update the mount point.
This is typically used to upgrade a mount to
read-write or downgrade it to read-only.
.El
.Sh NOTES
Note that issuing a read-only mount which requires UNDOs to be run will
still run the UNDOs, but will not flush the buffer cache buffers until/if
the mount is updated to read-write.
.Sh EXAMPLES
Mount a
.Nm HAMMER
file system made up of two volumes onto
.Pa /mnt :
.Bd -literal -offset indent
mount_hammer -o ro,noatime /dev/ad0s1d /dev/ad1s1d /mnt
.Ed
.Pp
A corresponding
.Xr fstab 5
entry is:
.Bd -literal -offset indent
/dev/ad0s1d:/dev/ad1s1d /mnt hammer ro,noatime
.Ed
.Sh DIAGNOSTICS
Exit status is 0 on success and 1 on error.
.Sh SEE ALSO
.Xr mount 2 ,
.Xr unmount 2 ,
.Xr fstab 5 ,
.Xr HAMMER 5 ,
.Xr disklabel 8 ,
.Xr disklabel64 8 ,
.Xr fdisk 8 ,
.Xr gpt 8 ,
.Xr hammer 8 ,
.Xr mount 8 ,
.Xr newfs_hammer 8
.Sh HISTORY
The
.Nm
utility first appeared in
.Dx 1.11 .
.Sh AUTHORS
.An Matthew Dillon Aq Mt dillon@backplane.com
