# $FreeBSD: src/gnu/usr.bin/groff/font/Makefile.inc,v 2.1.2.1 2001/04/26 17:08:01 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/font/Makefile.inc,v 1.2 2003/06/17 04:25:46 dillon Exp $

DIST_SUBDIR=	font/${.CURDIR:T}
TOPREL=		../..

.include "../Makefile.inc"
