KMOD=	ext2fs_freebsd
SRCS=	ext2_alloc.c ext2_balloc.c ext2_bmap.c ext2_csum.c ext2_extents.c ext2_hash.c ext2_htree.c ext2_ihash.c ext2_inode.c ext2_inode_cnv.c ext2_lookup.c ext2_subr.c ext2_vfsops.c ext2_vnops.c

.include <bsd.kmod.mk>
