# $FreeBSD: src/usr.sbin/jls/Makefile,v 1.1 2003/04/09 03:04:12 mike Exp $
# $DragonFly: src/usr.sbin/jls/Makefile,v 1.1 2005/01/31 22:29:59 joerg Exp $

PROG=	jls
MAN=	jls.8
WARNS?=	6

.include <bsd.prog.mk>
