#!/bin/csh
#

umount /mnt >& /dev/null
kldunload hammer2.ko >& /dev/null
kldstat | fgrep hammer2.ko >& /dev/null
if ( $status > 0 ) then
    kldload /usr/obj/usr/src/sys/vfs/hammer2/hammer2.ko
endif
mount_hammer2 /dev/da0s1d@ROOT /mnt
sysctl vfs.hammer2.debug=1
