#!/bin/csh
#

# ./mkvntest
umount /mnt >& /dev/null
kldunload hammer2.ko >& /dev/null
kldstat | fgrep hammer2.ko >& /dev/null
if ( $status > 0 ) then
    kldload /usr/obj/usr/src/sys/vfs/hammer2/hammer2.ko
endif
mount_hammer2 /dev/vn0@ROOT /mnt
