# $FreeBSD: src/sys/modules/dummynet/Makefile,v 1.1.2.2 2003/04/08 10:18:00 maxim Exp $
# $DragonFly: src/sys/net/dummynet/Makefile,v 1.5 2007/10/29 02:54:15 sephe Exp $

KMOD=   dummynet
SRCS=   ip_dummynet.c
KMODDEPS= ipfw

.include <bsd.kmod.mk>
