# $FreeBSD: src/sys/modules/dummynet/Makefile,v 1.1.2.2 2003/04/08 10:18:00 maxim Exp $
# $DragonFly: src/sys/net/dummynet/Makefile,v 1.6 2007/11/16 02:45:45 sephe Exp $

KMOD=   dummynet
SRCS=   ip_dummynet.c

.include <bsd.kmod.mk>
