# $Revision: 1.6 $
# $FreeBSD: src/sbin/routed/rtquery/Makefile,v 1.7.2.1 2001/04/25 10:58:50 ru Exp $
# $DragonFly: src/sbin/routed/rtquery/Makefile,v 1.5 2008/11/03 00:25:45 pavalos Exp $

PROG=	rtquery
MAN=	rtquery.8
LDADD+=	-lmd
DPADD+=	${LIBMD}
NO_WARRAY_BOUNDS=

.include <bsd.prog.mk>
