# $DragonFly: src/sys/dev/usbmisc/uchcom/Makefile,v 1.1 2007/11/07 09:07:44 hasso Exp $

S=	${.CURDIR}/../..
.PATH: $S/dev/usb

KMOD=	uchcom
SRCS=	uchcom.c opt_usb.h device_if.h bus_if.h

.include <bsd.kmod.mk>
