# $FreeBSD: src/gnu/usr.bin/groff/doc/Makefile,v 1.4.2.1 2000/12/07 09:57:02 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/doc/Makefile,v 1.2 2003/06/17 04:25:46 dillon Exp $

INFO=	groff
SRCDIR=	${DIST_DIR}

.include <bsd.info.mk>
