# $FreeBSD: src/sys/modules/drm/Makefile.inc,v 1.1.4.1 2003/04/26 07:31:06 anholt Exp $
# $DragonFly: src/sys/dev/drm/Attic/Makefile.inc,v 1.3 2003/08/15 08:32:29 dillon Exp $

#.include "../Makefile.inc"
