# $DragonFly: src/gnu/usr.bin/gdb/libbfd/Makefile.i386,v 1.4 2008/08/02 15:29:53 corecode Exp $

SRCS+=	elf32-gen.c elf32.c elf32-target.h
SRCS+=	coff-i386.c cpu-i386.c elf32-i386.c

VECTORS=	bfd_elf32_i386_vec \
		i386coff_vec \
		bfd_elf32_little_generic_vec \
		bfd_elf32_big_generic_vec

DEFAULT_VECTOR=	bfd_elf32_i386_vec

ARCHITECTURE=	bfd_i386_arch

BFD_DEFAULT_TARGET_SIZE?=	32
