#	From: @(#)Makefile	6.3 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/papers/malloc/Makefile,v 1.4 1999/08/28 00:18:08 peter Exp $
# $DragonFly: src/share/doc/papers/malloc/Makefile,v 1.2 2003/06/17 04:36:56 dillon Exp $

VOLUME=	papers
DOC=	malloc
SRCS=	abs.ms intro.ms kernel.ms malloc.ms problems.ms alternatives.ms
SRCS+=	performance.ms implementation.ms conclusion.ms
MACROS=	-ms

edit:
	vi ${SRCS}

.include <bsd.doc.mk>
