.PATH:	${.CURDIR}/..
KMOD	= cxm
SRCS	= cxm.c cxm.h cxm_dec_fw.c cxm_enc_fw.c cxm_msp34xxx.c cxm_eeprom.c \
	  cxm_ir.c cxm_tuner.c cxm_saa7115.c \
	  bus_if.h device_if.h iicbb_if.h pci_if.h pcidevs.h

.include <bsd.kmod.mk>
