#	from: @(#)Makefile.vax	6.1 (Berkeley) 3/3/91
# $FreeBSD: src/gnu/usr.bin/as/config/Makefile.vax,v 1.4 1999/08/27 23:34:27 peter Exp $
# $DragonFly: src/gnu/usr.bin/as/config/Attic/Makefile.vax,v 1.2 2003/06/17 04:25:44 dillon Exp $

SRCS+=		tc-vax.c atof-vax.c
