#	from: @(#)Makefile.i386	6.1 (Berkeley) 3/3/91
# $FreeBSD: src/gnu/usr.bin/as/config/Makefile.i386,v 1.6 1999/08/27 23:34:27 peter Exp $
# $DragonFly: src/gnu/usr.bin/as/config/Attic/Makefile.i386,v 1.2 2003/06/17 04:25:44 dillon Exp $

CFLAGS+=	-DNON_BROKEN_WORDS -DPIC
SRCS+=		tc-i386.c atof-ieee.c
