#	from: @(#)Makefile.hp300	6.1 (Berkeley) 3/3/91
# $FreeBSD: src/gnu/usr.bin/as/config/Makefile.hp300,v 1.4 1999/08/27 23:34:26 peter Exp $
# $DragonFly: src/gnu/usr.bin/as/config/Attic/Makefile.hp300,v 1.2 2003/06/17 04:25:44 dillon Exp $

CFLAGS+=	-Dm68851
SRCS+=		tc-m68k.c atof-ieee.c

gas_target=	m68k
