# $FreeBSD: src/sys/modules/splash/pcx/Makefile,v 1.3 1999/08/28 00:47:39 peter Exp $
# $DragonFly: src/sys/dev/video/fb/pcx/Makefile,v 1.3 2003/10/06 17:19:38 dillon Exp $

.PATH:  ${.CURDIR}/..
KMOD=	splash_pcx
SRCS=	splash_pcx.c splash.c
NOMAN=

.include <bsd.kmod.mk>
