# $FreeBSD: src/sys/modules/splash/pcx/Makefile,v 1.3 1999/08/28 00:47:39 peter Exp $
# $DragonFly: src/sys/dev/video/fb/pcx/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $

KMOD=	splash_pcx
SRCS=	splash_pcx.c
NOMAN=

.include <bsd.kmod.mk>
