#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/lastcomm/Makefile,v 1.3 2002/02/08 22:31:41 markm Exp $
# $DragonFly: src/usr.bin/lastcomm/Makefile,v 1.4 2007/08/27 16:50:55 pavalos Exp $

PROG=	lastcomm

.include <bsd.prog.mk>
