#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/lastcomm/Makefile,v 1.1.1.1.14.1 2001/10/01 12:51:15 dd Exp $
# $DragonFly: src/usr.bin/lastcomm/Makefile,v 1.4 2007/08/27 16:50:55 pavalos Exp $

PROG=	lastcomm

.include <bsd.prog.mk>
