#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/lastcomm/Makefile,v 1.1.1.1.14.1 2001/10/01 12:51:15 dd Exp $
# $DragonFly: src/usr.bin/lastcomm/Makefile,v 1.2 2003/06/17 04:29:27 dillon Exp $

PROG=	lastcomm
WARNS?=	2

.include <bsd.prog.mk>
