# $FreeBSD: src/sys/boot/arc/Makefile,v 1.2 1999/08/28 00:39:33 peter Exp $
# $DragonFly: src/sys/boot/arc/Attic/Makefile,v 1.3 2003/11/10 06:08:30 dillon Exp $

SUBDIR=		lib
SUBDIR+=	loader

.include <bsd.subdir.mk>
