# $FreeBSD: src/sys/boot/arc/Makefile,v 1.2 1999/08/28 00:39:33 peter Exp $
# $DragonFly: src/sys/boot/arc/Attic/Makefile,v 1.2 2003/06/17 04:28:16 dillon Exp $

SUBDIR=		lib
SUBDIR+=	loader

.include <bsd.subdir.mk>
