# $FreeBSD: src/kerberosIV/usr.bin/ksrvtgt/Makefile,v 1.2.2.2 2001/04/25 14:04:14 ru Exp $
# $DragonFly: src/kerberosIV/usr.bin/ksrvtgt/Attic/Makefile,v 1.2 2003/06/17 04:26:25 dillon Exp $

SCRIPTS=	ksrvtgt.in
MAN=		${KRB4DIR}/man/ksrvtgt.1

.include <bsd.prog.mk>

.PATH:	${KRB4DIR}/appl/kauth
