# $FreeBSD: src/gnu/usr.bin/cc/gcov/Makefile,v 1.1.2.1 2000/12/23 19:50:57 obrien Exp $
# $DragonFly: src/gnu/usr.bin/cc/gcov/Attic/Makefile,v 1.2 2003/06/17 04:25:45 dillon Exp $

.include "../Makefile.inc"

.PATH: ${GCCDIR}

PROG=	gcov
SRCS=	gcov.c
NOMAN=	1

.include <bsd.prog.mk>
