# $Id: Makefile,v 1.2 2003/04/27 00:22:11 max Exp $
# $FreeBSD: head/sys/modules/netgraph/bluetooth/Makefile 181233 2008-08-03 10:32:17Z ed $

SUBDIR=	\
	bluetooth \
	drivers \
	hci	\
	l2cap	\
	socket

.include <bsd.subdir.mk>
