# Makefile for building the sample syscall module
# $FreeBSD: src/share/examples/kld/syscall/module/Makefile,v 1.1.6.1 2002/07/17 14:13:53 ru Exp $
# $DragonFly: src/share/examples/kld/syscall/module/Makefile,v 1.2 2003/06/17 04:36:57 dillon Exp $

KMOD=	syscall
SRCS=	syscall.c

.include <bsd.kmod.mk>
