# $FreeBSD: src/sys/modules/i2c/controllers/pcf/Makefile,v 1.4 2005/11/22 17:32:51 marius Exp $

.PATH: ${.CURDIR}/..

KMOD=	pcf
SRCS=	pcf.c
SRCS+=	bus_if.h device_if.h iicbus_if.h isa_if.h

.include <bsd.kmod.mk>
