# $FreeBSD: src/sys/modules/fdesc/Makefile,v 1.6 1999/12/12 16:47:24 peter Exp $
# $DragonFly: src/sys/vfs/fdesc/Makefile,v 1.4 2004/08/13 17:51:10 dillon Exp $

KMOD=	fdesc
SRCS=	fdesc_vfsops.c fdesc_vnops.c
NOMAN=
CFLAGS+= -DFDESC

.include <bsd.kmod.mk>
