#	$OpenBSD: Makefile,v 1.3 2003/07/18 02:00:09 deraadt Exp $
#	$DragonFly: src/usr.bin/patch/Makefile,v 1.1 2004/09/24 18:44:28 joerg Exp $

PROG=	patch
SRCS=	patch.c pch.c inp.c util.c backupfile.c

WARNS?=	3

.include <bsd.prog.mk>
