# $FreeBSD: src/kerberos5/tools/make-print-version/Makefile,v 1.2 2004/12/21 08:47:02 ru Exp $
# $DragonFly: src/kerberos5/tools/make-print-version/Makefile,v 1.2 2005/07/14 18:02:33 joerg Exp $

PROG=	make-print-version
NOMAN=

.include <bsd.hostprog.mk>

.PATH: ${KRB5DIR}/lib/vers
