# $FreeBSD: src/kerberos5/tools/make-print-version/Makefile,v 1.2 2004/12/21 08:47:02 ru Exp $
# $DragonFly: src/kerberos5/tools/make-print-version/Makefile,v 1.1 2005/01/16 14:25:47 eirikn Exp $

PROG=	make-print-version
NOMAN=

.include <bsd.prog.mk>

.PATH: ${KRB5DIR}/lib/vers
