# $FreeBSD: src/sys/modules/md/Makefile,v 1.3 1999/11/28 18:52:57 bde Exp $
# $DragonFly: src/sys/dev/disk/md/Makefile,v 1.2 2003/06/17 04:28:44 dillon Exp $

.PATH:	${.CURDIR}/../../dev/md
KMOD=	md
SRCS=	md.c opt_mfs.h opt_md.h
NOMAN=

.include <bsd.kmod.mk>
