# $DragonFly: src/sys/dev/acpica5/acpi_video/Makefile,v 1.2 2008/09/06 21:21:31 hasso Exp $

KMOD=		acpi_video
CFLAGS+=	-I${.OBJDIR}/.. -I${.CURDIR}/..
SRCS=		acpi_video.c opt_acpi.h device_if.h bus_if.h

.include <bsd.kmod.mk>
