#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/banner/Makefile,v 1.3.6.2 2001/08/02 00:56:44 obrien Exp $
# $DragonFly: src/usr.bin/banner/Makefile,v 1.3 2005/01/16 04:28:00 cpressey Exp $

PROG=	banner
MAN=	banner.6

WARNS?=	6

.include <bsd.prog.mk>
