# $FreeBSD: src/sys/modules/umapfs/Makefile,v 1.8 1999/12/12 16:47:33 peter Exp $
# $DragonFly: src/sys/vfs/umapfs/Attic/Makefile,v 1.3 2003/08/15 07:26:16 dillon Exp $

KMOD=	umap
SRCS=	vnode_if.h \
	umap_subr.c umap_vfsops.c umap_vnops.c
NOMAN=

.include <bsd.kmod.mk>
