# $FreeBSD: src/sys/modules/umapfs/Makefile,v 1.8 1999/12/12 16:47:33 peter Exp $
# $DragonFly: src/sys/vfs/umapfs/Attic/Makefile,v 1.4 2004/08/13 17:51:14 dillon Exp $

KMOD=	umap
SRCS=	umap_subr.c umap_vfsops.c umap_vnops.c
NOMAN=

.include <bsd.kmod.mk>
