# Makefile for ISC DHCP client.
# $FreeBSD: src/sbin/dhclient/Makefile,v 1.6.2.7 2002/04/11 10:21:20 murray Exp $
# $DragonFly: src/sbin/dhclient/Makefile,v 1.3 2005/01/04 19:58:54 joerg Exp $

SUBDIR=	includes/ common dst minires omapip client

.include <bsd.subdir.mk>
