# $FreeBSD: head/sys/modules/sound/driver/es137x/Makefile 110498 2003-02-07 13:56:33Z nyan $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_es137x
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	es137x.c

.include <bsd.kmod.mk>
