# $FreeBSD: src/usr.sbin/lpr/filters.ru/koi2alt/Makefile,v 1.1.2.1 2002/02/01 01:03:40 gad Exp $
# $DragonFly: src/usr.sbin/lpr/filters.ru/koi2alt/Makefile,v 1.2 2003/06/17 04:29:56 dillon Exp $

PROG=	koi2alt
NOMAN=	#true

.include <bsd.prog.mk>
