# Used by the device build to check for device support
#
# $DragonFly: src/sys/platform/pc32/Makefile.inc,v 1.2 2006/11/07 20:48:15 dillon Exp $

ACPICA5_SUPPORT=1
EST_SUPPORT=1
SYSCONS_APM_SUPPORT=1

