# Used by the device build to check for device support
#

DEV_SUPPORT=	acpica agp bridge crypto disk drm misc netif \
		pccard powermng raid serial sound smbus video \
		virtual/virtio

BOOT0CFG_SUPPORT=1

