#	$NetBSD: Makefile,v 1.5 2010/02/06 23:45:25 he Exp $
#	@(#)Makefile	8.1 (Berkeley) 7/24/94

PROG=	gomoku
SRCS=	bdinit.c bdisp.c main.c makemove.c pickmove.c stoc.c
MAN=	gomoku.6
GAMESCURSES=

.include <bsd.prog.mk>
