# $DragonFly: src/gnu/usr.bin/cc34/Makefile,v 1.2 2004/06/20 20:59:21 joerg Exp $

SUBDIR=		cc_prep cc_tools libbackend libcpp cc1 cc
SUBDIR+=	cpp
SUBDIR+=	gcov
SUBDIR+=	cc1plus c++ c++filt
SUBDIR+=	f771 g77
SUBDIR+=	cc1obj

.ORDER: ${SUBDIR}

.include <bsd.subdir.mk>
