# $FreeBSD: src/usr.sbin/i4b/isdntelctl/Makefile,v 1.2.2.2 2001/08/01 17:29:18 obrien Exp $
# $DragonFly: src/usr.sbin/i4b/isdntelctl/Makefile,v 1.2 2003/06/17 04:29:55 dillon Exp $

PROG=	isdntelctl
MAN= 	isdntelctl.8
SRCS=	main.c

.include <bsd.prog.mk>
