.\"
.\" Copyright (c) 2016 The DragonFly Project.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd December 3, 2016
.Dt NVMECTL 8
.Os
.Sh NAME
.Nm nvmectl
.Nd NVM Express (NVMe) userland utility
.Sh SYNOPSIS
.Nm
.Op Fl v
.Ar command
.Ar device
.Sh DESCRIPTION
The
.Nm
utility interacts with the
.Xr nvme 4
controller specified in the
.Ar device
argument (for example
.Pa nvme0 ) .
.Pp
It supports the following options:
.Bl -tag -width indent
.It Fl v
Currently, this option is a no-op.
.El
.Pp
The following commands are available:
.Bl -tag -width indent
.It Ic errors
Displays errors from the controller's log.
.It Ic info
Displays S.M.A.R.T. information from the controller's log.
.El
.Sh EXAMPLES
.Dl nvmectl errors nvme0
.Pp
.Dl nvmectl info nvme0
.Sh SEE ALSO
.Xr nvme 4
.Sh HISTORY
The
.Nm
utility first appeared in
.Dx 4.5 .
.Sh AUTHORS
.An Matthew Dillon
