# $FreeBSD: src/sys/modules/vesa/Makefile,v 1.9 2000/01/29 15:08:42 peter Exp $
# $DragonFly: src/sys/dev/video/i386/vesa/Makefile,v 1.5 2007/08/19 11:39:11 swildner Exp $

.PATH:	${.CURDIR}/../../i386/isa
KMOD	=	vesa
SRCS	=	vesa.c opt_vga.h opt_vesa.h

.include <bsd.kmod.mk>
