# $FreeBSD: src/usr.sbin/stallion/stlstats/Makefile,v 1.6.2.2 2001/04/25 12:10:59 ru Exp $
# $DragonFly: src/usr.sbin/stallion/stlstats/Makefile,v 1.2 2003/06/17 04:30:03 dillon Exp $

PROG=	stlstats
MAN=	stlstats.8
MANSUBDIR=/i386

DPADD=	${LIBNCURSES} ${LIBMYTINFO}
LDADD=	-lncurses -lmytinfo

.include <bsd.prog.mk>
