.\"
.\" Copyright (c) 2014 The DragonFly Project.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd April 14, 2014
.Dt ACPIHELP 8
.Os
.Sh NAME
.Nm acpihelp
.Nd help utility for ASL operators, AML opcodes, and ACPI predefined names
.Sh SYNOPSIS
.Nm
.Op Ar option ...
.Op Ar name/prefix | hex_value
.Sh DESCRIPTION
The following options are supported:
.Bl -tag -width indent
.It Fl a Op Ar name/prefix
Find/Display both ASL operator and AML opcode name(s).
.It Fl e Op Ar hex_value
Decode ACPICA exception code.
.It Fl h
Display help.
.It Fl i
Display known ACPI Device IDs (_HID).
.It Fl k Op Ar name/prefix
Find/Display ASL non-operator keyword(s).
.It Fl m Op Ar name/prefix
Find/Display AML opcode name(s).
.It Fl o Op Ar hex_value
Decode hex AML opcode.
.It Fl p Op Ar name/prefix
Find/Display ASL predefined method name(s).
.It Fl s Op Ar name/prefix
Find/Display ASL operator name(s).
.It Fl v
Display version information.
.El
.Pp
If neither
.Ar name/prefix
nor
.Ar hex_value
are specified
.Nm
defaults to displaying all information available for the specified option.
.Pp
If a
.Ar name/prefix
but no options are specified
.Nm
defaults to finding ASL operator names if
.Ar name/prefix
does not start with an underscore, and to finding ASL predefined method
names if
.Ar name/prefix
does start with an underscore.
.Sh SEE ALSO
.Xr acpi 4 ,
.Xr acpibin 8 ,
.Xr acpiconf 8 ,
.Xr acpidump 8 ,
.Xr acpiexec 8 ,
.Xr acpinames 8 ,
.Xr acpixtract 8 ,
.Xr iasl 8
.Pp
.Lk https://acpica.org/documentation/
.Sh AUTHORS
The
.Nm
utility is provided by
.Tn Intel
as part of their
.Sy ACPICA
distribution.
.Pp
This manual page was written by
.An Sascha Wildner .
