#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/split/Makefile,v 1.2.2.2 2002/07/25 12:33:01 tjr Exp $
# $DragonFly: src/usr.bin/split/Makefile,v 1.2 2003/06/17 04:29:31 dillon Exp $

PROG=	split

.include <bsd.prog.mk>
