#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/split/Makefile,v 1.2.2.2 2002/07/25 12:33:01 tjr Exp $
# $DragonFly: src/usr.bin/split/Makefile,v 1.3 2005/01/02 01:45:20 cpressey Exp $

PROG=	split
WARNS?=	6

.include <bsd.prog.mk>
