#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/split/Makefile,v 1.2.2.2 2002/07/25 12:33:01 tjr Exp $
# $DragonFly: src/usr.bin/split/Makefile,v 1.4 2007/08/27 16:50:59 pavalos Exp $

PROG=	split

.include <bsd.prog.mk>
