# $FreeBSD: src/usr.bin/rwall/Makefile,v 1.4.2.1 2001/04/25 11:29:38 ru Exp $
# $DragonFly: src/usr.bin/rwall/Makefile,v 1.4 2007/08/27 16:50:58 pavalos Exp $

PROG=	rwall

DPADD=	${LIBRPCSVC}
LDADD=	-lrpcsvc

.include <bsd.prog.mk>
