#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/unexpand/Makefile,v 1.1.1.1.14.1 2002/07/09 10:35:16 tjr Exp $
# $DragonFly: src/usr.bin/unexpand/Makefile,v 1.4 2007/08/27 16:51:00 pavalos Exp $

PROG=	unexpand
NOMAN=	noman

.include <bsd.prog.mk>
