# $FreeBSD: src/usr.bin/gensetdefs/Makefile,v 1.6.2.1 2001/04/25 11:29:21 ru Exp $
# $DragonFly: src/usr.bin/gensetdefs/Attic/Makefile,v 1.2 2003/06/17 04:29:27 dillon Exp $

TARGET_ARCH?=	${MACHINE_ARCH}

PROG=	gensetdefs
MAN=	gensetdefs.8
CFLAGS+=	-Darch_${TARGET_ARCH}

.include <bsd.prog.mk>
