# $FreeBSD: src/secure/libexec/sftp-server/Makefile,v 1.1.2.3 2002/07/03 22:13:22 des Exp $
# $DragonFly: src/secure/libexec/sftp-server/Makefile,v 1.3 2004/07/31 19:03:01 geekgod Exp $

PROG=   sftp-server
SRCS=   sftp-server.c sftp-common.c
MAN=	sftp-server.8

.include "../../Makefile.ssh.common"
.include <bsd.prog.mk>
