# TARGET_OBS
SRCS+=	i386-tdep.c i387-tdep.c i386bsd-tdep.c i386fbsd-tdep.c i386dfly-tdep.c \
	bsd-uthread.c corelow.c solib.c solib-svr4.c

.if ${TARGET_ARCH} == ${MACHINE_ARCH}
# NATDEPFILES
SRCS+=	fork-child.c inf-ptrace.c \
	fbsd-nat.c i386-nat.c i386bsd-nat.c i386dfly-nat.c \
	gcore.c
.endif
