# $DragonFly: src/gnu/usr.bin/gdb/libgdb/Makefile.i386,v 1.1 2006/03/07 15:48:11 corecode Exp $

SRCS+=	i386-nat.c i386-tdep.c i386bsd-nat.c i386bsd-tdep.c i386fbsd-nat.c
SRCS+=	i386fbsd-tdep.c i387-tdep.c

tm.h: ${CONTRIBDIR}/config/i386/tm-fbsd.h
	cp ${.ALLSRC} ${.TARGET}

xm.h: ${CONTRIBDIR}/config/i386/xm-i386.h
	cp ${.ALLSRC} ${.TARGET}

CLEANFILES+=	kvm-fbsd.h
