# $DragonFly: src/gnu/usr.bin/gdb/libgdb/Makefile.i386,v 1.4 2008/01/14 21:36:38 corecode Exp $

# TDEPFILES (part 2, cleaned)
SRCS+=	i386-tdep.c i387-tdep.c i386bsd-tdep.c i386fbsd-tdep.c

# NATDEPFILES (part 2)
SRCS+=	fbsd-nat.c i386-nat.c i386bsd-nat.c i386fbsd-nat.c

nm.h:
	echo '#include "i386/nm-fbsd.h"' > ${.TARGET}

tm.h:
	echo '#include "i386/tm-fbsd.h"' > ${.TARGET}

xm.h:
	echo '#include "i386/xm-i386.h"' > ${.TARGET}
