# $FreeBSD: src/sys/modules/mly/Makefile,v 1.1.2.1 2000/10/27 10:07:02 msmith Exp $

KMOD		=  pst
SRCS		=  pst-pci.c pst-iop.c pst-raid.c
SRCS		+= device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
