#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/biff/Makefile,v 1.2.6.1 2001/08/02 01:06:37 obrien Exp $
# $DragonFly: src/usr.bin/biff/Makefile,v 1.2 2003/06/17 04:29:25 dillon Exp $

PROG=	biff
WARNS?=	2

.include <bsd.prog.mk>
