######################################################################
# Automatically generated by qmake (1.07a) Sat Jul 17 22:27:19 2004
######################################################################

#CONFIG += debug
TEMPLATE = app
DEPENDPATH += include src
INCLUDEPATH += . include
LIBS += -ldfui -laura

# Input
HEADERS += include/mainwindow.h \
           include/form.h

SOURCES += src/main.cpp src/form.cpp src/mainwindow.cpp

IMAGES  += images/icon.png
