#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/bcd/Makefile,v 1.2.6.2 2001/04/25 09:28:45 ru Exp $
# $DragonFly: src/games/bcd/Makefile,v 1.3 2005/08/03 13:26:19 eirikn Exp $

PROG=	bcd
MAN=	bcd.6
MLINKS=	bcd.6 ppt.6
WARNS?=	6

.include <bsd.prog.mk>

