#	from: @(#)Makefile	5.2 (Berkeley) 5/11/90
# $FreeBSD: src/usr.bin/rpcinfo/Makefile,v 1.8 2006/07/27 13:47:02 yar Exp $
# $DragonFly: src/usr.bin/rpcinfo/Makefile,v 1.3 2007/08/27 16:50:58 pavalos Exp $

PROG=	rpcinfo
MAN=	rpcinfo.8

CFLAGS+= -DPORTMAP
WARNS?=	2

.include <bsd.prog.mk>
