#	from: @(#)Makefile	5.2 (Berkeley) 5/11/90
# $FreeBSD: src/usr.bin/rpcinfo/Makefile,v 1.4.2.1 2001/04/25 11:29:36 ru Exp $
# $DragonFly: src/usr.bin/rpcinfo/Makefile,v 1.3 2007/08/27 16:50:58 pavalos Exp $

PROG=	rpcinfo
MAN=	rpcinfo.8
WARNS?=	0

.include <bsd.prog.mk>
