# $FreeBSD: src/gnu/usr.bin/perl/Makefile,v 1.9.2.2 2002/02/19 16:21:34 ru Exp $
# $DragonFly: src/gnu/usr.bin/perl/Attic/Makefile,v 1.3 2004/01/31 06:56:38 dillon Exp $

SUBDIR= libperl miniperl perl suidperl library pod utils x2p

.include <bsd.subdir.mk>
