# $FreeBSD: src/gnu/usr.bin/perl/Makefile,v 1.9.2.2 2002/02/19 16:21:34 ru Exp $
# $DragonFly: src/gnu/usr.bin/perl/Attic/Makefile,v 1.2 2003/06/17 04:25:47 dillon Exp $

SUBDIR= libperl miniperl perl suidperl library pod utils x2p

MAINTAINER=markm@freebsd.org

.include <bsd.subdir.mk>
