# $FreeBSD: src/usr.sbin/memcontrol/Makefile,v 1.2.2.1 2001/04/25 12:10:04 ru Exp $
# $DragonFly: src/usr.sbin/memcontrol/Makefile,v 1.3 2005/03/18 01:57:58 cpressey Exp $

PROG=		memcontrol
MAN=		memcontrol.8

.include <bsd.prog.mk>
