# $FreeBSD: src/usr.sbin/memcontrol/Makefile,v 1.2.2.1 2001/04/25 12:10:04 ru Exp $
# $DragonFly: src/usr.sbin/memcontrol/Makefile,v 1.2 2003/06/17 04:29:57 dillon Exp $

PROG=		memcontrol
MAN=		memcontrol.8

.include <bsd.prog.mk>
