# $FreeBSD: src/usr.sbin/btxld/Makefile,v 1.3.2.1 2001/04/25 12:09:21 ru Exp $
# $DragonFly: src/usr.sbin/btxld/Makefile,v 1.2 2003/06/17 04:29:52 dillon Exp $

PROG=	btxld
SRCS=	btxld.c elfh.c
MAN=	btxld.8

CFLAGS+=	-Wall

.include <bsd.prog.mk>
