/*
 * System call prototypes.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $DragonFly: src/sys/sys/sysproto.h,v 1.6 2003/07/30 00:19:16 dillon Exp $
 * created from DragonFly: src/sys/kern/syscalls.master,v 1.2 2003/06/17 04:28:41 dillon Exp 
 */

#ifndef _SYS_SYSPROTO_H_
#define	_SYS_SYSPROTO_H_

#include <sys/signal.h>

#include <sys/acl.h>

#include <sys/msgport.h>

#include <sys/sysmsg.h>

#define	PAD_(t)	(sizeof(register_t) <= sizeof(t) ? \
		0 : sizeof(register_t) - sizeof(t))

struct	nosys_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	sys_exit_args {
	union sysmsg sysmsg;
	int	rval;	char rval_[PAD_(int)];
};
struct	fork_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	read_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	void *	buf;	char buf_[PAD_(void *)];
	size_t	nbyte;	char nbyte_[PAD_(size_t)];
};
struct	write_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	const void *	buf;	char buf_[PAD_(const void *)];
	size_t	nbyte;	char nbyte_[PAD_(size_t)];
};
struct	open_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	flags;	char flags_[PAD_(int)];
	int	mode;	char mode_[PAD_(int)];
};
struct	close_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
};
struct	wait_args {
	union sysmsg sysmsg;
	int	pid;	char pid_[PAD_(int)];
	int *	status;	char status_[PAD_(int *)];
	int	options;	char options_[PAD_(int)];
	struct rusage *	rusage;	char rusage_[PAD_(struct rusage *)];
};
struct	link_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	char *	link;	char link_[PAD_(char *)];
};
struct	unlink_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
};
struct	chdir_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
};
struct	fchdir_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
};
struct	mknod_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	mode;	char mode_[PAD_(int)];
	int	dev;	char dev_[PAD_(int)];
};
struct	chmod_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	mode;	char mode_[PAD_(int)];
};
struct	chown_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	uid;	char uid_[PAD_(int)];
	int	gid;	char gid_[PAD_(int)];
};
struct	obreak_args {
	union sysmsg sysmsg;
	char *	nsize;	char nsize_[PAD_(char *)];
};
struct	getfsstat_args {
	union sysmsg sysmsg;
	struct statfs *	buf;	char buf_[PAD_(struct statfs *)];
	long	bufsize;	char bufsize_[PAD_(long)];
	int	flags;	char flags_[PAD_(int)];
};
struct	getpid_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	mount_args {
	union sysmsg sysmsg;
	char *	type;	char type_[PAD_(char *)];
	char *	path;	char path_[PAD_(char *)];
	int	flags;	char flags_[PAD_(int)];
	caddr_t	data;	char data_[PAD_(caddr_t)];
};
struct	unmount_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	flags;	char flags_[PAD_(int)];
};
struct	setuid_args {
	union sysmsg sysmsg;
	uid_t	uid;	char uid_[PAD_(uid_t)];
};
struct	getuid_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	geteuid_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	ptrace_args {
	union sysmsg sysmsg;
	int	req;	char req_[PAD_(int)];
	pid_t	pid;	char pid_[PAD_(pid_t)];
	caddr_t	addr;	char addr_[PAD_(caddr_t)];
	int	data;	char data_[PAD_(int)];
};
struct	recvmsg_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	struct msghdr *	msg;	char msg_[PAD_(struct msghdr *)];
	int	flags;	char flags_[PAD_(int)];
};
struct	sendmsg_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	caddr_t	msg;	char msg_[PAD_(caddr_t)];
	int	flags;	char flags_[PAD_(int)];
};
struct	recvfrom_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	caddr_t	buf;	char buf_[PAD_(caddr_t)];
	size_t	len;	char len_[PAD_(size_t)];
	int	flags;	char flags_[PAD_(int)];
	caddr_t	from;	char from_[PAD_(caddr_t)];
	int *	fromlenaddr;	char fromlenaddr_[PAD_(int *)];
};
struct	accept_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	caddr_t	name;	char name_[PAD_(caddr_t)];
	int *	anamelen;	char anamelen_[PAD_(int *)];
};
struct	getpeername_args {
	union sysmsg sysmsg;
	int	fdes;	char fdes_[PAD_(int)];
	caddr_t	asa;	char asa_[PAD_(caddr_t)];
	int *	alen;	char alen_[PAD_(int *)];
};
struct	getsockname_args {
	union sysmsg sysmsg;
	int	fdes;	char fdes_[PAD_(int)];
	caddr_t	asa;	char asa_[PAD_(caddr_t)];
	int *	alen;	char alen_[PAD_(int *)];
};
struct	access_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	flags;	char flags_[PAD_(int)];
};
struct	chflags_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	flags;	char flags_[PAD_(int)];
};
struct	fchflags_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	int	flags;	char flags_[PAD_(int)];
};
struct	sync_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	kill_args {
	union sysmsg sysmsg;
	int	pid;	char pid_[PAD_(int)];
	int	signum;	char signum_[PAD_(int)];
};
struct	getppid_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	dup_args {
	union sysmsg sysmsg;
	u_int	fd;	char fd_[PAD_(u_int)];
};
struct	pipe_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	getegid_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	profil_args {
	union sysmsg sysmsg;
	caddr_t	samples;	char samples_[PAD_(caddr_t)];
	size_t	size;	char size_[PAD_(size_t)];
	size_t	offset;	char offset_[PAD_(size_t)];
	u_int	scale;	char scale_[PAD_(u_int)];
};
struct	ktrace_args {
	union sysmsg sysmsg;
	const char *	fname;	char fname_[PAD_(const char *)];
	int	ops;	char ops_[PAD_(int)];
	int	facs;	char facs_[PAD_(int)];
	int	pid;	char pid_[PAD_(int)];
};
struct	getgid_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	getlogin_args {
	union sysmsg sysmsg;
	char *	namebuf;	char namebuf_[PAD_(char *)];
	u_int	namelen;	char namelen_[PAD_(u_int)];
};
struct	setlogin_args {
	union sysmsg sysmsg;
	char *	namebuf;	char namebuf_[PAD_(char *)];
};
struct	acct_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
};
struct	osigpending_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	sigaltstack_args {
	union sysmsg sysmsg;
	stack_t *	ss;	char ss_[PAD_(stack_t *)];
	stack_t *	oss;	char oss_[PAD_(stack_t *)];
};
struct	ioctl_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	u_long	com;	char com_[PAD_(u_long)];
	caddr_t	data;	char data_[PAD_(caddr_t)];
};
struct	reboot_args {
	union sysmsg sysmsg;
	int	opt;	char opt_[PAD_(int)];
};
struct	revoke_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
};
struct	symlink_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	char *	link;	char link_[PAD_(char *)];
};
struct	readlink_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	char *	buf;	char buf_[PAD_(char *)];
	int	count;	char count_[PAD_(int)];
};
struct	execve_args {
	union sysmsg sysmsg;
	char *	fname;	char fname_[PAD_(char *)];
	char **	argv;	char argv_[PAD_(char **)];
	char **	envv;	char envv_[PAD_(char **)];
};
struct	umask_args {
	union sysmsg sysmsg;
	int	newmask;	char newmask_[PAD_(int)];
};
struct	chroot_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
};
struct	getpagesize_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	msync_args {
	union sysmsg sysmsg;
	void *	addr;	char addr_[PAD_(void *)];
	size_t	len;	char len_[PAD_(size_t)];
	int	flags;	char flags_[PAD_(int)];
};
struct	vfork_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	sbrk_args {
	union sysmsg sysmsg;
	int	incr;	char incr_[PAD_(int)];
};
struct	sstk_args {
	union sysmsg sysmsg;
	int	incr;	char incr_[PAD_(int)];
};
struct	ovadvise_args {
	union sysmsg sysmsg;
	int	anom;	char anom_[PAD_(int)];
};
struct	munmap_args {
	union sysmsg sysmsg;
	void *	addr;	char addr_[PAD_(void *)];
	size_t	len;	char len_[PAD_(size_t)];
};
struct	mprotect_args {
	union sysmsg sysmsg;
	const void *	addr;	char addr_[PAD_(const void *)];
	size_t	len;	char len_[PAD_(size_t)];
	int	prot;	char prot_[PAD_(int)];
};
struct	madvise_args {
	union sysmsg sysmsg;
	void *	addr;	char addr_[PAD_(void *)];
	size_t	len;	char len_[PAD_(size_t)];
	int	behav;	char behav_[PAD_(int)];
};
struct	mincore_args {
	union sysmsg sysmsg;
	const void *	addr;	char addr_[PAD_(const void *)];
	size_t	len;	char len_[PAD_(size_t)];
	char *	vec;	char vec_[PAD_(char *)];
};
struct	getgroups_args {
	union sysmsg sysmsg;
	u_int	gidsetsize;	char gidsetsize_[PAD_(u_int)];
	gid_t *	gidset;	char gidset_[PAD_(gid_t *)];
};
struct	setgroups_args {
	union sysmsg sysmsg;
	u_int	gidsetsize;	char gidsetsize_[PAD_(u_int)];
	gid_t *	gidset;	char gidset_[PAD_(gid_t *)];
};
struct	getpgrp_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	setpgid_args {
	union sysmsg sysmsg;
	int	pid;	char pid_[PAD_(int)];
	int	pgid;	char pgid_[PAD_(int)];
};
struct	setitimer_args {
	union sysmsg sysmsg;
	u_int	which;	char which_[PAD_(u_int)];
	struct itimerval *	itv;	char itv_[PAD_(struct itimerval *)];
	struct itimerval *	oitv;	char oitv_[PAD_(struct itimerval *)];
};
struct	owait_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	swapon_args {
	union sysmsg sysmsg;
	char *	name;	char name_[PAD_(char *)];
};
struct	getitimer_args {
	union sysmsg sysmsg;
	u_int	which;	char which_[PAD_(u_int)];
	struct itimerval *	itv;	char itv_[PAD_(struct itimerval *)];
};
struct	getdtablesize_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	dup2_args {
	union sysmsg sysmsg;
	u_int	from;	char from_[PAD_(u_int)];
	u_int	to;	char to_[PAD_(u_int)];
};
struct	fcntl_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	int	cmd;	char cmd_[PAD_(int)];
	long	arg;	char arg_[PAD_(long)];
};
struct	select_args {
	union sysmsg sysmsg;
	int	nd;	char nd_[PAD_(int)];
	fd_set *	in;	char in_[PAD_(fd_set *)];
	fd_set *	ou;	char ou_[PAD_(fd_set *)];
	fd_set *	ex;	char ex_[PAD_(fd_set *)];
	struct timeval *	tv;	char tv_[PAD_(struct timeval *)];
};
struct	fsync_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
};
struct	setpriority_args {
	union sysmsg sysmsg;
	int	which;	char which_[PAD_(int)];
	int	who;	char who_[PAD_(int)];
	int	prio;	char prio_[PAD_(int)];
};
struct	socket_args {
	union sysmsg sysmsg;
	int	domain;	char domain_[PAD_(int)];
	int	type;	char type_[PAD_(int)];
	int	protocol;	char protocol_[PAD_(int)];
};
struct	connect_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	caddr_t	name;	char name_[PAD_(caddr_t)];
	int	namelen;	char namelen_[PAD_(int)];
};
struct	getpriority_args {
	union sysmsg sysmsg;
	int	which;	char which_[PAD_(int)];
	int	who;	char who_[PAD_(int)];
};
struct	bind_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	caddr_t	name;	char name_[PAD_(caddr_t)];
	int	namelen;	char namelen_[PAD_(int)];
};
struct	setsockopt_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	int	level;	char level_[PAD_(int)];
	int	name;	char name_[PAD_(int)];
	caddr_t	val;	char val_[PAD_(caddr_t)];
	int	valsize;	char valsize_[PAD_(int)];
};
struct	listen_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	int	backlog;	char backlog_[PAD_(int)];
};
struct	gettimeofday_args {
	union sysmsg sysmsg;
	struct timeval *	tp;	char tp_[PAD_(struct timeval *)];
	struct timezone *	tzp;	char tzp_[PAD_(struct timezone *)];
};
struct	getrusage_args {
	union sysmsg sysmsg;
	int	who;	char who_[PAD_(int)];
	struct rusage *	rusage;	char rusage_[PAD_(struct rusage *)];
};
struct	getsockopt_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	int	level;	char level_[PAD_(int)];
	int	name;	char name_[PAD_(int)];
	caddr_t	val;	char val_[PAD_(caddr_t)];
	int *	avalsize;	char avalsize_[PAD_(int *)];
};
struct	readv_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	struct iovec *	iovp;	char iovp_[PAD_(struct iovec *)];
	u_int	iovcnt;	char iovcnt_[PAD_(u_int)];
};
struct	writev_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	struct iovec *	iovp;	char iovp_[PAD_(struct iovec *)];
	u_int	iovcnt;	char iovcnt_[PAD_(u_int)];
};
struct	settimeofday_args {
	union sysmsg sysmsg;
	struct timeval *	tv;	char tv_[PAD_(struct timeval *)];
	struct timezone *	tzp;	char tzp_[PAD_(struct timezone *)];
};
struct	fchown_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	int	uid;	char uid_[PAD_(int)];
	int	gid;	char gid_[PAD_(int)];
};
struct	fchmod_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	int	mode;	char mode_[PAD_(int)];
};
struct	setreuid_args {
	union sysmsg sysmsg;
	int	ruid;	char ruid_[PAD_(int)];
	int	euid;	char euid_[PAD_(int)];
};
struct	setregid_args {
	union sysmsg sysmsg;
	int	rgid;	char rgid_[PAD_(int)];
	int	egid;	char egid_[PAD_(int)];
};
struct	rename_args {
	union sysmsg sysmsg;
	char *	from;	char from_[PAD_(char *)];
	char *	to;	char to_[PAD_(char *)];
};
struct	flock_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	int	how;	char how_[PAD_(int)];
};
struct	mkfifo_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	mode;	char mode_[PAD_(int)];
};
struct	sendto_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	caddr_t	buf;	char buf_[PAD_(caddr_t)];
	size_t	len;	char len_[PAD_(size_t)];
	int	flags;	char flags_[PAD_(int)];
	caddr_t	to;	char to_[PAD_(caddr_t)];
	int	tolen;	char tolen_[PAD_(int)];
};
struct	shutdown_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	int	how;	char how_[PAD_(int)];
};
struct	socketpair_args {
	union sysmsg sysmsg;
	int	domain;	char domain_[PAD_(int)];
	int	type;	char type_[PAD_(int)];
	int	protocol;	char protocol_[PAD_(int)];
	int *	rsv;	char rsv_[PAD_(int *)];
};
struct	mkdir_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	mode;	char mode_[PAD_(int)];
};
struct	rmdir_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
};
struct	utimes_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	struct timeval *	tptr;	char tptr_[PAD_(struct timeval *)];
};
struct	adjtime_args {
	union sysmsg sysmsg;
	struct timeval *	delta;	char delta_[PAD_(struct timeval *)];
	struct timeval *	olddelta;	char olddelta_[PAD_(struct timeval *)];
};
struct	ogethostid_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	setsid_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	quotactl_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	cmd;	char cmd_[PAD_(int)];
	int	uid;	char uid_[PAD_(int)];
	caddr_t	arg;	char arg_[PAD_(caddr_t)];
};
struct	oquota_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	nfssvc_args {
	union sysmsg sysmsg;
	int	flag;	char flag_[PAD_(int)];
	caddr_t	argp;	char argp_[PAD_(caddr_t)];
};
struct	statfs_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	struct statfs *	buf;	char buf_[PAD_(struct statfs *)];
};
struct	fstatfs_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	struct statfs *	buf;	char buf_[PAD_(struct statfs *)];
};
struct	getfh_args {
	union sysmsg sysmsg;
	char *	fname;	char fname_[PAD_(char *)];
	struct fhandle *	fhp;	char fhp_[PAD_(struct fhandle *)];
};
struct	getdomainname_args {
	union sysmsg sysmsg;
	char *	domainname;	char domainname_[PAD_(char *)];
	int	len;	char len_[PAD_(int)];
};
struct	setdomainname_args {
	union sysmsg sysmsg;
	char *	domainname;	char domainname_[PAD_(char *)];
	int	len;	char len_[PAD_(int)];
};
struct	uname_args {
	union sysmsg sysmsg;
	struct utsname *	name;	char name_[PAD_(struct utsname *)];
};
struct	sysarch_args {
	union sysmsg sysmsg;
	int	op;	char op_[PAD_(int)];
	char *	parms;	char parms_[PAD_(char *)];
};
struct	rtprio_args {
	union sysmsg sysmsg;
	int	function;	char function_[PAD_(int)];
	pid_t	pid;	char pid_[PAD_(pid_t)];
	struct rtprio *	rtp;	char rtp_[PAD_(struct rtprio *)];
};
struct	semsys_args {
	union sysmsg sysmsg;
	int	which;	char which_[PAD_(int)];
	int	a2;	char a2_[PAD_(int)];
	int	a3;	char a3_[PAD_(int)];
	int	a4;	char a4_[PAD_(int)];
	int	a5;	char a5_[PAD_(int)];
};
struct	msgsys_args {
	union sysmsg sysmsg;
	int	which;	char which_[PAD_(int)];
	int	a2;	char a2_[PAD_(int)];
	int	a3;	char a3_[PAD_(int)];
	int	a4;	char a4_[PAD_(int)];
	int	a5;	char a5_[PAD_(int)];
	int	a6;	char a6_[PAD_(int)];
};
struct	shmsys_args {
	union sysmsg sysmsg;
	int	which;	char which_[PAD_(int)];
	int	a2;	char a2_[PAD_(int)];
	int	a3;	char a3_[PAD_(int)];
	int	a4;	char a4_[PAD_(int)];
};
struct	pread_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	void *	buf;	char buf_[PAD_(void *)];
	size_t	nbyte;	char nbyte_[PAD_(size_t)];
	int	pad;	char pad_[PAD_(int)];
	off_t	offset;	char offset_[PAD_(off_t)];
};
struct	pwrite_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	const void *	buf;	char buf_[PAD_(const void *)];
	size_t	nbyte;	char nbyte_[PAD_(size_t)];
	int	pad;	char pad_[PAD_(int)];
	off_t	offset;	char offset_[PAD_(off_t)];
};
struct	ntp_adjtime_args {
	union sysmsg sysmsg;
	struct timex *	tp;	char tp_[PAD_(struct timex *)];
};
struct	setgid_args {
	union sysmsg sysmsg;
	gid_t	gid;	char gid_[PAD_(gid_t)];
};
struct	setegid_args {
	union sysmsg sysmsg;
	gid_t	egid;	char egid_[PAD_(gid_t)];
};
struct	seteuid_args {
	union sysmsg sysmsg;
	uid_t	euid;	char euid_[PAD_(uid_t)];
};
struct	stat_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	struct stat *	ub;	char ub_[PAD_(struct stat *)];
};
struct	fstat_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	struct stat *	sb;	char sb_[PAD_(struct stat *)];
};
struct	lstat_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	struct stat *	ub;	char ub_[PAD_(struct stat *)];
};
struct	pathconf_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	name;	char name_[PAD_(int)];
};
struct	fpathconf_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	int	name;	char name_[PAD_(int)];
};
struct	__getrlimit_args {
	union sysmsg sysmsg;
	u_int	which;	char which_[PAD_(u_int)];
	struct rlimit *	rlp;	char rlp_[PAD_(struct rlimit *)];
};
struct	__setrlimit_args {
	union sysmsg sysmsg;
	u_int	which;	char which_[PAD_(u_int)];
	struct rlimit *	rlp;	char rlp_[PAD_(struct rlimit *)];
};
struct	getdirentries_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	char *	buf;	char buf_[PAD_(char *)];
	u_int	count;	char count_[PAD_(u_int)];
	long *	basep;	char basep_[PAD_(long *)];
};
struct	mmap_args {
	union sysmsg sysmsg;
	caddr_t	addr;	char addr_[PAD_(caddr_t)];
	size_t	len;	char len_[PAD_(size_t)];
	int	prot;	char prot_[PAD_(int)];
	int	flags;	char flags_[PAD_(int)];
	int	fd;	char fd_[PAD_(int)];
	int	pad;	char pad_[PAD_(int)];
	off_t	pos;	char pos_[PAD_(off_t)];
};
struct	lseek_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	int	pad;	char pad_[PAD_(int)];
	off_t	offset;	char offset_[PAD_(off_t)];
	int	whence;	char whence_[PAD_(int)];
};
struct	truncate_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	pad;	char pad_[PAD_(int)];
	off_t	length;	char length_[PAD_(off_t)];
};
struct	ftruncate_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	int	pad;	char pad_[PAD_(int)];
	off_t	length;	char length_[PAD_(off_t)];
};
struct	sysctl_args {
	union sysmsg sysmsg;
	int *	name;	char name_[PAD_(int *)];
	u_int	namelen;	char namelen_[PAD_(u_int)];
	void *	old;	char old_[PAD_(void *)];
	size_t *	oldlenp;	char oldlenp_[PAD_(size_t *)];
	void *	new;	char new_[PAD_(void *)];
	size_t	newlen;	char newlen_[PAD_(size_t)];
};
struct	mlock_args {
	union sysmsg sysmsg;
	const void *	addr;	char addr_[PAD_(const void *)];
	size_t	len;	char len_[PAD_(size_t)];
};
struct	munlock_args {
	union sysmsg sysmsg;
	const void *	addr;	char addr_[PAD_(const void *)];
	size_t	len;	char len_[PAD_(size_t)];
};
struct	undelete_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
};
struct	futimes_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	struct timeval *	tptr;	char tptr_[PAD_(struct timeval *)];
};
struct	getpgid_args {
	union sysmsg sysmsg;
	pid_t	pid;	char pid_[PAD_(pid_t)];
};
struct	poll_args {
	union sysmsg sysmsg;
	struct pollfd *	fds;	char fds_[PAD_(struct pollfd *)];
	u_int	nfds;	char nfds_[PAD_(u_int)];
	int	timeout;	char timeout_[PAD_(int)];
};
struct	__semctl_args {
	union sysmsg sysmsg;
	int	semid;	char semid_[PAD_(int)];
	int	semnum;	char semnum_[PAD_(int)];
	int	cmd;	char cmd_[PAD_(int)];
	union semun *	arg;	char arg_[PAD_(union semun *)];
};
struct	semget_args {
	union sysmsg sysmsg;
	key_t	key;	char key_[PAD_(key_t)];
	int	nsems;	char nsems_[PAD_(int)];
	int	semflg;	char semflg_[PAD_(int)];
};
struct	semop_args {
	union sysmsg sysmsg;
	int	semid;	char semid_[PAD_(int)];
	struct sembuf *	sops;	char sops_[PAD_(struct sembuf *)];
	u_int	nsops;	char nsops_[PAD_(u_int)];
};
struct	msgctl_args {
	union sysmsg sysmsg;
	int	msqid;	char msqid_[PAD_(int)];
	int	cmd;	char cmd_[PAD_(int)];
	struct msqid_ds *	buf;	char buf_[PAD_(struct msqid_ds *)];
};
struct	msgget_args {
	union sysmsg sysmsg;
	key_t	key;	char key_[PAD_(key_t)];
	int	msgflg;	char msgflg_[PAD_(int)];
};
struct	msgsnd_args {
	union sysmsg sysmsg;
	int	msqid;	char msqid_[PAD_(int)];
	void *	msgp;	char msgp_[PAD_(void *)];
	size_t	msgsz;	char msgsz_[PAD_(size_t)];
	int	msgflg;	char msgflg_[PAD_(int)];
};
struct	msgrcv_args {
	union sysmsg sysmsg;
	int	msqid;	char msqid_[PAD_(int)];
	void *	msgp;	char msgp_[PAD_(void *)];
	size_t	msgsz;	char msgsz_[PAD_(size_t)];
	long	msgtyp;	char msgtyp_[PAD_(long)];
	int	msgflg;	char msgflg_[PAD_(int)];
};
struct	shmat_args {
	union sysmsg sysmsg;
	int	shmid;	char shmid_[PAD_(int)];
	void *	shmaddr;	char shmaddr_[PAD_(void *)];
	int	shmflg;	char shmflg_[PAD_(int)];
};
struct	shmctl_args {
	union sysmsg sysmsg;
	int	shmid;	char shmid_[PAD_(int)];
	int	cmd;	char cmd_[PAD_(int)];
	struct shmid_ds *	buf;	char buf_[PAD_(struct shmid_ds *)];
};
struct	shmdt_args {
	union sysmsg sysmsg;
	void *	shmaddr;	char shmaddr_[PAD_(void *)];
};
struct	shmget_args {
	union sysmsg sysmsg;
	key_t	key;	char key_[PAD_(key_t)];
	int	size;	char size_[PAD_(int)];
	int	shmflg;	char shmflg_[PAD_(int)];
};
struct	clock_gettime_args {
	union sysmsg sysmsg;
	clockid_t	clock_id;	char clock_id_[PAD_(clockid_t)];
	struct timespec *	tp;	char tp_[PAD_(struct timespec *)];
};
struct	clock_settime_args {
	union sysmsg sysmsg;
	clockid_t	clock_id;	char clock_id_[PAD_(clockid_t)];
	const struct timespec *	tp;	char tp_[PAD_(const struct timespec *)];
};
struct	clock_getres_args {
	union sysmsg sysmsg;
	clockid_t	clock_id;	char clock_id_[PAD_(clockid_t)];
	struct timespec *	tp;	char tp_[PAD_(struct timespec *)];
};
struct	nanosleep_args {
	union sysmsg sysmsg;
	const struct timespec *	rqtp;	char rqtp_[PAD_(const struct timespec *)];
	struct timespec *	rmtp;	char rmtp_[PAD_(struct timespec *)];
};
struct	minherit_args {
	union sysmsg sysmsg;
	void *	addr;	char addr_[PAD_(void *)];
	size_t	len;	char len_[PAD_(size_t)];
	int	inherit;	char inherit_[PAD_(int)];
};
struct	rfork_args {
	union sysmsg sysmsg;
	int	flags;	char flags_[PAD_(int)];
};
struct	openbsd_poll_args {
	union sysmsg sysmsg;
	struct pollfd *	fds;	char fds_[PAD_(struct pollfd *)];
	u_int	nfds;	char nfds_[PAD_(u_int)];
	int	timeout;	char timeout_[PAD_(int)];
};
struct	issetugid_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	lchown_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	uid;	char uid_[PAD_(int)];
	int	gid;	char gid_[PAD_(int)];
};
struct	getdents_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	char *	buf;	char buf_[PAD_(char *)];
	size_t	count;	char count_[PAD_(size_t)];
};
struct	lchmod_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	mode_t	mode;	char mode_[PAD_(mode_t)];
};
struct	lutimes_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	struct timeval *	tptr;	char tptr_[PAD_(struct timeval *)];
};
struct	nstat_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	struct nstat *	ub;	char ub_[PAD_(struct nstat *)];
};
struct	nfstat_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	struct nstat *	sb;	char sb_[PAD_(struct nstat *)];
};
struct	nlstat_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	struct nstat *	ub;	char ub_[PAD_(struct nstat *)];
};
struct	fhstatfs_args {
	union sysmsg sysmsg;
	const struct fhandle *	u_fhp;	char u_fhp_[PAD_(const struct fhandle *)];
	struct statfs *	buf;	char buf_[PAD_(struct statfs *)];
};
struct	fhopen_args {
	union sysmsg sysmsg;
	const struct fhandle *	u_fhp;	char u_fhp_[PAD_(const struct fhandle *)];
	int	flags;	char flags_[PAD_(int)];
};
struct	fhstat_args {
	union sysmsg sysmsg;
	const struct fhandle *	u_fhp;	char u_fhp_[PAD_(const struct fhandle *)];
	struct stat *	sb;	char sb_[PAD_(struct stat *)];
};
struct	modnext_args {
	union sysmsg sysmsg;
	int	modid;	char modid_[PAD_(int)];
};
struct	modstat_args {
	union sysmsg sysmsg;
	int	modid;	char modid_[PAD_(int)];
	struct module_stat *	stat;	char stat_[PAD_(struct module_stat *)];
};
struct	modfnext_args {
	union sysmsg sysmsg;
	int	modid;	char modid_[PAD_(int)];
};
struct	modfind_args {
	union sysmsg sysmsg;
	const char *	name;	char name_[PAD_(const char *)];
};
struct	kldload_args {
	union sysmsg sysmsg;
	const char *	file;	char file_[PAD_(const char *)];
};
struct	kldunload_args {
	union sysmsg sysmsg;
	int	fileid;	char fileid_[PAD_(int)];
};
struct	kldfind_args {
	union sysmsg sysmsg;
	const char *	file;	char file_[PAD_(const char *)];
};
struct	kldnext_args {
	union sysmsg sysmsg;
	int	fileid;	char fileid_[PAD_(int)];
};
struct	kldstat_args {
	union sysmsg sysmsg;
	int	fileid;	char fileid_[PAD_(int)];
	struct kld_file_stat *	stat;	char stat_[PAD_(struct kld_file_stat *)];
};
struct	kldfirstmod_args {
	union sysmsg sysmsg;
	int	fileid;	char fileid_[PAD_(int)];
};
struct	getsid_args {
	union sysmsg sysmsg;
	pid_t	pid;	char pid_[PAD_(pid_t)];
};
struct	setresuid_args {
	union sysmsg sysmsg;
	uid_t	ruid;	char ruid_[PAD_(uid_t)];
	uid_t	euid;	char euid_[PAD_(uid_t)];
	uid_t	suid;	char suid_[PAD_(uid_t)];
};
struct	setresgid_args {
	union sysmsg sysmsg;
	gid_t	rgid;	char rgid_[PAD_(gid_t)];
	gid_t	egid;	char egid_[PAD_(gid_t)];
	gid_t	sgid;	char sgid_[PAD_(gid_t)];
};
struct	aio_return_args {
	union sysmsg sysmsg;
	struct aiocb *	aiocbp;	char aiocbp_[PAD_(struct aiocb *)];
};
struct	aio_suspend_args {
	union sysmsg sysmsg;
	struct aiocb *const *	aiocbp;	char aiocbp_[PAD_(struct aiocb *const *)];
	int	nent;	char nent_[PAD_(int)];
	const struct timespec *	timeout;	char timeout_[PAD_(const struct timespec *)];
};
struct	aio_cancel_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	struct aiocb *	aiocbp;	char aiocbp_[PAD_(struct aiocb *)];
};
struct	aio_error_args {
	union sysmsg sysmsg;
	struct aiocb *	aiocbp;	char aiocbp_[PAD_(struct aiocb *)];
};
struct	aio_read_args {
	union sysmsg sysmsg;
	struct aiocb *	aiocbp;	char aiocbp_[PAD_(struct aiocb *)];
};
struct	aio_write_args {
	union sysmsg sysmsg;
	struct aiocb *	aiocbp;	char aiocbp_[PAD_(struct aiocb *)];
};
struct	lio_listio_args {
	union sysmsg sysmsg;
	int	mode;	char mode_[PAD_(int)];
	struct aiocb *const *	acb_list;	char acb_list_[PAD_(struct aiocb *const *)];
	int	nent;	char nent_[PAD_(int)];
	struct sigevent *	sig;	char sig_[PAD_(struct sigevent *)];
};
struct	yield_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	thr_sleep_args {
	union sysmsg sysmsg;
	const struct timespec *	timeout;	char timeout_[PAD_(const struct timespec *)];
};
struct	thr_wakeup_args {
	union sysmsg sysmsg;
	pid_t	pid;	char pid_[PAD_(pid_t)];
};
struct	mlockall_args {
	union sysmsg sysmsg;
	int	how;	char how_[PAD_(int)];
};
struct	munlockall_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	__getcwd_args {
	union sysmsg sysmsg;
	u_char *	buf;	char buf_[PAD_(u_char *)];
	u_int	buflen;	char buflen_[PAD_(u_int)];
};
struct	sched_setparam_args {
	union sysmsg sysmsg;
	pid_t	pid;	char pid_[PAD_(pid_t)];
	const struct sched_param *	param;	char param_[PAD_(const struct sched_param *)];
};
struct	sched_getparam_args {
	union sysmsg sysmsg;
	pid_t	pid;	char pid_[PAD_(pid_t)];
	struct sched_param *	param;	char param_[PAD_(struct sched_param *)];
};
struct	sched_setscheduler_args {
	union sysmsg sysmsg;
	pid_t	pid;	char pid_[PAD_(pid_t)];
	int	policy;	char policy_[PAD_(int)];
	const struct sched_param *	param;	char param_[PAD_(const struct sched_param *)];
};
struct	sched_getscheduler_args {
	union sysmsg sysmsg;
	pid_t	pid;	char pid_[PAD_(pid_t)];
};
struct	sched_yield_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	sched_get_priority_max_args {
	union sysmsg sysmsg;
	int	policy;	char policy_[PAD_(int)];
};
struct	sched_get_priority_min_args {
	union sysmsg sysmsg;
	int	policy;	char policy_[PAD_(int)];
};
struct	sched_rr_get_interval_args {
	union sysmsg sysmsg;
	pid_t	pid;	char pid_[PAD_(pid_t)];
	struct timespec *	interval;	char interval_[PAD_(struct timespec *)];
};
struct	utrace_args {
	union sysmsg sysmsg;
	const void *	addr;	char addr_[PAD_(const void *)];
	size_t	len;	char len_[PAD_(size_t)];
};
struct	kldsym_args {
	union sysmsg sysmsg;
	int	fileid;	char fileid_[PAD_(int)];
	int	cmd;	char cmd_[PAD_(int)];
	void *	data;	char data_[PAD_(void *)];
};
struct	jail_args {
	union sysmsg sysmsg;
	struct jail *	jail;	char jail_[PAD_(struct jail *)];
};
struct	sigprocmask_args {
	union sysmsg sysmsg;
	int	how;	char how_[PAD_(int)];
	const sigset_t *	set;	char set_[PAD_(const sigset_t *)];
	sigset_t *	oset;	char oset_[PAD_(sigset_t *)];
};
struct	sigsuspend_args {
	union sysmsg sysmsg;
	const sigset_t *	sigmask;	char sigmask_[PAD_(const sigset_t *)];
};
struct	sigaction_args {
	union sysmsg sysmsg;
	int	sig;	char sig_[PAD_(int)];
	const struct sigaction *	act;	char act_[PAD_(const struct sigaction *)];
	struct sigaction *	oact;	char oact_[PAD_(struct sigaction *)];
};
struct	sigpending_args {
	union sysmsg sysmsg;
	sigset_t *	set;	char set_[PAD_(sigset_t *)];
};
struct	sigreturn_args {
	union sysmsg sysmsg;
	ucontext_t *	sigcntxp;	char sigcntxp_[PAD_(ucontext_t *)];
};
struct	__acl_get_file_args {
	union sysmsg sysmsg;
	const char *	path;	char path_[PAD_(const char *)];
	acl_type_t	type;	char type_[PAD_(acl_type_t)];
	struct acl *	aclp;	char aclp_[PAD_(struct acl *)];
};
struct	__acl_set_file_args {
	union sysmsg sysmsg;
	const char *	path;	char path_[PAD_(const char *)];
	acl_type_t	type;	char type_[PAD_(acl_type_t)];
	struct acl *	aclp;	char aclp_[PAD_(struct acl *)];
};
struct	__acl_get_fd_args {
	union sysmsg sysmsg;
	int	filedes;	char filedes_[PAD_(int)];
	acl_type_t	type;	char type_[PAD_(acl_type_t)];
	struct acl *	aclp;	char aclp_[PAD_(struct acl *)];
};
struct	__acl_set_fd_args {
	union sysmsg sysmsg;
	int	filedes;	char filedes_[PAD_(int)];
	acl_type_t	type;	char type_[PAD_(acl_type_t)];
	struct acl *	aclp;	char aclp_[PAD_(struct acl *)];
};
struct	__acl_delete_file_args {
	union sysmsg sysmsg;
	const char *	path;	char path_[PAD_(const char *)];
	acl_type_t	type;	char type_[PAD_(acl_type_t)];
};
struct	__acl_delete_fd_args {
	union sysmsg sysmsg;
	int	filedes;	char filedes_[PAD_(int)];
	acl_type_t	type;	char type_[PAD_(acl_type_t)];
};
struct	__acl_aclcheck_file_args {
	union sysmsg sysmsg;
	const char *	path;	char path_[PAD_(const char *)];
	acl_type_t	type;	char type_[PAD_(acl_type_t)];
	struct acl *	aclp;	char aclp_[PAD_(struct acl *)];
};
struct	__acl_aclcheck_fd_args {
	union sysmsg sysmsg;
	int	filedes;	char filedes_[PAD_(int)];
	acl_type_t	type;	char type_[PAD_(acl_type_t)];
	struct acl *	aclp;	char aclp_[PAD_(struct acl *)];
};
struct	extattrctl_args {
	union sysmsg sysmsg;
	const char *	path;	char path_[PAD_(const char *)];
	int	cmd;	char cmd_[PAD_(int)];
	const char *	attrname;	char attrname_[PAD_(const char *)];
	char *	arg;	char arg_[PAD_(char *)];
};
struct	extattr_set_file_args {
	union sysmsg sysmsg;
	const char *	path;	char path_[PAD_(const char *)];
	const char *	attrname;	char attrname_[PAD_(const char *)];
	struct iovec *	iovp;	char iovp_[PAD_(struct iovec *)];
	unsigned	iovcnt;	char iovcnt_[PAD_(unsigned)];
};
struct	extattr_get_file_args {
	union sysmsg sysmsg;
	const char *	path;	char path_[PAD_(const char *)];
	const char *	attrname;	char attrname_[PAD_(const char *)];
	struct iovec *	iovp;	char iovp_[PAD_(struct iovec *)];
	unsigned	iovcnt;	char iovcnt_[PAD_(unsigned)];
};
struct	extattr_delete_file_args {
	union sysmsg sysmsg;
	const char *	path;	char path_[PAD_(const char *)];
	const char *	attrname;	char attrname_[PAD_(const char *)];
};
struct	aio_waitcomplete_args {
	union sysmsg sysmsg;
	struct aiocb **	aiocbp;	char aiocbp_[PAD_(struct aiocb **)];
	struct timespec *	timeout;	char timeout_[PAD_(struct timespec *)];
};
struct	getresuid_args {
	union sysmsg sysmsg;
	uid_t *	ruid;	char ruid_[PAD_(uid_t *)];
	uid_t *	euid;	char euid_[PAD_(uid_t *)];
	uid_t *	suid;	char suid_[PAD_(uid_t *)];
};
struct	getresgid_args {
	union sysmsg sysmsg;
	gid_t *	rgid;	char rgid_[PAD_(gid_t *)];
	gid_t *	egid;	char egid_[PAD_(gid_t *)];
	gid_t *	sgid;	char sgid_[PAD_(gid_t *)];
};
struct	kqueue_args {
	union sysmsg sysmsg;
	register_t dummy;
};
struct	kevent_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	const struct kevent *	changelist;	char changelist_[PAD_(const struct kevent *)];
	int	nchanges;	char nchanges_[PAD_(int)];
	struct kevent *	eventlist;	char eventlist_[PAD_(struct kevent *)];
	int	nevents;	char nevents_[PAD_(int)];
	const struct timespec *	timeout;	char timeout_[PAD_(const struct timespec *)];
};
struct	sendfile_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	int	s;	char s_[PAD_(int)];
	off_t	offset;	char offset_[PAD_(off_t)];
	size_t	nbytes;	char nbytes_[PAD_(size_t)];
	struct sf_hdtr *	hdtr;	char hdtr_[PAD_(struct sf_hdtr *)];
	off_t *	sbytes;	char sbytes_[PAD_(off_t *)];
	int	flags;	char flags_[PAD_(int)];
};

#ifdef _KERNEL

int	nosys __P((struct nosys_args *));
void	sys_exit __P((struct sys_exit_args *));
int	fork __P((struct fork_args *));
int	read __P((struct read_args *));
int	write __P((struct write_args *));
int	open __P((struct open_args *));
int	close __P((struct close_args *));
int	wait4 __P((struct wait_args *));
int	link __P((struct link_args *));
int	unlink __P((struct unlink_args *));
int	chdir __P((struct chdir_args *));
int	fchdir __P((struct fchdir_args *));
int	mknod __P((struct mknod_args *));
int	chmod __P((struct chmod_args *));
int	chown __P((struct chown_args *));
int	obreak __P((struct obreak_args *));
int	getfsstat __P((struct getfsstat_args *));
int	getpid __P((struct getpid_args *));
int	mount __P((struct mount_args *));
int	unmount __P((struct unmount_args *));
int	setuid __P((struct setuid_args *));
int	getuid __P((struct getuid_args *));
int	geteuid __P((struct geteuid_args *));
int	ptrace __P((struct ptrace_args *));
int	recvmsg __P((struct recvmsg_args *));
int	sendmsg __P((struct sendmsg_args *));
int	recvfrom __P((struct recvfrom_args *));
int	accept __P((struct accept_args *));
int	getpeername __P((struct getpeername_args *));
int	getsockname __P((struct getsockname_args *));
int	access __P((struct access_args *));
int	chflags __P((struct chflags_args *));
int	fchflags __P((struct fchflags_args *));
int	sync __P((struct sync_args *));
int	kill __P((struct kill_args *));
int	getppid __P((struct getppid_args *));
int	dup __P((struct dup_args *));
int	pipe __P((struct pipe_args *));
int	getegid __P((struct getegid_args *));
int	profil __P((struct profil_args *));
int	ktrace __P((struct ktrace_args *));
int	getgid __P((struct getgid_args *));
int	getlogin __P((struct getlogin_args *));
int	setlogin __P((struct setlogin_args *));
int	acct __P((struct acct_args *));
int	sigaltstack __P((struct sigaltstack_args *));
int	ioctl __P((struct ioctl_args *));
int	reboot __P((struct reboot_args *));
int	revoke __P((struct revoke_args *));
int	symlink __P((struct symlink_args *));
int	readlink __P((struct readlink_args *));
int	execve __P((struct execve_args *));
int	umask __P((struct umask_args *));
int	chroot __P((struct chroot_args *));
int	msync __P((struct msync_args *));
int	vfork __P((struct vfork_args *));
int	sbrk __P((struct sbrk_args *));
int	sstk __P((struct sstk_args *));
int	ovadvise __P((struct ovadvise_args *));
int	munmap __P((struct munmap_args *));
int	mprotect __P((struct mprotect_args *));
int	madvise __P((struct madvise_args *));
int	mincore __P((struct mincore_args *));
int	getgroups __P((struct getgroups_args *));
int	setgroups __P((struct setgroups_args *));
int	getpgrp __P((struct getpgrp_args *));
int	setpgid __P((struct setpgid_args *));
int	setitimer __P((struct setitimer_args *));
int	swapon __P((struct swapon_args *));
int	getitimer __P((struct getitimer_args *));
int	getdtablesize __P((struct getdtablesize_args *));
int	dup2 __P((struct dup2_args *));
int	fcntl __P((struct fcntl_args *));
int	select __P((struct select_args *));
int	fsync __P((struct fsync_args *));
int	setpriority __P((struct setpriority_args *));
int	socket __P((struct socket_args *));
int	connect __P((struct connect_args *));
int	getpriority __P((struct getpriority_args *));
int	bind __P((struct bind_args *));
int	setsockopt __P((struct setsockopt_args *));
int	listen __P((struct listen_args *));
int	gettimeofday __P((struct gettimeofday_args *));
int	getrusage __P((struct getrusage_args *));
int	getsockopt __P((struct getsockopt_args *));
int	readv __P((struct readv_args *));
int	writev __P((struct writev_args *));
int	settimeofday __P((struct settimeofday_args *));
int	fchown __P((struct fchown_args *));
int	fchmod __P((struct fchmod_args *));
int	setreuid __P((struct setreuid_args *));
int	setregid __P((struct setregid_args *));
int	rename __P((struct rename_args *));
int	flock __P((struct flock_args *));
int	mkfifo __P((struct mkfifo_args *));
int	sendto __P((struct sendto_args *));
int	shutdown __P((struct shutdown_args *));
int	socketpair __P((struct socketpair_args *));
int	mkdir __P((struct mkdir_args *));
int	rmdir __P((struct rmdir_args *));
int	utimes __P((struct utimes_args *));
int	adjtime __P((struct adjtime_args *));
int	setsid __P((struct setsid_args *));
int	quotactl __P((struct quotactl_args *));
int	nfssvc __P((struct nfssvc_args *));
int	statfs __P((struct statfs_args *));
int	fstatfs __P((struct fstatfs_args *));
int	getfh __P((struct getfh_args *));
int	getdomainname __P((struct getdomainname_args *));
int	setdomainname __P((struct setdomainname_args *));
int	uname __P((struct uname_args *));
int	sysarch __P((struct sysarch_args *));
int	rtprio __P((struct rtprio_args *));
int	semsys __P((struct semsys_args *));
int	msgsys __P((struct msgsys_args *));
int	shmsys __P((struct shmsys_args *));
int	pread __P((struct pread_args *));
int	pwrite __P((struct pwrite_args *));
int	ntp_adjtime __P((struct ntp_adjtime_args *));
int	setgid __P((struct setgid_args *));
int	setegid __P((struct setegid_args *));
int	seteuid __P((struct seteuid_args *));
int	stat __P((struct stat_args *));
int	fstat __P((struct fstat_args *));
int	lstat __P((struct lstat_args *));
int	pathconf __P((struct pathconf_args *));
int	fpathconf __P((struct fpathconf_args *));
int	getrlimit __P((struct __getrlimit_args *));
int	setrlimit __P((struct __setrlimit_args *));
int	getdirentries __P((struct getdirentries_args *));
int	mmap __P((struct mmap_args *));
int	lseek __P((struct lseek_args *));
int	truncate __P((struct truncate_args *));
int	ftruncate __P((struct ftruncate_args *));
int	__sysctl __P((struct sysctl_args *));
int	mlock __P((struct mlock_args *));
int	munlock __P((struct munlock_args *));
int	undelete __P((struct undelete_args *));
int	futimes __P((struct futimes_args *));
int	getpgid __P((struct getpgid_args *));
int	poll __P((struct poll_args *));
int	lkmnosys __P((struct nosys_args *));
int	__semctl __P((struct __semctl_args *));
int	semget __P((struct semget_args *));
int	semop __P((struct semop_args *));
int	msgctl __P((struct msgctl_args *));
int	msgget __P((struct msgget_args *));
int	msgsnd __P((struct msgsnd_args *));
int	msgrcv __P((struct msgrcv_args *));
int	shmat __P((struct shmat_args *));
int	shmctl __P((struct shmctl_args *));
int	shmdt __P((struct shmdt_args *));
int	shmget __P((struct shmget_args *));
int	clock_gettime __P((struct clock_gettime_args *));
int	clock_settime __P((struct clock_settime_args *));
int	clock_getres __P((struct clock_getres_args *));
int	nanosleep __P((struct nanosleep_args *));
int	minherit __P((struct minherit_args *));
int	rfork __P((struct rfork_args *));
int	openbsd_poll __P((struct openbsd_poll_args *));
int	issetugid __P((struct issetugid_args *));
int	lchown __P((struct lchown_args *));
int	getdents __P((struct getdents_args *));
int	lchmod __P((struct lchmod_args *));
int	lutimes __P((struct lutimes_args *));
int	nstat __P((struct nstat_args *));
int	nfstat __P((struct nfstat_args *));
int	nlstat __P((struct nlstat_args *));
int	fhstatfs __P((struct fhstatfs_args *));
int	fhopen __P((struct fhopen_args *));
int	fhstat __P((struct fhstat_args *));
int	modnext __P((struct modnext_args *));
int	modstat __P((struct modstat_args *));
int	modfnext __P((struct modfnext_args *));
int	modfind __P((struct modfind_args *));
int	kldload __P((struct kldload_args *));
int	kldunload __P((struct kldunload_args *));
int	kldfind __P((struct kldfind_args *));
int	kldnext __P((struct kldnext_args *));
int	kldstat __P((struct kldstat_args *));
int	kldfirstmod __P((struct kldfirstmod_args *));
int	getsid __P((struct getsid_args *));
int	setresuid __P((struct setresuid_args *));
int	setresgid __P((struct setresgid_args *));
int	aio_return __P((struct aio_return_args *));
int	aio_suspend __P((struct aio_suspend_args *));
int	aio_cancel __P((struct aio_cancel_args *));
int	aio_error __P((struct aio_error_args *));
int	aio_read __P((struct aio_read_args *));
int	aio_write __P((struct aio_write_args *));
int	lio_listio __P((struct lio_listio_args *));
int	yield __P((struct yield_args *));
int	thr_sleep __P((struct thr_sleep_args *));
int	thr_wakeup __P((struct thr_wakeup_args *));
int	mlockall __P((struct mlockall_args *));
int	munlockall __P((struct munlockall_args *));
int	__getcwd __P((struct __getcwd_args *));
int	sched_setparam __P((struct sched_setparam_args *));
int	sched_getparam __P((struct sched_getparam_args *));
int	sched_setscheduler __P((struct sched_setscheduler_args *));
int	sched_getscheduler __P((struct sched_getscheduler_args *));
int	sched_yield __P((struct sched_yield_args *));
int	sched_get_priority_max __P((struct sched_get_priority_max_args *));
int	sched_get_priority_min __P((struct sched_get_priority_min_args *));
int	sched_rr_get_interval __P((struct sched_rr_get_interval_args *));
int	utrace __P((struct utrace_args *));
int	kldsym __P((struct kldsym_args *));
int	jail __P((struct jail_args *));
int	sigprocmask __P((struct sigprocmask_args *));
int	sigsuspend __P((struct sigsuspend_args *));
int	sigaction __P((struct sigaction_args *));
int	sigpending __P((struct sigpending_args *));
int	sigreturn __P((struct sigreturn_args *));
int	__acl_get_file __P((struct __acl_get_file_args *));
int	__acl_set_file __P((struct __acl_set_file_args *));
int	__acl_get_fd __P((struct __acl_get_fd_args *));
int	__acl_set_fd __P((struct __acl_set_fd_args *));
int	__acl_delete_file __P((struct __acl_delete_file_args *));
int	__acl_delete_fd __P((struct __acl_delete_fd_args *));
int	__acl_aclcheck_file __P((struct __acl_aclcheck_file_args *));
int	__acl_aclcheck_fd __P((struct __acl_aclcheck_fd_args *));
int	extattrctl __P((struct extattrctl_args *));
int	extattr_set_file __P((struct extattr_set_file_args *));
int	extattr_get_file __P((struct extattr_get_file_args *));
int	extattr_delete_file __P((struct extattr_delete_file_args *));
int	aio_waitcomplete __P((struct aio_waitcomplete_args *));
int	getresuid __P((struct getresuid_args *));
int	getresgid __P((struct getresgid_args *));
int	kqueue __P((struct kqueue_args *));
int	kevent __P((struct kevent_args *));
int	sendfile __P((struct sendfile_args *));

#endif /* _KERNEL */

#ifdef COMPAT_43

struct	ocreat_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	int	mode;	char mode_[PAD_(int)];
};
struct	olseek_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	long	offset;	char offset_[PAD_(long)];
	int	whence;	char whence_[PAD_(int)];
};
struct	ostat_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	struct ostat *	ub;	char ub_[PAD_(struct ostat *)];
};
struct	olstat_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	struct ostat *	ub;	char ub_[PAD_(struct ostat *)];
};
struct	osigaction_args {
	union sysmsg sysmsg;
	int	signum;	char signum_[PAD_(int)];
	struct osigaction *	nsa;	char nsa_[PAD_(struct osigaction *)];
	struct osigaction *	osa;	char osa_[PAD_(struct osigaction *)];
};
struct	osigprocmask_args {
	union sysmsg sysmsg;
	int	how;	char how_[PAD_(int)];
	osigset_t	mask;	char mask_[PAD_(osigset_t)];
};
struct	ofstat_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	struct ostat *	sb;	char sb_[PAD_(struct ostat *)];
};
struct	getkerninfo_args {
	union sysmsg sysmsg;
	int	op;	char op_[PAD_(int)];
	char *	where;	char where_[PAD_(char *)];
	size_t *	size;	char size_[PAD_(size_t *)];
	int	arg;	char arg_[PAD_(int)];
};
struct	ommap_args {
	union sysmsg sysmsg;
	void *	addr;	char addr_[PAD_(void *)];
	int	len;	char len_[PAD_(int)];
	int	prot;	char prot_[PAD_(int)];
	int	flags;	char flags_[PAD_(int)];
	int	fd;	char fd_[PAD_(int)];
	long	pos;	char pos_[PAD_(long)];
};
struct	gethostname_args {
	union sysmsg sysmsg;
	char *	hostname;	char hostname_[PAD_(char *)];
	u_int	len;	char len_[PAD_(u_int)];
};
struct	sethostname_args {
	union sysmsg sysmsg;
	char *	hostname;	char hostname_[PAD_(char *)];
	u_int	len;	char len_[PAD_(u_int)];
};
struct	osend_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	caddr_t	buf;	char buf_[PAD_(caddr_t)];
	int	len;	char len_[PAD_(int)];
	int	flags;	char flags_[PAD_(int)];
};
struct	orecv_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	caddr_t	buf;	char buf_[PAD_(caddr_t)];
	int	len;	char len_[PAD_(int)];
	int	flags;	char flags_[PAD_(int)];
};
struct	osigreturn_args {
	union sysmsg sysmsg;
	struct osigcontext *	sigcntxp;	char sigcntxp_[PAD_(struct osigcontext *)];
};
struct	osigvec_args {
	union sysmsg sysmsg;
	int	signum;	char signum_[PAD_(int)];
	struct sigvec *	nsv;	char nsv_[PAD_(struct sigvec *)];
	struct sigvec *	osv;	char osv_[PAD_(struct sigvec *)];
};
struct	osigblock_args {
	union sysmsg sysmsg;
	int	mask;	char mask_[PAD_(int)];
};
struct	osigsetmask_args {
	union sysmsg sysmsg;
	int	mask;	char mask_[PAD_(int)];
};
struct	osigsuspend_args {
	union sysmsg sysmsg;
	osigset_t	mask;	char mask_[PAD_(osigset_t)];
};
struct	osigstack_args {
	union sysmsg sysmsg;
	struct sigstack *	nss;	char nss_[PAD_(struct sigstack *)];
	struct sigstack *	oss;	char oss_[PAD_(struct sigstack *)];
};
struct	orecvmsg_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	struct omsghdr *	msg;	char msg_[PAD_(struct omsghdr *)];
	int	flags;	char flags_[PAD_(int)];
};
struct	osendmsg_args {
	union sysmsg sysmsg;
	int	s;	char s_[PAD_(int)];
	caddr_t	msg;	char msg_[PAD_(caddr_t)];
	int	flags;	char flags_[PAD_(int)];
};
struct	otruncate_args {
	union sysmsg sysmsg;
	char *	path;	char path_[PAD_(char *)];
	long	length;	char length_[PAD_(long)];
};
struct	oftruncate_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	long	length;	char length_[PAD_(long)];
};
struct	ogetpeername_args {
	union sysmsg sysmsg;
	int	fdes;	char fdes_[PAD_(int)];
	caddr_t	asa;	char asa_[PAD_(caddr_t)];
	int *	alen;	char alen_[PAD_(int *)];
};
struct	osethostid_args {
	union sysmsg sysmsg;
	long	hostid;	char hostid_[PAD_(long)];
};
struct	ogetrlimit_args {
	union sysmsg sysmsg;
	u_int	which;	char which_[PAD_(u_int)];
	struct orlimit *	rlp;	char rlp_[PAD_(struct orlimit *)];
};
struct	osetrlimit_args {
	union sysmsg sysmsg;
	u_int	which;	char which_[PAD_(u_int)];
	struct orlimit *	rlp;	char rlp_[PAD_(struct orlimit *)];
};
struct	okillpg_args {
	union sysmsg sysmsg;
	int	pgid;	char pgid_[PAD_(int)];
	int	signum;	char signum_[PAD_(int)];
};
struct	ogetdirentries_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	char *	buf;	char buf_[PAD_(char *)];
	u_int	count;	char count_[PAD_(u_int)];
	long *	basep;	char basep_[PAD_(long *)];
};
struct	osendfile_args {
	union sysmsg sysmsg;
	int	fd;	char fd_[PAD_(int)];
	int	s;	char s_[PAD_(int)];
	off_t	offset;	char offset_[PAD_(off_t)];
	size_t	nbytes;	char nbytes_[PAD_(size_t)];
	struct sf_hdtr *	hdtr;	char hdtr_[PAD_(struct sf_hdtr *)];
	off_t *	sbytes;	char sbytes_[PAD_(off_t *)];
	int	flags;	char flags_[PAD_(int)];
};

#ifdef _KERNEL

int	ocreat __P((struct ocreat_args *));
int	olseek __P((struct olseek_args *));
int	ostat __P((struct ostat_args *));
int	olstat __P((struct olstat_args *));
int	osigaction __P((struct osigaction_args *));
int	osigprocmask __P((struct osigprocmask_args *));
int	osigpending __P((struct osigpending_args *));
int	ofstat __P((struct ofstat_args *));
int	ogetkerninfo __P((struct getkerninfo_args *));
int	ogetpagesize __P((struct getpagesize_args *));
int	ommap __P((struct ommap_args *));
int	owait __P((struct owait_args *));
int	ogethostname __P((struct gethostname_args *));
int	osethostname __P((struct sethostname_args *));
int	oaccept __P((struct accept_args *));
int	osend __P((struct osend_args *));
int	orecv __P((struct orecv_args *));
int	osigreturn __P((struct osigreturn_args *));
int	osigvec __P((struct osigvec_args *));
int	osigblock __P((struct osigblock_args *));
int	osigsetmask __P((struct osigsetmask_args *));
int	osigsuspend __P((struct osigsuspend_args *));
int	osigstack __P((struct osigstack_args *));
int	orecvmsg __P((struct orecvmsg_args *));
int	osendmsg __P((struct osendmsg_args *));
int	orecvfrom __P((struct recvfrom_args *));
int	otruncate __P((struct otruncate_args *));
int	oftruncate __P((struct oftruncate_args *));
int	ogetpeername __P((struct ogetpeername_args *));
int	ogethostid __P((struct ogethostid_args *));
int	osethostid __P((struct osethostid_args *));
int	ogetrlimit __P((struct ogetrlimit_args *));
int	osetrlimit __P((struct osetrlimit_args *));
int	okillpg __P((struct okillpg_args *));
int	oquota __P((struct oquota_args *));
int	ogetsockname __P((struct getsockname_args *));
int	ogetdirentries __P((struct ogetdirentries_args *));
int	osendfile __P((struct osendfile_args *));

#endif /* _KERNEL */

#endif /* COMPAT_43 */

#undef PAD_

#endif /* !_SYS_SYSPROTO_H_ */
