#
# $FreeBSD: src/gnu/usr.bin/perl/utils/c2ph/Makefile,v 1.2 1999/08/27 23:36:26 peter Exp $
# $DragonFly: src/gnu/usr.bin/perl/utils/c2ph/Attic/Makefile,v 1.2 2003/06/17 04:25:47 dillon Exp $
#

PROG=	c2ph

.include <bsd.prog.mk>
