# $FreeBSD: src/sys/modules/rue/Makefile,v 1.2 2004/06/27 12:33:16 imp Exp $
# $DragonFly: src/sys/dev/netif/rue/Makefile,v 1.1 2005/09/19 02:53:27 sephe Exp $

KMOD=	if_rue
SRCS=	if_rue.c
SRCS+=	miibus_if.h device_if.h bus_if.h opt_usb.h

.include <bsd.kmod.mk>
