# $FreeBSD: src/usr.bin/keylogin/Makefile,v 1.3 1999/08/28 01:02:27 peter Exp $
# $DragonFly: src/usr.bin/keylogin/Makefile,v 1.3 2007/08/27 16:50:55 pavalos Exp $

PROG=	keylogin

DPADD=	${LIBRPCSVC}
LDADD=	-lrpcsvc
WARNS?=	0

.include <bsd.prog.mk>
