# csu and libgcc* are normally built earlier by the _startup_libs120 target

SUBDIR_ORDERED=	libstdc++ libstdc++fs

SUBDIR+=	csu
SUBDIR+=	libgcc
SUBDIR+=	libgcc_eh
SUBDIR+=	libgcc_pic
SUBDIR+=	libgcov
SUBDIR+=	libgomp
SUBDIR+=	libssp
SUBDIR+=	libssp_nonshared
SUBDIR+=	libstdc++
SUBDIR+=	libstdc++fs

.include <bsd.subdir.mk>
