# csu and libgcc* are normally built earlier by the _startup_libs120 target

SUBDIR_ORDERED=

SUBDIR+=	csu
SUBDIR+=	libgcc
SUBDIR+=	libgcc_eh
SUBDIR+=	libgcc_pic
SUBDIR+=	libgcov
SUBDIR+=	libgomp
SUBDIR+=	libssp
SUBDIR+=	libssp_nonshared
SUBDIR+=	libstdcxx

.include <bsd.subdir.mk>
