# $DragonFly: src/gnu/usr.bin/cc40/cc_tools/gengenrtl/Attic/Makefile,v 1.1 2005/06/05 22:43:20 corecode Exp $

.include "../Makefile.inc"

PROG=	gengenrtl
SRCS=	gengenrtl.c
SRCS+=	${ERRORS_SRCS}

.include <bsd.hostprog.mk>
