# $FreeBSD: src/usr.bin/cmp/Makefile,v 1.2.6.1 2001/11/21 10:47:54 dwmalone Exp $
# $DragonFly: src/usr.bin/cmp/Makefile,v 1.4 2007/08/27 16:50:52 pavalos Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	cmp
SRCS=	cmp.c misc.c regular.c special.c

.include <bsd.prog.mk>
