# Makefile for acpi tools
# $Id: Makefile,v 1.1 2000/07/14 18:16:22 iwasaki Exp $
# $FreeBSD: src/usr.sbin/acpi/Makefile,v 1.3 2003/08/08 03:20:59 njl Exp $
# $DragonFly: src/usr.sbin/acpi/Makefile,v 1.1 2004/07/05 00:22:40 dillon Exp $

SUBDIR= acpiconf acpidb acpidump iasl

.include <bsd.subdir.mk>
