# $FreeBSD: src/share/doc/usd/12.vi/vi/Makefile,v 1.3 1999/08/28 00:18:54 peter Exp $
# $DragonFly: src/share/doc/usd/12.vi/vi/Makefile,v 1.2 2003/06/17 04:36:57 dillon Exp $

SRCS=	vi.in vi.chars
#DOC=	tutorial
SRCDIR=	${.CURDIR}/../../../../../contrib/nvi/docs/USD.doc/vitut

.include <bsd.doc.mk>
