# $FreeBSD: src/usr.sbin/stallion/stlload/Makefile,v 1.5.2.2 2001/04/25 12:10:59 ru Exp $
# $DragonFly: src/usr.sbin/stallion/stlload/Makefile,v 1.2 2003/06/17 04:30:03 dillon Exp $

PROG=	stlload
MAN=	stlload.8
MANSUBDIR=/i386

CFLAGS+=-DBOOTDIR=\"${BOOTDIR}\"

.include <bsd.prog.mk>
