#!/bin/sh

set -e

scriptdir=$(cd $(dirname $0) && pwd)
fwdir=$scriptdir/../../../contrib/dev/drm/radeonfw

for dir in $scriptdir/*; do
	if [ ! -d $dir ]; then
		continue
	fi
	rm -rf $dir
done

for file in $fwdir/*.uu; do
	img=$(basename $file)
	img=${img%.bin.uu}
	echo "Image: $img"

	mkdir -p $scriptdir/$img
	cat > $scriptdir/$img/Makefile <<EOF
# \$FreeBSD: head/sys/modules/drm2/radeonkmsfw/$img/Makefile 254885 2013-08-25 19:37:15Z dumbbell $

KMOD=	radeonkmsfw_$img
IMG=	$img

.include <bsd.kmod.mk>
EOF
done

rm $scriptdir/Makefile
echo "SUBDIR=\t\t\t\t\t\t\t\t\t\\" >> $scriptdir/Makefile

for dir in $scriptdir/*; do
	if [ ! -d $dir ]; then
		continue
	fi
	img=$(basename $dir)
	img=${img%.bin.uu}
	echo "\t$img\t\t\t\t\t\t\t\\" >> $scriptdir/Makefile
done

echo >> $scriptdir/Makefile
echo ".include <bsd.subdir.mk>" >> $scriptdir/Makefile
