#	From: @(#)Makefile	8.1 (Berkeley) 8/14/93
# $FreeBSD: src/share/doc/psd/12.make/Makefile,v 1.4.2.2 2000/11/24 10:08:45 ru Exp $
# $DragonFly: src/share/doc/psd/12.make/Makefile,v 1.2 2003/06/17 04:36:56 dillon Exp $

VOLUME=	psd/12.make
SRCS=	tutorial.ms
MACROS=	-ms
SRCDIR=	${.CURDIR}/../../../../usr.bin/make/PSD.doc

.include <bsd.doc.mk>
