.\" Copyright (c) 2007 The DragonFly Project.  All rights reserved.
.\" 
.\" This code is derived from software contributed to The DragonFly Project
.\" by Matthew Dillon <dillon@backplane.com>
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\" 
.\" $DragonFly: src/sbin/newfs_hammer/newfs_hammer.8,v 1.5 2008/02/19 21:02:08 thomas Exp $
.Dd September 10, 2007
.Dt NEWFS_HAMMER 8
.Os
.Sh NAME
.Nm newfs_hammer
.Nd construct a new HAMMER file system
.Sh SYNOPSIS
.Nm
.Fl L Ar label
.Op Fl U Ar uuid
.Ar special ...
.Sh DESCRIPTION
The
.Nm
utility creates a HAMMER filesystem on device
.Ar special .
If multiple devices are specified a single HAMMER filesystem is created
which spans all of them.
HAMMER filesystems are sector-size agnostic, however the
.Dx
implementation requires the sector size to be no larger than 16K.
HAMMER filesystems start at a relative offset of 0 and may only be created
under out-of-band disk labels (disklabel64 or gpt labels), or in standard
disklabel partitions which do not overlap the label area.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl L Ar label
All HAMMER filesystems must be named and names should be unique on a
per-machine basis.
.It Fl U Ar uuid
All HAMMER filesystems are assigned a globally unique UUID.
If no UUID is specified one will be synthesized.
.El
.\".Sh NOTES
.Sh EXAMPLES
.Bd -literal -offset indent
newfs_hammer -L Home /dev/ad0s1d
.Ed
.Pp
Create a file system named
.Sq Home
on
.Pa /dev/ad0s1d .
.Sh DIAGNOSTICS
Exit status is 0 on success and 1 on error.
.Sh SEE ALSO
.Xr disklabel 8 ,
.Xr fdisk 8 ,
.Xr newfs 8
.Sh HISTORY
The
.Nm
utility first appeared in
.Dx 1.11 .
.Sh AUTHORS
.An Matthew Dillon Aq dillon@backplane.com
