# $FreeBSD: src/sys/modules/cue/Makefile,v 1.2 2000/01/28 11:26:27 bde Exp $
# $DragonFly: src/sys/dev/netif/cue/Makefile,v 1.3 2005/05/25 11:46:10 joerg Exp $

KMOD	= if_cue
SRCS	= if_cue.c opt_bdg.h opt_usb.h device_if.h bus_if.h
SRCS	+= miibus_if.h

.include <bsd.kmod.mk>
