# $FreeBSD: src/sys/modules/cue/Makefile,v 1.2 2000/01/28 11:26:27 bde Exp $
# $DragonFly: src/sys/dev/netif/cue/Makefile,v 1.5 2006/11/18 10:00:19 swildner Exp $

KMOD	= if_cue
SRCS	= if_cue.c opt_usb.h device_if.h bus_if.h

.include <bsd.kmod.mk>
