#
# $FreeBSD: src/gnu/usr.bin/perl/utils/perlcc/Makefile,v 1.2 1999/08/27 23:36:29 peter Exp $
# $DragonFly: src/gnu/usr.bin/perl/utils/perlcc/Attic/Makefile,v 1.2 2003/06/17 04:25:47 dillon Exp $
#

PROG=	perlcc

.include <bsd.prog.mk>
