# $DragonFly: src/lib/i18n_module/Makefile,v 1.3 2008/04/10 10:21:00 hasso Exp $

SUBDIR=	BIG5 DECHanyu EUC EUCTW GBK2K HZ ISO2022 JOHAB MSKanji UES UTF1632
SUBDIR+=UTF7 UTF8 VIQR ZW
SUBDIR+=iconv_none iconv_std
SUBDIR+=mapper_646 mapper_none mapper_serial mapper_parallel mapper_std
SUBDIR+=mapper_zone

.include <bsd.subdir.mk>
