# $DragonFly: src/lib/i18n_module/Makefile,v 1.2 2005/03/11 21:50:39 joerg Exp $

SUBDIR=	BIG5 EUC EUCTW GBK2K ISO2022 MSKanji UTF1632 UTF7 UTF8
SUBDIR+=iconv_none iconv_std
SUBDIR+=mapper_646 mapper_none mapper_serial mapper_parallel mapper_std
SUBDIR+=mapper_zone

.include <bsd.subdir.mk>
