# Makefile for vfs modules
#
# $DragonFly: src/sys/vfs/Makefile,v 1.7 2006/08/17 22:07:49 dillon Exp $

SUBDIR=fifofs msdosfs portal gnu nfs procfs \
	hpfs ntfs smbfs isofs fdesc mfs nwfs udf \
	nullfs

.include <bsd.subdir.mk>
