# Makefile for vfs modules
#
# $DragonFly: src/sys/vfs/Makefile,v 1.7.8.1 2008/07/17 10:18:06 swildner Exp $

SUBDIR=fifofs msdosfs portal gnu nfs procfs \
	hpfs ntfs smbfs isofs fdesc mfs nwfs udf \
	nullfs hammer

.include <bsd.subdir.mk>
