#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/sbin/nfsd/Makefile,v 1.10.2.2 2001/04/25 10:58:42 ru Exp $
# $DragonFly: src/sbin/nfsd/Makefile,v 1.4 2006/10/17 00:55:43 pavalos Exp $

PROG=	nfsd
CFLAGS+=-DNFS
MAN=	nfsd.8
WARNS?=	2

.include <bsd.prog.mk>
