#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/sbin/nfsd/Makefile,v 1.10.2.2 2001/04/25 10:58:42 ru Exp $
# $DragonFly: src/sbin/nfsd/Makefile,v 1.6 2006/12/27 23:06:29 corecode Exp $

PROG=	nfsd
MAN=	nfsd.8

.include <bsd.prog.mk>
