# $DragonFly: src/share/installer/Makefile,v 1.2 2008/07/09 07:21:03 swildner Exp $

.PATH: ${.CURDIR}/../../contrib/bsdinstaller-1.1.6/src/frontends/ncurses

FILES=		cmdnames.conf fred.txt
NOOBJ=
FILESDIR=	${BINDIR}/installer

.include <bsd.prog.mk>
