.\" -*- mode: roff -*-
.ig

short_reference.roff

This file is part of groff, the GNU roff type-setting system.

Copyright (C) 2005, 2006, 2009 Free Software Foundation, Inc.
written by Joachim Walsdorff <Joachim.Walsdorff@urz.uni-heidelberg.de>.

groff is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or
(at your option) any later version.

groff is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

..
.
.time start
.pv 1.2 1.2 "" x
.H Short Reference for the HDtbl-Macros
This Short Reference describes the Heidelberger Table Macros
using the macros themselves.
.br
.nr t*csp .3n
.nr t*cpd .3n
.ds t*ff HN
.ds t*val m
.ds t*hal l
.xig
.TBL "width=10% 40% 25% 25%" border= "fsz=1 .8"
.CPTN Base- Optional- and Utility-Macros val=b
.TR
.TH Macro .TH Description .TH Predecessors .TH Successors 
.TR 
.TD \&.TBL .TD Begin a new table .TD \&.TD \&.TH \%.ETB cell content
.TD \&.CPTN \&.TR 
.TR 
.TD \&.CPTN .TD Optional numbered or unnumbered table caption
.TD \&.TBL .TD \&.TR 
.TR
.TD \&.TR .TD Begin a new table row .TD \&.TBL \&.CPTN cell content
.TD \&.TD \&.TR
.TR
.TD \&.TH .TD Optional begin table header cell 
.TD \&.TR \&.TD \&.TH \%.ETB cell content
.TD \&.TD \&.TH \&.TR \%.ETB cell content
.TR 
.TD \&.TH .TD Begin table data cell .TD \&.TR \&.TD \&.TH \%.ETB cell content
.TD \&.TD \&.TH \&.TR \%.ETB cell content
.TR 
.TD \&.ETB .TD Finish and print table .TD \&.TD \&.TH \%.ETB cell content
.TD \&.TBL \&.TR \&.TD \&.TH \%.ETB cell content
.TR
.TD \&.t*free 
.TD colspan=3 val=t Utility macro to free held tables. Use it outside any table.
.ETB
.bp
.x.
.TBL "fsz=1 .8" "width=20% 32% 8% 8% 8% 8% 8% 8%" border=
.TR
.TH Argument .TH Value .TH \&.TBL .TH \&.CPT .TH \&.TR .TH \&.TH .TH \&.TD .TH \&.ETB
.TR 
.TD border=\fI[n]\fP 
.TD border thickness .TD .ce X .TD .TD .TD .TD .TD
.TR
.TD bc=\fI[c]\fP 
.TD color of border and cellseperatorlines .TD .ce X .TD .TD .ce X .TD .ce X .TD .ce X .TD
.ETB
.H ------ incomplete -------
.time end
