#	from: @(#)Makefile	5.8 (Berkeley) 7/28/90
# $FreeBSD: src/usr.sbin/yppoll/Makefile,v 1.5.2.1 2001/04/25 12:11:14 ru Exp $
# $DragonFly: src/usr.sbin/yppoll/Makefile,v 1.2 2003/06/17 04:30:04 dillon Exp $

PROG=	yppoll
MAN=	yppoll.8

.include <bsd.prog.mk>
