# $DragonFly: src/gnu/usr.bin/cc34/cc_tools/genpreds/Makefile,v 1.1 2004/06/14 22:27:55 joerg Exp $

.include "../Makefile.inc"

PROG=	genpreds
SRCS=	genpreds.c insn-modes.h

.include <bsd.hostprog.mk>
