# $FreeBSD: src/usr.sbin/wpa/hostapd_cli/Makefile,v 1.2.2.1 2006/03/24 01:43:18 sam Exp $
# $DragonFly: src/usr.sbin/802_11/hostapd_cli/Makefile,v 1.1 2006/09/02 05:40:35 sephe Exp $

SRCDIR= ${.CURDIR}/../../../contrib/hostapd-0.4.9

.PATH: ${SRCDIR}

PROG=	hostapd_cli
SRCS=	hostapd_cli.c wpa_ctrl.c

MAN=	hostapd_cli.8

.include <bsd.prog.mk>
