# $OpenBSD: Makefile,v 1.1 2003/09/24 20:32:49 henning Exp $
# $DragonFly: src/usr.sbin/sensorsd/Makefile,v 1.1 2007/10/02 12:57:01 hasso Exp $

PROG=	sensorsd
MAN=	sensorsd.8 sensorsd.conf.5

CFLAGS+=	-Wall

.include <bsd.prog.mk>
