#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/sed/Makefile,v 1.2.6.1 2002/06/26 16:49:28 obrien Exp $
# $DragonFly: src/usr.bin/sed/Makefile,v 1.4 2008/04/08 13:23:38 swildner Exp $

PROG=	sed
SRCS=	compile.c main.c misc.c process.c

.include <bsd.prog.mk>
