# Build in parallel
SUBDIR=	addr2line \
	ar \
	cxxfilt \
	elfedit \
	gas \
	gprof \
	libgold \
	ld \
	nm \
	objcopy \
	objdump \
	ranlib \
	readelf \
	size \
	strings \
	strip

SUBDIR_ORDERED=

.include <bsd.subdir.mk>
