#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/leave/Makefile,v 1.3 1999/08/28 01:02:45 peter Exp $
# $DragonFly: src/usr.bin/leave/Makefile,v 1.3 2005/01/16 21:14:51 cpressey Exp $

PROG=	leave
WARNS?=	6
CFLAGS+=-Wall

.include <bsd.prog.mk>
