#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.sbin/diskpart/Makefile,v 1.2.14.1 2001/04/25 12:09:25 ru Exp $
# $DragonFly: src/usr.sbin/diskpart/Attic/Makefile,v 1.2 2003/06/17 04:29:53 dillon Exp $

PROG=	diskpart
MAN=	diskpart.8

.include <bsd.prog.mk>
