# $DragonFly: src/gnu/usr.bin/cc34/cc_tools/gencodes/Makefile,v 1.1 2004/06/14 22:27:54 joerg Exp $

.include "../Makefile.inc"

PROG=	gencodes
SRCS=	gencodes.c genrtl.h gensupport.c gtype-desc.h tm-preds.h
SRCS+=	insn-conditions.c insn-constants.h min-insn-modes.c insn-modes.h
SRCS+=	errors.c rtl.c read-rtl.c ggc-none.c
SRCS+=	concat.c hashtab.c obstack.c safe-ctype.c xexit.c xmalloc.c xstrdup.c

.include <bsd.hostprog.mk>
