/*
 * System call switch table.
 *
 * DO NOT EDIT-- To regenerate this file, edit syscalls.master followed
 *               by running make sysent in the same directory.
 */

#include <sys/param.h>
#include <sys/sysent.h>
#include <sys/sysmsg.h>
#include <sys/statvfs.h>

#define AS(name) (sizeof(struct name) / sizeof(register_t))

/* The casts are bogus but will do for now. */
struct sysent sysent[] = {
	{ 0, 4, (sy_call_t *)sys_xsyscall },		/* 0 = syscall */
	{ AS(exit_args), 4, (sy_call_t *)sys_exit },	/* 1 = exit */
	{ 0, 4, (sy_call_t *)sys_fork },			/* 2 = fork */
	{ AS(read_args), 8, (sy_call_t *)sys_read },	/* 3 = read */
	{ AS(write_args), 8, (sy_call_t *)sys_write },	/* 4 = write */
	{ AS(open_args), 4, (sy_call_t *)sys_open },	/* 5 = open */
	{ AS(close_args), 4, (sy_call_t *)sys_close },	/* 6 = close */
	{ AS(wait_args), 4, (sy_call_t *)sys_wait4 },	/* 7 = wait4 */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 8 = __nosys */
	{ AS(link_args), 4, (sy_call_t *)sys_link },	/* 9 = link */
	{ AS(unlink_args), 4, (sy_call_t *)sys_unlink },	/* 10 = unlink */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 11 = obsolete execv */
	{ AS(chdir_args), 4, (sy_call_t *)sys_chdir },	/* 12 = chdir */
	{ AS(fchdir_args), 4, (sy_call_t *)sys_fchdir },	/* 13 = fchdir */
	{ AS(mknod_args), 4, (sy_call_t *)sys_mknod },	/* 14 = mknod */
	{ AS(chmod_args), 4, (sy_call_t *)sys_chmod },	/* 15 = chmod */
	{ AS(chown_args), 4, (sy_call_t *)sys_chown },	/* 16 = chown */
	{ AS(obreak_args), 4, (sy_call_t *)sys_obreak },	/* 17 = break */
	{ AS(getfsstat_args), 4, (sy_call_t *)sys_getfsstat },	/* 18 = getfsstat */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 19 = obsolete old lseek */
	{ 0, 4, (sy_call_t *)sys_getpid },			/* 20 = getpid */
	{ AS(mount_args), 4, (sy_call_t *)sys_mount },	/* 21 = mount */
	{ AS(unmount_args), 4, (sy_call_t *)sys_unmount },	/* 22 = unmount */
	{ AS(setuid_args), 4, (sy_call_t *)sys_setuid },	/* 23 = setuid */
	{ 0, 4, (sy_call_t *)sys_getuid },			/* 24 = getuid */
	{ 0, 4, (sy_call_t *)sys_geteuid },		/* 25 = geteuid */
	{ AS(ptrace_args), 4, (sy_call_t *)sys_ptrace },	/* 26 = ptrace */
	{ AS(recvmsg_args), 4, (sy_call_t *)sys_recvmsg },	/* 27 = recvmsg */
	{ AS(sendmsg_args), 4, (sy_call_t *)sys_sendmsg },	/* 28 = sendmsg */
	{ AS(recvfrom_args), 4, (sy_call_t *)sys_recvfrom },	/* 29 = recvfrom */
	{ AS(accept_args), 4, (sy_call_t *)sys_accept },	/* 30 = accept */
	{ AS(getpeername_args), 4, (sy_call_t *)sys_getpeername },	/* 31 = getpeername */
	{ AS(getsockname_args), 4, (sy_call_t *)sys_getsockname },	/* 32 = getsockname */
	{ AS(access_args), 4, (sy_call_t *)sys_access },	/* 33 = access */
	{ AS(chflags_args), 4, (sy_call_t *)sys_chflags },	/* 34 = chflags */
	{ AS(fchflags_args), 4, (sy_call_t *)sys_fchflags },	/* 35 = fchflags */
	{ 0, 4, (sy_call_t *)sys_sync },			/* 36 = sync */
	{ AS(kill_args), 4, (sy_call_t *)sys_kill },	/* 37 = kill */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 38 = obsolete old stat */
	{ 0, 4, (sy_call_t *)sys_getppid },		/* 39 = getppid */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 40 = obsolete old lstat */
	{ AS(dup_args), 4, (sy_call_t *)sys_dup },		/* 41 = dup */
	{ 0, 4, (sy_call_t *)sys_pipe },			/* 42 = pipe */
	{ 0, 4, (sy_call_t *)sys_getegid },		/* 43 = getegid */
	{ AS(profil_args), 4, (sy_call_t *)sys_profil },	/* 44 = profil */
	{ AS(ktrace_args), 4, (sy_call_t *)sys_ktrace },	/* 45 = ktrace */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 46 = obsolete freebsd3_sigaction */
	{ 0, 4, (sy_call_t *)sys_getgid },			/* 47 = getgid */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 48 = obsolete freebsd3_sigprocmask */
	{ AS(getlogin_args), 4, (sy_call_t *)sys_getlogin },	/* 49 = getlogin */
	{ AS(setlogin_args), 4, (sy_call_t *)sys_setlogin },	/* 50 = setlogin */
	{ AS(acct_args), 4, (sy_call_t *)sys_acct },	/* 51 = acct */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 52 = obsolete freebsd3_sigpending */
	{ AS(sigaltstack_args), 4, (sy_call_t *)sys_sigaltstack },	/* 53 = sigaltstack */
	{ AS(ioctl_args), 4, (sy_call_t *)sys_ioctl },	/* 54 = ioctl */
	{ AS(reboot_args), 4, (sy_call_t *)sys_reboot },	/* 55 = reboot */
	{ AS(revoke_args), 4, (sy_call_t *)sys_revoke },	/* 56 = revoke */
	{ AS(symlink_args), 4, (sy_call_t *)sys_symlink },	/* 57 = symlink */
	{ AS(readlink_args), 4, (sy_call_t *)sys_readlink },	/* 58 = readlink */
	{ AS(execve_args), 4, (sy_call_t *)sys_execve },	/* 59 = execve */
	{ AS(umask_args), 4, (sy_call_t *)sys_umask },	/* 60 = umask */
	{ AS(chroot_args), 4, (sy_call_t *)sys_chroot },	/* 61 = chroot */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 62 = obsolete old fstat */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 63 = obsolete getkerninfo */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 64 = obsolete getpagesize */
	{ AS(msync_args), 4, (sy_call_t *)sys_msync },	/* 65 = msync */
	{ 0, 4, (sy_call_t *)sys_vfork },			/* 66 = vfork */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 67 = obsolete vread */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 68 = obsolete vwrite */
	{ AS(sbrk_args), 8, (sy_call_t *)sys_sbrk },	/* 69 = sbrk */
	{ AS(sstk_args), 4, (sy_call_t *)sys_sstk },	/* 70 = sstk */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 71 = obsolete old mmap */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 72 = obsolete vadvise */
	{ AS(munmap_args), 4, (sy_call_t *)sys_munmap },	/* 73 = munmap */
	{ AS(mprotect_args), 4, (sy_call_t *)sys_mprotect },	/* 74 = mprotect */
	{ AS(madvise_args), 4, (sy_call_t *)sys_madvise },	/* 75 = madvise */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 76 = obsolete vhangup */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 77 = obsolete vlimit */
	{ AS(mincore_args), 4, (sy_call_t *)sys_mincore },	/* 78 = mincore */
	{ AS(getgroups_args), 4, (sy_call_t *)sys_getgroups },	/* 79 = getgroups */
	{ AS(setgroups_args), 4, (sy_call_t *)sys_setgroups },	/* 80 = setgroups */
	{ 0, 4, (sy_call_t *)sys_getpgrp },		/* 81 = getpgrp */
	{ AS(setpgid_args), 4, (sy_call_t *)sys_setpgid },	/* 82 = setpgid */
	{ AS(setitimer_args), 4, (sy_call_t *)sys_setitimer },	/* 83 = setitimer */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 84 = obsolete wait */
	{ AS(swapon_args), 4, (sy_call_t *)sys_swapon },	/* 85 = swapon */
	{ AS(getitimer_args), 4, (sy_call_t *)sys_getitimer },	/* 86 = getitimer */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 87 = obsolete gethostname */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 88 = obsolete sethostname */
	{ 0, 4, (sy_call_t *)sys_getdtablesize },		/* 89 = getdtablesize */
	{ AS(dup2_args), 4, (sy_call_t *)sys_dup2 },	/* 90 = dup2 */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 91 = getdopt */
	{ AS(fcntl_args), 4, (sy_call_t *)sys_fcntl },	/* 92 = fcntl */
	{ AS(select_args), 4, (sy_call_t *)sys_select },	/* 93 = select */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 94 = setdopt */
	{ AS(fsync_args), 4, (sy_call_t *)sys_fsync },	/* 95 = fsync */
	{ AS(setpriority_args), 4, (sy_call_t *)sys_setpriority },	/* 96 = setpriority */
	{ AS(socket_args), 4, (sy_call_t *)sys_socket },	/* 97 = socket */
	{ AS(connect_args), 4, (sy_call_t *)sys_connect },	/* 98 = connect */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 99 = obsolete old accept */
	{ AS(getpriority_args), 4, (sy_call_t *)sys_getpriority },	/* 100 = getpriority */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 101 = obsolete send */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 102 = obsolete recv */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 103 = obsolete freebsd3_sigreturn */
	{ AS(bind_args), 4, (sy_call_t *)sys_bind },	/* 104 = bind */
	{ AS(setsockopt_args), 4, (sy_call_t *)sys_setsockopt },	/* 105 = setsockopt */
	{ AS(listen_args), 4, (sy_call_t *)sys_listen },	/* 106 = listen */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 107 = obsolete vtimes */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 108 = obsolete 4.3 sigvec */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 109 = obsolete 4.3 sigblock */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 110 = obsolete 4.3 sigsetmask */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 111 = obsolete freebsd3_sigsuspend */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 112 = obsolete sigstack */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 113 = obsolete old recvmsg */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 114 = obsolete old sendmsg */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 115 = obsolete vtrace */
	{ AS(gettimeofday_args), 4, (sy_call_t *)sys_gettimeofday },	/* 116 = gettimeofday */
	{ AS(getrusage_args), 4, (sy_call_t *)sys_getrusage },	/* 117 = getrusage */
	{ AS(getsockopt_args), 4, (sy_call_t *)sys_getsockopt },	/* 118 = getsockopt */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 119 = resuba */
	{ AS(readv_args), 4, (sy_call_t *)sys_readv },	/* 120 = readv */
	{ AS(writev_args), 4, (sy_call_t *)sys_writev },	/* 121 = writev */
	{ AS(settimeofday_args), 4, (sy_call_t *)sys_settimeofday },	/* 122 = settimeofday */
	{ AS(fchown_args), 4, (sy_call_t *)sys_fchown },	/* 123 = fchown */
	{ AS(fchmod_args), 4, (sy_call_t *)sys_fchmod },	/* 124 = fchmod */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 125 = obsolete old recvfrom */
	{ AS(setreuid_args), 4, (sy_call_t *)sys_setreuid },	/* 126 = setreuid */
	{ AS(setregid_args), 4, (sy_call_t *)sys_setregid },	/* 127 = setregid */
	{ AS(rename_args), 4, (sy_call_t *)sys_rename },	/* 128 = rename */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 129 = obsolete old truncate */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 130 = obsolete old ftruncate */
	{ AS(flock_args), 4, (sy_call_t *)sys_flock },	/* 131 = flock */
	{ AS(mkfifo_args), 4, (sy_call_t *)sys_mkfifo },	/* 132 = mkfifo */
	{ AS(sendto_args), 4, (sy_call_t *)sys_sendto },	/* 133 = sendto */
	{ AS(shutdown_args), 4, (sy_call_t *)sys_shutdown },	/* 134 = shutdown */
	{ AS(socketpair_args), 4, (sy_call_t *)sys_socketpair },	/* 135 = socketpair */
	{ AS(mkdir_args), 4, (sy_call_t *)sys_mkdir },	/* 136 = mkdir */
	{ AS(rmdir_args), 4, (sy_call_t *)sys_rmdir },	/* 137 = rmdir */
	{ AS(utimes_args), 4, (sy_call_t *)sys_utimes },	/* 138 = utimes */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 139 = obsolete 4.2 sigreturn */
	{ AS(adjtime_args), 4, (sy_call_t *)sys_adjtime },	/* 140 = adjtime */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 141 = obsolete old getpeername */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 142 = obsolete 4.3 gethostid */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 143 = obsolete 4.3 sethostid */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 144 = obsolete old getrlimit */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 145 = obsolete old setrlimit */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 146 = obsolete 4.3 killpg */
	{ 0, 4, (sy_call_t *)sys_setsid },			/* 147 = setsid */
	{ AS(quotactl_args), 4, (sy_call_t *)sys_quotactl },	/* 148 = quotactl */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 149 = obsolete quota */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 150 = obsolete old getsockname */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 151 = sem_lock */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 152 = sem_wakeup */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 153 = asyncdaemon */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 154 = nosys */
	{ AS(nfssvc_args), 4, (sy_call_t *)sys_nosys },	/* 155 = nfssvc */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 156 = obsolete old getdirentries */
	{ AS(statfs_args), 4, (sy_call_t *)sys_statfs },	/* 157 = statfs */
	{ AS(fstatfs_args), 4, (sy_call_t *)sys_fstatfs },	/* 158 = fstatfs */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 159 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 160 = nosys */
	{ AS(getfh_args), 4, (sy_call_t *)sys_getfh },	/* 161 = getfh */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 162 = obsolete getdomainname */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 163 = obsolete setdomainname */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 164 = obsolete uname */
	{ AS(sysarch_args), 4, (sy_call_t *)sys_sysarch },	/* 165 = sysarch */
	{ AS(rtprio_args), 4, (sy_call_t *)sys_rtprio },	/* 166 = rtprio */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 167 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 168 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 169 = obsolete semsys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 170 = obsolete msgsys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 171 = obsolete shmsys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 172 = nosys */
	{ AS(extpread_args), 8, (sy_call_t *)sys_extpread },	/* 173 = extpread */
	{ AS(extpwrite_args), 8, (sy_call_t *)sys_extpwrite },	/* 174 = extpwrite */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 175 = nosys */
	{ AS(ntp_adjtime_args), 4, (sy_call_t *)sys_ntp_adjtime },	/* 176 = ntp_adjtime */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 177 = sfork */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 178 = getdescriptor */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 179 = setdescriptor */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 180 = nosys */
	{ AS(setgid_args), 4, (sy_call_t *)sys_setgid },	/* 181 = setgid */
	{ AS(setegid_args), 4, (sy_call_t *)sys_setegid },	/* 182 = setegid */
	{ AS(seteuid_args), 4, (sy_call_t *)sys_seteuid },	/* 183 = seteuid */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 184 = lfs_bmapv */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 185 = lfs_markv */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 186 = lfs_segclean */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 187 = lfs_segwait */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 188 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 189 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 190 = nosys */
	{ AS(pathconf_args), 4, (sy_call_t *)sys_pathconf },	/* 191 = pathconf */
	{ AS(fpathconf_args), 4, (sy_call_t *)sys_fpathconf },	/* 192 = fpathconf */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 193 = nosys */
	{ AS(__getrlimit_args), 4, (sy_call_t *)sys_getrlimit },	/* 194 = getrlimit */
	{ AS(__setrlimit_args), 4, (sy_call_t *)sys_setrlimit },	/* 195 = setrlimit */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 196 = nosys */
	{ AS(mmap_args), 8, (sy_call_t *)sys_mmap },	/* 197 = mmap */
	{ 0, 4, (sy_call_t *)sys_xsyscall },		/* 198 = __syscall */
	{ AS(lseek_args), 8, (sy_call_t *)sys_lseek },	/* 199 = lseek */
	{ AS(truncate_args), 4, (sy_call_t *)sys_truncate },	/* 200 = truncate */
	{ AS(ftruncate_args), 4, (sy_call_t *)sys_ftruncate },	/* 201 = ftruncate */
	{ AS(sysctl_args), 4, (sy_call_t *)sys___sysctl },	/* 202 = __sysctl */
	{ AS(mlock_args), 4, (sy_call_t *)sys_mlock },	/* 203 = mlock */
	{ AS(munlock_args), 4, (sy_call_t *)sys_munlock },	/* 204 = munlock */
	{ AS(undelete_args), 4, (sy_call_t *)sys_undelete },	/* 205 = undelete */
	{ AS(futimes_args), 4, (sy_call_t *)sys_futimes },	/* 206 = futimes */
	{ AS(getpgid_args), 4, (sy_call_t *)sys_getpgid },	/* 207 = getpgid */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 208 = newreboot */
	{ AS(poll_args), 4, (sy_call_t *)sys_poll },	/* 209 = poll */
	{ AS(nosys_args), 4, (sy_call_t *)sys_lkmnosys },	/* 210 = lkmnosys */
	{ AS(nosys_args), 4, (sy_call_t *)sys_lkmnosys },	/* 211 = lkmnosys */
	{ AS(nosys_args), 4, (sy_call_t *)sys_lkmnosys },	/* 212 = lkmnosys */
	{ AS(nosys_args), 4, (sy_call_t *)sys_lkmnosys },	/* 213 = lkmnosys */
	{ AS(nosys_args), 4, (sy_call_t *)sys_lkmnosys },	/* 214 = lkmnosys */
	{ AS(nosys_args), 4, (sy_call_t *)sys_lkmnosys },	/* 215 = lkmnosys */
	{ AS(nosys_args), 4, (sy_call_t *)sys_lkmnosys },	/* 216 = lkmnosys */
	{ AS(nosys_args), 4, (sy_call_t *)sys_lkmnosys },	/* 217 = lkmnosys */
	{ AS(nosys_args), 4, (sy_call_t *)sys_lkmnosys },	/* 218 = lkmnosys */
	{ AS(nosys_args), 4, (sy_call_t *)sys_lkmnosys },	/* 219 = lkmnosys */
	{ AS(__semctl_args), 4, (sy_call_t *)sys___semctl },	/* 220 = __semctl */
	{ AS(semget_args), 4, (sy_call_t *)sys_semget },	/* 221 = semget */
	{ AS(semop_args), 4, (sy_call_t *)sys_semop },	/* 222 = semop */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 223 = semconfig */
	{ AS(msgctl_args), 4, (sy_call_t *)sys_msgctl },	/* 224 = msgctl */
	{ AS(msgget_args), 4, (sy_call_t *)sys_msgget },	/* 225 = msgget */
	{ AS(msgsnd_args), 4, (sy_call_t *)sys_msgsnd },	/* 226 = msgsnd */
	{ AS(msgrcv_args), 4, (sy_call_t *)sys_msgrcv },	/* 227 = msgrcv */
	{ AS(shmat_args), 8, (sy_call_t *)sys_shmat },	/* 228 = shmat */
	{ AS(shmctl_args), 4, (sy_call_t *)sys_shmctl },	/* 229 = shmctl */
	{ AS(shmdt_args), 4, (sy_call_t *)sys_shmdt },	/* 230 = shmdt */
	{ AS(shmget_args), 4, (sy_call_t *)sys_shmget },	/* 231 = shmget */
	{ AS(clock_gettime_args), 4, (sy_call_t *)sys_clock_gettime },	/* 232 = clock_gettime */
	{ AS(clock_settime_args), 4, (sy_call_t *)sys_clock_settime },	/* 233 = clock_settime */
	{ AS(clock_getres_args), 4, (sy_call_t *)sys_clock_getres },	/* 234 = clock_getres */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 235 = timer_create */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 236 = timer_delete */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 237 = timer_settime */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 238 = timer_gettime */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 239 = timer_getoverrun */
	{ AS(nanosleep_args), 4, (sy_call_t *)sys_nanosleep },	/* 240 = nanosleep */
	{ AS(clock_nanosleep_args), 4, (sy_call_t *)sys_clock_nanosleep },	/* 241 = clock_nanosleep */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 242 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 243 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 244 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 245 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 246 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 247 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 248 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 249 = nosys */
	{ AS(minherit_args), 4, (sy_call_t *)sys_minherit },	/* 250 = minherit */
	{ AS(rfork_args), 4, (sy_call_t *)sys_rfork },	/* 251 = rfork */
	{ AS(openbsd_poll_args), 4, (sy_call_t *)sys_openbsd_poll },	/* 252 = openbsd_poll */
	{ 0, 4, (sy_call_t *)sys_issetugid },		/* 253 = issetugid */
	{ AS(lchown_args), 4, (sy_call_t *)sys_lchown },	/* 254 = lchown */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 255 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 256 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 257 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 258 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 259 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 260 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 261 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 262 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 263 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 264 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 265 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 266 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 267 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 268 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 269 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 270 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 271 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 272 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 273 = nosys */
	{ AS(lchmod_args), 4, (sy_call_t *)sys_lchmod },	/* 274 = lchmod */
	{ AS(lchown_args), 4, (sy_call_t *)sys_lchown },	/* 275 = netbsd_lchown */
	{ AS(lutimes_args), 4, (sy_call_t *)sys_lutimes },	/* 276 = lutimes */
	{ AS(msync_args), 4, (sy_call_t *)sys_msync },	/* 277 = netbsd_msync */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 278 = obsolete nstat */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 279 = obsolete nfstat */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 280 = obsolete nlstat */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 281 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 282 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 283 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 284 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 285 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 286 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 287 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 288 = nosys */
	{ AS(extpreadv_args), 8, (sy_call_t *)sys_extpreadv },	/* 289 = extpreadv */
	{ AS(extpwritev_args), 8, (sy_call_t *)sys_extpwritev },	/* 290 = extpwritev */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 291 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 292 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 293 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 294 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 295 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 296 = nosys */
	{ AS(fhstatfs_args), 4, (sy_call_t *)sys_fhstatfs },	/* 297 = fhstatfs */
	{ AS(fhopen_args), 4, (sy_call_t *)sys_fhopen },	/* 298 = fhopen */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 299 = nosys */
	{ AS(modnext_args), 4, (sy_call_t *)sys_modnext },	/* 300 = modnext */
	{ AS(modstat_args), 4, (sy_call_t *)sys_modstat },	/* 301 = modstat */
	{ AS(modfnext_args), 4, (sy_call_t *)sys_modfnext },	/* 302 = modfnext */
	{ AS(modfind_args), 4, (sy_call_t *)sys_modfind },	/* 303 = modfind */
	{ AS(kldload_args), 4, (sy_call_t *)sys_kldload },	/* 304 = kldload */
	{ AS(kldunload_args), 4, (sy_call_t *)sys_kldunload },	/* 305 = kldunload */
	{ AS(kldfind_args), 4, (sy_call_t *)sys_kldfind },	/* 306 = kldfind */
	{ AS(kldnext_args), 4, (sy_call_t *)sys_kldnext },	/* 307 = kldnext */
	{ AS(kldstat_args), 4, (sy_call_t *)sys_kldstat },	/* 308 = kldstat */
	{ AS(kldfirstmod_args), 4, (sy_call_t *)sys_kldfirstmod },	/* 309 = kldfirstmod */
	{ AS(getsid_args), 4, (sy_call_t *)sys_getsid },	/* 310 = getsid */
	{ AS(setresuid_args), 4, (sy_call_t *)sys_setresuid },	/* 311 = setresuid */
	{ AS(setresgid_args), 4, (sy_call_t *)sys_setresgid },	/* 312 = setresgid */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 313 = obsolete signanosleep */
	{ AS(aio_return_args), 4, (sy_call_t *)sys_aio_return },	/* 314 = aio_return */
	{ AS(aio_suspend_args), 4, (sy_call_t *)sys_aio_suspend },	/* 315 = aio_suspend */
	{ AS(aio_cancel_args), 4, (sy_call_t *)sys_aio_cancel },	/* 316 = aio_cancel */
	{ AS(aio_error_args), 4, (sy_call_t *)sys_aio_error },	/* 317 = aio_error */
	{ AS(aio_read_args), 4, (sy_call_t *)sys_aio_read },	/* 318 = aio_read */
	{ AS(aio_write_args), 4, (sy_call_t *)sys_aio_write },	/* 319 = aio_write */
	{ AS(lio_listio_args), 4, (sy_call_t *)sys_lio_listio },	/* 320 = lio_listio */
	{ 0, 4, (sy_call_t *)sys_yield },			/* 321 = yield */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 322 = thr_sleep */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 323 = thr_wakeup */
	{ AS(mlockall_args), 4, (sy_call_t *)sys_mlockall },	/* 324 = mlockall */
	{ 0, 4, (sy_call_t *)sys_munlockall },		/* 325 = munlockall */
	{ AS(__getcwd_args), 4, (sy_call_t *)sys___getcwd },	/* 326 = __getcwd */
	{ AS(sched_setparam_args), 4, (sy_call_t *)sys_sched_setparam },	/* 327 = sched_setparam */
	{ AS(sched_getparam_args), 4, (sy_call_t *)sys_sched_getparam },	/* 328 = sched_getparam */
	{ AS(sched_setscheduler_args), 4, (sy_call_t *)sys_sched_setscheduler },	/* 329 = sched_setscheduler */
	{ AS(sched_getscheduler_args), 4, (sy_call_t *)sys_sched_getscheduler },	/* 330 = sched_getscheduler */
	{ 0, 4, (sy_call_t *)sys_sched_yield },		/* 331 = sched_yield */
	{ AS(sched_get_priority_max_args), 4, (sy_call_t *)sys_sched_get_priority_max },	/* 332 = sched_get_priority_max */
	{ AS(sched_get_priority_min_args), 4, (sy_call_t *)sys_sched_get_priority_min },	/* 333 = sched_get_priority_min */
	{ AS(sched_rr_get_interval_args), 4, (sy_call_t *)sys_sched_rr_get_interval },	/* 334 = sched_rr_get_interval */
	{ AS(utrace_args), 4, (sy_call_t *)sys_utrace },	/* 335 = utrace */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 336 = obsolete freebsd4_sendfile */
	{ AS(kldsym_args), 4, (sy_call_t *)sys_kldsym },	/* 337 = kldsym */
	{ AS(jail_args), 4, (sy_call_t *)sys_jail },	/* 338 = jail */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 339 = pioctl */
	{ AS(sigprocmask_args), 4, (sy_call_t *)sys_sigprocmask },	/* 340 = sigprocmask */
	{ AS(sigsuspend_args), 4, (sy_call_t *)sys_sigsuspend },	/* 341 = sigsuspend */
	{ AS(sigaction_args), 4, (sy_call_t *)sys_sigaction },	/* 342 = sigaction */
	{ AS(sigpending_args), 4, (sy_call_t *)sys_sigpending },	/* 343 = sigpending */
	{ AS(sigreturn_args), 4, (sy_call_t *)sys_sigreturn },	/* 344 = sigreturn */
	{ AS(sigtimedwait_args), 4, (sy_call_t *)sys_sigtimedwait },	/* 345 = sigtimedwait */
	{ AS(sigwaitinfo_args), 4, (sy_call_t *)sys_sigwaitinfo },	/* 346 = sigwaitinfo */
	{ AS(__acl_get_file_args), 4, (sy_call_t *)sys___acl_get_file },	/* 347 = __acl_get_file */
	{ AS(__acl_set_file_args), 4, (sy_call_t *)sys___acl_set_file },	/* 348 = __acl_set_file */
	{ AS(__acl_get_fd_args), 4, (sy_call_t *)sys___acl_get_fd },	/* 349 = __acl_get_fd */
	{ AS(__acl_set_fd_args), 4, (sy_call_t *)sys___acl_set_fd },	/* 350 = __acl_set_fd */
	{ AS(__acl_delete_file_args), 4, (sy_call_t *)sys___acl_delete_file },	/* 351 = __acl_delete_file */
	{ AS(__acl_delete_fd_args), 4, (sy_call_t *)sys___acl_delete_fd },	/* 352 = __acl_delete_fd */
	{ AS(__acl_aclcheck_file_args), 4, (sy_call_t *)sys___acl_aclcheck_file },	/* 353 = __acl_aclcheck_file */
	{ AS(__acl_aclcheck_fd_args), 4, (sy_call_t *)sys___acl_aclcheck_fd },	/* 354 = __acl_aclcheck_fd */
	{ AS(extattrctl_args), 4, (sy_call_t *)sys_extattrctl },	/* 355 = extattrctl */
	{ AS(extattr_set_file_args), 4, (sy_call_t *)sys_extattr_set_file },	/* 356 = extattr_set_file */
	{ AS(extattr_get_file_args), 4, (sy_call_t *)sys_extattr_get_file },	/* 357 = extattr_get_file */
	{ AS(extattr_delete_file_args), 4, (sy_call_t *)sys_extattr_delete_file },	/* 358 = extattr_delete_file */
	{ AS(aio_waitcomplete_args), 4, (sy_call_t *)sys_aio_waitcomplete },	/* 359 = aio_waitcomplete */
	{ AS(getresuid_args), 4, (sy_call_t *)sys_getresuid },	/* 360 = getresuid */
	{ AS(getresgid_args), 4, (sy_call_t *)sys_getresgid },	/* 361 = getresgid */
	{ 0, 4, (sy_call_t *)sys_kqueue },			/* 362 = kqueue */
	{ AS(kevent_args), 4, (sy_call_t *)sys_kevent },	/* 363 = kevent */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 364 = sctp_peeloff */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 365 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 366 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 367 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 368 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 369 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 370 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 371 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 372 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 373 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 374 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 375 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 376 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 377 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 378 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 379 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 380 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 381 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 382 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 383 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 384 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 385 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 386 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 387 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 388 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 389 = nosys */
	{ AS(kenv_args), 4, (sy_call_t *)sys_kenv },	/* 390 = kenv */
	{ AS(lchflags_args), 4, (sy_call_t *)sys_lchflags },	/* 391 = lchflags */
	{ AS(uuidgen_args), 4, (sy_call_t *)sys_uuidgen },	/* 392 = uuidgen */
	{ AS(sendfile_args), 4, (sy_call_t *)sys_sendfile },	/* 393 = sendfile */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 394 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 395 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 396 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 397 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 398 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 399 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 400 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 401 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 402 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 403 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 404 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 405 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 406 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 407 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 408 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 409 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 410 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 411 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 412 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 413 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 414 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 415 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 416 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 417 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 418 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 419 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 420 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 421 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 422 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 423 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 424 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 425 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 426 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 427 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 428 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 429 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 430 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 431 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 432 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 433 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 434 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 435 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 436 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 437 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 438 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 439 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 440 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 441 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 442 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 443 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 444 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 445 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 446 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 447 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 448 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 449 = nosys */
	{ AS(varsym_set_args), 4, (sy_call_t *)sys_varsym_set },	/* 450 = varsym_set */
	{ AS(varsym_get_args), 4, (sy_call_t *)sys_varsym_get },	/* 451 = varsym_get */
	{ AS(varsym_list_args), 4, (sy_call_t *)sys_varsym_list },	/* 452 = varsym_list */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 453 = obsolete upc_register */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 454 = obsolete upc_control */
	{ AS(syscap_get_args), 4, (sy_call_t *)sys_syscap_get },	/* 455 = syscap_get */
	{ AS(syscap_set_args), 4, (sy_call_t *)sys_syscap_set },	/* 456 = syscap_set */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 457 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 458 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 459 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 460 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 461 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 462 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 463 = nosys */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 464 = nosys */
	{ AS(exec_sys_register_args), 4, (sy_call_t *)sys_exec_sys_register },	/* 465 = exec_sys_register */
	{ AS(exec_sys_unregister_args), 4, (sy_call_t *)sys_exec_sys_unregister },	/* 466 = exec_sys_unregister */
	{ AS(sys_checkpoint_args), 4, (sy_call_t *)sys_sys_checkpoint },	/* 467 = sys_checkpoint */
	{ AS(mountctl_args), 4, (sy_call_t *)sys_mountctl },	/* 468 = mountctl */
	{ AS(umtx_sleep_args), 4, (sy_call_t *)sys_umtx_sleep },	/* 469 = umtx_sleep */
	{ AS(umtx_wakeup_args), 4, (sy_call_t *)sys_umtx_wakeup },	/* 470 = umtx_wakeup */
	{ AS(jail_attach_args), 4, (sy_call_t *)sys_jail_attach },	/* 471 = jail_attach */
	{ AS(set_tls_area_args), 4, (sy_call_t *)sys_set_tls_area },	/* 472 = set_tls_area */
	{ AS(get_tls_area_args), 4, (sy_call_t *)sys_get_tls_area },	/* 473 = get_tls_area */
	{ AS(closefrom_args), 4, (sy_call_t *)sys_closefrom },	/* 474 = closefrom */
	{ AS(stat_args), 4, (sy_call_t *)sys_stat },	/* 475 = stat */
	{ AS(fstat_args), 4, (sy_call_t *)sys_fstat },	/* 476 = fstat */
	{ AS(lstat_args), 4, (sy_call_t *)sys_lstat },	/* 477 = lstat */
	{ AS(fhstat_args), 4, (sy_call_t *)sys_fhstat },	/* 478 = fhstat */
	{ AS(getdirentries_args), 4, (sy_call_t *)sys_getdirentries },	/* 479 = getdirentries */
	{ AS(getdents_args), 4, (sy_call_t *)sys_getdents },	/* 480 = getdents */
	{ AS(usched_set_args), 4, (sy_call_t *)sys_usched_set },	/* 481 = usched_set */
	{ AS(extaccept_args), 4, (sy_call_t *)sys_extaccept },	/* 482 = extaccept */
	{ AS(extconnect_args), 4, (sy_call_t *)sys_extconnect },	/* 483 = extconnect */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 484 = obsolete syslink */
	{ AS(mcontrol_args), 4, (sy_call_t *)sys_mcontrol },	/* 485 = mcontrol */
	{ AS(vmspace_create_args), 4, (sy_call_t *)sys_vmspace_create },	/* 486 = vmspace_create */
	{ AS(vmspace_destroy_args), 4, (sy_call_t *)sys_vmspace_destroy },	/* 487 = vmspace_destroy */
	{ AS(vmspace_ctl_args), 4, (sy_call_t *)sys_vmspace_ctl },	/* 488 = vmspace_ctl */
	{ AS(vmspace_mmap_args), 4, (sy_call_t *)sys_vmspace_mmap },	/* 489 = vmspace_mmap */
	{ AS(vmspace_munmap_args), 4, (sy_call_t *)sys_vmspace_munmap },	/* 490 = vmspace_munmap */
	{ AS(vmspace_mcontrol_args), 4, (sy_call_t *)sys_vmspace_mcontrol },	/* 491 = vmspace_mcontrol */
	{ AS(vmspace_pread_args), 8, (sy_call_t *)sys_vmspace_pread },	/* 492 = vmspace_pread */
	{ AS(vmspace_pwrite_args), 8, (sy_call_t *)sys_vmspace_pwrite },	/* 493 = vmspace_pwrite */
	{ AS(extexit_args), 4, (sy_call_t *)sys_extexit },	/* 494 = extexit */
	{ AS(lwp_create_args), 4, (sy_call_t *)sys_lwp_create },	/* 495 = lwp_create */
	{ 0, 4, (sy_call_t *)sys_lwp_gettid },		/* 496 = lwp_gettid */
	{ AS(lwp_kill_args), 4, (sy_call_t *)sys_lwp_kill },	/* 497 = lwp_kill */
	{ AS(lwp_rtprio_args), 4, (sy_call_t *)sys_lwp_rtprio },	/* 498 = lwp_rtprio */
	{ AS(pselect_args), 4, (sy_call_t *)sys_pselect },	/* 499 = pselect */
	{ AS(statvfs_args), 4, (sy_call_t *)sys_statvfs },	/* 500 = statvfs */
	{ AS(fstatvfs_args), 4, (sy_call_t *)sys_fstatvfs },	/* 501 = fstatvfs */
	{ AS(fhstatvfs_args), 4, (sy_call_t *)sys_fhstatvfs },	/* 502 = fhstatvfs */
	{ AS(getvfsstat_args), 4, (sy_call_t *)sys_getvfsstat },	/* 503 = getvfsstat */
	{ AS(openat_args), 4, (sy_call_t *)sys_openat },	/* 504 = openat */
	{ AS(fstatat_args), 4, (sy_call_t *)sys_fstatat },	/* 505 = fstatat */
	{ AS(fchmodat_args), 4, (sy_call_t *)sys_fchmodat },	/* 506 = fchmodat */
	{ AS(fchownat_args), 4, (sy_call_t *)sys_fchownat },	/* 507 = fchownat */
	{ AS(unlinkat_args), 4, (sy_call_t *)sys_unlinkat },	/* 508 = unlinkat */
	{ AS(faccessat_args), 4, (sy_call_t *)sys_faccessat },	/* 509 = faccessat */
	{ AS(mq_open_args), 4, (sy_call_t *)sys_mq_open },	/* 510 = mq_open */
	{ AS(mq_close_args), 4, (sy_call_t *)sys_mq_close },	/* 511 = mq_close */
	{ AS(mq_unlink_args), 4, (sy_call_t *)sys_mq_unlink },	/* 512 = mq_unlink */
	{ AS(mq_getattr_args), 4, (sy_call_t *)sys_mq_getattr },	/* 513 = mq_getattr */
	{ AS(mq_setattr_args), 4, (sy_call_t *)sys_mq_setattr },	/* 514 = mq_setattr */
	{ AS(mq_notify_args), 4, (sy_call_t *)sys_mq_notify },	/* 515 = mq_notify */
	{ AS(mq_send_args), 4, (sy_call_t *)sys_mq_send },	/* 516 = mq_send */
	{ AS(mq_receive_args), 8, (sy_call_t *)sys_mq_receive },	/* 517 = mq_receive */
	{ AS(mq_timedsend_args), 4, (sy_call_t *)sys_mq_timedsend },	/* 518 = mq_timedsend */
	{ AS(mq_timedreceive_args), 8, (sy_call_t *)sys_mq_timedreceive },	/* 519 = mq_timedreceive */
	{ AS(ioprio_set_args), 4, (sy_call_t *)sys_ioprio_set },	/* 520 = ioprio_set */
	{ AS(ioprio_get_args), 4, (sy_call_t *)sys_ioprio_get },	/* 521 = ioprio_get */
	{ AS(chroot_kernel_args), 4, (sy_call_t *)sys_chroot_kernel },	/* 522 = chroot_kernel */
	{ AS(renameat_args), 4, (sy_call_t *)sys_renameat },	/* 523 = renameat */
	{ AS(mkdirat_args), 4, (sy_call_t *)sys_mkdirat },	/* 524 = mkdirat */
	{ AS(mkfifoat_args), 4, (sy_call_t *)sys_mkfifoat },	/* 525 = mkfifoat */
	{ AS(mknodat_args), 4, (sy_call_t *)sys_mknodat },	/* 526 = mknodat */
	{ AS(readlinkat_args), 4, (sy_call_t *)sys_readlinkat },	/* 527 = readlinkat */
	{ AS(symlinkat_args), 4, (sy_call_t *)sys_symlinkat },	/* 528 = symlinkat */
	{ AS(swapoff_args), 4, (sy_call_t *)sys_swapoff },	/* 529 = swapoff */
	{ AS(vquotactl_args), 4, (sy_call_t *)sys_vquotactl },	/* 530 = vquotactl */
	{ AS(linkat_args), 4, (sy_call_t *)sys_linkat },	/* 531 = linkat */
	{ AS(eaccess_args), 4, (sy_call_t *)sys_eaccess },	/* 532 = eaccess */
	{ AS(lpathconf_args), 4, (sy_call_t *)sys_lpathconf },	/* 533 = lpathconf */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 534 = obsolete vmm_guest_ctl */
	{ 0, 4, (sy_call_t *)sys_nosys },			/* 535 = obsolete vmm_guest_sync_addr */
	{ AS(procctl_args), 4, (sy_call_t *)sys_procctl },	/* 536 = procctl */
	{ AS(chflagsat_args), 4, (sy_call_t *)sys_chflagsat },	/* 537 = chflagsat */
	{ AS(pipe2_args), 4, (sy_call_t *)sys_pipe2 },	/* 538 = pipe2 */
	{ AS(utimensat_args), 4, (sy_call_t *)sys_utimensat },	/* 539 = utimensat */
	{ AS(futimens_args), 4, (sy_call_t *)sys_futimens },	/* 540 = futimens */
	{ AS(accept4_args), 4, (sy_call_t *)sys_accept4 },	/* 541 = accept4 */
	{ AS(lwp_setname_args), 4, (sy_call_t *)sys_lwp_setname },	/* 542 = lwp_setname */
	{ AS(ppoll_args), 4, (sy_call_t *)sys_ppoll },	/* 543 = ppoll */
	{ AS(lwp_setaffinity_args), 4, (sy_call_t *)sys_lwp_setaffinity },	/* 544 = lwp_setaffinity */
	{ AS(lwp_getaffinity_args), 4, (sy_call_t *)sys_lwp_getaffinity },	/* 545 = lwp_getaffinity */
	{ AS(lwp_create2_args), 4, (sy_call_t *)sys_lwp_create2 },	/* 546 = lwp_create2 */
	{ AS(getcpuclockid_args), 4, (sy_call_t *)sys_getcpuclockid },	/* 547 = getcpuclockid */
	{ AS(wait6_args), 4, (sy_call_t *)sys_wait6 },	/* 548 = wait6 */
	{ AS(lwp_getname_args), 4, (sy_call_t *)sys_lwp_getname },	/* 549 = lwp_getname */
	{ AS(getrandom_args), 8, (sy_call_t *)sys_getrandom },	/* 550 = getrandom */
	{ AS(__realpath_args), 8, (sy_call_t *)sys___realpath },	/* 551 = __realpath */
	{ AS(fexecve_args), 4, (sy_call_t *)sys_fexecve },	/* 552 = fexecve */
	{ AS(posix_fallocate_args), 4, (sy_call_t *)sys_posix_fallocate },	/* 553 = posix_fallocate */
	{ AS(fdatasync_args), 4, (sy_call_t *)sys_fdatasync },	/* 554 = fdatasync */
};
