# $FreeBSD: src/sys/boot/sparc64/Makefile,v 1.2 2002/03/28 01:41:23 obrien Exp $
# $DragonFly: src/sys/boot/sparc64/Makefile,v 1.1 2003/11/10 06:08:40 dillon Exp $

SUBDIR=	boot1 loader

.include <bsd.subdir.mk>
