#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/number/Makefile,v 1.2.6.1 2001/04/25 09:28:59 ru Exp $
# $DragonFly: src/games/number/Makefile,v 1.4 2006/10/08 16:22:36 pavalos Exp $

PROG=	number
MAN=	number.6

.include <bsd.prog.mk>
