.ig
Copyright (C) 1989, 2001, 2009
  Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.
.TH MMROFF @MAN1EXT@ "@MDATE@" "Groff Version @VERSION@"
.SH NAME
mmroff \- reference preprocessor
.SH SYNOPSIS
.B mmroff
[
.I -x
]
.I groff_arguments
.SH DESCRIPTION
\fBmmroff\fP is a simple preprocessor for \fBgroff\fP, it is
used for expanding references in \fBm@TMAC_M_PREFIX@m\fP, see
\fBgroff_mm(@MAN7EXT@)\fP.
\fBgroff\fP is executed twice, first with \fB-z\fP and \fB-rRef=1\fR
to collect all references and then to do the real processing
when the reference file is up to date.
.TP
\fB\-x\fR
Just create the reference file. This can be used to refresh
the reference file, it isn't always needed to have accurate
references and by using this option \fBgroff\fP will only
be run once.
.\".SH BUGS
.SH AUTHOR
J\[:o]rgen H\[:a]gg, Lund, Sweden <jh@axis.se>.
.SH FILES
.TP
.B @MACRODIR@/@TMAC_M_PREFIX@m.tmac
.TP
.B @TMAC_MDIR@/*.cov
.TP
.B @TMAC_MDIR@/*.MT
.TP
.B @TMAC_MDIR@/locale
.SH "SEE ALSO"
.BR groff_mm(@MAN7EXT@),
.BR groff_mmse(@MAN7EXT@),
.BR groff (@MAN1EXT@),
.BR @g@troff (@MAN1EXT@),
.BR @g@tbl (@MAN1EXT@),
.BR @g@pic (@MAN1EXT@),
.BR @g@eqn (@MAN1EXT@)
.
.\" Local Variables:
.\" mode: nroff
.\" End:
