# $FreeBSD: src/sys/modules/bktr/Makefile.inc,v 1.1.2.1 2002/12/01 09:01:08 nyan Exp $
# $DragonFly: src/sys/dev/video/bktr/Attic/Makefile.inc,v 1.3 2003/08/15 08:32:32 dillon Exp $

#.include "../Makefile.inc"
