# $FreeBSD: src/sys/modules/bktr/Makefile.inc,v 1.1.2.1 2002/12/01 09:01:08 nyan Exp $
# $DragonFly: src/sys/dev/video/bktr/Attic/Makefile.inc,v 1.2 2003/06/17 04:28:43 dillon Exp $

.include "../Makefile.inc"
