#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/sbin/shutdown/Makefile,v 1.3.6.2 2001/07/30 10:38:08 dd Exp $
# $DragonFly: src/sbin/shutdown/Makefile,v 1.2 2003/06/17 04:27:34 dillon Exp $

PROG=	shutdown
WARNS?=	2
MAN=	shutdown.8
BINGRP=	operator
BINMODE=4550

.include <bsd.prog.mk>
