# $FreeBSD: src/usr.sbin/pkg_install/update/Makefile,v 1.1.2.2 2001/04/25 14:05:02 ru Exp $
# $DragonFly: src/usr.sbin/pkg_install/update/Attic/Makefile,v 1.2 2003/06/17 04:29:59 dillon Exp $

SCRIPTS=	pkg_update.pl
MAN=		pkg_update.1

.include <bsd.prog.mk>
