# $FreeBSD: src/gnu/lib/libstdc++/doc/Makefile,v 1.7 2002/05/29 21:14:48 obrien Exp $
# $DragonFly: src/gnu/lib/gcc3/libstdc++/doc/Attic/Makefile,v 1.1 2004/01/22 21:45:57 joerg Exp $

SRCDIR= ${.CURDIR}/../../../../../contrib/libstdc++3

.PATH: ${SRCDIR}/../libio

INFO = iostream

INFOENTRY_iostream= "* iostream: (iostream).	The GNU C++ I/O library."

MAKEINFOFLAGS+= -I ${SRCDIR}/../libio 

.include <bsd.info.mk>
