#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/sbin/clri/Makefile,v 1.2.14.2 2001/08/01 05:54:57 obrien Exp $
# $DragonFly: src/sbin/clri/Makefile,v 1.2 2003/06/17 04:27:32 dillon Exp $

PROG=	clri
WARNS?=	2
MAN=	clri.8

.include <bsd.prog.mk>
