# $FreeBSD: src/sys/modules/gx/Makefile,v 1.1.2.2 2001/12/04 20:01:53 brooks Exp $
# $DragonFly: src/sys/dev/netif/gx/Attic/Makefile,v 1.4 2006/06/25 11:02:38 corecode Exp $

KMOD	= if_gx
SRCS	= if_gx.c device_if.h bus_if.h pci_if.h miibus_if.h
KMODDEPS = miibus

.include <bsd.kmod.mk>
