# $FreeBSD: src/usr.bin/whereis/Makefile,v 1.7 2002/12/30 09:48:40 obrien Exp $
# $DragonFly: src/usr.bin/whereis/Makefile,v 1.4 2005/01/03 01:44:56 cpressey Exp $

PROG=	whereis
MAN=	whereis.1
WARNS?=	6

.include <bsd.prog.mk>
