# $FreeBSD: src/usr.bin/whereis/Makefile,v 1.2.8.2 2001/04/25 14:04:39 ru Exp $
# $DragonFly: src/usr.bin/whereis/Makefile,v 1.2 2003/06/17 04:29:33 dillon Exp $

SCRIPTS=whereis.pl
MAN=	whereis.1

.include <bsd.prog.mk>
