# $FreeBSD: src/sbin/adjkerntz/Makefile,v 1.2.14.2 2001/07/30 10:38:04 dd Exp $
# $DragonFly: src/sbin/adjkerntz/Makefile,v 1.4 2006/10/17 00:55:39 pavalos Exp $

PROG=   adjkerntz
MAN=	adjkerntz.8

.include <bsd.prog.mk>
