# $FreeBSD: src/sbin/adjkerntz/Makefile,v 1.2.14.2 2001/07/30 10:38:04 dd Exp $
# $DragonFly: src/sbin/adjkerntz/Makefile,v 1.3 2005/01/17 07:27:45 cpressey Exp $

PROG=   adjkerntz
WARNS?=	6
MAN=	adjkerntz.8

.include <bsd.prog.mk>
