# $FreeBSD: src/sys/modules/ispfw/Makefile,v 1.1.2.1 2000/07/04 02:11:04 mjacob Exp $
# $DragonFly: src/sys/dev/disk/ispfw/Makefile,v 1.2 2003/06/17 04:28:44 dillon Exp $

.PATH:	${.CURDIR}/../../dev/ispfw
KMOD	= ispfw
SRCS	= ispfw.c

.include <bsd.kmod.mk>
