# $FreeBSD: src/usr.sbin/daemon/Makefile,v 1.1.2.1 2002/08/28 17:25:54 sheldonh Exp $
# $DragonFly: src/usr.sbin/daemon/Makefile,v 1.2 2003/06/17 04:29:53 dillon Exp $

PROG=	daemon
WARNS?=	2
MAN=	daemon.8

.include <bsd.prog.mk>
