# $FreeBSD: src/usr.sbin/daemon/Makefile,v 1.1.2.1 2002/08/28 17:25:54 sheldonh Exp $
# $DragonFly: src/usr.sbin/daemon/Makefile,v 1.3 2004/12/21 23:30:57 liamfoy Exp $

PROG=	daemon
WARNS?=	6	
MAN=	daemon.8

.include <bsd.prog.mk>
