#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/fish/Makefile,v 1.4.6.3 2002/02/18 16:02:41 ru Exp $

PROG=	fish
.if !defined(NO_SHARE)
FILES=	fish.instr
.endif
MAN=	fish.6

.include <bsd.prog.mk>
