#
# Build the Handbook with just the content from this chapter.
#
# $DragonFly: doc/en/books/handbook/pkgsrc/Makefile,v 1.1 2006/07/12 04:01:00 justin Exp $
#

CHAPTERS= 	pkgsrc/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
