# $FreeBSD: src/gnu/lib/libstdc++/doc/Makefile,v 1.5 2000/01/03 17:40:47 obrien Exp $
# $DragonFly: src/gnu/lib/gcc2/libstdc++/doc/Attic/Makefile,v 1.1 2004/01/16 07:45:20 dillon Exp $

SRCDIR= ${.CURDIR}/../../../../../contrib/libstdc++

.PATH: ${SRCDIR}/../libio

INFO = iostream

INFOENTRY_iostream= "* iostream: (iostream).	The GNU C++ I/O library."

MAKEINFOFLAGS+= -I ${SRCDIR}/../libio 

.include <bsd.info.mk>
