# $FreeBSD: src/kerberos5/libexec/Makefile,v 1.6 2004/01/30 11:06:48 mr Exp $
# $DragonFly: src/kerberos5/libexec/Makefile,v 1.3 2005/01/16 14:25:46 eirikn Exp $

SUBDIR=	ipropd-master ipropd-slave hprop hpropd kadmind kdc kpasswdd

.include <bsd.subdir.mk>
