# $FreeBSD: src/gnu/usr.bin/groff/man/Makefile,v 1.9 2002/10/11 08:58:14 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/man/Makefile,v 1.3 2005/09/01 20:47:12 asmodai Exp $

MAN=		groff_font.5 groff_out.5 groff_tmac.5
MLINKS=		groff_tmac.5 tmac.5
MAN+=		ditroff.7 groff.7 groff_char.7 groff_diff.7 roff.7
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
