.\"
.\" Copyright (c) 2014 The DragonFly Project.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd April 30, 2014
.Dt ACPIDUMP 8
.Os
.Sh NAME
.Nm acpidump
.Nd obtain system ACPI tables and save in ASCII hex format
.Sh SYNOPSIS
.Nm
.Op Ar option ...
.Sh DESCRIPTION
The following options are supported:
.Bl -tag -width indent
.It Fl a Ar address
Get table via a physical address.
.It Fl b
Dump tables to binary files.
.It Fl c
Dump customized tables.
.It Fl f Ar binary_file
Get table via a binary file.
.It Fl h
Display the help message.
.It Fl \&?
Alias for
.Fl h .
.It Fl n Ar signature
Get table via a name/signature.
.It Fl o Ar file
Redirect output to file.
.It Fl r Ar address
Dump tables from specified RSDP.
.It Fl s
Print table summaries only.
.It Fl v
Display version information.
.It Fl x
Do not use but dump XSDT.
.It Fl x Fl x
Do not use or dump XSDT.
.It Fl z
Verbose mode.
.El
.Sh SEE ALSO
.Xr acpi 4 ,
.Xr acpibin 8 ,
.Xr acpiconf 8 ,
.Xr acpiexec 8 ,
.Xr acpihelp 8 ,
.Xr acpinames 8 ,
.Xr acpixtract 8 ,
.Xr iasl 8
.Pp
.Lk https://acpica.org/documentation/
.Sh AUTHORS
The
.Nm
utility is provided by
.Tn Intel
as part of their
.Sy ACPICA
distribution.
.Pp
This manual page was written by
.An Sascha Wildner .
