# $FreeBSD: src/usr.sbin/acpi/acpidump/Makefile,v 1.7 2003/08/28 03:33:07 njl Exp $
# $DragonFly: src/usr.sbin/acpi/acpidump/Makefile,v 1.1 2004/07/05 00:22:43 dillon Exp $

PROG=	acpidump
MAN=	acpidump.8
SRCS=	acpi.c acpi_user.c acpidump.c
WARNS?=	6

.include <bsd.prog.mk>
