#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/last/Makefile,v 1.1.1.1.14.2 2001/08/01 23:54:27 obrien Exp $
# $DragonFly: src/usr.bin/last/Makefile,v 1.3 2007/08/27 16:50:55 pavalos Exp $

PROG=	last
WARNS?=	1

.include <bsd.prog.mk>
