# $FreeBSD: src/usr.bin/bzip2recover/Makefile,v 1.1.2.1 2003/01/04 17:17:08 obrien Exp $
# $DragonFly: src/usr.bin/bzip2recover/Makefile,v 1.3 2004/01/31 06:56:43 dillon Exp $

BZ2DIR=	${.CURDIR}/../../contrib/bzip2
.PATH: ${BZ2DIR}

PROG=	bzip2recover
NOMAN=

.include <bsd.prog.mk>
