# $FreeBSD: src/usr.sbin/mixer/Makefile,v 1.6.2.2 2001/07/30 10:22:58 dd Exp $
# $DragonFly: src/usr.sbin/mixer/Makefile,v 1.2 2003/06/17 04:29:57 dillon Exp $

PROG=	mixer
WARNS?=	2
MAN=	mixer.8

.include <bsd.prog.mk>
