# $FreeBSD: src/sys/modules/wb/Makefile,v 1.8 2000/01/28 11:26:43 bde Exp $
# $DragonFly: src/sys/dev/netif/wb/Makefile,v 1.4 2006/06/25 11:02:39 corecode Exp $

KMOD	= if_wb
SRCS	= if_wb.c device_if.h
SRCS	+= bus_if.h miibus_if.h pci_if.h

.include <bsd.kmod.mk>
