/*
 * Union of syscall args for messaging.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $DragonFly: src/sys/emulation/svr4/Attic/svr4_union.h,v 1.4 2003/08/12 02:36:15 dillon Exp $
 * created from DragonFly: src/sys/emulation/svr4/syscalls.master,v 1.3 2003/08/07 21:17:19 dillon Exp 
 */

union sysunion {
#ifdef _KERNEL /* header only applies in kernel */
	struct	lwkt_msg lmsg;
	union	sysmsg sysmsg;
#endif
	struct	svr4_sys_open_args svr4_sys_open;
	struct	svr4_sys_wait_args svr4_sys_wait;
	struct	svr4_sys_creat_args svr4_sys_creat;
	struct	svr4_sys_execv_args svr4_sys_execv;
	struct	svr4_sys_time_args svr4_sys_time;
	struct	svr4_sys_mknod_args svr4_sys_mknod;
	struct	svr4_sys_break_args svr4_sys_break;
	struct	svr4_sys_stat_args svr4_sys_stat;
	struct	svr4_sys_alarm_args svr4_sys_alarm;
	struct	svr4_sys_fstat_args svr4_sys_fstat;
	struct	svr4_sys_pause_args svr4_sys_pause;
	struct	svr4_sys_utime_args svr4_sys_utime;
	struct	svr4_sys_access_args svr4_sys_access;
	struct	svr4_sys_nice_args svr4_sys_nice;
	struct	svr4_sys_kill_args svr4_sys_kill;
	struct	svr4_sys_pgrpsys_args svr4_sys_pgrpsys;
	struct	svr4_sys_times_args svr4_sys_times;
	struct	svr4_sys_signal_args svr4_sys_signal;
#if defined(NOTYET)
	struct	svr4_sys_msgsys_args svr4_sys_msgsys;
#else
#endif
	struct	svr4_sys_sysarch_args svr4_sys_sysarch;
	struct	svr4_sys_ioctl_args svr4_sys_ioctl;
	struct	svr4_sys_utssys_args svr4_sys_utssys;
	struct	svr4_sys_execve_args svr4_sys_execve;
	struct	svr4_sys_fcntl_args svr4_sys_fcntl;
	struct	svr4_sys_ulimit_args svr4_sys_ulimit;
	struct	svr4_sys_getdents_args svr4_sys_getdents;
	struct	svr4_sys_getmsg_args svr4_sys_getmsg;
	struct	svr4_sys_putmsg_args svr4_sys_putmsg;
	struct	svr4_sys_poll_args svr4_sys_poll;
	struct	svr4_sys_lstat_args svr4_sys_lstat;
	struct	svr4_sys_sigprocmask_args svr4_sys_sigprocmask;
	struct	svr4_sys_sigsuspend_args svr4_sys_sigsuspend;
	struct	svr4_sys_sigaltstack_args svr4_sys_sigaltstack;
	struct	svr4_sys_sigaction_args svr4_sys_sigaction;
	struct	svr4_sys_sigpending_args svr4_sys_sigpending;
	struct	svr4_sys_context_args svr4_sys_context;
	struct	svr4_sys_statvfs_args svr4_sys_statvfs;
	struct	svr4_sys_fstatvfs_args svr4_sys_fstatvfs;
	struct	svr4_sys_waitsys_args svr4_sys_waitsys;
	struct	svr4_sys_hrtsys_args svr4_sys_hrtsys;
	struct	svr4_sys_pathconf_args svr4_sys_pathconf;
	struct	svr4_sys_mmap_args svr4_sys_mmap;
	struct	svr4_sys_fpathconf_args svr4_sys_fpathconf;
	struct	svr4_sys_xstat_args svr4_sys_xstat;
	struct	svr4_sys_lxstat_args svr4_sys_lxstat;
	struct	svr4_sys_fxstat_args svr4_sys_fxstat;
	struct	svr4_sys_xmknod_args svr4_sys_xmknod;
	struct	svr4_sys_setrlimit_args svr4_sys_setrlimit;
	struct	svr4_sys_getrlimit_args svr4_sys_getrlimit;
	struct	svr4_sys_memcntl_args svr4_sys_memcntl;
	struct	svr4_sys_uname_args svr4_sys_uname;
	struct	svr4_sys_sysconfig_args svr4_sys_sysconfig;
	struct	svr4_sys_systeminfo_args svr4_sys_systeminfo;
	struct	svr4_sys_fchroot_args svr4_sys_fchroot;
	struct	svr4_sys_utimes_args svr4_sys_utimes;
	struct	svr4_sys_vhangup_args svr4_sys_vhangup;
	struct	svr4_sys_gettimeofday_args svr4_sys_gettimeofday;
	struct	svr4_sys_llseek_args svr4_sys_llseek;
	struct	svr4_sys_acl_args svr4_sys_acl;
	struct	svr4_sys_auditsys_args svr4_sys_auditsys;
	struct	svr4_sys_facl_args svr4_sys_facl;
	struct	svr4_sys_resolvepath_args svr4_sys_resolvepath;
	struct	svr4_sys_getdents64_args svr4_sys_getdents64;
	struct	svr4_sys_mmap64_args svr4_sys_mmap64;
	struct	svr4_sys_stat64_args svr4_sys_stat64;
	struct	svr4_sys_lstat64_args svr4_sys_lstat64;
	struct	svr4_sys_fstat64_args svr4_sys_fstat64;
	struct	svr4_sys_statvfs64_args svr4_sys_statvfs64;
	struct	svr4_sys_fstatvfs64_args svr4_sys_fstatvfs64;
	struct	svr4_sys_setrlimit64_args svr4_sys_setrlimit64;
	struct	svr4_sys_getrlimit64_args svr4_sys_getrlimit64;
	struct	svr4_sys_creat64_args svr4_sys_creat64;
	struct	svr4_sys_open64_args svr4_sys_open64;
	struct	svr4_sys_socket_args svr4_sys_socket;
	struct	svr4_sys_recv_args svr4_sys_recv;
	struct	svr4_sys_send_args svr4_sys_send;
	struct	svr4_sys_sendto_args svr4_sys_sendto;
};
