# $FreeBSD: src/usr.sbin/pcvt/fontedit/Makefile,v 1.4.6.1 2001/04/25 12:10:27 ru Exp $
# $DragonFly: src/usr.sbin/pcvt/fontedit/Attic/Makefile,v 1.2 2003/06/17 04:29:59 dillon Exp $

PROG=	fontedit

.include <bsd.prog.mk>
