# Makefile for kld char device driver.
# $FreeBSD: src/share/examples/kld/cdev/module/Makefile,v 1.3.2.2 2002/07/17 14:13:52 ru Exp $
# $DragonFly: src/share/examples/kld/cdev/module/Makefile,v 1.2 2003/06/17 04:36:57 dillon Exp $

KMOD=	cdev
SRCS=	cdev.c cdevmod.c

.include <bsd.kmod.mk>
