# $FreeBSD: src/gnu/usr.bin/groff/src/libs/libdriver/Makefile,v 1.1.2.2 2002/07/19 18:46:24 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/libs/libdriver/Makefile,v 1.2 2003/06/17 04:25:46 dillon Exp $

LIB=		driver
INTERNALLIB=	YES
SRCS=		input.cc printer.cc

.include <bsd.lib.mk>
