LIB=		iberty
SHLIB_MAJOR=	2
SRCS=		argv.c concat.c hex.c
SRCS+=		lbasename.c lrealpath.c
SRCS+=		xatexit.c xexit.c
SRCS+=		xcalloc.c xmalloc.c xmemdup.c xrealloc.c xstrdup.c xstrerror.c

NOMAN=1

.include <bsd.lib.mk>
