# $DragonFly: src/lib/libiberty/Makefile,v 1.3 2004/10/23 12:15:21 joerg Exp $

LIB=		iberty
SHLIB_MAJOR=	1
SRCS=		argv.c concat.c hex.c
SRCS+=		lbasename.c lrealpath.c
SRCS+=		xatexit.c xexit.c
SRCS+=		xcalloc.c xmalloc.c xmemdup.c xrealloc.c xstrdup.c xstrerror.c
WARNS?=		6

NOMAN=1

.include <bsd.lib.mk>
