# $FreeBSD: src/usr.sbin/mrouted/mtrace/Makefile,v 1.10.2.1 2001/04/25 12:10:12 ru Exp $
# $DragonFly: src/usr.sbin/mrouted/mtrace/Makefile,v 1.2 2003/06/17 04:29:57 dillon Exp $

PROG=	mtrace

S=	${.CURDIR}/..
.PATH:	$S
CFLAGS+=	-I$S

MAN=	mtrace.8
BINMODE=4555

.include <bsd.prog.mk>
