#	@(#)Makefile.inc	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/sbin/Makefile.inc,v 1.5.6.1 2001/08/01 05:53:59 obrien Exp $
# $DragonFly: src/sbin/Makefile.inc,v 1.2 2003/06/17 04:27:31 dillon Exp $

BINDIR?=	/sbin
NOSHARED?=	YES
