# $FreeBSD: src/usr.bin/getopt/Makefile,v 1.2.2.1 2001/04/25 11:29:22 ru Exp $
# $DragonFly: src/usr.bin/getopt/Makefile,v 1.3 2005/04/14 15:49:12 eirikn Exp $
#

PROG=	getopt
WARNS?=	6

.include <bsd.prog.mk>
