# $FreeBSD: src/usr.sbin/wormcontrol/Makefile,v 1.1.1.1.10.1 2001/04/25 12:11:12 ru Exp $
# $DragonFly: src/usr.sbin/wormcontrol/Attic/Makefile,v 1.2 2003/06/17 04:30:04 dillon Exp $

PROG=	wormcontrol
MAN=	wormcontrol.8

.include <bsd.prog.mk>
