# $FreeBSD: src/gnu/usr.bin/groff/Makefile,v 2.6.2.2 2001/04/26 17:07:52 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/Makefile,v 1.2 2003/06/17 04:25:45 dillon Exp $

SUBDIR=		contrib doc font man src tmac

.include <bsd.subdir.mk>
