# This file builds one or more host programs.
#
# +++ variables for one-program mode +++
#
# PROG		Program name
# PROG_CXX	C++ program name
# SRCS		Source files to build the program
# OBJS		Extra objects
# LDADD		Libraries to link the program with
# DPADD		Libraries that the program depends on
# CFLAGS	Compiler flags
# CXXFLAGS	C++ compiler flags
# LDFLAGS	Linker flags
#
# +++ variables for multiple-program mode +++
#
# PROGS		List of program names
# PROGS_CXX	List of C++ program names
# SRCS_${P}	Source files to build program ${P}
# OBJS_${P}	Extra objects for program ${P}
# LDADD_${P}	Extra libraries to link program ${P} with
# DPADD_${P}	Extra libraries that program ${P} depends on
# CFLAGS_${P}	Extra compiler flags for program ${P}
# CXXFLAGS_${P}	Extra C++ compiler flags for program ${P}
# LDFLAGS_${P}	Extra linker flags for program ${P}
#
# LDADD, DPADD, CFLAGS, CXXFLAGS and LDFLAGS apply to all programs.
#

.include <bsd.init.mk>
.include <bsd.libnames.mk>

# Hint HOST_CCVER handling.
__USE_HOST_CCVER=
NO_WERROR=

.SUFFIXES: .out .nx .no .c .cc .cpp .cxx .C .m .y .l .s .S

PROGS?=
PROGS_CXX?=

.if defined(PROG) || defined(PROG_CXX)
. if !empty(PROGS) || !empty(PROGS_CXX)
.  error cannot mix PROG/PROG_CXX with PROGS/PROGS_CXX
. endif
PROGS:=		${PROG}
PROGS_CXX:=	${PROG_CXX}

. if defined(PROG_CXX)
PROG:=		${PROG_CXX}
. endif

SRCS_${PROG}:=	${SRCS}
OBJS_${PROG}:=	${OBJS}
.endif

_ALL_PROGS=	${PROGS} ${PROGS_CXX}

all: objwarn ${_ALL_PROGS:S/$/.nx/g}

# Header files are often generated by .nx binaries.  All .nx binaries must
# be built in the depend stage so the related header files can be generated
afterdepend: all

# Collect all sources for depend generation.
SRCS=

.for _p in ${_ALL_PROGS}

. if empty(SRCS_${_p}) && empty(OBJS_${_p})
.  if ${PROGS_CXX:M${_p}} != ""
SRCS_${_p}=	${_p}.cc
.  else
SRCS_${_p}=	${_p}.c
.  endif
. endif

SRCS+=		${SRCS_${_p}}
OBJS_${_p}+=	${SRCS_${_p}:N*.h:R:S/$/.no/}

# If there are Objective C sources, link with Objective C libraries.
. if ${SRCS_${_p}:M*.m} != ""
OBJCLIBS?=	-lobjc
LDADD_${_p}+=	${OBJCLIBS}
. endif

. if ${PROGS_CXX:M${_p}} != ""
DPADD_${_p}+=	${LIBSTDCPLUSPLUS}
. endif

${_p}.nx: ${OBJS_${_p}}
. if ${PROGS_CXX:M${_p}} != ""
	${NXCXX_LINK} ${NXCXXFLAGS} ${CXXFLAGS_${_p}} \
	    ${NXLDFLAGS} ${LDFLAGS_${_p}} \
	    -o ${.TARGET} ${OBJS_${_p}} ${LDADD} ${LDADD_${_p}}
. else
	${NXCC_LINK} ${NXCFLAGS} ${CFLAGS_${_p}} \
	    ${NXLDFLAGS} ${LDFLAGS_${_p}} \
	    -o ${.TARGET} ${OBJS_${_p}} ${LDADD} ${LDADD_${_p}}
. endif

CLEANFILES+=	${_p}.nx ${OBJS_${_p}}

.endfor  # ${_ALL_PROGS}

# Propagate per-program CFLAGS to .no builds via FLAGS_GROUPS.
.if ${_ALL_PROGS:[#]} > 1
FLAGS_GROUPS+=		${_ALL_PROGS:S/^/_prog_/}
. for _p in ${_ALL_PROGS}
_prog_${_p}_FLAGS=	${CFLAGS_${_p}}
_prog_${_p}_FLAGS_FILES=${SRCS_${_p}}
. endfor
.endif

_EXTRADEPEND:
	sed -i '' -Ee 's/^([^.]+)\.o:/\1.no:/' ${DEPENDFILE}
.for _p in ${_ALL_PROGS}
	echo ${_p}.nx: ${DPADD} ${DPADD_${_p}} ${LIBC} >> ${DEPENDFILE}
.endfor

.include <bsd.dep.mk>

.if !exists(${.OBJDIR}/${DEPENDFILE})
. for _p in ${_ALL_PROGS}
${OBJS_${_p}}: ${SRCS_${_p}:M*.h}
. endfor
.endif

.include <bsd.obj.mk>
.include <bsd.sys.mk>
