# $FreeBSD: src/share/mk/Makefile,v 1.27.2.8 2002/07/22 14:21:51 ru Exp $
# $DragonFly: src/share/mk/Makefile,v 1.17 2007/01/15 18:29:44 corecode Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/8/93

FILES=	bsd.README
FILES+=	bsd.cpu.mk bsd.cpu.gcc41.mk bsd.cpu.custom.mk
FILES+=	bsd.cpu.gcc44.mk
FILES+=	bsd.dep.mk bsd.doc.mk bsd.files.mk bsd.patch.mk
FILES+=	bsd.incs.mk bsd.info.mk bsd.init.mk
FILES+=	bsd.kmod.mk bsd.hostlib.mk
FILES+=	bsd.lib.mk bsd.libnames.mk bsd.links.mk bsd.man.mk bsd.nls.mk
FILES+=	bsd.obj.mk bsd.own.mk
FILES+=	bsd.hostprog.mk bsd.prog.mk bsd.subdir.mk bsd.sys.mk
FILES+=	sys.mk
NOOBJ=	noobj
FILESDIR=	${BINDIR}/mk

.include <bsd.prog.mk>
