# $FreeBSD: src/sys/modules/my/Makefile,v 1.1.2.1 2002/04/16 20:38:52 julian Exp $
# $DragonFly: src/sys/dev/netif/my/Makefile,v 1.4 2007/03/11 03:46:48 swildner Exp $

KMOD=	if_my
SRCS=	if_my.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
