# $FreeBSD: src/sys/modules/my/Makefile,v 1.1.2.1 2002/04/16 20:38:52 julian Exp $
# $DragonFly: src/sys/dev/netif/my/Makefile,v 1.2 2003/06/17 04:28:45 dillon Exp $

.PATH: ${.CURDIR}/../../dev/my

KMOD=	if_my
SRCS=	if_my.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
