SUBDIR=	alpm amdpm aps coretemp
SUBDIR+=intpm kate km lm powernow uguru
SUBDIR+=viapm wbsio perfbias clockmod
SUBDIR+=memtemp corepower

# Empty for concurrent build
#
SUBDIR_ORDERED=

.include <bsd.subdir.mk>
