# $FreeBSD: src/include/rpc/Makefile,v 1.2.2.1 2002/07/22 14:21:46 ru Exp $
# $DragonFly: src/include/rpc/Makefile,v 1.2 2003/06/17 04:25:58 dillon Exp $

NOOBJ=	noobj
INCS=	auth.h auth_unix.h clnt.h pmap_clnt.h pmap_prot.h pmap_rmt.h \
	rpc.h rpc_com.h rpc_msg.h svc.h svc_auth.h types.h xdr.h \
	auth_des.h des.h des_crypt.h
INCSDIR=${INCLUDEDIR}/rpc

.include <bsd.prog.mk>
