# $FreeBSD: src/usr.bin/gencat/Makefile,v 1.5 1999/08/28 01:01:40 peter Exp $
# $DragonFly: src/usr.bin/gencat/Makefile,v 1.2 2003/06/17 04:29:27 dillon Exp $

PROG=	gencat
SRCS=	gencat.c genlib.c

CFLAGS+= -I${.CURDIR}/../../lib/libc/nls

.include <bsd.prog.mk>
