# $DragonFly: src/sbin/rcrun/Makefile,v 1.1 2003/12/11 23:56:05 dillon Exp $

SCRIPTS=rcrun.sh
LINKS=	${BINDIR}/rcrun ${BINDIR}/rcstart \
	${BINDIR}/rcrun ${BINDIR}/rcstop \
	${BINDIR}/rcrun ${BINDIR}/rcrestart \
	${BINDIR}/rcrun ${BINDIR}/rcvar \
	${BINDIR}/rcrun ${BINDIR}/rclist \
	${BINDIR}/rcrun ${BINDIR}/rcforce \
	${BINDIR}/rcrun ${BINDIR}/rcfast

#MAN=	rcrun.8

.include <bsd.prog.mk>
