# $DragonFly: src/sbin/rcrun/Makefile,v 1.2 2003/12/13 02:49:09 dillon Exp $

SCRIPTS=rcrun.sh
SYMLINKS= \
	rcrun ${BINDIR}/rcstart \
	rcrun ${BINDIR}/rcstop \
	rcrun ${BINDIR}/rcrestart \
	rcrun ${BINDIR}/rcvar \
	rcrun ${BINDIR}/rclist \
	rcrun ${BINDIR}/rcforce \
	rcrun ${BINDIR}/rcfast \
	rcrun ${BINDIR}/rcenable \
	rcrun ${BINDIR}/rcdisable

#MAN=	rcrun.8

.include <bsd.prog.mk>
