RELTOP:= ..

RELSRC=		${RELTOP}/../../../contrib/texinfo
SRCDIR=		${.CURDIR}/${RELSRC}

CFLAGS+=	-I. -I${.CURDIR}

DPADD=		${RELTOP}/libgnu/libgnu.a
LDADD=		${RELTOP}/libgnu/libgnu.a
DPADD+=		${RELTOP}/libtxi/libtxi.a
LDADD+=		${RELTOP}/libtxi/libtxi.a


BINDIR?=	/usr/bin
