#
# $FreeBSD: src/gnu/usr.bin/texinfo/Makefile,v 1.10.2.1 2002/03/30 17:09:24 ru Exp $
# $DragonFly: src/gnu/usr.bin/texinfo/Makefile,v 1.2 2003/06/17 04:25:49 dillon Exp $
#

SUBDIR= libtxi makeinfo info infokey install-info texindex doc

.include <bsd.subdir.mk>
