#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/lam/Makefile,v 1.1.1.1.14.1 2001/08/11 03:03:19 mike Exp $
# $DragonFly: src/usr.bin/lam/Makefile,v 1.4 2007/08/27 16:50:55 pavalos Exp $

PROG=	lam

.include <bsd.prog.mk>
