#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/lam/Makefile,v 1.1.1.1.14.1 2001/08/11 03:03:19 mike Exp $
# $DragonFly: src/usr.bin/lam/Makefile,v 1.3 2005/01/05 00:38:38 cpressey Exp $

PROG=	lam
WARNS?=	6

.include <bsd.prog.mk>
