#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/lam/Makefile,v 1.1.1.1.14.1 2001/08/11 03:03:19 mike Exp $
# $DragonFly: src/usr.bin/lam/Makefile,v 1.2 2003/06/17 04:29:27 dillon Exp $

PROG=	lam
WARNS?=	2

.include <bsd.prog.mk>
