# $FreeBSD: src/sys/boot/alpha/Makefile,v 1.6 1999/11/03 20:19:30 dfr Exp $
# $DragonFly: src/sys/boot/alpha/Attic/Makefile,v 1.3 2003/11/10 06:08:22 dillon Exp $

SUBDIR=		libalpha
SUBDIR+=	boot1 loader cdboot netboot

.include <bsd.subdir.mk>
