.\"-
.\" Copyright (c) 2007 The DragonFly Project.
.\" 
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" - Redistributions of source code must retain the above copyright notice,
.\"   this list of conditions and the following disclaimer.
.\" - Redistributions in binary form must reproduce the above copyright notice,
.\"   this list of conditions and the following disclaimer in the documentation
.\"   and/or other materials provided with the distribution.
.\" - Neither the name of The DragonFly Project nor the names of its
.\"   contributors may be used to endorse or promote products derived
.\"   from this software without specific, prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\" EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
.\" PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\" NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd February 6, 2011
.Dt PKG_RADD 1
.Os
.Sh NAME
.Nm pkg_radd
.Nd installs packages
.Sh SYNOPSIS
.Nm
.Ar package ...
.Sh DESCRIPTION
.Nm
acts as a wrapper for
.Xr pkg_add 1 .
It sets the
.Ev PKG_PATH
variable to the
.Dx
default
.Xr pkgsrc 7
binary package server or uses the global
.Pa /etc/pkg_radd.conf
config file to calculate
.Ev PKG_PATH .
In
.Pa /etc/pkg_radd.conf ,
set
.Ev BINPKG_BASE
to your favorite binary packages mirror URL to allow
.Nm
to automatically retrieve the latest set of binary packages for your
.Dx
release.
If you want to use a specific set of packages, set
.Ev BINPKG_SITES
instead.
.Pp
All options passed to
.Nm
are passed to
.Xr pkg_add 1 .
.Sh EXAMPLES
The following is an example of a typical usage of the
.Nm
command:
.Pp
.Dl "# pkg_radd host"
.Pp
If you don't know which version of your desired package to install you can
use
.Xr pkg_search 1
to find the correct version.
.Pp
.Dl "# pkg_search fvwm2"
.Dl "# pkg_radd -v fvwm-2.4.20nb1"
.Pp
If you add the following line
.Pp
.Dl "BINPKG_BASE=http://mirror-master.dragonflybsd.org/packages"
.Pp
to
.Pa /etc/pkg_radd.conf ,
.Nm
fetches packages from the main
.Dx
server.
If possible, replace the entry with one of the mirrors as listed in
.Pa http://www.dragonflybsd.org/mirrors/ .
.Sh SEE ALSO
.Xr pkg_add 1 ,
.Xr pkg_create 1 ,
.Xr pkg_delete 1 ,
.Xr pkg_info 1 ,
.Xr pkg_search 1 ,
.Xr pkgsrc 7
.Sh HISTORY
The
.Nm
utility first appeared in
.Dx 1.11 .
.Sh AUTHORS
.Nm
was written by
.An Simon 'corecode' Schubert Aq Mt corecode@fs.ei.tum.de .
