# $FreeBSD: src/usr.sbin/mrouted/testrsrr/Makefile,v 1.4 1999/08/28 01:17:16 peter Exp $
# $DragonFly: src/usr.sbin/mrouted/testrsrr/Makefile,v 1.2 2003/06/17 04:29:57 dillon Exp $

PROG=	testrsrr

S=	${.CURDIR}/..
.PATH:	$S
CFLAGS+=	-I$S

SRCS=	testrsrr.c
NOMAN=

install:

.include <bsd.prog.mk>
