# $FreeBSD: src/usr.sbin/nsupdate/Makefile,v 1.2 1999/11/30 06:16:46 peter Exp $
# $DragonFly: src/usr.sbin/nsupdate/Makefile,v 1.2 2003/06/17 04:29:57 dillon Exp $

USE_LIBBIND=	yes
.include "${.CURDIR}/../named/Makefile.inc"

.PATH:	${BIND_DIR}/bin/nsupdate

PROG=	nsupdate
NOMAN=	hmm..

.include <bsd.prog.mk>
