# $FreeBSD: src/lib/csu/i386-elf/Makefile,v 1.6.2.5 2002/11/23 17:44:29 ru Exp $

SRCS+=		crt1.c crti.S crtn.S
OBJS+=		gcrt1.o
INSTALLOBJS+=	crt1.o crti.o crtn.o gcrt1.o
CLEANFILES+=	crt1.o crti.o crtn.o gcrt1.o
WARNS?=		2

CFLAGS+=	-elf -fkeep-inline-functions \
		-I${CSUDIR}/../common
LDFLAGS+=	-elf

.PATH:		${CSUDIR} ${CSUDIR}/../common

gcrt1.o:	crt1.c
	${CC} ${CFLAGS} -DGCRT -c -o gcrt1.o ${CSUDIR}/crt1.c
