# Build standard version of panel
LIB=	private_panel
PRIVATELIB=

SHLIBDIR?=	/lib

ZPANEL=	yes

INCS=		panel.h
INCSDIR=	${INCLUDEDIR}/priv/ncurses

.include "${.CURDIR}/../Makefile.sources"
.include <bsd.lib.mk>
