#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $DragonFly: src/games/canfield/cfscores/Makefile,v 1.2 2005/11/19 09:50:30 swildner Exp $

PROG=	cfscores
CFLAGS+=-I${.CURDIR}/../canfield
NOMAN=	noman
WARNS?=	6

.include "../../Makefile.inc"
.include <bsd.prog.mk>
