# $FreeBSD: src/gnu/usr.bin/groff/src/roff/nroff/Makefile,v 1.1.2.1 2001/04/26 17:08:34 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/roff/nroff/Makefile,v 1.2 2003/06/17 04:25:46 dillon Exp $

SCRIPTS=	nroff
MAN=		nroff.1
CLEANFILES=	${SCRIPTS} ${MAN}

.include <bsd.prog.mk>
