# $FreeBSD: src/usr.sbin/pkg_install/version/Makefile,v 1.5.2.5 2001/09/21 16:54:17 bmah Exp $
# $DragonFly: src/usr.sbin/pkg_install/version/Attic/Makefile,v 1.2 2003/06/17 04:29:59 dillon Exp $

SCRIPTS=	pkg_version.pl
MAN=		pkg_version.1

test:
	./test-pkg_version.sh

.include <bsd.prog.mk>
