# $FreeBSD: src/usr.bin/dnskeygen/Makefile,v 1.1.4.1 2001/04/25 11:29:18 ru Exp $
# $DragonFly: src/usr.bin/dnskeygen/Attic/Makefile,v 1.2 2003/06/17 04:29:25 dillon Exp $

USE_LIBBIND=	true
.include "${.CURDIR}/../../usr.sbin/named/Makefile.inc"

.PATH:	${BIND_DIR}/bin/dnskeygen
.PATH:	${BIND_DIR}/doc/man

PROG=	dnskeygen

.include <bsd.prog.mk>
