# $FreeBSD: src/sys/modules/txp/Makefile,v 1.2.2.2 2001/12/04 20:01:54 brooks Exp $
# $DragonFly: src/sys/dev/netif/txp/Makefile,v 1.3 2005/06/20 13:24:14 joerg Exp $

KMOD=	if_txp
SRCS=	if_txp.c opt_bdg.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
