# $FreeBSD: src/sys/modules/txp/Makefile,v 1.2.2.2 2001/12/04 20:01:54 brooks Exp $
# $DragonFly: src/sys/dev/netif/txp/Makefile,v 1.2 2003/06/17 04:28:47 dillon Exp $

.PATH: ${.CURDIR}/../../dev/txp

KMOD=	if_txp
SRCS=	if_txp.c opt_bdg.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
