# $FreeBSD: src/usr.sbin/procctl/Makefile,v 1.4.2.1 2001/04/25 12:10:38 ru Exp $
# $DragonFly: src/usr.sbin/procctl/Makefile,v 1.2 2003/06/17 04:30:01 dillon Exp $

PROG=	procctl
MAN=	procctl.8

.include <bsd.prog.mk>
