# $FreeBSD: src/usr.sbin/pcvt/ispcvt/Makefile,v 1.5.6.1 2001/04/25 12:10:27 ru Exp $
# $DragonFly: src/usr.sbin/pcvt/ispcvt/Attic/Makefile,v 1.2 2003/06/17 04:29:59 dillon Exp $

PROG=	ispcvt
MAN=	ispcvt.8

.include <bsd.prog.mk>
