#       $FreeBSD: src/sys/modules/uhid/Makefile,v 1.7 1999/11/28 18:53:30 bde Exp $ 
#       $DragonFly: src/sys/dev/usbmisc/uhid/Makefile,v 1.3 2004/01/31 06:56:28 dillon Exp $ 

.PATH:  	 ${.CURDIR}/../../dev/usb
KMOD		 = uhid
SRCS		 = bus_if.h device_if.h vnode_if.h opt_usb.h uhid.c
NOMAN		 =

.include <bsd.kmod.mk>
