# $FreeBSD: src/usr.sbin/spkrtest/Makefile,v 1.8.2.2 2001/04/25 14:05:16 ru Exp $
# $DragonFly: src/usr.sbin/spkrtest/Makefile,v 1.4 2004/11/16 22:21:15 joerg Exp $

SCRIPTS=spkrtest.sh
MAN=	spkrtest.8

.include <bsd.prog.mk>
