# $FreeBSD: src/usr.sbin/spkrtest/Makefile,v 1.8.2.2 2001/04/25 14:05:16 ru Exp $
# $DragonFly: src/usr.sbin/spkrtest/Makefile,v 1.2 2003/06/17 04:30:03 dillon Exp $

MAINTAINER= wosch

SCRIPTS=spkrtest.pl
MAN=	spkrtest.8

.include <bsd.prog.mk>
