# This is a dummy make file.
# It used to exist to provide the possibility of building the dynamic
# linker as an executable rather than a shared library.
# To restore this capability, import libexec/rtld-elf/i386/elf_rtld.x
# from FreeBSD into the same directory containing this make file.
#
#To build with the gnu linker, uncomment the following line:
#LDSCRIPT=	${.CURDIR}/${MACHINE_ARCH}/elf_rtld.x
