# $FreeBSD: src/sys/modules/pcn/Makefile,v 1.1.2.1 2000/10/03 18:46:56 wpaul Exp $
# $DragonFly: src/sys/dev/netif/pcn/Makefile,v 1.4 2006/06/25 11:02:39 corecode Exp $

KMOD	= if_pcn
SRCS	= if_pcn.c device_if.h bus_if.h pci_if.h
SRCS	+= miibus_if.h

.include <bsd.kmod.mk>
