# $FreeBSD: src/usr.bin/makewhatis/Makefile,v 1.3 2002/11/18 10:11:22 ru Exp $
# $DragonFly: src/usr.sbin/makewhatis/Makefile,v 1.1 2004/03/25 18:05:48 joerg Exp $

PROG=		makewhatis
DPADD=		${LIBZ}
LDADD=		-lz
MAN=		makewhatis.8

.include <bsd.prog.mk>
