# $FreeBSD: src/sys/modules/syscons/fade/Makefile,v 1.9 1999/08/28 00:47:47 peter Exp $
# $DragonFly: src/sys/dev/misc/syscons/fade/Makefile,v 1.2 2003/06/17 04:28:47 dillon Exp $

KMOD=	fade_saver
SRCS= 	fade_saver.c

KCFLAGS+= -I${.CURDIR}/..

.include <bsd.kmod.mk>
