# $FreeBSD: src/sys/modules/cbb/Makefile,v 1.2 1999/11/28 18:52:41 bde Exp $
# $DragonFly: src/sys/bus/pccard/pccbb/Attic/Makefile,v 1.2 2003/06/17 04:28:43 dillon Exp $

.PATH:  ${.CURDIR}/../../pci
KMOD=   cbb
SRCS=   pccbb.c \
	device_if.h bus_if.h
NOMAN=

.include <bsd.kmod.mk>
