# $DragonFly: src/sys/netproto/802_11/wlan_ratectl/sample/Makefile,v 1.1 2007/04/01 13:59:41 sephe Exp $

KMOD	= wlan_ratectl_sample
SRCS	= ieee80211_ratectl_sample.c
KMODDEPS= wlan

.include <bsd.kmod.mk>
