# $FreeBSD: src/usr.bin/kzip/Makefile,v 1.6.2.1 2001/04/25 11:29:25 ru Exp $
# $DragonFly: src/usr.bin/kzip/Makefile,v 1.2 2003/06/17 04:29:27 dillon Exp $

PROG=	kzip
MAN=	kzip.8

.include <bsd.prog.mk>
