# $FreeBSD: src/usr.bin/kzip/Makefile,v 1.6.2.1 2001/04/25 11:29:25 ru Exp $
# $DragonFly: src/usr.bin/kzip/Makefile,v 1.3 2007/08/27 16:50:55 pavalos Exp $

PROG=	kzip
MAN=	kzip.8
WARNS?=	2

.include <bsd.prog.mk>
