# $FreeBSD: src/games/grdc/Makefile,v 1.4.2.2 2001/10/02 11:51:49 ru Exp $
# $DragonFly: src/games/grdc/Makefile,v 1.4 2006/10/08 16:22:35 pavalos Exp $

PROG=   grdc
MAN=   grdc.6
DPADD=  ${LIBNCURSES}
LDADD=  -lncurses

.include <bsd.prog.mk>
