# $FreeBSD: src/sbin/ipfw/Makefile,v 1.6.6.3 2002/07/24 03:21:23 luigi Exp $

PROG =	ipfw3
MAN =	ipfw3.8
SRCS =	ipfw3.c
SRCS += ipfw3sync.c ipfw3sync.h
SRCS += ipfw3nat.c ipfw3nat.h
WARNS?=	2

.include <bsd.prog.mk>
