.\"
.\" Copyright (c) 2014 The DragonFly Project.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd November 8, 2014
.Dt ACPIEXEC 8
.Os
.Sh NAME
.Nm acpiexec
.Nd load ACPI tables and execute control methods from user space
.Sh SYNOPSIS
.Nm
.Op Ar option ...
.Ar aml_file ...
.Sh DESCRIPTION
The following options are supported:
.Bl -tag -width indent
.It Fl b Ar \&"command_line\&"
Batch mode command line execution (cmd1;cmd2;...).
.It Fl da
Disable method abort on error.
.It Fl di
Disable execution of STA/INI methods during init.
.It Fl do
Disable Operation Region address simulation.
.It Fl dr
Disable repair of method return values.
.It Fl ds
Disable method auto-serialization.
.It Fl dt
Disable allocation tracking (performance).
.It Fl ef
Enable display of final memory statistics.
.It Fl ei
Enable additional tests for ACPICA interfaces.
.It Fl el
Enable loading of additional test tables.
.It Fl es
Enable Interpreter Slack Mode.
.It Fl et
Enable debug semaphore timeout.
.It Fl fi Ar file
Specify namespace initialization file.
.It Fl fv Ar value
Operation Region initialization fill value.
.It Fl h
Display the help message.
.It Fl \&?
Alias for
.Fl h .
.It Fl m Op Ar method
Batch mode method execution.
The default method is
.Sy MAIN .
.It Fl r
Use hardware-reduced FADT V5.
.It Fl v
Display version information.
.It Fl vi
Verbose initialization output.
.It Fl vr
Verbose region handler output.
.It Fl x Ar debug_level
Debug output level.
.El
.Pp
From within the interactive mode, use
.Sq \&?
or
.Dq help
to see a list of available AML Debugger commands.
.Sh SEE ALSO
.Xr acpi 4 ,
.Xr acpibin 8 ,
.Xr acpiconf 8 ,
.Xr acpidump 8 ,
.Xr acpihelp 8 ,
.Xr acpinames 8 ,
.Xr acpixtract 8 ,
.Xr iasl 8
.Pp
.Lk https://acpica.org/documentation/
.Sh AUTHORS
The
.Nm
utility is provided by
.Tn Intel
as part of their
.Sy ACPICA
distribution.
.Pp
This manual page was written by
.An Sascha Wildner .
