# $FreeBSD: src/kerberosIV/libexec/Makefile.inc,v 1.2 1999/08/28 01:31:22 peter Exp $
# $DragonFly: src/kerberosIV/libexec/Attic/Makefile.inc,v 1.2 2003/06/17 04:26:25 dillon Exp $

BINDIR=	/usr/libexec

.include "../Makefile.inc"
