# $DragonFly: src/gnu/usr.bin/cc41/cc_tools/genpreds/Makefile,v 1.1 2006/09/27 12:10:34 corecode Exp $

.include "../Makefile.inc"

PROG=	genpreds
SRCS=	genpreds.c insn-modes.h gtype-desc.h
SRCS+=	${RTL_SRCS} ${EARLY_SRCS} ${PRINT_SRCS} ${ERRORS_SRCS}

.include <bsd.hostprog.mk>
