# $NetBSD: Makefile,v 1.2 2006/02/16 19:19:49 tnozaki Exp $
# FreeBSD: src/usr.bin/locale/Makefile,v 1.4 2003/06/25 23:05:11 phantom Exp
# $DragonFly: src/usr.bin/locale/Makefile,v 1.1 2006/07/01 10:47:39 eirikn Exp $

PROG = locale
WARNS ?= 3

.include <bsd.prog.mk>
