# $FreeBSD: src/sys/modules/syscons/logo/Makefile,v 1.3 1999/08/28 00:47:51 peter Exp $
# $DragonFly: src/sys/dev/misc/syscons/logo/Makefile,v 1.2 2003/06/17 04:28:47 dillon Exp $

KMOD=	logo_saver
SRCS= 	logo_saver.c

KCFLAGS+= -I${.CURDIR}/.. -I${.CURDIR}

.include <bsd.kmod.mk>
