# $DragonFly: src/usr.sbin/dntpd/Makefile,v 1.1 2005/04/24 02:36:50 dillon Exp $

PROG=	dntpd
SRCS=	main.c socket.c ntpreq.c convert.c log.c client.c system.c

LDADD += -lm

WARNS?=	6
MAN=

.include <bsd.prog.mk>
