# $FreeBSD: src/usr.bin/fsync/Makefile,v 1.2.2.1 2000/07/20 00:41:26 ps Exp $
# $DragonFly: src/usr.bin/fsync/Makefile,v 1.3 2004/12/12 17:01:05 liamfoy Exp $

PROG=	fsync

WARNS?=	6
.include <bsd.prog.mk>
