#	$NetBSD: src/share/locale/Makefile,v 1.4 2004/07/21 19:02:17 tshiozak Exp $
#	$DragonFly: src/share/locale/Makefile,v 1.1 2005/03/11 15:57:42 joerg Exp $

.include <bsd.own.mk>

NOOBJ=	# defined
NOMAN=	# defined

SUBDIR=	ctype

FILES=		locale.alias
FILESOWN=	${LOCALEOWN}
FILESGRP=	${LOCALEGRP}
FILESMODE=	${LOCALEMODE}
FILESDIR=	${LOCALEDIR}

.include <bsd.prog.mk>
