#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/chflags/Makefile,v 1.8.2.2 2001/08/01 23:09:18 obrien Exp $
# $DragonFly: src/usr.bin/chflags/Makefile,v 1.2 2003/06/17 04:29:25 dillon Exp $

NOSHARED?=yes

PROG=	chflags
SRCS=	chflags.c

WARNS?=	2
.include <bsd.prog.mk>
