# $FreeBSD: src/usr.bin/stat/Makefile,v 1.2 2002/08/13 08:23:49 dougb Exp $
# $DragonFly: src/usr.bin/stat/Makefile,v 1.2 2007/08/27 16:50:59 pavalos Exp $

PROG=	stat
WARNS?=	2

LINKS=	${BINDIR}/stat ${BINDIR}/readlink
MLINKS=	stat.1 readlink.1

.include <bsd.prog.mk>
