# $FreeBSD: src/kerberos5/lib/Makefile.inc,v 1.1.1.1.2.2 2002/09/01 04:22:01 nectar Exp $
# $DragonFly: src/kerberos5/lib/Makefile.inc,v 1.2 2003/06/17 04:26:17 dillon Exp $

SHLIB_MAJOR?=	5
SHLIB_MINOR?=	0

.include "../Makefile.inc"
