#	@(#)Makefile    1.1 (Julian Elischer)	3/28/93
# $FreeBSD: src/sbin/i386/nextboot/Makefile,v 1.1.8.1 2001/04/25 10:58:21 ru Exp $
# $DragonFly: src/sbin/i386/nextboot/Makefile,v 1.3 2005/01/17 07:27:45 cpressey Exp $

PROG=	nextboot
WARNS?=	6
MAN=	nextboot.8

.include <bsd.prog.mk>
