# $FreeBSD: src/usr.sbin/i4b/isdntest/Makefile,v 1.2.2.2 2001/08/01 17:29:18 obrien Exp $
# $DragonFly: src/usr.sbin/i4b/isdntest/Makefile,v 1.2 2003/06/17 04:29:55 dillon Exp $

PROG=	isdntest
MAN=	isdntest.8
SRCS=	main.c

install:
	@echo isdntest is not installed automatically

.include <bsd.prog.mk>
