# $DragonFly: src/sys/dev/netif/Makefile,v 1.32 2008/03/05 14:10:39 sephe Exp $
#

SUBDIR= an acx ar ath aue axe bce bfe bge bwi cue dc ed em ep et fwe fxp \
	ipw iwi iwl kue lge lnc mii_layer my msk nfe nge pcn ral re rl rtw \
	rue rum sbni sbsh sf sis sk sln sr ste stge \
	ti tl tx txp ural vge vr vx wb wi xe xl

.include <bsd.subdir.mk>
