# $DragonFly: src/sys/dev/netif/Makefile,v 1.21 2006/08/27 03:36:08 sephe Exp $
#

SUBDIR= an acx ar ath aue axe bfe bge cue dc ed em ep fwe fxp gx ipw iwi kue \
	lge lnc mii_layer my nfe nge nv pcn ral ray re rl rue sbni sbsh sf \
	sis sk sr ste ti tl tx txp vge vr vx wb wi xe xl

.include <bsd.subdir.mk>
