#       from @(#)Makefile.inc	8.1 (Berkeley) 6/4/93
# $FreeBSD: src/lib/libc/db/db/Makefile.inc,v 1.3 1999/08/27 23:58:17 peter Exp $
# $DragonFly: src/lib/libcr/db/db/Attic/Makefile.inc,v 1.2 2003/06/17 04:26:41 dillon Exp $

.PATH: ${.CURDIR}/../libc/db/db

SRCS+=	db.c
