#       from @(#)Makefile.inc	8.1 (Berkeley) 6/4/93
# $FreeBSD: src/lib/libc/db/db/Makefile.inc,v 1.3 1999/08/27 23:58:17 peter Exp $
# $DragonFly: src/lib/libcr/db/db/Attic/Makefile.inc,v 1.3 2003/07/24 21:41:46 dillon Exp $

.PATH: ${.CURDIR}/../libcr/db/db

SRCS+=	db.c
