.\"
.\" Copyright (c) 2015 The DragonFly Project.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of The DragonFly Project nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific, prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd May 29, 2020
.Dt ACPICALL 8
.Os
.Sh NAME
.Nm acpicall
.Nd call ACPI methods
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl b Ar hexstring
.Op Fl d Ar file
.Op Fl i Ar number
.Op Fl o Ar i | s | b | o
.Op Fl s Ar string
.Op Fl U Ar uuid
.Ar path
.Sh DESCRIPTION
The
.Nm
utility calls the ACPI method
.Ar path
with the arguments specified by any
.Fl b ,
.Fl i ,
.Fl o ,
.Fl s ,
and
.Fl U
options.
The
.Ar path
argument must be a full ACPI namespace path such as
.Pa \e_SB.PCI0.PEGR.GFX0._DSM .
.Pp
Note that in order to be able to use the
.Nm
utility, the
.Va debug.acpi.allow_method_calls
loader tunable must be specified in
.Pa /boot/loader.conf .
.Pp
The following options are supported:
.Bl -tag -width indent
.It Fl b Ar hexstring
Pass
.Ar hexstring
as a buffer argument.
.It Fl d Ar file
Specify the path of the ACPI control device.
The default is
.Pa /dev/acpi .
.It Fl i Ar number
Pass
.Ar number
as an integer argument.
.It Fl o Ar i | s | b | o
Choose the format to print the result in:
.Ar ( i ) Ns nteger ,
.Ar ( s ) Ns tring ,
.Ar ( b ) Ns uffer ,
or
.Ar ( o ) Ns bject .
.It Fl s Ar string
Pass
.Ar string
as a string argument.
.It Fl U Ar uuid
Pass
.Ar uuid
as a buffer argument.
.It Fl v
Increase verbosity.
.El
.Sh EXAMPLES
Note that many ACPI methods are specific to the BIOS and machine in
question, so it is impossible to present any generic examples that will
work everywhere.
Some familiarity with ASL and the DSDT code of the specific machine to
be tweaked is highly recommended.
.Pp
The following calls were successfully used to turn off the discrete
.Tn NVIDIA
GPU on the
.Tn Optimus
based
.Tn Asus K53SV
laptop:
.Bd -literal
acpicall -U a486d8f8-0bda-471b-a72b-6042a6b5bee0 \e
         -i 256 -i 26 -b 01000003 "\e_SB.PCI0.PEGR.GFX0._DSM"

acpicall "\e_SB.PCI0.PEGR.GFX0._PS3"
.Ed
.Sh SEE ALSO
.Xr acpi 4 ,
.Xr acpibin 8 ,
.Xr acpiconf 8 ,
.Xr acpidump 8 ,
.Xr acpiexec 8 ,
.Xr acpihelp 8 ,
.Xr acpixtract 8 ,
.Xr iasl 8
.Sh AUTHORS
.Nm
is based on the
.Nm acpi_call
utility by
.An Maxim Ignatenko Aq Mt gelraen.ua@gmail.com .
This manual page was written by
.An Sascha Wildner .
