#
# $FreeBSD: src/gnu/lib/libgmp/doc/Makefile,v 1.8 1999/08/27 23:32:51 peter Exp $
# $DragonFly: src/gnu/lib/libgmp/doc/Attic/Makefile,v 1.2 2003/06/17 04:25:44 dillon Exp $
#
INFO = gmp
INFOSECTION= "Programming & development tools."

SRCDIR= ${.CURDIR}/../../../../contrib/libgmp

.include <bsd.info.mk>
