# $FreeBSD: src/usr.bin/catman/Makefile,v 1.1 2002/05/18 09:19:07 markm Exp $
# $DragonFly: src/usr.bin/catman/Makefile,v 1.2 2005/01/16 04:28:00 cpressey Exp $

PROG=	catman
WARNS?=	6

.include <bsd.prog.mk>
