#	@(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: src/libexec/Makefile,v 1.42.2.5 2002/11/12 17:32:48 obrien Exp $

SUBDIR=	atrun \
	bootpd \
	comsat \
	customcc \
	dma \
	fingerd \
	ftpd \
	getty \
	makekey \
	makewhatis.local \
	mknetid \
	pppoed \
	rbootd \
	revnetgroup \
	rpc.rquotad \
	rpc.rstatd \
	rpc.rusersd \
	rpc.rwalld \
	rpc.sprayd \
	rtld-elf \
	sftp-server \
	ssh-keysign \
	ssh-pkcs11-helper \
	talkd \
	tcpd \
	telnetd \
	tftpd \
	utmp_update \
	ypxfr

# maximum parallelism
#
SUBDIR_ORDERED=

.include <bsd.subdir.mk>
