#	@(#)Makefile.inc	8.1 (Berkeley) 6/4/93
# $FreeBSD: src/lib/libc/amd64/net/Makefile.inc,v 1.6 1999/08/27 23:59:24 peter Exp $
# $DragonFly: src/lib/libcr/amd64/net/Attic/Makefile.inc,v 1.1 2004/03/13 19:46:55 eirikn Exp $

SRCS+=	htonl.S htons.S ntohl.S ntohs.S
