# Makefile copyright Andreas Klemm <andreas@FreeBSD.ORG> 1998
#
# $FreeBSD: src/gnu/usr.bin/dc/doc/Makefile,v 1.4 1999/08/27 23:35:31 peter Exp $
# $DragonFly: src/gnu/usr.bin/dc/doc/Attic/Makefile,v 1.2 2003/06/17 04:25:45 dillon Exp $

.PATH:	${.CURDIR}/../../../../contrib/bc/doc

INFO = dc
INFOSECTION= "System Utilities"
INFOENTRY_dc= "* DC: (dc).			The GNU Desktop Calculator."

.include <bsd.info.mk>
