#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.sbin/edquota/Makefile,v 1.2.14.2 2002/03/22 19:14:54 mikeh Exp $
# $DragonFly: src/usr.sbin/edquota/Makefile,v 1.2 2003/06/17 04:29:53 dillon Exp $

PROG=	edquota
WARNS?=	2
MAN=	edquota.8

.include <bsd.prog.mk>
