# $FreeBSD: src/kerberos5/tools/Makefile,v 1.2 2004/02/01 09:30:02 ru Exp $
# $DragonFly: src/kerberos5/tools/Makefile,v 1.2 2005/07/14 18:02:33 joerg Exp $

SUBDIR=	make-print-version make-roken asn1_compile

buildincludes: depend

.include <bsd.subdir.mk>
