# $FreeBSD: src/gnu/usr.bin/groff/src/libs/Makefile,v 1.1 2001/04/17 12:37:08 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/libs/Makefile,v 1.3 2005/09/01 20:47:13 asmodai Exp $

SUBDIR=		libgroff libdriver libbib

.include <bsd.subdir.mk>
