#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/locate/Makefile,v 1.6 1999/08/28 01:02:52 peter Exp $
# $DragonFly: src/usr.bin/locate/Makefile,v 1.3 2004/01/31 06:56:44 dillon Exp $

SUBDIR=	bigram code locate

.include <bsd.subdir.mk>
