# $FreeBSD: src/sbin/kget/Makefile,v 1.3.2.2 2001/04/25 10:58:28 ru Exp $
# $DragonFly: src/sbin/kget/Makefile,v 1.4 2006/10/17 00:55:41 pavalos Exp $
#
PROG=	kget
MAN=	kget.8

.include <bsd.prog.mk>
