# $FreeBSD: src/sbin/kget/Makefile,v 1.3.2.2 2001/04/25 10:58:28 ru Exp $
# $DragonFly: src/sbin/kget/Makefile,v 1.3 2005/01/15 08:36:25 cpressey Exp $
#
PROG=	kget
WARNS?=	6
MAN=	kget.8

.include <bsd.prog.mk>
