# $DragonFly: src/gnu/usr.bin/cc41/cc_tools/fini/Attic/Makefile,v 1.1 2006/09/27 12:10:34 corecode Exp $

.include "../Makefile.inc"

.PATH:	${GCCDIR}/gcc/f

PROG=	fini
SRCS=	fini.c

.include <bsd.hostprog.mk>
