#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/env/Makefile,v 1.2.6.1 2001/08/02 02:25:58 obrien Exp $
# $DragonFly: src/usr.bin/env/Makefile,v 1.2 2003/06/17 04:29:26 dillon Exp $

PROG=	env
WARNS?=	2
NOMAN=	noman

.include <bsd.prog.mk>
