# $DragonFly: src/lib/pam_module/pam_radius/Makefile,v 1.2 2005/07/28 19:25:41 joerg Exp $

LIB=	pam_radius
SRCS=	pam_radius.c
MAN=	pam_radius.8

DPADD=	${LIBRADIUS}
LDADD=	-lradius

.include <bsd.lib.mk>
