# $DragonFly: src/sys/dev/netif/owi/Attic/Makefile,v 1.1 2004/09/05 13:34:56 joerg Exp $

KMOD=	if_owi
SRCS=	if_owi.c if_owi_pccard.c if_owi_pci.c owi_hostap.c \
	card_if.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
