# Testcase				type		Options			Command line arguments
io/kqueue_1/kqueue_1			userland	defaults
io/kqueue_2/kqueue_2			userland	defaults
io/pselect_1/pselect_1			userland	defaults
io/select_1/select_1			userland	defaults
io/select_2/select_2			userland	defaults
io/select_3/select_3			userland	defaults
io/select_4/select_4			userland	defaults
io/sendfd_1/sendfd_1			userland	timeout=20

mem/mmap_madvise_1/mmap_madvise_1	userland	defaults
mem/mmap_1/mmap_1			userland	timeout=300		200000

priv/setreuid/setreuid			userland	runas=nobody

compiler/div128/div128			buildonly	defaults

threads/umtx_errno/umtx_errno		userland	timeout=300		20000

crypto/aes/aestest			userland	defaults		ecbnk44.txt
crypto/aes/aestest			userland	defaults		ecbnk48.txt
crypto/aes/aestest			userland	defaults		ecbnt44.txt
crypto/aes/aestest			userland	defaults		ecbnt48.txt
crypto/aes/aestest			userland	defaults		ecbvk44.txt
crypto/aes/aestest			userland	defaults		ecbvk48.txt
crypto/aes/aestest			userland	defaults		ecbvt44.txt
crypto/aes/aestest			userland	defaults		ecbvt48.txt
crypto/aesctr/aesctr			userland	defaults
crypto/aesxts/aes_xts			userland	defaults
crypto/serpent/serpent_test		userland	defaults		serpentecb_vk.txt
crypto/serpent/serpent_test		userland	defaults		serpentecb_vt.txt
crypto/twofish/twofish_test		userland	defaults		twofishecb_vk.txt
crypto/twofish/twofish_test		userland	defaults		twofishecb_vt.txt

sysv/sysvmsg/msgtest			userland	defaults		./msgtest
sysv/sysvsem/semtest			userland	defaults		./semtest
sysv/sysvshm/shmtest			userland	defaults		./shmtest

