# Testcase				type		Options			Command line arguments
sample/test1/test1			userland	defaults		arg1 "arg 2" arg3 arg4
sample/test1/test1			userland	make=gmake
sample/test2/test2			userland	defaults
sample/test3/test3			userland	defaults
sample/test4/test4			userland	timeout=30
sample/test5/test5			userland	defaults
sample/test5/test5			userland	nobuild
sample/testk1/testk1.ko			kernel		defaults
sample/testb1/testb1			buildonly	defaults

io/kqueue_1/kqueue_1			userland	defaults
io/kqueue_2/kqueue_2			userland	defaults
io/pselect_1/pselect_1			userland	defaults
io/select_1/select_1			userland	defaults
io/select_2/select_2			userland	defaults
io/select_3/select_3			userland	defaults
io/select_4/select_4			userland	defaults
io/sendfd_1/sendfd_1			userland	timeout=20

mem/mmap_madvise_1/mmap_madvise_1	userland	defaults
mem/mmap_1/mmap_1			userland	timeout=300		200000

priv/setreuid/setreuid			userland	runas=nobody

compiler/div128/div128			buildonly	defaults

threads/umtx_errno/umtx_errno		userland	timeout=300		20000

crypto/aes/aestest			userland	defaults		ecbnk44.txt
crypto/aes/aestest			userland	defaults		ecbnk48.txt
crypto/aes/aestest			userland	defaults		ecbnt44.txt
crypto/aes/aestest			userland	defaults		ecbnt48.txt
crypto/aes/aestest			userland	defaults		ecbvk44.txt
crypto/aes/aestest			userland	defaults		ecbvk48.txt
crypto/aes/aestest			userland	defaults		ecbvt44.txt
crypto/aes/aestest			userland	defaults		ecbvt48.txt
crypto/aesctr/aesctr			userland	defaults
crypto/aesxts/aes_xts			userland	defaults
crypto/serpent/serpent_test		userland	defaults		serpentecb_vk.txt
crypto/serpent/serpent_test		userland	defaults		serpentecb_vt.txt
crypto/twofish/twofish_test		userland	defaults		twofishecb_vk.txt
crypto/twofish/twofish_test		userland	defaults		twofishecb_vt.txt

# POSIX IPC tests
posixipc/close_unnamed_semaphore/close_unnamed_semaphore        userland        defaults
posixipc/create_excl_existing_sem/create_excl_existing_sem      userland        defaults
posixipc/create_unnamed_semaphore/create_unnamed_semaphore      userland        defaults
posixipc/destroy_named_semaphore/destroy_named_semaphore        userland        defaults
posixipc/file_test/file_test                                    userland        defaults
posixipc/init_bad_value/init_bad_value                          userland        defaults
posixipc/max_value/max_value                                    userland        defaults
posixipc/open_after_unlink/open_after_unlink                    userland        defaults
posixipc/open_bad_value/open_bad_value                          userland        defaults
posixipc/open_extra_flags/open_extra_flags                      userland        defaults
posixipc/open_invalid_path/open_invalid_path                    userland        defaults
posixipc/open_named_semaphore/open_named_semaphore              userland        defaults
posixipc/open_non_existing/open_non_existing                    userland        defaults
posixipc/open_path_too_long/open_path_too_long                  userland        defaults
posixipc/post_test/post_test                                    userland        defaults
posixipc/timedwait_expired/timedwait_expired                    userland        defaults
posixipc/timedwait_locked/timedwait_locked                      userland        defaults
posixipc/timedwait_unlocked/timedwait_unlocked                  userland        defaults
posixipc/trywait_locked/trywait_locked                          userland        defaults
posixipc/trywait_unlocked/trywait_unlocked                      userland        defaults
posixipc/unlink_path_too_long/unlink_path_too_long              userland        defaults
posixipc/use_after_unlink/use_after_unlink                      userland        defaults
posixipc/wait_locked/wait_locked                                userland        defaults
posixipc/wait_two_proc/wait_two_proc                            userland        defaults
posixipc/wait_unlocked/wait_unlocked                            userland        defaults

#openat_1		userland	intpre,intpost,timeout=100
#openat_1		userland	intpre,intpost,timeout=100
#openat_1		userland	intpre,intpost,timeout=100
#openat_1		userland	intpre,intpost,timeout=100
#openat_1		userland	intpre,intpost,timeout=100
#openat_1		userland	intpre,intpost,timeout=100
#openat_1		userland	intpre,intpost,timeout=100
#openat_2		userland	defaults
#openat_3		userland	pre=openat_pre,post=openat_post
