#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/sbin/dumpfs/Makefile,v 1.2.14.1 2001/04/25 10:58:16 ru Exp $
# $DragonFly: src/sbin/dumpfs/Makefile,v 1.3 2005/01/14 06:02:45 cpressey Exp $

PROG=	dumpfs
WARNS?=	6
MAN=	dumpfs.8

.include <bsd.prog.mk>
