# $DragonFly: src/sys/emulation/ndis/Makefile,v 1.1 2004/07/29 20:51:33 dillon Exp $
#

KMOD=	ndis
SRCS=	subr_pe.c subr_ndis.c subr_hal.c subr_ntoskrnl.c kern_ndis.c
SRCS+=	opt_bdg.h device_if.h bus_if.h pci_if.h vnode_if.h

.include <bsd.kmod.mk>

