# $DragonFly: src/sys/emulation/ndis/Makefile,v 1.2 2004/08/13 17:51:08 dillon Exp $
#

KMOD=	ndis
SRCS=	subr_pe.c subr_ndis.c subr_hal.c subr_ntoskrnl.c kern_ndis.c
SRCS+=	opt_bdg.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>

