#	@(#)Makefile	8.1 (Berkeley) 3/31/94
# $FreeBSD: src/games/random/Makefile,v 1.1.1.1.14.2 2003/02/15 10:34:35 seanc Exp $
# $DragonFly: src/games/random/Makefile,v 1.4 2006/10/08 16:22:36 pavalos Exp $

PROG=	random
MAN=	random.6
SRCS=	random.c randomize_fd.c

.include <bsd.prog.mk>
