# $FreeBSD: src/sys/modules/netgraph/hole/Makefile,v 1.1.4.3 2001/12/21 09:00:48 ru Exp $
# $DragonFly: src/sys/netgraph/hole/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:21 archie Exp $

KMOD=		ng_hole
SRCS= 		ng_hole.c
KMODDEPS=	netgraph

.include <bsd.kmod.mk>
