# $FreeBSD: src/release/picobsd/tinyware/sps/Makefile,v 1.2 1999/08/28 01:34:00 peter Exp $
# $DragonFly: src/release/picobsd/tinyware/sps/Attic/Makefile,v 1.2 2003/06/17 04:27:21 dillon Exp $
#
PROG=sps
SRCS= 	sps.c
NOMAN=yes

.include <bsd.prog.mk>


