#
# $DragonFly: doc/en/articles/new-bsdusers/Makefile,v 1.2 2005/08/14 09:18:30 asmodai Exp $
#
# Article: DragonFly Quick Start

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
