#
# $DragonFly: doc/en/articles/new-bsdusers/Makefile,v 1.3 2005/08/14 21:03:37 asmodai Exp $
#
# Article: DragonFly Quick Start

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
