# $FreeBSD: src/gnu/usr.bin/groff/src/utils/pfbtops/Makefile,v 1.1.2.1 2001/04/26 17:08:40 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/utils/pfbtops/Makefile,v 1.2 2003/06/17 04:25:46 dillon Exp $

PROG=		pfbtops
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
