# $FreeBSD: src/share/doc/IPv6/Makefile,v 1.1.2.1 2002/02/18 15:03:33 ru Exp $
# $DragonFly: src/share/doc/IPv6/Makefile,v 1.2 2003/06/17 04:36:56 dillon Exp $

NOOBJ=		noobj
FILES=		IMPLEMENTATION
FILESDIR=	${SHAREDIR}/doc/IPv6

.include <bsd.prog.mk>
