# decompression functionality from libz for libstand

# relative to stand/lib
ZLIBDIR= ${LIBSTAND_SRC}/../../contrib/zlib
.PATH: ${ZLIBDIR}

CFLAGS+=-DCOMPILING_LIBSTAND -I${ZLIBDIR}
SRCS+=	adler32.c crc32.c deflate.c infback.c inffast.c inflate.c \
	inftrees.c zutil.c
