# $DragonFly: src/sys/dev/acpica5/acpi_thinkpad/Makefile,v 1.1 2008/08/28 07:10:05 hasso Exp $

KMOD=		acpi_thinkpad
CFLAGS+=	-I${.OBJDIR}/.. -I${.CURDIR}/..
SRCS=		acpi_thinkpad.c opt_acpi.h device_if.h bus_if.h

.include <bsd.kmod.mk>
