#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/share/man/man8/man8.alpha/Makefile,v 1.7.2.2 2001/04/25 11:11:33 ru Exp $
# $DragonFly: src/share/man/man8/man8.alpha/Attic/Makefile,v 1.2 2003/06/17 04:37:01 dillon Exp $

MAN=	MAKEDEV.8
MANSUBDIR=/alpha

.include <bsd.prog.mk>
