# $FreeBSD: src/usr.bin/rpcgen/Makefile,v 1.5.6.1 2001/04/25 11:29:34 ru Exp $
# $DragonFly: src/usr.bin/rpcgen/Makefile,v 1.4 2007/08/27 16:50:58 pavalos Exp $

PROG=	rpcgen
SRCS=	rpc_main.c  rpc_clntout.c rpc_cout.c rpc_hout.c rpc_parse.c \
	rpc_sample.c rpc_scan.c rpc_svcout.c rpc_tblout.c rpc_util.c

.include <bsd.prog.mk>
