# $FreeBSD: src/sys/boot/i386/btx/Makefile,v 1.6 1999/08/28 00:40:03 peter Exp $
# $DragonFly: src/sys/boot/i386/btx/Attic/Makefile,v 1.3 2003/11/10 06:08:35 dillon Exp $

SUBDIR=	btx btxldr lib

.include <bsd.subdir.mk>
