# $FreeBSD: src/sys/boot/i386/btx/Makefile.inc,v 1.1 2003/06/26 03:51:57 peter Exp $
# $DragonFly: src/sys/boot/i386/btx/Attic/Makefile.inc,v 1.1 2003/11/10 06:08:35 dillon Exp $
.include <${.CURDIR}/../../Makefile.inc>
