NOOBJ=

FILES=	README \
	ftpd \
	gdm \
	imap \
	login \
	other \
	passwd \
	pop3 \
	sshd \
	su \
	system \
	telnetd \
	xdm \
	xserver

FILESDIR= /etc/pam.d
FILESMODE= 644
FILESMODE_README= 444
LINKS=	${FILESDIR}/ftpd ${FILESDIR}/ftp

.include <bsd.prog.mk>
