# $FreeBSD: src/sys/modules/splash/bmp/Makefile,v 1.2.2.2 2002/12/01 09:01:08 nyan Exp $
# $DragonFly: src/sys/dev/video/fb/bmp/Makefile,v 1.3 2003/10/06 17:19:36 dillon Exp $

.PATH:	${.CURDIR}/..
KMOD=	splash_bmp
SRCS= 	splash_bmp.c splash.c

NOMAN=

.include <bsd.kmod.mk>
