# $FreeBSD: src/sys/modules/splash/bmp/Makefile,v 1.2.2.2 2002/12/01 09:01:08 nyan Exp $
# $DragonFly: src/sys/dev/video/fb/bmp/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $

KMOD=	splash_bmp
SRCS= 	splash_bmp.c

NOMAN=

.include <bsd.kmod.mk>
