# $FreeBSD: src/sys/modules/netgraph/ksocket/Makefile,v 1.1.4.3 2001/12/21 09:00:48 ru Exp $
# $DragonFly: src/sys/netgraph/ksocket/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $

KMOD=		ng_ksocket
SRCS= 		ng_ksocket.c

.include <bsd.kmod.mk>
