# $FreeBSD: src/sbin/ip6fw/Makefile,v 1.1.2.1 2001/04/25 10:58:23 ru Exp $
# $DragonFly: src/sbin/ip6fw/Makefile,v 1.3 2006/10/17 00:55:41 pavalos Exp $

PROG=   ip6fw
MAN=	ip6fw.8
WARNS?=	2

.include <bsd.prog.mk>
