# $DragonFly: src/sys/dev/pccard/pccbb/Makefile,v 1.1 2004/02/10 07:55:47 joerg Exp $

KMOD=   cbb
SRCS=   pccbb.c \
	device_if.h bus_if.h pci_if.h pcib_if.h power_if.h card_if.h
NOMAN=

.include <bsd.kmod.mk>
