#	$Id: Makefile,v 9.0 2012/10/19 15:13:11 zy Exp $
# $FreeBSD: head/usr.bin/vi/catalog/Makefile 254244 2013-08-12 09:56:52Z peter $

.PATH: ${.CURDIR}/../../../contrib/nvi2/catalog

PROG=	vidump
SRCS=	dump.c

.include <bsd.hostprog.mk>
