#	$OpenBSD: Makefile,v 1.1 2003/09/19 17:58:25 otto Exp $
#	$DragonFly: src/usr.bin/dc/Makefile,v 1.1 2004/09/20 04:20:39 dillon Exp $

PROG=	dc
SRCS=	dc.c bcode.c inout.c mem.c stack.c
COPTS+= -Wall
LDADD=	-lcrypto

.include <bsd.prog.mk>
