#	@(#)Makefile	8.2 (Berkeley) 4/18/94
# $FreeBSD: src/usr.sbin/arp/Makefile,v 1.4.6.2 2002/03/15 22:50:14 mikeh Exp $
# $DragonFly: src/usr.sbin/arp/Makefile,v 1.3 2005/01/17 01:49:24 cpressey Exp $

PROG=	arp
MAN=	arp.8

.include <bsd.prog.mk>
