# $NetBSD: Makefile,v 1.7 2003/08/03 09:23:15 lukem Exp $	
# $DragonFly: src/lib/libedit/readline/Makefile,v 1.2 2008/06/27 08:06:48 corecode Exp $

NOOBJ=		# defined

.include <bsd.own.mk>

.PATH:	${NETBSDSRCDIR}/lib/libedit

INCS=		readline.h tilde.h history.h
INCSDIR=	/usr/include/readline

.include <bsd.prog.mk>
