# $NetBSD: Makefile,v 1.7 2003/08/03 09:23:15 lukem Exp $	
# $DragonFly: src/lib/libedit/readline/Makefile,v 1.1 2005/11/13 11:58:30 corecode Exp $

NOOBJ=		# defined

.include <bsd.own.mk>

.PATH:	${NETBSDSRCDIR}/lib/libedit

INCS=		readline.h
INCSDIR=	/usr/include/readline
INCSYMLINKS=	readline.h ${INCSDIR}/history.h

.include <bsd.prog.mk>
