# $FreeBSD: src/gnu/usr.bin/groff/src/devices/Makefile,v 1.1 2001/04/17 12:37:02 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/devices/Makefile,v 1.3 2005/09/01 20:47:12 asmodai Exp $

SUBDIR=		grodvi grohtml grolbp grolj4 grops grotty

.include <bsd.subdir.mk>
