#	From: @(#)Makefile	8.1 (Berkeley) 6/9/93
# $FreeBSD: src/usr.bin/expand/Makefile,v 1.2.6.2 2002/07/09 10:42:30 tjr Exp $
# $DragonFly: src/usr.bin/expand/Makefile,v 1.2 2003/06/17 04:29:26 dillon Exp $

PROG=	expand
MLINKS=	expand.1 unexpand.1

.include <bsd.prog.mk>
