# $FreeBSD: src/gnu/usr.bin/groff/font/devascii/Makefile,v 1.1 2001/04/17 12:36:46 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/font/devascii/Makefile,v 1.3 2005/09/01 20:47:12 asmodai Exp $

DEV=		ascii

.include "../Makefile.tty"
.include "../Makefile.dev"
