#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.sbin/rwhod/Makefile,v 1.2.14.1 2001/04/25 12:10:49 ru Exp $
# $DragonFly: src/usr.sbin/rwhod/Makefile,v 1.3 2005/03/17 15:39:34 joerg Exp $

PROG=	rwhod
MAN=	rwhod.8
WARNS?=	6

.include <bsd.prog.mk>
