# $FreeBSD: src/gnu/usr.bin/groff/contrib/Makefile.inc,v 1.1.2.1 2001/04/26 17:07:55 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/contrib/Makefile.inc,v 1.2 2003/06/17 04:25:45 dillon Exp $

DIST_SUBDIR=	contrib/${.CURDIR:T}
TOPREL=		../..

.include "../Makefile.inc"
