# $FreeBSD: src/gnu/usr.bin/groff/contrib/Makefile,v 1.1 2001/04/17 12:36:32 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/contrib/Makefile,v 1.3 2005/09/01 20:47:11 asmodai Exp $

SUBDIR=		mm

.include <bsd.subdir.mk>
