# $FreeBSD: src/gnu/usr.bin/groff/contrib/Makefile,v 1.1.2.1 2001/04/26 17:07:55 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/contrib/Makefile,v 1.2 2003/06/17 04:25:45 dillon Exp $

SUBDIR=		mm

.include <bsd.subdir.mk>
