#	$NetBSD: Makefile,v 1.2 1998/07/12 20:40:45 augustss Exp $
#	$FreeBSD: src/usr.sbin/usbdevs/Makefile,v 1.5.2.1 2001/04/25 12:11:08 ru Exp $
#	$DragonFly: src/usr.sbin/usbdevs/Makefile,v 1.4 2005/01/17 01:49:24 cpressey Exp $

PROG=	usbdevs
WARNS?=	6
MAN=	usbdevs.8
CFLAGS+=-I${.CURDIR}/../../sys

.include <bsd.prog.mk>
