# $FreeBSD: src/sys/modules/ti/Makefile,v 1.8.2.1 2001/12/04 20:01:53 brooks Exp $
# $DragonFly: src/sys/dev/netif/ti/Makefile,v 1.3 2005/06/14 13:34:52 joerg Exp $

KMOD	= if_ti
SRCS	= if_ti.c opt_bdg.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
