# $FreeBSD: src/sbin/newfs_msdos/Makefile,v 1.2.2.2 2001/04/25 10:58:42 ru Exp $
# $DragonFly: src/sbin/newfs_msdos/Makefile,v 1.4 2006/10/17 00:55:43 pavalos Exp $

PROG=	newfs_msdos
MAN=	newfs_msdos.8
WARNS?=	2

.include <bsd.prog.mk>
