.PATH: ${.CURDIR}/../../../usr.bin/strfile

PROG=	strfile
CFLAGS+=-I${.CURDIR}/../../../usr.bin/strfile

build-tools: strfile.nx

# this strfile is used in place, it is not installed anywhere
install:

.include <bsd.hostprog.mk>
