# $FreeBSD: src/usr.sbin/burncd/Makefile,v 1.2.2.1 2001/04/25 12:09:21 ru Exp $
# $DragonFly: src/usr.sbin/burncd/Makefile,v 1.2 2003/06/17 04:29:52 dillon Exp $

PROG=	burncd
MAN=	burncd.8

.include <bsd.prog.mk>
