# $FreeBSD: src/usr.bin/killall/Makefile,v 1.3.2.1 2000/09/09 23:58:19 ps Exp $
# $DragonFly: src/usr.bin/killall/Makefile,v 1.3 2005/05/13 21:31:49 joerg Exp $

PROG=	killall
WARNS?=	6

.include <bsd.prog.mk>
