# $DragonFly: src/lib/pam_module/pam_deny/Makefile,v 1.1 2005/07/08 15:42:01 joerg Exp $

LIB=	pam_deny
SRCS=	pam_deny.c
WARNS?=	6
WARNS_NO_UNUSED_PARAMETERS=

.include <bsd.lib.mk>

.PATH: ${OPENPAM_DIR}/modules/pam_deny
