# $DragonFly: src/gnu/usr.bin/cc40/cc_tools/genpeep/Attic/Makefile,v 1.1 2005/06/05 22:43:21 corecode Exp $

.include "../Makefile.inc"
.include "../../Makefile.langs"

PROG=	genpeep
SRCS=	genpeep.c insn-modes.h gtype-desc.h insn-constants.h tm-preds.h options.h
SRCS+=	${RTL_SRCS} ${SUPPORT_SRCS} ${PRINT_SRCS} ${ERRORS_SRCS}

.include <bsd.hostprog.mk>
