# $FreeBSD: src/sys/modules/snp/Makefile,v 1.3.2.1 2002/03/11 01:24:44 dd Exp $
# $DragonFly: src/sys/dev/misc/snp/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $

.PATH: ${.CURDIR}/../../dev/snp

KMOD=	snp
SRCS=	snp.c vnode_if.h

.include <bsd.kmod.mk>
