# $FreeBSD: src/usr.bin/lockf/Makefile,v 1.4 1999/08/28 01:03:05 peter Exp $
# $DragonFly: src/usr.bin/lockf/Makefile,v 1.3 2005/01/05 00:46:52 cpressey Exp $

PROG=	lockf
CFLAGS+=-Wall
WARNS?=	6

.include <bsd.prog.mk>
