# $FreeBSD: src/usr.bin/lockf/Makefile,v 1.4 1999/08/28 01:03:05 peter Exp $
# $DragonFly: src/usr.bin/lockf/Makefile,v 1.2 2003/06/17 04:29:28 dillon Exp $

PROG=	lockf
CFLAGS+=-Wall

.include <bsd.prog.mk>
