# $FreeBSD: src/usr.sbin/pcvt/Misc/Makefile,v 1.3.6.1 2002/02/18 15:03:37 ru Exp $
# $DragonFly: src/usr.sbin/pcvt/Misc/Attic/Makefile,v 1.2 2003/06/17 04:29:59 dillon Exp $

NOOBJ=	noobj
FILES=	README.FIRST
SUBDIR=	Doc Etc

.include "Makefile.inc"
.include <bsd.prog.mk>
