# $FreeBSD: src/usr.sbin/pcvt/Misc/Makefile.inc,v 1.3.6.1 2002/02/18 15:03:37 ru Exp $
# $DragonFly: src/usr.sbin/pcvt/Misc/Attic/Makefile.inc,v 1.2 2003/06/17 04:29:59 dillon Exp $

DISTRIBUTION=	doc
BINDIR=		${SHAREDIR}/pcvt
