# $FreeBSD: src/gnu/usr.bin/cvs/Makefile,v 1.13.2.3 2002/12/19 21:18:01 peter Exp $
# $DragonFly: src/gnu/usr.bin/cvs/Makefile,v 1.4 2005/09/10 11:55:42 asmodai Exp $

SUBDIR = lib libdiff cvs contrib doc

.include <bsd.subdir.mk>
