# $FreeBSD: src/gnu/usr.bin/cvs/Makefile,v 1.13.2.3 2002/12/19 21:18:01 peter Exp $
# $DragonFly: src/gnu/usr.bin/cvs/Makefile,v 1.2 2003/06/17 04:25:45 dillon Exp $

MAINTAINER=	peter@FreeBSD.org

SUBDIR = lib libdiff cvs contrib cvsbug doc

.include <bsd.subdir.mk>
