# $DragonFly: src/usr.bin/make/Makefile.dist,v 1.3 2005/01/06 11:35:27 okumoto Exp $
# a very simple makefile...
pmake:
	@echo 'make started.'
	cc -DDEFSHELL=1 -I. -c *.c
	cc *.o -o pmake
	@echo 'make completed.'
