# $FreeBSD: src/etc/periodic/Makefile,v 1.2.2.1 2002/02/25 10:53:28 cjc Exp $
# $DragonFly: src/etc/periodic/Makefile,v 1.2 2003/06/17 04:24:48 dillon Exp $

SUBDIR=	daily security weekly monthly

.include <bsd.subdir.mk>
