# XXX Some notes

# Declare Name of kernel module
KMOD	= if_lgue

# Enumerate Source files for kernel module
SRCS	= if_lgue.c opt_usb.h device_if.h bus_if.h

# Include kernel module makefile
.include <bsd.kmod.mk>
