# $FreeBSD: src/gnu/lib/libreadline/Makefile,v 1.34 2000/01/29 12:01:51 obrien Exp $
# $DragonFly: src/gnu/lib/libreadline/Attic/Makefile,v 1.2 2003/06/17 04:25:44 dillon Exp $

SUBDIR = history readline

.include <bsd.subdir.mk>
