#	From: @(#)Makefile	8.2 (Berkeley) 2/28/94
# $FreeBSD: src/share/doc/smm/08.sendmailop/Makefile,v 1.5.2.1 2000/10/26 23:05:13 gshapiro Exp $
# $DragonFly: src/share/doc/smm/08.sendmailop/Makefile,v 1.3 2004/01/31 06:56:41 dillon Exp $

VOLUME=	smm/08.sendmailop
SRCS=	op.me
MACROS=	-me

SRCDIR=	${.CURDIR}/../../../../contrib/sendmail/doc/op

USE_PIC=	yes
USE_EQN=	yes

.include <bsd.doc.mk>
