# $FreeBSD: src/sys/modules/tx/Makefile,v 1.4.2.4 2002/10/29 01:43:50 semenu Exp $

KMOD	= if_tx
SRCS	= if_tx.c device_if.h bus_if.h pci_if.h pcidevs.h
SRCS	+= miibus_if.h miidevs.h

.include <bsd.kmod.mk>
