#	@(#)Makefile	8.2 (Berkeley) 4/22/94
# $FreeBSD: src/sbin/nologin/Makefile,v 1.6.6.2 2001/04/25 14:04:15 ru Exp $
# $DragonFly: src/sbin/nologin/Makefile,v 1.3 2008/02/05 10:58:04 matthias Exp $

PROG=	nologin
SRCS=	nologin.c
MAN=	nologin.5 nologin.8

.include <bsd.prog.mk>
