#	@(#)Makefile	8.2 (Berkeley) 4/22/94
# $FreeBSD: src/sbin/nologin/Makefile,v 1.6.6.2 2001/04/25 14:04:15 ru Exp $
# $DragonFly: src/sbin/nologin/Makefile,v 1.2 2003/06/17 04:27:34 dillon Exp $

SCRIPTS=nologin.sh
MAN=	nologin.5 nologin.8

.include <bsd.prog.mk>
