# $FreeBSD: src/sys/modules/syscons/Makefile.inc,v 1.2 1999/08/28 00:47:44 peter Exp $
# $DragonFly: src/sys/dev/misc/syscons/Makefile.inc,v 1.2 2003/06/17 04:28:47 dillon Exp $

.include "../Makefile.inc"
