# $DragonFly: src/sys/dev/usbmisc/Makefile,v 1.5 2007/08/16 20:38:33 hasso Exp $
#

SUBDIR= uark ubsa ucom ufm uftdi ugen uhid ukbd ulpt umass umodem ums umsm \
	uplcom uscanner uslcom uvisor uvscom umct

.include <bsd.subdir.mk>
