# $DragonFly: src/sys/dev/usbmisc/Makefile,v 1.4 2007/08/14 22:28:11 hasso Exp $
#

SUBDIR= uark ubsa ucom ufm uftdi ugen uhid ukbd ulpt umass umodem ums \
	uplcom uscanner uslcom uvisor uvscom umct

.include <bsd.subdir.mk>
