# $DragonFly: src/sys/dev/usbmisc/Makefile,v 1.8 2007/11/07 09:07:44 hasso Exp $
#

SUBDIR= moscom uark ubsa uchcom ucom ufm uftdi ugen uhid ukbd ulpt umass \
	umodem ums umsm uplcom uscanner uslcom uticom uvisor uvscom umct

.include <bsd.subdir.mk>
