# $FreeBSD: src/tools/tools/ath/athregs/Makefile,v 1.2 2009/03/11 17:46:01 sam Exp $

PROG=	athregs

.PATH.c: ${.CURDIR}/../common

SRCS=	dumpregs.c
SRCS+=	dumpregs_5210.c
SRCS+=	dumpregs_5211.c
SRCS+=	dumpregs_5212.c
SRCS+=	dumpregs_5416.c

.include <../Makefile.inc>

.include <bsd.prog.mk>
