#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $DragonFly: src/usr.bin/limits/Makefile,v 1.3 2007/08/27 16:50:55 pavalos Exp $

PROG=	limits

LDADD+= -lutil
DPADD+= ${LIBUTIL}

BINMODE=0555

.include <bsd.prog.mk>
