# $FreeBSD: src/usr.sbin/pppstats/Makefile,v 1.7.2.1 2001/04/25 12:10:35 ru Exp $
# $DragonFly: src/usr.sbin/pppstats/Makefile,v 1.3 2004/01/31 06:56:46 dillon Exp $

PROG=	pppstats
MAN=	pppstats.8

.include <bsd.prog.mk>
