# $FreeBSD: src/usr.sbin/pppstats/Makefile,v 1.7.2.1 2001/04/25 12:10:35 ru Exp $
# $DragonFly: src/usr.sbin/pppstats/Makefile,v 1.2 2003/06/17 04:30:01 dillon Exp $

PROG=	pppstats
MAN=	pppstats.8

#as per policies in handbook
MAINTAINER=	peter@freebsd.org

.include <bsd.prog.mk>
