# $FreeBSD: src/lib/liby/Makefile,v 1.7 1999/08/28 00:05:59 peter Exp $
# $DragonFly: src/lib/liby/Makefile,v 1.4 2005/04/21 13:42:34 joerg Exp $

LIB=		y
SHLIB_MAJOR=	3
WARNS?=		1

SRCS=	main.c yyerror.c

NOPIC=	true

.include <bsd.lib.mk>
