# $FreeBSD: src/lib/liby/Makefile,v 1.7 1999/08/28 00:05:59 peter Exp $
# $DragonFly: src/lib/liby/Makefile,v 1.3 2004/03/20 16:27:40 drhodus Exp $

LIB=		y
SHLIB_MAJOR=	2
SHLIB_MINOR=	0

SRCS=	main.c yyerror.c

NOPIC=	true

.include <bsd.lib.mk>
