# $FreeBSD: src/usr.sbin/vidcontrol/Makefile,v 1.2.6.1 2001/04/25 12:11:09 ru Exp $
# $DragonFly: src/usr.sbin/vidcontrol/Makefile,v 1.4 2007/04/09 09:45:12 swildner Exp $

PROG=	vidcontrol
SRCS=	vidcontrol.c decode.c

.include <bsd.prog.mk>
