#	@(#)Makefile.inc	8.1 (Berkeley) 6/4/93
# $FreeBSD: src/lib/libc/amd64/net/Makefile.inc,v 1.6 1999/08/27 23:59:24 peter Exp $
# $DragonFly: src/lib/libc/amd64/net/Makefile.inc,v 1.1 2004/02/02 05:43:14 dillon Exp $

SRCS+=	htonl.S htons.S ntohl.S ntohs.S
