#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/wump/Makefile,v 1.3.6.3 2002/02/18 16:02:43 ru Exp $
# $DragonFly: src/games/wump/Makefile,v 1.2 2003/06/17 04:25:25 dillon Exp $

PROG=	wump
FILES=	wump.info
MAN=	wump.6
HIDEGAME=hidegame

.include <bsd.prog.mk>
