# $DragonFly: src/usr.bin/ktrdump/Makefile,v 1.1 2005/03/08 01:54:59 hmp Exp $
# $FreeBSD: src/usr.bin/ktrdump/Makefile,v 1.3 2002/06/06 11:27:03 ru Exp $

PROG=	ktrdump
DPADD=	${LIBKVM}
LDADD=	-lkvm
MAN=	ktrdump.8

.include <bsd.prog.mk>
