#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.sbin/chroot/Makefile,v 1.2.14.2 2002/03/15 22:54:59 mikeh Exp $
# $DragonFly: src/usr.sbin/chroot/Makefile,v 1.3 2004/11/28 16:38:21 liamfoy Exp $

PROG=	chroot
WARNS?=	6 	
MAN=	chroot.8

.include <bsd.prog.mk>
