#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/unifdef/Makefile,v 1.1.1.1.14.3 2003/01/29 21:46:39 fanf Exp $
# $DragonFly: src/usr.bin/unifdef/Makefile,v 1.4 2005/01/16 21:14:51 cpressey Exp $

PROG=	unifdef
SCRIPTS=unifdefall.sh
MLINKS=	unifdef.1 unifdefall.1
WARNS?=	6

.include <bsd.prog.mk>
