# $FreeBSD: src/gnu/usr.bin/groff/src/preproc/html/Makefile,v 1.7 2004/12/21 08:47:00 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/preproc/html/Makefile,v 1.3 2005/09/01 20:47:13 asmodai Exp $

PROG_CXX=	pre-grohtml
SRCS=		pre-html.cpp pushback.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
NOMAN=

.include <bsd.prog.mk>
