# $FreeBSD: src/gnu/usr.bin/groff/src/preproc/html/Makefile,v 1.1.2.3 2003/02/14 15:22:14 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/preproc/html/Makefile,v 1.2 2003/06/17 04:25:46 dillon Exp $

PROG_CXX=	pre-grohtml
SRCS=		pre-html.cc pushback.cc
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
NOMAN=		YES

.include <bsd.prog.mk>
