# $FreeBSD: src/sys/modules/union/Makefile,v 1.7 1999/12/12 20:34:11 peter Exp $
# $DragonFly: src/sys/vfs/union/Makefile,v 1.3 2003/08/15 07:26:16 dillon Exp $

KMOD=	union
SRCS=	vnode_if.h \
	union_subr.c union_vfsops.c union_vnops.c
NOMAN=

.include <bsd.kmod.mk>
