# $FreeBSD: src/sys/modules/union/Makefile,v 1.7 1999/12/12 20:34:11 peter Exp $
# $DragonFly: src/sys/vfs/union/Makefile,v 1.4 2004/08/13 17:51:14 dillon Exp $

KMOD=	union
SRCS=	union_subr.c union_vfsops.c union_vnops.c
NOMAN=

.include <bsd.kmod.mk>
