# $FreeBSD: src/sys/modules/vinum/Makefile,v 1.17 2000/01/04 23:46:41 grog Exp $ 

KMOD= vinum

SRCS= opt_vinum.h vinum.c vinumconfig.c vinumdaemon.c \
	vinuminterrupt.c vinumio.c \
	vinumioctl.c vinumlock.c vinummemory.c vinumparser.c \
	vinumraid5.c vinumrequest.c vinumrevive.c vinumstate.c \
	vinumutil.c

.include <bsd.kmod.mk>
