# $FreeBSD: src/usr.bin/c89/Makefile,v 1.1.1.1.8.3 2001/05/22 19:05:01 schweikh Exp $
# $DragonFly: src/usr.bin/c89/Makefile,v 1.3 2005/01/16 19:17:28 joerg Exp $

PROG=	c89
MAN=	c89.1
WARNS?=	6

.include <bsd.prog.mk>
