# $FreeBSD: src/gnu/usr.bin/man/apropos/Makefile,v 1.15.2.1 2001/04/25 14:04:13 ru Exp $

SCRIPTS=apropos.sh
MAN=	apropos.1

LINKS=	${BINDIR}/apropos ${BINDIR}/whatis
MLINKS=	apropos.1 whatis.1

.include <bsd.prog.mk>
