# $FreeBSD: head/lib/libpam/modules/pam_opieaccess/Makefile 275024 2014-11-25 11:07:26Z bapt $

LIB=	pam_opieaccess
SRCS=	pam_opieaccess.c
MAN=	pam_opieaccess.8

DPADD=	${LIBOPIE}
LDADD=	-lopie

.include <bsd.lib.mk>
