# $FreeBSD: src/usr.bin/enigma/Makefile,v 1.3.6.3 2001/07/30 09:59:16 dd Exp $
# $DragonFly: src/usr.bin/enigma/Makefile,v 1.2 2003/06/17 04:29:26 dillon Exp $

PROG=	enigma
WARNS?=	2

LINKS=	${BINDIR}/enigma ${BINDIR}/crypt
MLINKS=	enigma.1 crypt.1

.include <bsd.prog.mk>
