# Used by the device build to check for device support
#

DEV_SUPPORT=	acpica agp bridge crypto disk drm drm2 misc netif \
		pccard powermng raid serial sound usbmisc video \
		virtual/virtio

#SYSCONS_APM_SUPPORT=1
BOOT0CFG_SUPPORT=1

