# Used by the device build to check for device support
#

DEV_SUPPORT=	acpica agp bridge crypto disk drm misc netif \
		pccard powermng raid serial sound smbus video \
		virtual/hyperv virtual/virtio virtual/vmware
