#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/mt/Makefile,v 1.3 1999/08/28 01:04:23 peter Exp $
# $DragonFly: src/usr.bin/mt/Makefile,v 1.3 2004/02/04 14:34:36 rob Exp $

PROG=	mt
CFLAGS+=-I${.CURDIR}/../../sys
CFLAGS+=-D__FreeBSD__

.include <bsd.prog.mk>
