#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/mt/Makefile,v 1.3 1999/08/28 01:04:23 peter Exp $
# $DragonFly: src/usr.bin/mt/Makefile,v 1.5 2007/08/27 16:50:56 pavalos Exp $

PROG=	mt
CFLAGS+=-I${.CURDIR}/../../sys
WARNS?=	1

.include <bsd.prog.mk>
