# $FreeBSD: src/gnu/usr.bin/groff/font/devutf8/Makefile,v 1.1.2.1 2001/04/26 17:08:07 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/font/devutf8/Makefile,v 1.2 2003/06/17 04:25:46 dillon Exp $

DEV=		utf8

.include "../Makefile.tty"
.include "../Makefile.dev"
