.include "../Makefile.inc"

SRCDIR=		${BASEDIR}/doc
INFOSECTION=	"System Utilities"
INFOENTRY_diff=	"* DIFF: (diff).                 DIFF/PATCH Reference Manual."
INFO=		diffutils

.include <bsd.info.mk>
