# $FreeBSD: src/gnu/usr.bin/diff/doc/Makefile,v 1.6 1999/08/27 23:35:33 peter Exp $
# $DragonFly: src/gnu/usr.bin/diff/doc/Makefile,v 1.2 2003/06/17 04:25:45 dillon Exp $

INFO = diff

INFOENTRY_diff= "* DIFF: (diff).                 DIFF/PATCH Reference Manual."

SRCDIR=${.CURDIR}/../../../../contrib/diff

.include <bsd.info.mk>
