#
# Makefile for pccardc/pccardd.
# $FreeBSD: src/usr.sbin/pccard/Makefile,v 1.5 1999/08/28 01:17:30 peter Exp $
# $DragonFly: src/usr.sbin/pccard/Attic/Makefile,v 1.2 2003/06/17 04:29:59 dillon Exp $
#
SUBDIR= pccardc pccardd

.include <bsd.subdir.mk>
