.\"
.\" Copyright (c) 2002 M. Warner Losh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD: /repoman/r/ncvs/src/share/man/man4/cardbus.4,v 1.2 2002/11/29 16:30:04 ru Exp $
.\" $DragonFly: src/share/man/man4/cardbus.4,v 1.2 2007/03/04 20:10:34 swildner Exp $
.\"
.Dd March 4, 2007
.Dt CARDBUS 4
.Os
.Sh NAME
.Nm cardbus
.Nd CardBus bus driver
.Sh SYNOPSIS
.Cd device cardbus
.Sh DESCRIPTION
The
.Nm
driver implements the CardBus bus.
The
.Nm
driver supports all cardbus bridges in the system.
.Sh TUNABLES
.Bl -tag -width ".Va hw.cardbus.cis_debug"
.It Va hw.cardbus.debug
A non-zero value causes more verbose information to be printed when a
32-bit CardBus card is inserted or removed.
.It Va hw.cardbus.cis_debug
A non-zero value causes the CIS parsing of the 32-bit CardBus card to be
much more verbose.
.El
.Sh SEE ALSO
.Xr pccard 4 ,
.Xr pccbb 4
.Sh BUGS
There is no way cause a program to run when a card is inserted.
