.\"	$NetBSD: drm.4,v 1.7 2009/05/12 08:16:46 wiz Exp $
.\"
.\" Copyright (c) 2007 Thomas Klausner
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd September 13, 2013
.Dt DRM 4
.Os
.Sh NAME
.Nm drm
.Nd Direct Rendering Manager (DRI kernel support)
.Sh DESCRIPTION
The
.Tn Direct Rendering Manager
is part of the
.Tn Direct Rendering Infrastructure
(see
.Pa http://dri.freedesktop.org/ )
for supporting video acceleration.
For older chipsets it's used for 3d acceleration only, but newer chipsets
may require
.Nm
for 2d acceleration (XVideo, EXA) as well.
.Pp
The
.Nm
drivers provide support for the following chipsets:
.Pp
.Bl -column -offset -indent ".Sy ModuleXXX" ".Sy DeviceXXX" ".Sy ChipsetXXX"
.It Sy Module Ta Sy Kernel Ta Sy Chipset
.It Pa i915kms.ko Ta n/a Ta Intel i915, i945, i965, G3x, G4x
.It Pa mach64.ko Ta Cd mach64drm Ta Mach64 (3D Rage Pro, Rage)
.It Pa mga.ko Ta Cd mgadrm Ta Matrox G[24]00, G[45]50
.It Pa r128.ko Ta Cd r128drm Ta Rage 128
.It Pa radeon.ko Ta Cd radeondrm Ta Radeon
.It Pa savage.ko Ta Cd savagedrm Ta S3 Savage
.It Pa sis.ko Ta Cd sisdrm Ta SiS
.It Pa tdfx.ko Ta Cd tdfxdrm Ta 3dfx (Voodoo)
.\".It Pa via.ko Ta Cd viadrm Ta VIA
.El
.Pp
In most cases
.Xr Xorg 1
will take care of loading the appropriate modules and it is not necessary to
modify
.Xr loader.conf 5
or the kernel configuration to enable
.Nm
support.
.Pp
Newer versions of
.Xr Xorg 1 ,
like the one from
.Xr dports 7 ,
do a pretty good job of figuring out the right configuration on their own,
so having no
.Xr xorg.conf 5
file at all is usually the best advice.
If for some reason an
.Xr xorg.conf 5
is preferred, DRI must be enabled:
.Pp
.Bd -literal
Section "DRI"
        Group "wheel"
        Mode 0660
EndSection
.Ed
.Pp
With KMS, DRI is always enabled since the
.Nm
is always required.
.\".Pp
.\"In order to use two graphics cards (an on-board and another
.\"AGP/PCI/PCIe card) with DRI, a
.\".Pa /dev/dri/card1
.\"link to
.\".Pa /dev/dri/card0
.\"has to be created using
.\".Xr devfsctl 8 .
.Pp
If
.Xr Xorg 1
acceleration fails to initialize with a
.Dq contigmalloc_map: failed size...
error in dmesg, the reserve of memory for DMA ran out early and should
be increased to a sufficiently high value by setting the
.Va vm.dma_reserved
loader tunable.
A read only
.Xr sysctl 8
variable of the same name is provided for obtaining its current value.
.Pp
Debugging output can be enabled and disabled by setting the
.Xr sysctl 8
node
.Ar hw.dri.0.debug .
.Sh SEE ALSO
.Xr Xorg 1 ,
.Xr xorg.conf 5
.Sh HISTORY
DRM was first available for Linux.
Subsequently Eric Anholt ported the DRM kernel modules to
.Fx .
.Sh CAVEATS
Disable AIGLX if necessary
.Pq Pa xorg.conf :
.Bd -literal -offset indent
Section "ServerFlags"
        Option  "AIGLX" "off"
EndSection
.\"
.\"Section "Extensions"
.\"        Option "Composite" "Disable"
.\"EndSection
.Ed
.Pp
.Cd options DRM_DEBUG
can slow DRI down a lot, disable it once
.Nm
works.
