#	@(#)Makefile	8.1 (Berkeley) 6/18/93
# $FreeBSD: src/share/man/man4/Makefile,v 1.83.2.66 2003/06/04 17:10:30 sam Exp $

MAN=	aac.4 \
	acpi.4 \
	acpi_asus.4 \
	acpi_fujitsu.4 \
	acpi_hp.4 \
	acpi_panasonic.4 \
	acpi_sony.4 \
	acpi_thermal.4 \
	acpi_thinkpad.4 \
	acpi_toshiba.4 \
	acpi_video.4 \
	acpi_wmi.4 \
	adv.4 \
	adw.4 \
	ae.4 \
	aesni.4 \
	age.4 \
	agp.4 \
	ahc.4 \
	ahci.4 \
	ahd.4 \
	aibs.4 \
	aic.4 \
	alc.4 \
	ale.4 \
	alpm.4 \
	altq.4 \
	amd.4 \
	amdpm.4 \
	amdsbwd.4 \
	amdsmb.4 \
	amr.4 \
	an.4 \
	apm.4 \
	aps.4 \
	arcmsr.4 \
	arp.4 \
	asr.4 \
	ath.4 \
	ath_hal.4 \
	atkbd.4 \
	atkbdc.4 \
	aue.4 \
	axe.4 \
	bce.4 \
	bfe.4 \
	bge.4 \
	bktr.4 \
	blackhole.4 \
	bluetooth.4 \
	bnx.4 \
	bpf.4 \
	bridge.4 \
	bt.4 \
	cardbus.4 \
	carp.4 \
	ccd.4 \
	cd.4 \
	ch.4 \
	ciss.4 \
	cmx.4 \
	coretemp.4 \
	crypto.4 \
	csa.4 \
	cue.4 \
	cxm.4 \
	da.4 \
	dc.4 \
	dcons.4 \
	dcons_crom.4 \
	ddb.4 \
	de.4 \
	devctl.4 \
	disc.4 \
	divert.4 \
	dm.4 \
	dm_target_striped.4 \
	dm_target_crypt.4 \
	dpt.4 \
	drm.4 \
	dsched.4 \
	dsched_bfq.4 \
	dummynet.4 \
	ecc.4 \
	ed.4 \
	ef.4 \
	ehci.4 \
	em.4 \
	est.4 \
	et.4 \
	exca.4 \
	faith.4 \
	fast_ipsec.4 \
	fd.4 \
	fdc.4 \
	firewire.4 \
	fwe.4 \
	fwohci.4 \
	fxp.4 \
	gdb.4 \
	gif.4 \
	gre.4 \
	hifn.4 \
	hpt27xx.4 \
	hptiop.4 \
	hptmv.4 \
	hptrr.4 \
	ichsmb.4 \
	ichwd.4 \
	icmp.4 \
	icmp6.4 \
	ida.4 \
	ieee80211.4 \
	ifmedia.4 \
	ifmib.4 \
	igb.4 \
	iic.4 \
	iicbb.4 \
	iicbus.4 \
	iicsmb.4 \
	iir.4 \
	inet.4 \
	inet6.4 \
	intpm.4 \
	intro.4 \
	ip.4 \
	ip6.4 \
	ipfirewall.4 \
	ips.4 \
	ipsec.4 \
	isa.4 \
	iscsi_initiator.4 \
	isp.4 \
	ispfw.4 \
	it.4 \
	iwi.4 \
	iwifw.4 \
	iwn.4 \
	iwnfw.4 \
	ix.4 \
	jme.4 \
	joy.4 \
	kate.4 \
	kbdmux.4 \
	keyboard.4 \
	kld.4 \
	km.4 \
	ktr.4 \
	kue.4 \
	lge.4 \
	lgue.4 \
	lm.4 \
	lo.4 \
	lp.4 \
	lpbb.4 \
	lpt.4 \
	md.4 \
	mem.4 \
	mfi.4 \
	miibus.4 \
	mlx.4 \
	mly.4 \
	mmc.4 \
	mmcsd.4 \
	mn.4 \
	moscom.4 \
	mouse.4 \
	mps.4 \
	mpt.4 \
	msk.4 \
	mtio.4 \
	multicast.4 \
	mxge.4 \
	my.4 \
	nata.4 \
	natapicam.4 \
	nataraid.4 \
	natm.4 \
	ncr.4 \
	ncv.4 \
	ndis.4 \
	netgraph.4 \
	netintro.4 \
	nfe.4 \
	ng_async.4 \
	ng_bpf.4 \
	ng_bridge.4 \
	ng_cisco.4 \
	nge.4 \
	ng_echo.4 \
	ng_eiface.4 \
	ng_etf.4 \
	ng_ether.4 \
	ng_frame_relay.4 \
	ng_hole.4 \
	ng_iface.4 \
	ng_ksocket.4 \
	ng_l2tp.4 \
	ng_lmi.4 \
	ng_mppc.4 \
	ng_one2many.4 \
	ng_ppp.4 \
	ng_pppoe.4 \
	ng_pptpgre.4 \
	ng_rfc1490.4 \
	ng_socket.4 \
	ng_tee.4 \
	ng_tty.4 \
	ng_UI.4 \
	ng_vjc.4 \
	nmdm.4 \
	nsclpcsio.4 \
	nsp.4 \
	null.4 \
	oce.4 \
	ohci.4 \
	orm.4 \
	padlock.4 \
	pass.4 \
	pccard.4 \
	pccbb.4 \
	pcf.4 \
	pci.4 \
	pcm.4 \
	pcn.4 \
	pf.4 \
	pflog.4 \
	pim.4 \
	polling.4 \
	powernow.4 \
	ppbus.4 \
	ppc.4 \
	ppi.4 \
	ppp.4 \
	psm.4 \
	pt.4 \
	pty.4 \
	puc.4 \
	puffs.4 \
	ral.4 \
	random.4 \
	rdrand.4 \
	re.4 \
	rl.4 \
	rndtest.4 \
	route.4 \
	rp.4 \
	rue.4 \
	sa.4 \
	safe.4 \
	sbp.4 \
	sbsh.4 \
	screen.4 \
	scsi.4 \
	sd.4 \
	sdhci.4 \
	ses.4 \
	sf.4 \
	si.4 \
	sili.4 \
	sio.4 \
	sis.4 \
	sk.4 \
	sl.4 \
	sln.4 \
	smb.4 \
	smbus.4 \
	smp.4 \
	sn.4 \
	snd_als4000.4 \
	snd_atiixp.4 \
	snd_cmi.4 \
	snd_cs4281.4 \
	snd_csa.4 \
	snd_ds1.4 \
	snd_emu10k1.4 \
	snd_envy24.4 \
	snd_envy24ht.4 \
	snd_es137x.4 \
	snd_fm801.4 \
	snd_hda.4 \
	snd_ich.4 \
	snd_maestro3.4 \
	snd_maestro.4 \
	snd_neomagic.4 \
	snd_solo.4 \
	snd_spicds.4 \
	snd_t4dwave.4 \
	snd_uaudio.4 \
	snd_via8233.4 \
	snd_via82c686.4 \
	snd_vibes.4 \
	snp.4 \
	splash.4 \
	sppp.4 \
	st.4 \
	ste.4 \
	stf.4 \
	stg.4 \
	stge.4 \
	sym.4 \
	syncer.4 \
	syscons.4 \
	sysmouse.4 \
	tap.4 \
	targ.4 \
	tcp.4 \
	termios.4 \
	ti.4 \
	tl.4 \
	tpm.4 \
	trm.4 \
	tty.4 \
	tun.4 \
	twa.4 \
	twe.4 \
	tws.4 \
	txp.4 \
	uark.4 \
	ubsa.4 \
	ubsec.4 \
	ubt.4 \
	uchcom.4 \
	ucom.4 \
	udp.4 \
	ufm.4 \
	uftdi.4 \
	ugen.4 \
	ugensa.4 \
	uguru.4 \
	uhci.4 \
	uhid.4 \
	ukbd.4 \
	ulpt.4 \
	umass.4 \
	umct.4 \
	umodem.4 \
	ums.4 \
	unix.4 \
	uplcom.4 \
	urio.4 \
	usb.4 \
	uscanner.4 \
	uslcom.4 \
	uticom.4 \
	uvisor.4 \
	uvscom.4 \
	vga.4 \
	vge.4 \
	vinum.4 \
	virtio.4 \
	virtio_blk.4 \
	vlan.4 \
	vn.4 \
	vpo.4 \
	vr.4 \
	watchdog.4 \
	wb.4 \
	wbsio.4 \
	wi.4 \
	wlan.4 \
	wlan_acl.4 \
	wlan_amrr.4 \
	wlan_ccmp.4 \
	wlan_tkip.4 \
	wlan_wep.4 \
	wlan_xauth.4 \
	wpi.4 \
	xe.4 \
	xl.4 \
	xpt.4 \
	zero.4

# XXX re-add when pfsync(4) has been fixed
#	pfsync.4 \

# XXX re-add when adjusted to the new 802.11 framework
#	acx.4 \
#	bwi.4 \
#	iwl.4 \
#	rtw.4 \
#	ural.4 \

MLINKS=	acpi_thermal.4 acpi_tz.4
#MLINKS+=acx.4 if_acx.4
MLINKS+=ae.4 if_ae.4
MLINKS+=age.4 if_age.4
MLINKS+=agp.4 agpgart.4
MLINKS+=alc.4 if_alc.4
MLINKS+=ale.4 if_ale.4
MLINKS+=an.4 if_an.4
MLINKS+=ath.4 if_ath.4
MLINKS+=aue.4 if_aue.4
MLINKS+=axe.4 if_axe.4
MLINKS+=bce.4 if_bce.4
MLINKS+=bfe.4 if_bfe.4
MLINKS+=bge.4 if_bge.4
MLINKS+=bktr.4 brooktree.4
MLINKS+=bnx.4 if_bnx.4
MLINKS+=bridge.4 if_bridge.4
#MLINKS+=bwi.4 if_bwi.4
MLINKS+=crypto.4 cryptodev.4
MLINKS+=cue.4 if_cue.4
MLINKS+=dc.4 if_dc.4
MLINKS+=disc.4 if_disc.4
MLINKS+=dm.4 dm_target_linear.4
MLINKS+=drm.4 i915kms.4 \
	drm.4 mach64drm.4 \
	drm.4 mach64.4 \
	drm.4 mgadrm.4 \
	drm.4 mga.4 \
	drm.4 r128drm.4 \
	drm.4 r128.4 \
	drm.4 radeondrm.4 \
	drm.4 radeon.4 \
	drm.4 savagedrm.4 \
	drm.4 savage.4 \
	drm.4 sisdrm.4 \
	drm.4 sis.4 \
	drm.4 tdfxdrm.4 \
	drm.4 tdfx.4
#	drm.4 viadrm.4
MLINKS+=dsched.4 dsched_fq.4
MLINKS+=ed.4 if_ed.4
MLINKS+=ef.4 if_ef.4
MLINKS+=em.4 emx.4 \
	em.4 if_em.4 \
	em.4 if_emx.4
MLINKS+=et.4 if_et.4
MLINKS+=faith.4 if_faith.4
MLINKS+=fd.4 stderr.4 \
	fd.4 stdin.4 \
	fd.4 stdout.4
MLINKS+=fwe.4 if_fwe.4
MLINKS+=fxp.4 if_fxp.4
MLINKS+=gif.4 if_gif.4
MLINKS+=gre.4 if_gre.4
MLINKS+=ipfirewall.4 ipaccounting.4 \
	ipfirewall.4 ipacct.4 \
	ipfirewall.4 ipfw.4
MLINKS+=iicbus.4 ic.4 \
	iicbus.4 if_ic.4
MLINKS+=igb.4 if_igb.4
MLINKS+=iwi.4 if_iwi.4
#MLINKS+=iwl.4 if_iwl.4
MLINKS+=iwn.4 if_iwn.4
MLINKS+=ix.4 if_ix.4 \
	ix.4 ixgbe.4 \
	ix.4 if_ixgbe.4
MLINKS+=jme.4 if_jme.4
MLINKS+=kue.4 if_kue.4
MLINKS+=lge.4 if_lge.4
MLINKS+=lgue.4 if_lgue.4
MLINKS+=lo.4 loop.4
MLINKS+=lp.4 plip.4
MLINKS+=mem.4 kmem.4
MLINKS+=msk.4 if_msk.4
MLINKS+=mxge.4 if_mxge.4
MLINKS+=my.4 if_my.4
MLINKS+=nata.4 acd.4 \
	nata.4 ad.4 \
	nata.4 afd.4 \
	nata.4 ast.4
MLINKS+=nataraid.4 ar.4
MLINKS+=netintro.4 networking.4
MLINKS+=nfe.4 if_nfe.4
MLINKS+=nge.4 if_nge.4
MLINKS+=oce.4 if_oce.4
MLINKS+=pccbb.4 cbb.4
MLINKS+=pcm.4 sound.4
MLINKS+=pcn.4 if_pcn.4
MLINKS+=ppp.4 if_ppp.4
MLINKS+=ral.4 if_ral.4
MLINKS+=random.4 urandom.4
MLINKS+=re.4 if_re.4
MLINKS+=rl.4 if_rl.4
#MLINKS+=rtw.4 if_rtw.4
MLINKS+=rue.4 if_rue.4
MLINKS+=sbsh.4 if_sbsh.4
MLINKS+=scsi.4 CAM.4 \
	scsi.4 cam.4 \
	scsi.4 scbus.4 \
	scsi.4 SCSI.4
MLINKS+=sf.4 if_sf.4
MLINKS+=sis.4 if_sis.4
MLINKS+=sk.4 if_sk.4
MLINKS+=sl.4 if_sl.4
MLINKS+=sln.4 if_sln.4
MLINKS+=smp.4 SMP.4
MLINKS+=splash.4 screensaver.4
MLINKS+=ste.4 if_ste.4
MLINKS+=stf.4 if_stf.4
MLINKS+=stge.4 if_stge.4
MLINKS+=syscons.4 sc.4
MLINKS+=tap.4 if_tap.4
MLINKS+=ti.4 if_ti.4
MLINKS+=tl.4 if_tl.4
MLINKS+=tun.4 if_tun.4
MLINKS+=txp.4 if_txp.4
#MLINKS+=ural.4 if_ural.4
MLINKS+=vga.4 vesa.4
MLINKS+=vge.4 if_vge.4
MLINKS+=vlan.4 if_vlan.4
MLINKS+=vpo.4 imm.4
MLINKS+=vr.4 if_vr.4
MLINKS+=wb.4 if_wb.4
MLINKS+=wi.4 if_wi.4
MLINKS+=wpi.4 if_wpi.4
MLINKS+=xe.4 if_xe.4
MLINKS+=xl.4 if_xl.4

.if defined(WANT_USB4BSD)
MAN+=	rum.4 \
	run.4 \
	runfw.4 \
	usb_quirk.4 \
	urtwn.4
MLINKS+=rum.4 if_rum.4
MLINKS+=run.4 if_run.4
MLINKS+=urtwn.4 if_urtwn.4
.endif

.if ${MACHINE_ARCH} == "i386"
SUBDIR=	 man4.${MACHINE_ARCH}
.endif

.include <bsd.prog.mk>
