.\" Copyright (c) 2014 LSI Corp
.\" All rights reserved.
.\" Author: Kashyap Desai
.\" Support: freebsdraid@lsi.com
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the <ORGANIZATION> nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
.\" COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
.\" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\" The views and conclusions contained in the software and documentation
.\" are those of the authors and should not be interpreted as representing
.\" official policies, either expressed or implied, of the FreeBSD Project.
.\"
.\" $FreeBSD: head/share/man/man4/mrsas.4 267182 2014-06-06 19:00:43Z joel $
.\"
.Dd July 18, 2014
.Dt MRSAS 4
.Os
.Sh NAME
.Nm mrsas
.Nd "LSI MegaRAID 6Gb/s and 12Gb/s SAS+SATA RAID controller driver"
.Sh SYNOPSIS
To compile this driver into the kernel,
place the following lines in your
kernel configuration file:
.Bd -ragged -offset indent
.Cd "device pci"
.Cd "device mrsas"
.Ed
.Pp
Alternatively, to load the driver as a
module at boot time, place the following line in
.Xr loader.conf 5 :
.Bd -literal -offset indent
mrsas_load="YES"
.Ed
.Sh DESCRIPTION
The
.Nm
driver will detect LSI's next generation (6Gb/s and 12Gb/s) PCI Express
SAS/SATA RAID controllers.
See the
.Nm HARDWARE
section for the supported devices list.
A disk (virtual disk/physical disk) attached to the
.Nm
driver will be visible to the user through
.Xr camcontrol 8
as
.Pa /dev/da?
device nodes.
A simple management interface is also provided on a per-controller basis via the
.Pa /dev/mrsas?
device node.
.Pp
The
.Nm
name is derived from the phrase "MegaRAID SAS HBA", which is
substantially different than the old "MegaRAID" Driver
.Xr mfi 4
which does not connect targets
to the
.Xr cam 4
layer and thus requires a new driver which attaches targets to the
.Xr cam 4
layer.
Older MegaRAID controllers are supported by
.Xr mfi 4
and
.Xr amr 4
and will not work with
.Nm ,
but both the
.Xr mfi 4
and
.Nm
drivers can detect and manage the LSI MegaRAID SAS 2208/2308/3008/3108 series of
controllers.
.Sh HARDWARE
The
.Nm
driver supports the following hardware:
.Pp
[ Thunderbolt 6Gb/s MR controller ]
.Bl -bullet -compact
.It
LSI MegaRAID SAS 9265
.It
LSI MegaRAID SAS 9266
.It
LSI MegaRAID SAS 9267
.It
LSI MegaRAID SAS 9270
.It
LSI MegaRAID SAS 9271
.It
LSI MegaRAID SAS 9272
.It
LSI MegaRAID SAS 9285
.It
LSI MegaRAID SAS 9286
.It
DELL PERC H810
.It
DELL PERC H710/P
.El
.Pp
[ Invader/Fury 12Gb/s MR controller ]
.Bl -bullet -compact
.It
LSI MegaRAID SAS 9380
.It
LSI MegaRAID SAS 9361
.It
LSI MegaRAID SAS 9341
.It
DELL PERC H830
.It
DELL PERC H730/P
.It
DELL PERC H330
.El
.Sh CONFIGURATION
A tunable is provided to adjust the
.Nm
driver's behaviour when attaching to a card.
By default, the driver will attach to all known cards with
high probe priority.
For
.Dq Thunderbolt
series cards this behavior can be changed to attaching via the
.Xr mfi 4
driver by setting the following tunable value in
.Xr loader.conf 5 :
.Bd -literal -offset indent
hw.mrsas.mfi_enable=1
.Ed
.Pp
By default, the driver will use MSI if it is supported.
This behavior can be turned off by setting the following tunable value in
.Xr loader.conf 5 :
.Bd -literal -offset indent
hw.mrsas.msi.enable=0
.Ed
.Pp
To disable Online Controller Reset(OCR) for a specific
.Nm
driver instance, set the
following tunable value in
.Xr loader.conf 5 :
.Bd -literal -offset indent
hw.mrsasX.disable_ocr=1
.Ed
.Pp
where X is the adapter number.
.Pp
To change the I/O timeout value for a specific
.Nm
driver instance, set the following tunable value in
.Xr loader.conf 5 :
.Bd -literal -offset indent
hw.mrsasX.mrsas_io_timeout=NNNNNN
.Ed
.Pp
where NNNNNN is the timeout value in milli-seconds.
.Pp
To change the firmware fault check timer value for a specific
.Nm
driver instance, set the following tunable value in
.Xr loader.conf 5 :
.Bd -literal -offset indent
hw.mrsasX.mrsas_fw_fault_check_delay=NN
.Ed
.Pp
where NN is the fault check delay value in seconds.
.Pp
The current number of active I/O commands is shown in the
.Va hw.mrsasX.fw_outstanding
.Xr sysctl 8
variable.
.Sh DEBUGGING
To enable debugging prints from the
.Nm
driver, set the
.Va hw.mrsas.X.debug_level
variable, where X is the adapter number, either in
.Xr loader.conf 5
or via
.Xr sysctl 8 .
The following bits have the described effects:
.Pp
.Bl -tag -width "0x01" -offset indent -compact
.It 0x01
Enable informational prints.
.It 0x02
Enable tracing prints.
.It 0x04
Enable prints for driver faults.
.It 0x08
Enable prints for OCR and I/O timeout.
.It 0x10
Enable prints for AEN events.
.El
.Sh FILES
.Bl -tag -width ".Pa /dev/mrsas?" -compact
.It Pa /dev/da?
array/logical disk interface
.It Pa /dev/mrsas?
management interface
.El
.Sh SEE ALSO
.Xr amr 4 ,
.Xr cam 4 ,
.Xr mfi 4 ,
.Xr pci 4 ,
.Xr device.hints 5 ,
.Xr camcontrol 8
.Sh HISTORY
The
.Nm
driver first appeared in
.Fx 10.1
and was ported to
.Dx 3.9 .
.Bd -ragged
.Cd "mfi Driver:"
.Xr mfi 4
is the old
.Fx
driver which started with support for Gen-1 Controllers and
was extended to support up to MR-Fusion (Device ID = 0x005B, 0x005D, 0x005F).
.Ed
.Bd -ragged
.Cd "mrsas Driver:"
.Nm
is the new driver reworked by LSI which supports Thunderbolt and onward
products.
The SAS+SATA RAID controller with device id 0x005b is referred to as
the Thunderbolt controller throughout this man page.
.Ed
.Bd -ragged
.Nm cam aware HBA drivers:
.Fx
has a
.Xr cam 4
layer which attaches storage devices and provides a common access mechanism to
storage controllers and attached devices.
The
.Nm
driver is
.Xr cam 4
aware and devices associated with
.Nm
can be seen using
.Xr camcontrol 8 .
The
.Xr mfi 4
driver does not understand the
.Xr cam 4
layer and it directly associates storage disks to the block layer.
.Pp
.Nm Thunderbolt Controller:
This is the 6Gb/s MegaRAID HBA card which has device id 0x005B.
.Pp
.Nm Invader Controller:
This is 12Gb/s MegaRAID HBA card which has device id 0x005D.
.Pp
.Nm Fury Controller:
This is the 12Gb/s MegaRAID HBA card which has device id 0x005F.
.Ed
.Sh AUTHORS
The
.Nm
driver and this manual page were written by
.An Kashyap Desai Aq Mt Kashyap.Desai@lsi.com .
It was ported to
.Dx
by
.An Sascha Wildner Aq Mt swildner@dragonflybsd.org .
.Sh TODO
.\"The driver does not support big-endian architectures at this time.
.\".Pp
The driver does not support alias for device name (it is required when the user
switches between two drivers and does not want to edit
.Pa /etc/fstab
manually for
.Pa /dev/mfid?
device nodes).
It is recommended to use the approriate device nodes in
.Pa /dev/serno
instead.
They should be available for all controllers supported by
.Nm .
.Pp
The
.Nm
driver exposes devices as
.Pa /dev/da? ,
whereas
.Xr mfi 4
exposes devices as
.Pa /dev/mfid? .
.Pp
.Nm
does not support the Linux Emulator interface.
.Pp
.Nm
will not work with
.Xr mfiutil 8 .
