.\" Copyright (c) 2005, 2006
.\"     Damien Bergamini <damien.bergamini@free.fr>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" $FreeBSD: src/share/man/man4/ural.4,v 1.11 2006/10/07 18:18:40 flz Exp $
.\"
.Dd July 26, 2008
.Os
.Dt URAL 4
.Sh NAME
.Nm ural
.Nd "Ralink Technology RT2500USB IEEE 802.11 driver"
.Sh SYNOPSIS
To compile this driver into the kernel,
place the following lines in your
kernel configuration file:
.Bd -ragged -offset indent
.Cd "device ehci"
.Cd "device uhci"
.Cd "device ohci"
.Cd "device oldusb"
.Cd "device ural"
.Cd "device wlan"
.Cd "device wlan_ratectl_onoe"
.Ed
.Pp
Alternatively, to load the driver as a
module at boot time, place the following line in
.Xr loader.conf 5 :
.Bd -literal -offset indent
if_ural_load="YES"
.Ed
.Sh DESCRIPTION
The
.Nm
driver supports USB 2.0 wireless adapters based on the RT2500USB chipset.
.Pp
The RT2500USB chipset consists of two integrated chips, a RT2570 MAC/BBP
and a radio transceiver (the model of which depends on the card revision).
.Pp
The RT2522, RT2523, RT2524, RT2525, RT2525e and RT2526 radio transceivers
operate in the 2.4GHz band (802.11b/g) whereas the RT5222 is a dual-band radio
transceiver that can operate in the 2.4GHz and 5.2GHz bands (802.11a).
.Sh HARDWARE
The
.Nm
driver supports the following adapters:
.Pp
.Bl -bullet -compact
.It
AMIT WL532U
.It
ASUS WL-167g
.It
Belkin F5D7050 v2000
.It
Buffalo WLI-U2-KG54
.It
Buffalo WLI-U2-KG54-AI
.It
Buffalo WLI-U2-KG54-YB
.It
CNet CWD-854
.It
Compex WLU54G 2A1100
.It
Conceptronic C54RU
.It
D-Link DWL-G122 b1
.It
Dynalink WLG25USB
.It
E-Tech WGUS02
.It
Eminent 3035
.It
Gigabyte GN-WBKG
.It
Hercules HWGUSB2-54
.It
KCORP LifeStyle KLS-685
.It
Linksys HU200-TS
.It
Linksys WUSB54G v4
.It
Linksys WUSB54GP v4
.It
MSI MS-6861
.It
MSI MS-6865
.It
MSI MS-6869
.It
Nintendo Wi-Fi USB Connector
.It
NovaTech NV-902
.It
OvisLink Evo-W54USB
.It
SerComm UB801R
.It
SparkLAN WL-685R
.It
Sphairon UB801R
.It
Surecom EP-9001-g
.It
Sweex LC100060
.It
Tonze UW-6200C
.It
Zaapa ZNWUSB-54
.It
Zinwell ZPlus-G250
.It
Zinwell ZWX-G261
.It
Zonet ZEW2500P
.El
.Pp
An up to date list can be found at
.Pa http://ralink.rapla.net/ .
.Sh EXAMPLES
Refer to the
.Sx EXAMPLES
section of
.Xr wlan 4 .
.Sh DIAGNOSTICS
.Bl -diag
.It "ural%d: device timeout"
The driver will reset the hardware.
This should not happen.
.El
.Sh SEE ALSO
.Xr arp 4 ,
.Xr ifmedia 4 ,
.Xr netintro 4 ,
.Xr usb 4 ,
.Xr wlan 4 ,
.Xr wlan_ratectl 4 ,
.Xr hostapd 8 ,
.Xr ifconfig 8 ,
.Xr wpa_supplicant 8
.Rs
.%T "Ralink Technology"
.%O http://www.ralinktech.com/
.Re
.Sh HISTORY
The
.Nm
driver first appeared in
.Ox 3.7 .
.Sh CAVEATS
The
.Nm
driver supports automatic adaptation of the transmit speed in IBSS
and HostAP operating modes,
but it does not work well if there are more than one peer node.
.Sh AUTHORS
The
.Nm
driver was written by
.An Damien Bergamini Aq Mt damien@FreeBSD.org .
