#!/bin/sh
#
# $DragonFly: site/src/wiki2html,v 1.4 2005/01/15 20:59:24 okumoto Exp $

cat << EOF
#!/usr/local/www/cgi-bin/tablecg
#
# \$DragonFly\$

\$TITLE(DragonFly Frequently Asked Questions)

EOF

#
# 1-2.	Extract content section from downloaded page.
# 3.	Delete table of contents section.
# 4.	Remove URLs to edit links.
# 5-6.	Convert <h1> tags to bold.
# 7.	Fix relitive references for DFWiki.
# 8.	Fix relitive references for FAQs.
# 9.	Remove span urlexpansion (URL stuff)
# 10.	Remove footer at bottom of page. (note: since sed is really
#	just working with lines, NOT removing the </p> is difficult.  So I
#	just add one back using echo.
#
sed	-e '1,/<!-- start content -->/d' \
        -e '/<!-- end content -->/,$d' \
        -e '/<table border="0" id="toc">/,/<\/table>/d' \
        -e 's,^<div class="editsection" style="float:right;margin-left:5px;">.*<\/div>,,' \
        -e 's/<h1>/<b>/g' \
        -e 's/<\/h1>/<\/b>/g' \
	-e 's,a href="/dfwiki/index\.php/Main_Page,a href="http://www.sitetronics.com/dfwiki/index.php/Main_Page,g' \
	-e 's,dfwiki/index.php/DragonFly_FAQ\([^"]*\)",main/FAQ\1.cgi",g' \
	-e "s,<span class='urlexpansion'> ([^)]*)</span>,,g" \
	-e '/<\/p><div class="printfooter">/,/<\/dvi>/d'

echo '</p>'
