#	from: @(#)Makefile	5.5 (Berkeley) 5/11/90
# $FreeBSD: src/usr.sbin/rtprio/Makefile,v 1.6.2.1 2001/04/25 12:10:48 ru Exp $
# $DragonFly: src/usr.sbin/rtprio/Makefile,v 1.2 2003/06/17 04:30:03 dillon Exp $

PROG=	rtprio
LINKS=  ${BINDIR}/rtprio ${BINDIR}/idprio
MLINKS= rtprio.1 idprio.1

.include <bsd.prog.mk>
