# Makefile copyright James Raynard (jraynard@freebsd.org) 1997
#
# $FreeBSD: src/gnu/usr.bin/awk/doc/Makefile,v 1.5 1999/08/27 23:34:37 peter Exp $
# $DragonFly: src/gnu/usr.bin/awk/doc/Attic/Makefile,v 1.2 2003/06/17 04:25:44 dillon Exp $

.PATH:	${.CURDIR}/../../../../contrib/awk/doc

INFO = gawk
INFOSECTION= "System Utilities"
INFOENTRY_gawk= "* GAWK: (gawk).			The GNU AWK language interpreter manual."

.include <bsd.info.mk>
