#$FreeBSD: src/sbin/atacontrol/Makefile,v 1.6.2.1 2002/03/18 08:40:00 sos Exp $
#$DragonFly: src/sbin/atacontrol/Makefile,v 1.3 2005/01/09 04:43:33 cpressey Exp $

PROG=	atacontrol
WARNS=	6
MAN=	atacontrol.8

.include <bsd.prog.mk>
