#$FreeBSD: src/sbin/atacontrol/Makefile,v 1.6.2.1 2002/03/18 08:40:00 sos Exp $
#$DragonFly: src/sbin/atacontrol/Makefile,v 1.4 2005/01/09 15:41:38 joerg Exp $

PROG=	atacontrol
WARNS?=	6
MAN=	atacontrol.8

.include <bsd.prog.mk>
