# $DragonFly: src/gnu/usr.bin/cc41/cc_tools/Makefile.tools,v 1.2 2007/08/25 15:29:28 corecode Exp $

MIC= sh ${GCCDIR}/move-if-change
TOOLGENDIR= ${OTOPDIR}/cc_tools/gen
.PATH: ${TOOLGENDIR}
CFLAGS+= -I${TOOLGENDIR}
