# $FreeBSD: src/gnu/lib/Makefile,v 1.25.2.4 2001/01/06 23:16:53 obrien Exp $

SUBDIR= gcc41 libdevmapper libdialog liblvm libregex

.if !defined(NO_GCC44)
SUBDIR+= gcc44
.endif

.include <bsd.subdir.mk>
