# $FreeBSD: src/gnu/lib/Makefile,v 1.25.2.4 2001/01/06 23:16:53 obrien Exp $

SUBDIR= gcc44 libcryptsetup libdevmapper libdialog libluks liblvm libregex

.if !defined(NO_GCC41)
SUBDIR+= gcc41
.endif

.include <bsd.subdir.mk>
