# $FreeBSD: src/usr.bin/mktemp/Makefile,v 1.1 1998/04/14 07:39:56 peter Exp $
# $DragonFly: src/usr.bin/mktemp/Makefile,v 1.3 2005/01/01 21:10:43 cpressey Exp $

PROG=	mktemp
WARNS?=	6

.include <bsd.prog.mk>
