#!/bin/sh
# objdump the symbol table, but strip off the headings and symbol
# numbers and sort the result.  Intended for use in comparing symbol
# tables that may not be in the same order.
#
# $FreeBSD: src/gnu/usr.bin/as/testscripts/dounsortsymbols,v 1.4 1999/08/27 23:34:36 peter Exp $
# $DragonFly: src/gnu/usr.bin/as/testscripts/Attic/dounsortsymbols,v 1.2 2003/06/17 04:25:44 dillon Exp $

objdump +symbols +omit-symbol-numbers $1 \
	| sort
#eof
