# $FreeBSD: src/usr.bin/genassym/Makefile,v 1.1.2.1 2001/04/25 11:29:20 ru Exp $
# $DragonFly: src/usr.bin/genassym/Attic/Makefile,v 1.2 2003/06/17 04:29:27 dillon Exp $

TARGET_ARCH?=	${MACHINE_ARCH}

PROG=		genassym
MAN=		genassym.8
CFLAGS+=	-Wall -Darch_${TARGET_ARCH}

.include <bsd.prog.mk>
