# $FreeBSD: src/usr.sbin/devinfo/Makefile,v 1.6 2002/05/12 14:23:15 rwatson Exp $
# $DragonFly: src/usr.sbin/devinfo/Makefile,v 1.2 2008/09/30 17:11:16 swildner Exp $

PROG=	devinfo
MAN=	devinfo.8

DPADD=	${LIBDEVINFO}
LDADD=	-ldevinfo

.include <bsd.prog.mk>
