# $FreeBSD: src/usr.sbin/devinfo/Makefile,v 1.6 2002/05/12 14:23:15 rwatson Exp $
# $DragonFly: src/usr.sbin/devinfo/Makefile,v 1.1 2008/09/30 12:20:29 hasso Exp $

PROG=	devinfo
MAN=	devinfo.8

WARNS?=	2

DPADD=	${LIBDEVINFO}
LDADD=	-ldevinfo

.include <bsd.prog.mk>
