# $FreeBSD: src/sys/modules/amr/amr_cam/Makefile,v 1.1 2008/11/03 04:13:27 scottl Exp $

.PATH: ${.CURDIR}/..

KMOD=	amr_cam
SRCS=	amr_cam.c device_if.h bus_if.h
SRCS+=	opt_amr.h opt_cam.h opt_scsi.h

.include <bsd.kmod.mk>
