# $FreeBSD: src/share/doc/papers/contents/Makefile,v 1.5.2.1 2002/02/18 12:29:43 ru Exp $
# $DragonFly: src/share/doc/papers/contents/Makefile,v 1.2 2003/06/17 04:36:56 dillon Exp $

VOLUME=	papers
DOC=	contents
SRCS=	contents.ms
MACROS=	-ms

.include <bsd.doc.mk>
