# $FreeBSD: src/secure/usr.bin/ssh-agent/Makefile,v 1.2.2.3 2002/07/03 22:20:31 des Exp $
# $DragonFly: src/secure/usr.bin/ssh-agent/Makefile,v 1.4 2008/04/07 01:20:18 pavalos Exp $

PROG=	ssh-agent
SRCS=	ssh-agent.c ssh-pkcs11-client.c roaming_dummy.c
WARNS?=	3

.include "../../Makefile.ssh.common"
.include <bsd.prog.mk>
