#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/pom/Makefile,v 1.2.8.1 2001/04/25 09:29:00 ru Exp $
# $DragonFly: src/games/pom/Makefile,v 1.4 2006/08/08 17:08:49 pavalos Exp $

PROG=	pom
WARNS?=	6
MAN=	pom.6
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
