#	$OpenBSD: Makefile,v 1.1 1997/01/26 02:23:20 millert Exp $
# $FreeBSD: src/sbin/fsirand/Makefile,v 1.2.10.1 2001/04/25 10:58:19 ru Exp $
# $DragonFly: src/sbin/fsirand/Makefile,v 1.5 2006/10/31 20:22:22 pavalos Exp $

PROG=	fsirand
MAN=	fsirand.8
DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
