#	From: @(#)Makefile	8.1 (Berkeley) 4/20/94
# $FreeBSD: src/share/doc/papers/nqnfs/Makefile,v 1.5 1999/08/28 00:18:15 peter Exp $
# $DragonFly: src/share/doc/papers/nqnfs/Makefile,v 1.2 2003/06/17 04:36:56 dillon Exp $

VOLUME=	papers
DOC=	nqnfs
SRCS=	nqnfs.me
MACROS=	-me
USE_PIC=	yes
USE_TBL=	yes

.include <bsd.doc.mk>
