# $FreeBSD: src/usr.sbin/adduser/Makefile,v 1.14.2.2 2001/04/25 14:04:49 ru Exp $
# $DragonFly: src/usr.sbin/adduser/Makefile,v 1.3 2004/01/31 06:56:44 dillon Exp $

SCRIPTS=adduser.perl rmuser.perl
MAN=	adduser.8 rmuser.8

.include <bsd.prog.mk>
