#	from: @(#)Makefile	5.8 (Berkeley) 7/28/90
# $FreeBSD: src/usr.bin/ypmatch/Makefile,v 1.4 1999/08/28 01:08:10 peter Exp $
# $DragonFly: src/usr.bin/ypmatch/Makefile,v 1.3 2007/08/27 16:51:02 pavalos Exp $

PROG=	ypmatch

.include <bsd.prog.mk>
