# $FreeBSD: src/etc/periodic/weekly/Makefile,v 1.4.2.3 2002/07/18 12:36:07 ru Exp $

FILES=	310.locate \
	320.whatis \
	330.catman \
	340.noid \
	450.status-security \
	999.local

.include <bsd.prog.mk>
