# $FreeBSD: src/etc/periodic/weekly/Makefile,v 1.4.2.3 2002/07/18 12:36:07 ru Exp $
# $DragonFly: src/etc/periodic/weekly/Makefile,v 1.3 2003/06/17 05:15:04 dillon Exp $

FILES=	120.clean-kvmdb \
	310.locate \
	320.whatis \
	330.catman \
	340.noid \
	400.status-pkg \
	999.local

.include <bsd.prog.mk>
