# $FreeBSD: src/usr.sbin/spray/Makefile,v 1.5.2.1 2001/04/25 12:10:58 ru Exp $
# $DragonFly: src/usr.sbin/spray/Makefile,v 1.2 2003/06/17 04:30:03 dillon Exp $

PROG=	spray
MAN=	spray.8
DPADD=	${LIBRPCSVC}
LDADD=	-lrpcsvc

.include <bsd.prog.mk>
