# $FreeBSD: src/gnu/usr.bin/groff/src/utils/afmtodit/Makefile,v 1.1 2001/04/17 12:37:15 ru Exp $
# $DragonFly: src/gnu/usr.bin/groff/src/utils/afmtodit/Makefile,v 1.3 2005/09/01 20:47:14 asmodai Exp $

SCRIPTS=	afmtodit
MAN=		afmtodit.1
CLEANFILES=	${SCRIPTS} ${MAN}

.include <bsd.prog.mk>
