# $FreeBSD: src/sys/modules/asr/Makefile,v 1.1.2.1 2000/09/21 20:33:53 msmith Exp $
# $DragonFly: src/sys/dev/raid/asr/Makefile,v 1.3 2004/08/23 15:11:44 joerg Exp $

KMOD		=  asr
SRCS		=  asr.c
SRCS		+= opt_scsi.h opt_cam.h
SRCS		+= device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
