# $FreeBSD: src/kerberos5/usr.sbin/Makefile,v 1.2 2000/02/28 19:15:28 markm Exp $
# $DragonFly: src/kerberos5/usr.sbin/Makefile,v 1.2 2003/06/17 04:26:18 dillon Exp $

SUBDIR=	k5stash ktutil

.include <bsd.subdir.mk>
