# $FreeBSD: src/kerberos5/usr.sbin/Makefile.inc,v 1.1.1.1 2000/01/24 19:56:25 markm Exp $
# $DragonFly: src/kerberos5/usr.sbin/Makefile.inc,v 1.2 2003/06/17 04:26:18 dillon Exp $

BINDIR=	/usr/sbin

.include "../Makefile.inc"
