# $FreeBSD: src/kerberos5/usr.sbin/Makefile,v 1.3 2003/03/09 21:56:55 markm Exp $
# $DragonFly: src/kerberos5/usr.sbin/Makefile,v 1.3 2005/01/16 14:25:47 eirikn Exp $

SUBDIR=	kstash ktutil

.include <bsd.subdir.mk>
