# $DragonFly: src/sys/net/Makefile,v 1.1 2003/08/15 07:03:09 dillon Exp $
#

SUBDIR=accf_data accf_http disc ef faith gif gre sl stf tap tun \
	vlan bridge dummynet ipfilter ipfw ip6fw ip_mroute \
	sppp ppp_layer

.include <bsd.subdir.mk>
