# $DragonFly: src/sys/net/Makefile,v 1.2 2004/09/19 22:32:47 joerg Exp $
#

SUBDIR=accf_data accf_http disc ef faith gif gre sl stf tap tun \
	vlan bridge dummynet ipfilter ipfw ip6fw ip_mroute \
	sppp ppp_layer pf

.include <bsd.subdir.mk>
