# $DragonFly: src/sys/net/Makefile,v 1.4 2005/12/21 16:37:15 corecode Exp $
#

SUBDIR=accf_data accf_http disc ef faith gif gre sl stf tap tun \
	vlan bridge oldbridge dummynet ipfilter ipfw ip6fw ip_mroute \
	sppp ppp_layer pf

.include <bsd.subdir.mk>
