# $FreeBSD: src/usr.sbin/i4b/isdndecode/Makefile,v 1.2.2.2 2001/08/01 17:29:17 obrien Exp $
# $DragonFly: src/usr.sbin/i4b/isdndecode/Makefile,v 1.2 2003/06/17 04:29:55 dillon Exp $

PROG=	isdndecode
MAN=	isdndecode.8
SRCS=	main.c layer1.c layer2.c layer3.c layer3_subr.c facility.c pcause.c 

.include <bsd.prog.mk>

