# $FreeBSD: src/usr.bin/sockstat/Makefile,v 1.2.2.2 2001/04/25 14:04:32 ru Exp $
# $DragonFly: src/usr.bin/sockstat/Makefile,v 1.3 2004/01/31 06:56:44 dillon Exp $

SCRIPTS=	sockstat.pl
MAN=		sockstat.1

.include <bsd.prog.mk>
