# $FreeBSD: src/usr.bin/sockstat/Makefile,v 1.2.2.2 2001/04/25 14:04:32 ru Exp $
# $DragonFly: src/usr.bin/sockstat/Makefile,v 1.4 2005/01/04 18:56:58 joerg Exp $

PROG=	sockstat
MAN=	sockstat.1
DPADD=	${LIBKINFO}
LDADD=	${LIBKINFO}

.include <bsd.prog.mk>
