# $FreeBSD: src/usr.bin/sockstat/Makefile,v 1.2.2.2 2001/04/25 14:04:32 ru Exp $
# $DragonFly: src/usr.bin/sockstat/Makefile,v 1.2 2003/06/17 04:29:31 dillon Exp $

MAINTAINER=	des@freebsd.org
SCRIPTS=	sockstat.pl
MAN=		sockstat.1

.include <bsd.prog.mk>
