# $NetBSD: Makefile.inc,v 1.1 2006/11/23 03:25:25 tnozaki Exp $
# $DragonFly: src/share/i18n/esdb/GB/Makefile.inc,v 1.1 2008/04/10 10:21:12 hasso Exp $

.PATH: ${.CURDIR}/GB

CODE:=		GB
SEP_GB=
.include "${.CURDIR}/Makefile.part"
