#	$OpenBSD: Makefile,v 1.3 2004/02/01 15:18:01 jmc Exp $
#	$DragonFly: src/share/doc/usd/06.bc/Makefile,v 1.1 2004/09/20 04:20:32 dillon Exp $

VOLUME=	usd/06.bc
SRCS=	bc
MACROS=	-ms
SRCDIR=	${.CURDIR}/../../../../usr.bin/bc/USD.doc

.include <bsd.doc.mk>
