# $FreeBSD: src/sys/boot/i386/Makefile,v 1.19 2002/12/31 02:29:03 obrien Exp $
# $DragonFly: src/sys/boot/i386/Attic/Makefile,v 1.3 2003/11/10 06:08:34 dillon Exp $

SUBDIR=		mbr boot0 btx boot2 cdboot kgzldr libi386 loader

# special boot programs, 'self-extracting boot2+loader'
SUBDIR+=	pxeldr

.include <bsd.subdir.mk>
