# $FreeBSD: src/usr.sbin/jail/Makefile,v 1.4.2.2 2003/05/08 13:04:24 maxim Exp $
# $DragonFly: src/usr.sbin/jail/Makefile,v 1.2 2003/06/17 04:29:55 dillon Exp $

PROG=	jail
MAN=	jail.8
DPADD=	${LIBUTIL}
LDADD=	-lutil

.include	<bsd.prog.mk>
