# $FreeBSD: src/share/man/man9/Makefile,v 1.60.2.26 2003/06/13 01:04:17 hmp Exp $

MAN=	accept_filter.9 \
	accf_data.9 \
	accf_http.9 \
	acl.9 \
	altq.9 \
	at_exit.9 \
	at_fork.9 \
	atomic.9 \
	bios.9 \
	boot.9 \
	buf.9 \
	bufcache.9 \
	BUS_ADD_CHILD.9 \
	bus_alloc_resource.9 \
	bus_dma.9 \
	bus_generic_attach.9 \
	bus_generic_detach.9 \
	bus_generic_print_child.9 \
	bus_generic_read_ivar.9 \
	bus_generic_shutdown.9 \
	bus_get_resource.9 \
	BUS_PRINT_CHILD.9 \
	BUS_READ_IVAR.9 \
	bus_release_resource.9 \
	bus_set_resource.9 \
	BUS_SETUP_INTR.9 \
	bus_space.9 \
	byteorder.9 \
	callout.9 \
	cd.9 \
	condvar.9 \
	config_intrhook.9 \
	contigmalloc.9 \
	copy.9 \
	crit_enter.9 \
	crypto.9 \
	DB_COMMAND.9 \
	DECLARE_MODULE.9 \
	DELAY.9 \
	devclass.9 \
	devclass_add_driver.9 \
	devclass_find.9 \
	devclass_get_count.9 \
	devclass_get_device.9 \
	devclass_get_devices.9 \
	devclass_get_maxunit.9 \
	devclass_get_name.9 \
	devclass_get_softc.9 \
	device.9 \
	device_add_child.9 \
	DEVICE_ATTACH.9 \
	device_delete_child.9 \
	DEVICE_DETACH.9 \
	device_enable.9 \
	device_find_child.9 \
	device_get_children.9 \
	device_get_devclass.9 \
	device_get_driver.9 \
	device_get_ivars.9 \
	device_get_name.9 \
	device_get_parent.9 \
	device_get_softc.9 \
	device_get_state.9 \
	device_get_unit.9 \
	DEVICE_IDENTIFY.9 \
	device_printf.9 \
	DEVICE_PROBE.9 \
	device_probe_and_attach.9 \
	device_quiet.9 \
	device_set_desc.9 \
	device_set_driver.9 \
	device_set_flags.9 \
	DEVICE_SHUTDOWN.9 \
	DEV_MODULE.9 \
	devstat.9 \
	devtoname.9 \
	driver.9 \
	DRIVER_MODULE.9 \
	dsched.9 \
	EVENTHANDLER.9 \
	extattr.9 \
	fetch.9 \
	firmware.9 \
	hash.9 \
	hashinit.9 \
	hexncpy.9 \
	hexdump.9 \
	idr.9 \
	ieee80211.9 \
	ieee80211_beacon.9 \
	ieee80211_bmiss.9 \
	ieee80211_crypto.9 \
	ieee80211_ddb.9 \
	ieee80211_input.9 \
	ieee80211_node.9 \
	ieee80211_output.9 \
	ieee80211_proto.9 \
	ieee80211_radiotap.9 \
	ieee80211_regdomain.9 \
	ieee80211_scan.9 \
	ieee80211_vap.9 \
	ifnet.9 \
	inittodr.9 \
	intro.9 \
	ioctl.9 \
	KASSERT.9 \
	kenv.9 \
	kernacc.9 \
	kether_ntoa.9 \
	kmalloc.9 \
	kobj.9 \
	kprintf.9 \
	ksignal.9 \
	ktr.9 \
	lock.9 \
	lwbuf.9 \
	make_autoclone_dev.9 \
	make_dev.9 \
	mbuf.9 \
	MD5.9 \
	memcchr.9 \
	memory.9 \
	microseq.9 \
	microtime.9 \
	microuptime.9 \
	module.9 \
	MODULE_DEPEND.9 \
	MODULE_VERSION.9 \
	mpipe.9 \
	msgport.9 \
	mutex.9 \
	nlookup.9 \
	objcache.9 \
	panic.9 \
	pci.9 \
	pfil.9 \
	pfind.9 \
	pgfind.9 \
	physio.9 \
	posix4.9 \
	priv.9 \
	prop_copyin_ioctl.9 \
	putter.9 \
	resettodr.9 \
	rman.9 \
	rtalloc.9 \
	rtentry.9 \
	sbuf.9 \
	sensor_attach.9 \
	serializer.9 \
	sglist.9 \
	sleep.9 \
	spinlock.9 \
	store.9 \
	style.9 \
	SYSCALL_MODULE.9 \
	syscall.9 \
	sysctl.9 \
	sysctl_add_oid.9 \
	sysctl_ctx_init.9 \
	SYSINIT.9 \
	systimer.9 \
	taskqueue.9 \
	tbridge.9 \
	time.9 \
	token.9 \
	tvtohz.9 \
	uio.9 \
	usbdi.9 \
	vcount.9 \
	vflush.9 \
	VFS.9 \
	VFS_CHECKEXP.9 \
	VFS_FHTOVP.9 \
	VFS_MOUNT.9 \
	VFS_QUOTACTL.9 \
	VFS_ROOT.9 \
	VFS_SET.9 \
	VFS_START.9 \
	VFS_STATFS.9 \
	VFS_SYNC.9 \
	VFS_UNMOUNT.9 \
	vfs_unmountall.9 \
	VFS_VGET.9 \
	VFS_VPTOFH.9 \
	vget.9 \
	vhold.9 \
	vm_map_findspace.9 \
	vm_page_alloc.9 \
	vn_fullpath.9 \
	vnode.9 \
	VOP_ACCESS.9 \
	VOP_ACLCHECK.9 \
	VOP_ADVLOCK.9 \
	VOP_ATTRIB.9 \
	VOP_CREATE.9 \
	VOP_FSYNC.9 \
	VOP_GETACL.9 \
	VOP_GETEXTATTR.9 \
	VOP_GETPAGES.9 \
	VOP_INACTIVE.9 \
	VOP_IOCTL.9 \
	VOP_LEASE.9 \
	VOP_LINK.9 \
	VOP_LOCK.9 \
	VOP_LOOKUP.9 \
	VOP_MMAP.9 \
	VOP_OPENCLOSE.9 \
	VOP_PATHCONF.9 \
	VOP_PRINT.9 \
	VOP_RDWR.9 \
	VOP_READDIR.9 \
	VOP_READLINK.9 \
	VOP_REALLOCBLKS.9 \
	VOP_REMOVE.9 \
	VOP_RENAME.9 \
	VOP_SETACL.9 \
	VOP_SETEXTATTR.9 \
	VOP_STRATEGY.9 \
	vput.9 \
	vref.9 \
	vrele.9 \
	vslock.9 \
	wdog.9 \
	zone.9
#	ieee80211_amrr.9 \

MLINKS+=accept_filter.9 accept_filt_add.9 \
	accept_filter.9 accept_filt_del.9 \
	accept_filter.9 accept_filt_generic_mod_event.9 \
	accept_filter.9 accept_filt_get.9
MLINKS+=altq.9 ifq_classify.9 \
	altq.9 ifq_dequeue.9 \
	altq.9 ifq_enqueue.9 \
	altq.9 ifq_handoff.9 \
	altq.9 ifq_is_empty.9 \
	altq.9 ifq_is_enabled.9 \
	altq.9 ifq_poll.9 \
	altq.9 ifq_purge.9 \
	altq.9 ifq_set_maxlen.9 \
	altq.9 ifq_set_ready.9
MLINKS+=at_exit.9 rm_at_exit.9
MLINKS+=at_fork.9 rm_at_fork.9
MLINKS+=bios.9 bios32.9 \
	bios.9 bios32_SDlookup.9 \
	bios.9 BIOS_PADDRTOVADDR.9 \
	bios.9 bios_sigsearch.9 \
	bios.9 BIOS_VADDRTOPADDR.9
MLINKS+=buf.9 bp.9
MLINKS+=bufcache.9 bread.9 \
	bufcache.9 bwrite.9 \
	bufcache.9 bufinit.9
MLINKS+=bus_alloc_resource.9 bus_alloc_resource_any.9
MLINKS+=bus_dma.9 busdma.9 \
	bus_dma.9 bus_dmamap_create.9 \
	bus_dma.9 bus_dmamap_destroy.9 \
	bus_dma.9 bus_dmamap_load.9 \
	bus_dma.9 bus_dmamap_load_mbuf.9 \
	bus_dma.9 bus_dmamap_load_mbuf_defrag.9 \
	bus_dma.9 bus_dmamap_load_mbuf_segment.9 \
	bus_dma.9 bus_dmamap_load_uio.9 \
	bus_dma.9 bus_dmamap_sync.9 \
	bus_dma.9 bus_dmamap_unload.9 \
	bus_dma.9 bus_dmamem_alloc.9 \
	bus_dma.9 bus_dmamem_coherent.9 \
	bus_dma.9 bus_dmamem_coherent_any.9 \
	bus_dma.9 bus_dmamem_free.9 \
	bus_dma.9 bus_dma_tag_create.9 \
	bus_dma.9 bus_dma_tag_destroy.9
MLINKS+=bus_generic_read_ivar.9 bus_generic_write_ivar.9
MLINKS+=BUS_READ_IVAR.9 BUS_WRITE_IVAR.9
MLINKS+=BUS_SETUP_INTR.9 bus_setup_intr.9 \
	BUS_SETUP_INTR.9 bus_setup_intr_descr.9 \
	BUS_SETUP_INTR.9 BUS_TEARDOWN_INTR.9 \
	BUS_SETUP_INTR.9 bus_teardown_intr.9
MLINKS+=bus_space.9 bus_space_barrier.9 \
	bus_space.9 bus_space_copy_region_1.9 \
	bus_space.9 bus_space_copy_region_2.9 \
	bus_space.9 bus_space_copy_region_4.9 \
	bus_space.9 bus_space_copy_region_stream_1.9 \
	bus_space.9 bus_space_copy_region_stream_2.9 \
	bus_space.9 bus_space_copy_region_stream_4.9 \
	bus_space.9 bus_space_free.9 \
	bus_space.9 bus_space_map.9 \
	bus_space.9 bus_space_read_1.9 \
	bus_space.9 bus_space_read_2.9 \
	bus_space.9 bus_space_read_4.9 \
	bus_space.9 bus_space_read_multi_1.9 \
	bus_space.9 bus_space_read_multi_2.9 \
	bus_space.9 bus_space_read_multi_4.9 \
	bus_space.9 bus_space_read_multi_stream_1.9 \
	bus_space.9 bus_space_read_multi_stream_2.9 \
	bus_space.9 bus_space_read_multi_stream_4.9 \
	bus_space.9 bus_space_read_region_1.9 \
	bus_space.9 bus_space_read_region_2.9 \
	bus_space.9 bus_space_read_region_4.9 \
	bus_space.9 bus_space_read_region_stream_1.9 \
	bus_space.9 bus_space_read_region_stream_2.9 \
	bus_space.9 bus_space_read_region_stream_4.9 \
	bus_space.9 bus_space_read_stream_1.9 \
	bus_space.9 bus_space_read_stream_2.9 \
	bus_space.9 bus_space_read_stream_4.9 \
	bus_space.9 bus_space_set_multi_1.9 \
	bus_space.9 bus_space_set_multi_2.9 \
	bus_space.9 bus_space_set_multi_4.9 \
	bus_space.9 bus_space_set_multi_stream_1.9 \
	bus_space.9 bus_space_set_multi_stream_2.9 \
	bus_space.9 bus_space_set_multi_stream_4.9 \
	bus_space.9 bus_space_set_region_1.9 \
	bus_space.9 bus_space_set_region_2.9 \
	bus_space.9 bus_space_set_region_4.9 \
	bus_space.9 bus_space_set_region_stream_1.9 \
	bus_space.9 bus_space_set_region_stream_2.9 \
	bus_space.9 bus_space_set_region_stream_4.9 \
	bus_space.9 bus_space_subregion.9 \
	bus_space.9 bus_space_unmap.9 \
	bus_space.9 bus_space_write_1.9 \
	bus_space.9 bus_space_write_2.9 \
	bus_space.9 bus_space_write_4.9 \
	bus_space.9 bus_space_write_multi_1.9 \
	bus_space.9 bus_space_write_multi_2.9 \
	bus_space.9 bus_space_write_multi_4.9 \
	bus_space.9 bus_space_write_multi_stream_1.9 \
	bus_space.9 bus_space_write_multi_stream_2.9 \
	bus_space.9 bus_space_write_multi_stream_4.9 \
	bus_space.9 bus_space_write_region_1.9 \
	bus_space.9 bus_space_write_region_2.9 \
	bus_space.9 bus_space_write_region_4.9 \
	bus_space.9 bus_space_write_region_stream_1.9 \
	bus_space.9 bus_space_write_region_stream_2.9 \
	bus_space.9 bus_space_write_region_stream_4.9 \
	bus_space.9 bus_space_write_stream_1.9 \
	bus_space.9 bus_space_write_stream_2.9 \
	bus_space.9 bus_space_write_stream_4.9
MLINKS+=byteorder.9 be16dec.9 \
	byteorder.9 be16enc.9 \
	byteorder.9 be16toh.9 \
	byteorder.9 be32dec.9 \
	byteorder.9 be32enc.9 \
	byteorder.9 be32toh.9 \
	byteorder.9 be64dec.9 \
	byteorder.9 be64enc.9 \
	byteorder.9 be64toh.9 \
	byteorder.9 bswap16.9 \
	byteorder.9 bswap32.9 \
	byteorder.9 bswap64.9 \
	byteorder.9 htobe16.9 \
	byteorder.9 htobe32.9 \
	byteorder.9 htobe64.9 \
	byteorder.9 htole16.9 \
	byteorder.9 htole32.9 \
	byteorder.9 htole64.9 \
	byteorder.9 le16dec.9 \
	byteorder.9 le16enc.9 \
	byteorder.9 le16toh.9 \
	byteorder.9 le32dec.9 \
	byteorder.9 le32enc.9 \
	byteorder.9 le32toh.9 \
	byteorder.9 le64dec.9 \
	byteorder.9 le64enc.9 \
	byteorder.9 le64toh.9
MLINKS+=callout.9 callout_active.9 \
	callout.9 callout_deactivate.9 \
	callout.9 callout_init.9 \
	callout.9 callout_init_mp.9 \
	callout.9 callout_pending.9 \
	callout.9 callout_reset.9 \
	callout.9 callout_stop.9 \
	callout.9 timeout.9 \
	callout.9 untimeout.9
MLINKS+=condvar.9 cv_broadcast.9 \
	condvar.9 cv_broadcastpri.9 \
	condvar.9 cv_destroy.9 \
	condvar.9 cv_init.9 \
	condvar.9 cv_signal.9 \
	condvar.9 cv_timedwait.9 \
	condvar.9 cv_timedwait_sig.9 \
	condvar.9 cv_wait.9 \
	condvar.9 cv_wait_sig.9
MLINKS+=config_intrhook.9 config_intrhook_disestablish.9 \
	config_intrhook.9 config_intrhook_establish.9
MLINKS+=contigmalloc.9 contigfree.9
MLINKS+=copy.9 copyin.9 \
	copy.9 copyin_nofault.9 \
	copy.9 copyinstr.9 \
	copy.9 copyout.9 \
	copy.9 copyout_nofault.9 \
	copy.9 copystr.9
MLINKS+=crit_enter.9 crit_enter_gd.9 \
	crit_enter.9 crit_enter_id.9 \
	crit_enter.9 crit_exit.9 \
	crit_enter.9 crit_exit_gd.9 \
	crit_enter.9 crit_exit_id.9
MLINKS+=crypto.9 crypto_dispatch.9 \
	crypto.9 crypto_done.9 \
	crypto.9 crypto_find_device_byhid.9 \
	crypto.9 crypto_find_driver.9 \
	crypto.9 crypto_freereq.9 \
	crypto.9 crypto_freesession.9 \
	crypto.9 crypto_getcaps.9 \
	crypto.9 crypto_get_driverid.9 \
	crypto.9 crypto_getreq.9 \
	crypto.9 crypto_kdispatch.9 \
	crypto.9 crypto_kdone.9 \
	crypto.9 crypto_kregister.9 \
	crypto.9 crypto_newsession.9 \
	crypto.9 crypto_register.9 \
	crypto.9 crypto_unblock.9 \
	crypto.9 crypto_unregister.9 \
	crypto.9 crypto_unregister_all.9
MLINKS+=DB_COMMAND.9 DB_SHOW_COMMAND.9
MLINKS+=devclass_add_driver.9 devclass_delete_driver.9 \
	devclass_add_driver.9 devclass_find_driver.9
MLINKS+=device_add_child.9 device_add_child_ordered.9
MLINKS+=device_enable.9 device_disable.9 \
	device_enable.9 device_is_enabled.9
MLINKS+=device_get_name.9 device_get_nameunit.9
MLINKS+=device_get_state.9 device_busy.9 \
	device_get_state.9 device_is_alive.9 \
	device_get_state.9 device_unbusy.9
MLINKS+=device_quiet.9 device_is_quiet.9 \
	device_quiet.9 device_verbose.9
MLINKS+=device_set_desc.9 device_get_desc.9 \
	device_set_desc.9 device_set_desc_copy.9
MLINKS+=device_set_flags.9 device_get_flags.9
MLINKS+=devstat.9 devicestat.9 \
	devstat.9 devstat_add_entry.9 \
	devstat.9 devstat_end_transaction.9 \
	devstat.9 devstat_end_transaction_buf.9 \
	devstat.9 devstat_remove_entry.9 \
	devstat.9 devstat_start_transaction.9
MLINKS+=DRIVER_MODULE.9 DRIVER_MODULE_ORDERED.9
MLINKS+=dsched.9 dsched_cancel_bio.9 \
	dsched.9 dsched_debug.9 \
	dsched.9 DSCHED_DISK_CTX_LOCK.9 \
	dsched.9 dsched_disk_ctx_ref.9 \
	dsched.9 DSCHED_DISK_CTX_UNLOCK.9 \
	dsched.9 dsched_disk_ctx_unref.9 \
	dsched.9 dsched_get_bio_dp.9 \
	dsched.9 dsched_get_bio_priv.9 \
	dsched.9 dsched_get_disk_priv.9 \
	dsched.9 dsched_new_policy_thread_tdio.9 \
	dsched.9 DSCHED_POLICY_MODULE.9 \
	dsched.9 dsched_register.9 \
	dsched.9 dsched_strategy_async.9 \
	dsched.9 dsched_strategy_raw.9 \
	dsched.9 DSCHED_THREAD_IO_LOCK.9 \
	dsched.9 dsched_thread_io_ref.9 \
	dsched.9 DSCHED_THREAD_IO_UNLOCK.9 \
	dsched.9 dsched_thread_io_unref.9 \
	dsched.9 dsched_unregister.9
MLINKS+=EVENTHANDLER.9 EVENTHANDLER_DECLARE.9 \
	EVENTHANDLER.9 EVENTHANDLER_DEREGISTER.9 \
	EVENTHANDLER.9 eventhandler_deregister.9 \
	EVENTHANDLER.9 eventhandler_find_list.9 \
	EVENTHANDLER.9 EVENTHANDLER_INVOKE.9 \
	EVENTHANDLER.9 EVENTHANDLER_REGISTER.9 \
	EVENTHANDLER.9 eventhandler_register.9
MLINKS+=fetch.9 fubyte.9 \
	fetch.9 fusword.9 \
	fetch.9 fuword.9
MLINKS+=firmware.9 firmware_get.9 \
	firmware.9 firmware_put.9 \
	firmware.9 firmware_register.9 \
	firmware.9 firmware_unregister.9
MLINKS+=hash.9 hash32.9 \
	hash.9 hash32_buf.9 \
	hash.9 hash32_str.9 \
	hash.9 hash32_stre.9 \
	hash.9 hash32_strn.9 \
	hash.9 hash32_strne.9
MLINKS+=hashinit.9 hashdestroy.9 \
	hashinit.9 hashinit_ext.9 \
	hashinit.9 phashinit.9 \
	hashinit.9 phashinit_ext.9
MLINKS+=idr.9 idr_destroy.9 \
	idr.9 idr_find.9 \
	idr.9 idr_for_each.9 \
	idr.9 idr_get_new.9 \
	idr.9 idr_get_new_above.9 \
	idr.9 idr_init.9 \
	idr.9 idr_init1.9 \
	idr.9 idr_pre_get.9 \
	idr.9 idr_remove.9 \
	idr.9 idr_remove_all.9 \
	idr.9 idr_replace.9
MLINKS+=ioctl.9 _IOR.9 \
	ioctl.9 _IOW.9 \
	ioctl.9 _IOWR.9 \
	ioctl.9 _IO.9
MLINKS+=ieee80211.9 ieee80211_ifattach.9 \
	ieee80211.9 ieee80211_ifdetach.9
#MLINKS+=ieee80211_amrr.9 ieee80211_amrr_choose.9 \
#	ieee80211_amrr.9 ieee80211_amrr_cleanup.9 \
#	ieee80211_amrr.9 ieee80211_amrr_init.9 \
#	ieee80211_amrr.9 ieee80211_amrr_node_init.9 \
#	ieee80211_amrr.9 ieee80211_amrr_setinterval.9 \
#	ieee80211_amrr.9 ieee80211_amrr_tx_complete.9 \
#	ieee80211_amrr.9 ieee80211_amrr_tx_update.9
MLINKS+=ieee80211_beacon.9 ieee80211_beacon_alloc.9 \
	ieee80211_beacon.9 ieee80211_beacon_notify.9 \
	ieee80211_beacon.9 ieee80211_beacon_update.9
MLINKS+=ieee80211_bmiss.9 ieee80211_beacon_miss.9
MLINKS+=ieee80211_crypto.9 ieee80211_crypto_available.9 \
	ieee80211_crypto.9 ieee80211_crypto_decap.9 \
	ieee80211_crypto.9 ieee80211_crypto_delglobalkeys.9 \
	ieee80211_crypto.9 ieee80211_crypto_delkey.9 \
	ieee80211_crypto.9 ieee80211_crypto_demic.9 \
	ieee80211_crypto.9 ieee80211_crypto_encap.9 \
	ieee80211_crypto.9 ieee80211_crypto_enmic.9 \
	ieee80211_crypto.9 ieee80211_crypto_newkey.9 \
	ieee80211_crypto.9 ieee80211_crypto_register.9 \
	ieee80211_crypto.9 ieee80211_crypto_reload_keys.9 \
	ieee80211_crypto.9 ieee80211_crypto_setkey.9 \
	ieee80211_crypto.9 ieee80211_crypto_unregister.9 \
	ieee80211_crypto.9 ieee80211_key_update_begin.9 \
	ieee80211_crypto.9 ieee80211_key_update_end.9 \
	ieee80211_crypto.9 ieee80211_notify_michael_failure.9 \
	ieee80211_crypto.9 ieee80211_notify_replay_failure.9
MLINKS+=ieee80211_input.9 ieee80211_input_all.9
MLINKS+=ieee80211_node.9 ieee80211_dump_node.9 \
	ieee80211_node.9 ieee80211_dump_nodes.9 \
	ieee80211_node.9 ieee80211_find_rxnode.9 \
	ieee80211_node.9 ieee80211_find_rxnode_withkey.9 \
	ieee80211_node.9 ieee80211_free_node.9 \
	ieee80211_node.9 ieee80211_iterate_nodes.9 \
	ieee80211_node.9 ieee80211_ref_node.9 \
	ieee80211_node.9 ieee80211_unref_node.9
MLINKS+=ieee80211_output.9 ieee80211_process_callback.9 \
	ieee80211_output.9 M_SEQNO_GET.9 \
	ieee80211_output.9 M_WME_GETAC.9
MLINKS+=ieee80211_proto.9 ieee80211_new_state.9 \
	ieee80211_proto.9 ieee80211_resume_all.9 \
	ieee80211_proto.9 ieee80211_start_all.9 \
	ieee80211_proto.9 ieee80211_stop_all.9 \
	ieee80211_proto.9 ieee80211_suspend_all.9 \
	ieee80211_proto.9 ieee80211_waitfor_parent.9
MLINKS+=ieee80211_radiotap.9 ieee80211_radiotap_active.9 \
	ieee80211_radiotap.9 ieee80211_radiotap_active_vap.9 \
	ieee80211_radiotap.9 ieee80211_radiotap_attach.9 \
	ieee80211_radiotap.9 ieee80211_radiotap_tx.9 \
	ieee80211_radiotap.9 radiotap.9
MLINKS+=ieee80211_regdomain.9 ieee80211_alloc_countryie.9 \
	ieee80211_regdomain.9 ieee80211_init_channels.9 \
	ieee80211_regdomain.9 ieee80211_sort_channels.9
MLINKS+=ieee80211_scan.9 ieee80211_add_scan.9 \
	ieee80211_scan.9 ieee80211_bg_scan.9 \
	ieee80211_scan.9 ieee80211_cancel_anyscan.9 \
	ieee80211_scan.9 ieee80211_cancel_scan.9 \
	ieee80211_scan.9 ieee80211_check_scan.9 \
	ieee80211_scan.9 ieee80211_check_scan_current.9 \
	ieee80211_scan.9 ieee80211_probe_curchan.9 \
	ieee80211_scan.9 ieee80211_scan_assoc_fail.9 \
	ieee80211_scan.9 ieee80211_scan_done.9 \
	ieee80211_scan.9 ieee80211_scan_dump_channels.9 \
	ieee80211_scan.9 ieee80211_scan_flush.9 \
	ieee80211_scan.9 ieee80211_scan_iterate.9 \
	ieee80211_scan.9 ieee80211_scanner_get.9 \
	ieee80211_scan.9 ieee80211_scanner_register.9 \
	ieee80211_scan.9 ieee80211_scanner_unregister.9 \
	ieee80211_scan.9 ieee80211_scanner_unregister_all.9 \
	ieee80211_scan.9 ieee80211_scan_next.9 \
	ieee80211_scan.9 ieee80211_scan_timeout.9 \
	ieee80211_scan.9 ieee80211_start_scan.9
MLINKS+=ieee80211_vap.9 ieee80211_vap_attach.9 \
	ieee80211_vap.9 ieee80211_vap_detach.9 \
	ieee80211_vap.9 ieee80211_vap_setup.9
MLINKS+=ifnet.9 ifaddr.9 \
	ifnet.9 if_data.9 \
	ifnet.9 ifqueue.9
MLINKS+=KASSERT.9 KKASSERT.9
MLINKS+=kenv.9 kfreeenv.9 \
	kenv.9 kgetenv.9 \
	kenv.9 kgetenv_int.9 \
	kenv.9 kgetenv_quad.9 \
	kenv.9 kgetenv_string.9 \
	kenv.9 kgetenv_ulong.9 \
	kenv.9 ksetenv.9 \
	kenv.9 ktestenv.9 \
	kenv.9 kunsetenv.9
MLINKS+=kernacc.9 useracc.9
MLINKS+=kmalloc.9 kfree.9 \
	kmalloc.9 krealloc.9 \
	kmalloc.9 MALLOC_DECLARE.9 \
	kmalloc.9 MALLOC_DEFINE.9
MLINKS+=kobj.9 DEFINE_CLASS.9 \
	kobj.9 kobj_class_compile.9 \
	kobj.9 kobj_class_free.9 \
	kobj.9 kobj_create.9 \
	kobj.9 kobj_delete.9 \
	kobj.9 kobj_init.9
MLINKS+=kprintf.9 krateprintf.9 \
	kprintf.9 ksnprintf.9 \
	kprintf.9 ksprintf.9 \
	kprintf.9 kvprintf.9 \
	kprintf.9 kvsnprintf.9 \
	kprintf.9 kvsprintf.9 \
	kprintf.9 log.9 \
	kprintf.9 tprintf.9 \
	kprintf.9 uprintf.9
MLINKS+=ksignal.9 gsignal.9 \
	ksignal.9 pgsignal.9
MLINKS+=ktr.9 KTR_COND_LOG.9 \
	ktr.9 KTR_INFO.9 \
	ktr.9 KTR_INFO_MASTER.9 \
	ktr.9 KTR_INFO_MASTER_EXTERN.9 \
	ktr.9 KTR_LOG.9
MLINKS+=kether_ntoa.9 kether_aton.9
MLINKS+=lock.9 lockcount.9 \
	lock.9 lockcountnb.9 \
	lock.9 lockinit.9 \
	lock.9 lockmgr.9 \
	lock.9 lockmgr_printinfo.9 \
	lock.9 lockstatus.9 \
	lock.9 lockuninit.9
MLINKS+=lwbuf.9 lwbuf_alloc.9 \
	lwbuf.9 lwbuf_free.9 \
	lwbuf.9 lwbuf_kva.9 \
	lwbuf.9 lwbuf_page.9 \
	lwbuf.9 lwbuf_set_global.9
MLINKS+=make_autoclone_dev.9 destroy_autoclone_dev.9 \
	make_autoclone_dev.9 DEVFS_CLONE_BITMAP.9 \
	make_autoclone_dev.9 devfs_clone_bitmap_chk.9 \
	make_autoclone_dev.9 devfs_clone_bitmap_fff.9 \
	make_autoclone_dev.9 devfs_clone_bitmap_get.9 \
	make_autoclone_dev.9 devfs_clone_bitmap_init.9 \
	make_autoclone_dev.9 devfs_clone_bitmap_put.9 \
	make_autoclone_dev.9 devfs_clone_bitmap_set.9 \
	make_autoclone_dev.9 devfs_clone_bitmap_uninit.9 \
	make_autoclone_dev.9 DEVFS_DECLARE_CLONE_BITMAP.9
MLINKS+=make_dev.9 destroy_dev.9 \
	make_dev.9 destroy_only_dev.9 \
	make_dev.9 devfs_scan_callback.9 \
	make_dev.9 dev_ops_intercept.9 \
	make_dev.9 dev_ops_remove_all.9 \
	make_dev.9 dev_ops_remove_minor.9 \
	make_dev.9 dev_ops_restore.9 \
	make_dev.9 make_dev_alias.9 \
	make_dev.9 make_dev_covering.9 \
	make_dev.9 make_only_dev.9 \
	make_dev.9 reference_dev.9 \
	make_dev.9 release_dev.9
MLINKS+=mbuf.9 m_adj.9 \
	mbuf.9 M_ALIGN.9 \
	mbuf.9 m_cat.9 \
	mbuf.9 MCLGET.9 \
	mbuf.9 m_copyback.9 \
	mbuf.9 m_copydata.9 \
	mbuf.9 m_copym.9 \
	mbuf.9 m_copypacket.9 \
	mbuf.9 m_devget.9 \
	mbuf.9 m_dup.9 \
	mbuf.9 m_free.9 \
	mbuf.9 m_freem.9 \
	mbuf.9 MGET.9 \
	mbuf.9 m_getclr.9 \
	mbuf.9 MGETHDR.9 \
	mbuf.9 m_getm.9 \
	mbuf.9 MH_ALIGN.9 \
	mbuf.9 M_LEADINGSPACE.9 \
	mbuf.9 M_PREPEND.9 \
	mbuf.9 m_pullup.9 \
	mbuf.9 m_split.9 \
	mbuf.9 mtod.9 \
	mbuf.9 M_TRAILINGSPACE.9
MLINKS+=MD5.9 MD5Init.9 \
	MD5.9 MD5Transform.9
MLINKS+=microtime.9 getmicrotime.9 \
	microtime.9 getnanotime.9 \
	microtime.9 nanotime.9
MLINKS+=microuptime.9 getmicrouptime.9 \
	microuptime.9 getnanouptime.9 \
	microuptime.9 nanouptime.9
MLINKS+=mpipe.9 mpipe_alloc_nowait.9 \
	mpipe.9 mpipe_alloc_waitok.9 \
	mpipe.9 mpipe_done.9 \
	mpipe.9 mpipe_free.9 \
	mpipe.9 mpipe_init.9
MLINKS+=msgport.9 lwkt_abortmsg.9 \
	msgport.9 lwkt_beginmsg.9 \
	msgport.9 lwkt_checkmsg.9 \
	msgport.9 lwkt_domsg.9 \
	msgport.9 lwkt_dropmsg.9 \
	msgport.9 lwkt_forwardmsg.9 \
	msgport.9 lwkt_getport.9 \
	msgport.9 lwkt_initmsg.9 \
	msgport.9 lwkt_initmsg_abortable.9 \
	msgport.9 lwkt_initport_panic.9 \
	msgport.9 lwkt_initport_putonly.9 \
	msgport.9 lwkt_initport_replyonly.9 \
	msgport.9 lwkt_initport_replyonly_null.9 \
	msgport.9 lwkt_initport_serialize.9 \
	msgport.9 lwkt_initport_spin.9 \
	msgport.9 lwkt_initport_thread.9 \
	msgport.9 lwkt_replymsg.9 \
	msgport.9 lwkt_sendmsg.9 \
	msgport.9 lwkt_waitmsg.9 \
	msgport.9 lwkt_waitport.9
MLINKS+=mutex.9 mtx_downgrade.9 \
	mutex.9 mtx_drop.9 \
	mutex.9 mtx_hold.9 \
	mutex.9 mtx_init.9 \
	mutex.9 mtx_islocked.9 \
	mutex.9 mtx_islocked_ex.9 \
	mutex.9 mtx_lock.9 \
	mutex.9 mtx_lock_ex.9 \
	mutex.9 mtx_lock_ex_quick.9 \
	mutex.9 mtx_lock_ex_try.9 \
	mutex.9 mtx_lockrefs.9 \
	mutex.9 mtx_lock_sh.9 \
	mutex.9 mtx_lock_sh_quick.9 \
	mutex.9 mtx_lock_sh_try.9 \
	mutex.9 mtx_notlocked.9 \
	mutex.9 mtx_notlocked_ex.9 \
	mutex.9 mtx_notowned.9 \
	mutex.9 mtx_owned.9 \
	mutex.9 mtx_spinlock.9 \
	mutex.9 mtx_spinlock_try.9 \
	mutex.9 mtx_spinunlock.9 \
	mutex.9 mtx_uninit.9 \
	mutex.9 mtx_unlock.9 \
	mutex.9 mtx_unlock_ex.9 \
	mutex.9 mtx_unlock_sh.9 \
	mutex.9 mtx_upgrade_try.9
MLINKS+=nlookup.9 naccess.9 \
	nlookup.9 naccess_va.9 \
	nlookup.9 nlookup_done.9 \
	nlookup.9 nlookup_done_at.9 \
	nlookup.9 nlookup_init.9 \
	nlookup.9 nlookup_init_at.9 \
	nlookup.9 nlookup_init_raw.9 \
	nlookup.9 nlookup_init_root.9 \
	nlookup.9 nlookup_mp.9 \
	nlookup.9 nlookup_set_cred.9 \
	nlookup.9 nlookup_simple.9 \
	nlookup.9 nlookup_zero.9 \
	nlookup.9 nreadsymlink.9
MLINKS+=objcache.9 objcache_create.9 \
	objcache.9 objcache_create_mbacked.9 \
	objcache.9 objcache_create_simple.9 \
	objcache.9 objcache_destroy.9 \
	objcache.9 objcache_dtor.9 \
	objcache.9 objcache_get.9 \
	objcache.9 objcache_malloc_alloc.9 \
	objcache.9 objcache_malloc_free.9 \
	objcache.9 objcache_nop_alloc.9 \
	objcache.9 objcache_nop_free.9 \
	objcache.9 objcache_put.9 \
	objcache.9 objcache_reclaimlist.9
MLINKS+=pci.9 pci_disable_busmaster.9 \
	pci.9 pci_disable_io.9 \
	pci.9 pci_enable_busmaster.9 \
	pci.9 pci_enable_io.9 \
	pci.9 pci_find_bsf.9 \
	pci.9 pci_find_dbsf.9 \
	pci.9 pci_find_device.9 \
	pci.9 pci_get_powerstate.9 \
	pci.9 pci_read_config.9 \
	pci.9 pci_set_powerstate.9 \
	pci.9 pci_write_config.9
MLINKS+=pfil.9 pfil_add_hook.9 \
	pfil.9 pfil_head_get.9 \
	pfil.9 pfil_head_register.9 \
	pfil.9 pfil_head_unregister.9 \
	pfil.9 pfil_hook_get.9 \
	pfil.9 pfil_remove_hook.9 \
	pfil.9 pfil_run_hooks.9
MLINKS+=pfind.9 zpfind.9
MLINKS+=physio.9 physread.9 \
	physio.9 physwrite.9
MLINKS+=posix4.9 p1003_1b.9
MLINKS+=priv.9 priv_check.9 \
	priv.9 priv_check_cred.9
MLINKS+=prop_copyin_ioctl.9 prop_array_copyin.9 \
	prop_copyin_ioctl.9 prop_array_copyout.9 \
	prop_copyin_ioctl.9 prop_array_copyin_ioctl.9 \
	prop_copyin_ioctl.9 prop_array_copyout_ioctl.9 \
	prop_copyin_ioctl.9 prop_dictionary_copyin.9 \
	prop_copyin_ioctl.9 prop_dictionary_copyout.9 \
	prop_copyin_ioctl.9 prop_dictionary_copyin_ioctl.9 \
	prop_copyin_ioctl.9 prop_dictionary_copyout_ioctl.9
MLINKS+=rman.9 rman_activate_resource.9 \
	rman.9 rman_deactivate_resource.9 \
	rman.9 rman_fini.9 \
	rman.9 rman_get_bushandle.9 \
	rman.9 rman_get_bustag.9 \
	rman.9 rman_get_device.9 \
	rman.9 rman_get_end.9 \
	rman.9 rman_get_flags.9 \
	rman.9 rman_get_size.9 \
	rman.9 rman_get_start.9 \
	rman.9 rman_get_virtual.9 \
	rman.9 rman_init.9 \
	rman.9 rman_make_alignment_flags.9 \
	rman.9 rman_manage_region.9 \
	rman.9 rman_release_resource.9 \
	rman.9 rman_reserve_resource.9 \
	rman.9 rman_set_bushandle.9 \
	rman.9 rman_set_bustag.9 \
	rman.9 rman_set_virtual.9
#	rman.9 rman_await_resource.9 \
#	rman.9 rman_get_rid.9 \
#	rman.9 rman_reserve_resource_bound.9 \
#	rman.9 rman_set_rid.9
MLINKS+=rtalloc.9 rtalloc1.9 \
	rtalloc.9 rtalloc_ign.9
MLINKS+=sbuf.9 sbuf_bcat.9 \
	sbuf.9 sbuf_bcopyin.9 \
	sbuf.9 sbuf_bcpy.9 \
	sbuf.9 sbuf_cat.9 \
	sbuf.9 sbuf_clear.9 \
	sbuf.9 sbuf_copyin.9 \
	sbuf.9 sbuf_cpy.9 \
	sbuf.9 sbuf_data.9 \
	sbuf.9 sbuf_delete.9 \
	sbuf.9 sbuf_done.9 \
	sbuf.9 sbuf_finish.9 \
	sbuf.9 sbuf_len.9 \
	sbuf.9 sbuf_new.9 \
	sbuf.9 sbuf_overflowed.9 \
	sbuf.9 sbuf_printf.9 \
	sbuf.9 sbuf_putc.9 \
	sbuf.9 sbuf_setpos.9 \
	sbuf.9 sbuf_trim.9 \
	sbuf.9 sbuf_vprintf.9
MLINKS+=sensor_attach.9 sensordev_install.9 \
	sensor_attach.9 sensordev_deinstall.9 \
	sensor_attach.9 sensor_detach.9 \
	sensor_attach.9 ksensordev.9 \
	sensor_attach.9 ksensor.9 \
	sensor_attach.9 sensor_task_register.9 \
	sensor_attach.9 sensor_task_unregister.9
MLINKS+=serializer.9 ASSERT_NOT_SERIALIZED.9 \
	serializer.9 ASSERT_SERIALIZED.9 \
	serializer.9 IS_SERIALIZED.9 \
	serializer.9 lwkt_serialize_adaptive_enter.9 \
	serializer.9 lwkt_serialize_enter.9 \
	serializer.9 lwkt_serialize_exit.9 \
	serializer.9 lwkt_serialize_handler_call.9 \
	serializer.9 lwkt_serialize_handler_disable.9 \
	serializer.9 lwkt_serialize_handler_enable.9 \
	serializer.9 lwkt_serialize_handler_try.9 \
	serializer.9 lwkt_serialize_init.9 \
	serializer.9 lwkt_serialize_try.9
MLINKS+=sglist.9 sglist_alloc.9 \
	sglist.9 sglist_append.9 \
	sglist.9 sglist_append_mbuf.9 \
	sglist.9 sglist_append_phys.9 \
	sglist.9 sglist_append_uio.9 \
	sglist.9 sglist_append_user.9 \
	sglist.9 sglist_build.9 \
	sglist.9 sglist_clone.9 \
	sglist.9 sglist_consume_uio.9 \
	sglist.9 sglist_count.9 \
	sglist.9 sglist_free.9 \
	sglist.9 sglist_hold.9 \
	sglist.9 sglist_init.9 \
	sglist.9 sglist_join.9 \
	sglist.9 sglist_length.9 \
	sglist.9 sglist_reset.9 \
	sglist.9 sglist_slice.9 \
	sglist.9 sglist_split.9
MLINKS+=sleep.9 lksleep.9 \
	sleep.9 mtxsleep.9 \
	sleep.9 ssleep.9 \
	sleep.9 tsleep.9 \
	sleep.9 tsleep_interlock.9 \
	sleep.9 wakeup.9 \
	sleep.9 wakeup_one.9 \
	sleep.9 zsleep.9
MLINKS+=spinlock.9 spin_init.9 \
	spinlock.9 spin_lock.9 \
	spinlock.9 spin_lock_quick.9 \
	spinlock.9 spin_trylock.9 \
	spinlock.9 spin_uninit.9 \
	spinlock.9 spin_unlock.9 \
	spinlock.9 spin_unlock_quick.9 \
	spinlock.9 spin_pool_lock.9 \
	spinlock.9 spin_pool_unlock.9
MLINKS+=store.9 casuword.9 \
	store.9 subyte.9 \
	store.9 susword.9 \
	store.9 suword.9 \
	store.9 suword32.9
MLINKS+=syscall.9 syscalls.master.5
MLINKS+=sysctl.9 SYSCTL_DECL.9 \
	sysctl.9 SYSCTL_INT.9 \
	sysctl.9 SYSCTL_LONG.9 \
	sysctl.9 SYSCTL_NODE.9 \
	sysctl.9 SYSCTL_OPAQUE.9 \
	sysctl.9 SYSCTL_PROC.9 \
	sysctl.9 SYSCTL_QUAD.9 \
	sysctl.9 SYSCTL_STRING.9 \
	sysctl.9 SYSCTL_STRUCT.9 \
	sysctl.9 SYSCTL_UINT.9 \
	sysctl.9 SYSCTL_ULONG.9 \
	sysctl.9 SYSCTL_UQUAD.9
MLINKS+=sysctl_add_oid.9 SYSCTL_ADD_INT.9 \
	sysctl_add_oid.9 SYSCTL_ADD_LONG.9 \
	sysctl_add_oid.9 SYSCTL_ADD_NODE.9 \
	sysctl_add_oid.9 SYSCTL_ADD_OID.9 \
	sysctl_add_oid.9 SYSCTL_ADD_OPAQUE.9 \
	sysctl_add_oid.9 SYSCTL_ADD_PROC.9 \
	sysctl_add_oid.9 SYSCTL_ADD_QUAD.9 \
	sysctl_add_oid.9 SYSCTL_ADD_STRING.9 \
	sysctl_add_oid.9 SYSCTL_ADD_STRUCT.9 \
	sysctl_add_oid.9 SYSCTL_ADD_UINT.9 \
	sysctl_add_oid.9 SYSCTL_ADD_ULONG.9 \
	sysctl_add_oid.9 SYSCTL_ADD_UQUAD.9 \
	sysctl_add_oid.9 SYSCTL_CHILDREN.9 \
	sysctl_add_oid.9 sysctl_remove_oid.9 \
	sysctl_add_oid.9 SYSCTL_STATIC_CHILDREN.9
MLINKS+=sysctl_ctx_init.9 sysctl_ctx_entry_add.9 \
	sysctl_ctx_init.9 sysctl_ctx_entry_del.9 \
	sysctl_ctx_init.9 sysctl_ctx_entry_find.9 \
	sysctl_ctx_init.9 sysctl_ctx_free.9
MLINKS+=SYSINIT.9 sysinit.9
MLINKS+=systimer.9 systimer_adjust_periodic.9 \
	systimer.9 systimer_init_oneshot.9 \
	systimer.9 systimer_init_periodic.9 \
	systimer.9 systimer_init_periodic_nq.9 \
	systimer.9 systimers.9
MLINKS+=taskqueue.9 TASK_INIT.9 \
	taskqueue.9 taskqueue_block.9 \
	taskqueue.9 taskqueue_cancel.9 \
	taskqueue.9 taskqueue_cancel_timeout.9 \
	taskqueue.9 taskqueue_create.9 \
	taskqueue.9 taskqueue_drain.9 \
	taskqueue.9 taskqueue_drain_timeout.9 \
	taskqueue.9 TASKQUEUE_DECLARE.9 \
	taskqueue.9 TASKQUEUE_DEFINE.9 \
	taskqueue.9 taskqueue_enqueue.9 \
	taskqueue.9 taskqueue_enqueue_timeout.9 \
	taskqueue.9 taskqueue_find.9 \
	taskqueue.9 taskqueue_free.9 \
	taskqueue.9 taskqueue_run.9 \
	taskqueue.9 taskqueue_start_threads.9 \
	taskqueue.9 taskqueue_unblock.9
MLINKS+=tbridge.9 tbridge_printf.9 \
	tbridge.9 TBRIDGE_TESTCASE_MODULE.9 \
	tbridge.9 tbridge_test_done.9
MLINKS+=time.9 boottime.9 \
	time.9 time_second.9
MLINKS+=token.9 lwkt_getpooltoken.9 \
	token.9 lwkt_gettoken.9 \
	token.9 lwkt_gettoken_shared.9 \
	token.9 lwkt_reltoken.9 \
	token.9 lwkt_token_init.9 \
	token.9 lwkt_token_pool_lookup.9 \
	token.9 lwkt_token_swap.9 \
	token.9 lwkt_token_uninit.9 \
	token.9 lwkt_trytoken.9
MLINKS+=tvtohz.9 tvtohz_high.9 \
	tvtohz.9 tvtohz_low.9
MLINKS+=uio.9 uiomove.9
MLINKS+=usbdi.9 usbd_abort_default_pipe.9 \
	usbdi.9 usbd_abort_pipe.9 \
	usbdi.9 usbd_alloc_buffer.9 \
	usbdi.9 usbd_alloc_xfer.9 \
	usbdi.9 usbd_bulk_transfer.9 \
	usbdi.9 usbd_clear_endpoint_stall.9 \
	usbdi.9 usbd_clear_endpoint_stall_async.9 \
	usbdi.9 usbd_clear_endpoint_toggle.9 \
	usbdi.9 usbd_close_pipe.9 \
	usbdi.9 usbd_device2interface_handle.9 \
	usbdi.9 usbd_devinfo.9 \
	usbdi.9 usbd_dopoll.9 \
	usbdi.9 usbd_do_request.9 \
	usbdi.9 usbd_do_request_async.9 \
	usbdi.9 usbd_do_request_flags.9 \
	usbdi.9 usbd_do_request_flags_pipe.9 \
	usbdi.9 usbd_endpoint_count.9 \
	usbdi.9 usbd_errstr.9 \
	usbdi.9 usb_detach_wait.9 \
	usbdi.9 usb_detach_wakeup.9 \
	usbdi.9 usbd_fill_deviceinfo.9 \
	usbdi.9 usbd_find_edesc.9 \
	usbdi.9 usbd_find_idesc.9 \
	usbdi.9 usbd_free_buffer.9 \
	usbdi.9 usbd_free_xfer.9 \
	usbdi.9 usbd_get_buffer.9 \
	usbdi.9 usbd_get_config.9 \
	usbdi.9 usbd_get_config_desc.9 \
	usbdi.9 usbd_get_config_desc_full.9 \
	usbdi.9 usbd_get_config_descriptor.9 \
	usbdi.9 usbd_get_device_descriptor.9 \
	usbdi.9 usbd_get_endpoint_descriptor.9 \
	usbdi.9 usbd_get_interface_altindex.9 \
	usbdi.9 usbd_get_interface_descriptor.9 \
	usbdi.9 usbd_get_no_alts.9 \
	usbdi.9 usbd_get_quirks.9 \
	usbdi.9 usbd_get_speed.9 \
	usbdi.9 usbd_get_string.9 \
	usbdi.9 usbd_get_string_desc.9 \
	usbdi.9 usbd_get_xfer_status.9 \
	usbdi.9 usbd_interface2device_handle.9 \
	usbdi.9 usbd_interface2endpoint_descriptor.9 \
	usbdi.9 usbd_interface_count.9 \
	usbdi.9 usbd_intr_transfer.9 \
	usbdi.9 usbd_open_pipe.9 \
	usbdi.9 usbd_open_pipe_intr.9 \
	usbdi.9 usbd_pipe2device_handle.9 \
	usbdi.9 usbd_ratecheck.9 \
	usbdi.9 usbd_set_config_index.9 \
	usbdi.9 usbd_set_config_no.9 \
	usbdi.9 usbd_set_interface.9 \
	usbdi.9 usbd_set_polling.9 \
	usbdi.9 usbd_setup_default_xfer.9 \
	usbdi.9 usbd_setup_isoc_xfer.9 \
	usbdi.9 usbd_setup_xfer.9 \
	usbdi.9 usbd_sync_transfer.9 \
	usbdi.9 usbd_transfer.9 \
	usbdi.9 usb_find_desc.9
MLINKS+=vcount.9 count_dev.9
MLINKS+=vhold.9 vdrop.9
MLINKS+=VOP_ATTRIB.9 VOP_GETATTR.9 \
	VOP_ATTRIB.9 VOP_SETATTR.9
MLINKS+=VOP_CREATE.9 VOP_MKDIR.9 \
	VOP_CREATE.9 VOP_MKNOD.9 \
	VOP_CREATE.9 VOP_SYMLINK.9
MLINKS+=VOP_GETPAGES.9 VOP_PUTPAGES.9
MLINKS+=VOP_INACTIVE.9 VOP_RECLAIM.9
MLINKS+=VOP_LOCK.9 vn_lock.9 \
	VOP_LOCK.9 VOP_ISLOCKED.9 \
	VOP_LOCK.9 VOP_UNLOCK.9
MLINKS+=VOP_OPENCLOSE.9 VOP_CLOSE.9 \
	VOP_OPENCLOSE.9 VOP_OPEN.9
MLINKS+=VOP_RDWR.9 VOP_READ.9 \
	VOP_RDWR.9 VOP_WRITE.9
MLINKS+=VOP_REMOVE.9 VOP_RMDIR.9
MLINKS+=vref.9 VREF.9
MLINKS+=vslock.9 vsunlock.9
MLINKS+=wdog.9 wdog_register.9 \
	wdog.9 wdog_unregister.9
MLINKS+=zone.9 zalloc.9 \
	zone.9 zbootinit.9 \
	zone.9 zdestroy.9 \
	zone.9 zfree.9 \
	zone.9 zinit.9 \
	zone.9 zinitna.9

.include <bsd.prog.mk>
