# must come before boot2
SUBDIR=	btx

SUBDIR=	boot0 boot0sio boot2 cdboot libi386 loader loader_tftp mbr

# special boot programs, 'self-extracting boot2+loader'
SUBDIR+=pxeldr pxeldr_tftp

.include <bsd.subdir.mk>
