# $DragonFly: src/secure/lib/libssh/Makefile.etc,v 1.1 2005/07/07 12:43:36 corecode Exp $
#

FILES=		${SSHDIR}/moduli
FILESDIR=	/etc/ssh
FILESOWN=	${BINOWN}
FILESGRP=	${BINGRP}
FILESMODE=	644

.include "../../Makefile.ssh.common"
.include <bsd.prog.mk>
