# $DragonFly: src/lib/pam_module/pam_cleartext_pass_ok/Makefile,v 1.2 2005/07/12 22:55:46 joerg Exp $

LIB=	pam_cleartext_pass_ok
SRCS=	pam_cleartext_pass_ok.c
WARNS?=	6
NOMAN=

LDADD=	-lskey

.include <bsd.lib.mk>
