# $DragonFly: src/lib/pam_module/pam_cleartext_pass_ok/Makefile,v 1.3 2005/07/28 19:25:40 joerg Exp $

LIB=	pam_cleartext_pass_ok
SRCS=	pam_cleartext_pass_ok.c
WARNS?=	6
NOMAN=

DPADD=	${LIBSKEY}
LDADD=	-lskey

.include <bsd.lib.mk>
