# $FreeBSD: src/share/doc/papers/Makefile,v 1.7.2.1 2000/08/20 13:16:28 mpp Exp $

SUBDIR=	beyond4.3 \
	contents \
	diskperf \
	fsinterface \
	jail \
	kernmalloc \
	kerntune \
	malloc \
	memfs \
	newvm \
	relengr \
	sysperf

.include <bsd.subdir.mk>
