# $FreeBSD: src/share/doc/legal/realtek/Makefile,v 1.1 2013/07/11 00:28:44 svnexp Exp $

NO_OBJ=
FILES=		${.CURDIR}/../../../../sys/contrib/dev/urtwn/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal/realtek

.include <bsd.prog.mk>
