#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/id/Makefile,v 1.5.6.3 2001/12/20 12:09:03 ru Exp $
# $DragonFly: src/usr.bin/id/Makefile,v 1.3 2004/09/19 17:25:42 joerg Exp $

PROG=	id
WARNS?=	6
LINKS=	${BINDIR}/id ${BINDIR}/groups
LINKS+=	${BINDIR}/id ${BINDIR}/whoami
MAN=	id.1 groups.1 whoami.1

.include <bsd.prog.mk>
