# $DragonFly: src/lib/pam_module/pam_tacplus/Makefile,v 1.2 2005/07/12 22:45:38 joerg Exp $

LIB=	pam_tacplus
SRCS=	pam_tacplus.c
WARNS?=	6
MAN=	pam_tacplus.8

LDADD=	-ltacplus
DPADD=	${LIBTACPLUS}

.include <bsd.lib.mk>
