# $FreeBSD: src/sys/modules/netgraph/frame_relay/Makefile,v 1.1.4.3 2001/12/21 09:00:48 ru Exp $
# $DragonFly: src/sys/netgraph/frame_relay/Makefile,v 1.2 2003/06/17 04:28:46 dillon Exp $
# $Whistle: Makefile,v 1.1 1999/01/19 19:39:21 archie Exp $

KMOD=		ng_frame_relay
SRCS= 		ng_frame_relay.c

.include <bsd.kmod.mk>
