#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/msgs/Makefile,v 1.6 1999/08/28 01:04:21 peter Exp $
# $DragonFly: src/usr.bin/msgs/Makefile,v 1.4 2007/08/27 16:50:56 pavalos Exp $

PROG=	msgs
DPADD=	${LIBTERMCAP}
LDADD=	-ltermcap

.include <bsd.prog.mk>
