#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/msgs/Makefile,v 1.6 1999/08/28 01:04:21 peter Exp $
# $DragonFly: src/usr.bin/msgs/Makefile,v 1.3 2005/02/02 06:39:09 cpressey Exp $

PROG=	msgs
WARNS?=	6
DPADD=	${LIBTERMCAP}
LDADD=	-ltermcap

.include <bsd.prog.mk>
