#	@(#)Makefile	5.33.1.1 (Berkeley) 5/6/91
# $FreeBSD: src/gnu/Makefile,v 1.33.2.1 2002/07/25 16:33:10 obrien Exp $
# $DragonFly: src/gnu/Makefile,v 1.2 2003/06/17 04:25:42 dillon Exp $

SUBDIR= lib libexec usr.bin usr.sbin

.include <bsd.subdir.mk>
