# $FreeBSD: src/sys/modules/aic7xxx/Makefile.inc,v 1.1.2.1 2002/12/01 09:01:07 nyan Exp $
# $DragonFly: src/sys/dev/disk/aic7xxx/Makefile.inc,v 1.2 2003/06/17 04:28:43 dillon Exp $

.include "../Makefile.inc"
