# $FreeBSD: src/gnu/usr.bin/tar/doc/Makefile,v 1.3.2.1 2002/07/14 13:19:48 sobomax Exp $
# $DragonFly: src/gnu/usr.bin/tar/doc/Attic/Makefile,v 1.2 2003/06/17 04:25:49 dillon Exp $

INFO=	tar
SRCDIR=	${.CURDIR}/../../../../contrib/tar/doc

.include <bsd.info.mk>
