#	@(#)Makefile	8.1 (Berkeley) 6/9/93
# $FreeBSD: src/usr.bin/renice/Makefile,v 1.2.14.1 2001/04/25 11:29:33 ru Exp $
# $DragonFly: src/usr.bin/renice/Makefile,v 1.2 2003/06/17 04:29:30 dillon Exp $

PROG=	renice
MAN=	renice.8

.include <bsd.prog.mk>
