# $DragonFly: src/sys/dev/netif/ath/Makefile,v 1.1 2006/07/13 09:15:22 sephe Exp $

SUBDIR	= hal ath

# Choose the desired rate below
SUBDIR	+= rate_sample
#SUBDIR	+= rate_amrr
#SUBDIR	+= rate_onoe 

.include <bsd.subdir.mk>
