# $FreeBSD: src/usr.bin/pathchk/Makefile,v 1.1.2.1 2002/11/08 04:20:33 tjr Exp $
# $DragonFly: src/usr.bin/pathchk/Makefile,v 1.3 2004/12/31 08:11:56 cpressey Exp $

PROG=	pathchk
WARNS?=	6

.include <bsd.prog.mk>
