# $DragonFly: src/gnu/usr.bin/cc34/cc_tools/genemit/Makefile,v 1.1 2004/06/14 22:27:55 joerg Exp $

.include "../Makefile.inc"

PROG=	genemit
SRCS=	genemit.c genrtl.h insn-modes.h gensupport.c gtype-desc.h
SRCS+=	insn-conditions.c tm-preds.h insn-constants.h min-insn-modes.c
SRCS+=	errors.c rtl.c read-rtl.c ggc-none.c
SRCS+=	concat.c hashtab.c obstack.c safe-ctype.c xexit.c xmalloc.c xstrdup.c

.include <bsd.hostprog.mk>
