# $DragonFly: src/gnu/usr.bin/cc40/cc_tools/genpreds/Attic/Makefile,v 1.1 2005/06/05 22:43:21 corecode Exp $

.include "../Makefile.inc"

PROG=	genpreds
SRCS=	genpreds.c insn-modes.h gtype-desc.h
SRCS+=	${RTL_SRCS} ${EARLY_SRCS} ${PRINT_SRCS} ${ERRORS_SRCS}

.include <bsd.hostprog.mk>
