# $FreeBSD: src/kerberos5/doc/Makefile,v 1.1 2002/07/05 05:47:13 ru Exp $
# $DragonFly: src/kerberos5/doc/Makefile,v 1.1 2005/01/16 14:25:46 eirikn Exp $

INFO=	heimdal
SRCDIR=	${.CURDIR}/../../crypto/heimdal-0.6.3/doc

.include <bsd.info.mk>
